### PR TITLE
HttpMessages implementing HttpContent types too aren't handled correctly (Fixes #12750)

### LINKED ISSUE #12750: HttpMessages implementing HttpContent types too aren't handled correctly
Changes due to #12709 have added a code path where `HttpMessage` types that implement `HttpContent` types too are handled in their separate code paths while handled as just `HttpMessage` right after too.

The fact that CI doesn't fail there means that there are no types like that (and it's not impacting existing users using default types too).

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

Changes due to #12709 have added a code path.

Modifications:

Restore the "just http message" case as separated by the http content ones

Result:

Same encoding as original code

### CODE REVIEW

**Comment by franz1981** [comment]
@normanmaurer @chrisvest I still don't know if I should add a test case here really - there were no failing tests on the CI

**Comment by chrisvest** [comment]
@franz1981 Would probably be nice to have a test case.

Also, rebase to get the build passing again.

**Comment by chrisvest** [comment]
Checkstyle is unhappy:

```
Error:  /home/runner/work/netty/netty/codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:194:9: Redundant 'public' modifier. [RedundantModifier]
Error:  /home/runner/work/netty/netty/codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:198:9: Redundant 'public' modifier. [RedundantModifier]
Error:  /home/runner/work/netty/netty/codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:202:9: Redundant 'public' modifier. [RedundantModifier]
Error:  /home/runner/work/netty/netty/codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:206:9: Redundant 'public' modifier. [RedundantModifier]
Error:  /home/runner/work/netty/netty/codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:213:9: Redundant 'public' modifier. [RedundantModifier]
Error:  /home/runner/work/netty/netty/codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:349: Line is longer than 120 characters (found 125). [LineLength]
```

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java [hunk 1]
```diff
@@ -182,6 +181,180 @@ public void testEmptyContentNotsChunkedWithTrailers() throws Exception {
...
+                        hash = 31;
+                    }
+                } else {
+                    hash = 31;
+                }
+                hash = 31 * hash + trailingHeaders().hashCode();
+                hash = 31 * hash + super.hashCode();
+                this.hash = hash;
+            }
+            return hash;
```
Comment (chrisvest) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:328]: How come we need to go to these lengths for the equals and hashCode?

Comment (franz1981) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:328]: Good point, no we don't need it indeed :O 
let me simplify it

Comment (franz1981) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:328]: Ah no, I've copied from default full http msg I see :O

Comment (chrisvest) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:320]: So what's the conclusion?

Comment (franz1981) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestEncoderTest.java:320]: It was copied by `DefaultFullHttpMessage` like the most of its code!
