### PR TITLE
Fix CRLF split between 2 buffers before separator

### LINKED ISSUE #11668: Multipart upload splits CRLF across 2 chunks
### Expected behavior

CLRF is always part of a single chunk.

### Actual behavior

CRLF _can_ be split across 2 chunks (in some super rare exotic circumstances), causing the first CR to be considered part of the multipart payload and being offered to the Decoder, causing

```
io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: java.io.IOException: Out of size: 5043445 > 5043444
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.loadDataMultipartOptimized(HttpPostMultipartRequestDecoder.java:1190)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.getFileUpload(HttpPostMultipartRequestDecoder.java:926)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:572)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBodyMultipart(HttpPostMultipartRequestDecoder.java:463)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBody(HttpPostMultipartRequestDecoder.java:432)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:347)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:54)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
```

This is **very much** a _theory_. Any hints to figure out whether something else could cause this would be appreciated.

### Steps to reproduce

We have a test in Apache Flink that uploads a multipart HTTP request containing a bit of JSON as a MemoryAttribute and a FileUpload.
When the size of these attributes is just right (deviating by as much as 3 bytes hides the issue) the decoding of the request fails.
If it fails, then it is always with an off-by-one error as shown above, one more byte arriving than expected.

While debugging I inspected the chunk that causes the error. The last readable byte in the chunk had the value '13', i.e., CR. This makes me to believe that it is somehow possible that the CRLF can be split across chunks.

According to the the [4.1.49 decoder](https://github.com/netty/netty/blob/d0ec961cce19646519d6a0d59e7604b0eacd9bf2/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java#L1101) this should be impossible, but the explicit check was removed in 1529ef1794e0a6654fa4334fd979b769d6940e61.

We further consistently observe that the return value `HttpPostRequestEncoder#length()` after finalizing the request differs by _exactly 1_ between successful and failed runs, e.g., 5043832 (successful) vs 5043831 (failed).
Not sure what to make of that, but it's too consistent to ignore.

We have only observed this error after upgrading from 4.1.49 to 4.1.65.

### Minimal yet complete reproducer code (or URL to code)

Still working on that. I could provide a reproducer that relies on a few Apache Flink classes if that would be acceptable.

### Netty version

4.1.65.Final

### JVM version (e.g. `java -version`)

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### OS version (e.g. `uname -a`)

Windows 11, but we also observed it on Ubuntu 20.

### PR DESCRIPTION
**Pull request by fredericBregier**
Motivation:

When a buffer ends with the last chunk for a part but containing
only a CR and no LF neither separator, it ends up with the CR
included within the content of the part, which is wrong.

Modification:

Rare case, but fixed by checking when not getting the delimiter,
not finding a LineBreak, we check if the last byte of the chunk is a CR
and if the content could be added to the current part (current length +
current buffer length - 1) could lead to the end of the part.

Result:

If the CR is not part of the HttpData, then the CR can be safely ignored, 
waiting for the future LF and separator, and the buffer minus this CR 
can be added to the part content.

If not, the CR is part of the content and shall be included in the HttpData.

Add a non regression test.

Fixes #11668

### CODE REVIEW

**Comment by zentol** [comment]
I can confirm that this fixed the issue for us. 👍

**Comment by fredericBregier** [comment]
@zentol Great to hear that! Not so easy, since I had to take into account very special cases (where the content is finishing for instance with a CR or LF or CRLF, before the delimiter). So the test to ensure it is valid.
Hopefully, the existing tests help me to not introduce another bug. And I created a new one for this specific issue.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java [hunk 1]
```diff
@@ -1175,12 +1175,22 @@ private static boolean loadDataMultipartOptimized(ByteBuf undecodedChunk, String
...
-            int lastPosition = undecodedChunk.readableBytes() - bdelimiter.length - 1;
+            int readableBytes = undecodedChunk.readableBytes();
+            int lastPosition = readableBytes - bdelimiter.length - 1;
             if (lastPosition < 0) {
                 // Not enough bytes, but at most delimiter.length bytes available so can still try to find CRLF there
                 lastPosition = 0;
             }
-            posDelimiter = HttpPostBodyUtil.findLastLineBreak(undecodedChunk, startReaderIndex  + lastPosition);
+            posDelimiter = HttpPostBodyUtil.findLastLineBreak(undecodedChunk, startReaderIndex + lastPosition);
+            // No LineBreak, howver CR can be at the end of the buffer, LF not yet there (issue #11668)
```
Comment (hyperxpro) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1185]:
```suggestion
            // No LineBreak, however CR can be at the end of the buffer, LF is not yet there (issue #11668)
```

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1185]: OK ;-)

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java]: Done ;-)

Comment (hyperxpro) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java]: :D

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 2]
```diff
@@ -358,4 +358,121 @@ private void commonNotBadReleaseBuffersDuringDecoding(HttpDataFactory factory, b
         factory.cleanAllHttpData();
         decoder.destroy();
     }
+
+    // Issue #11668
+    private void commonTestFileDelimiterLFLastChunk(HttpDataFactory factory, boolean inMemory)
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:363]: nit: static

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 3]
```diff
@@ -358,4 +358,121 @@ private void commonNotBadReleaseBuffersDuringDecoding(HttpDataFactory factory, b
...
+        HttpRequest request = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/upload");
+        request.headers().set("content-type", "multipart/form-data; boundary=861fbeab-cd20-470c-9609-d40a0f704466");
+        // +4 => 2xCRLF (beginning, end)
+        request.headers().set("content-length", prefix.length() + fileSize + suffix.length() + 4);
+
+        HttpPostMultipartRequestDecoder decoder = new HttpPostMultipartRequestDecoder(factory, request);
+        ByteBuf buf = Unpooled.wrappedBuffer(prefix.getBytes(CharsetUtil.UTF_8));
+        decoder.offer(new DefaultHttpContent(buf));
+        assertNotNull(((HttpData) decoder.currentPartialHttpData()).content());
+        buf.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:396]: I am a bit confused... Why we release here ? Shouldn't the decoder have ownership of the buffer now ?

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 4]
```diff
@@ -358,4 +358,121 @@ private void commonNotBadReleaseBuffersDuringDecoding(HttpDataFactory factory, b
...
+        byte[] body = new byte[bytesPerChunk];
+        Arrays.fill(body, (byte) 1);
+        // Set first bytes as CRLF to ensure it is correctly getting the last CRLF
+        body[0] = HttpConstants.CR;
+        body[1] = HttpConstants.LF;
+        for (int i = 0; i < nbChunks; i++) {
+            ByteBuf content = Unpooled.wrappedBuffer(body, 0, bytesPerChunk);
+            decoder.offer(new DefaultHttpContent(content)); // **OutOfMemory previously here**
+            assertNotNull(((HttpData) decoder.currentPartialHttpData()).content());
+            content.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:407]: same comment as above

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 5]
```diff
@@ -358,4 +358,121 @@ private void commonNotBadReleaseBuffersDuringDecoding(HttpDataFactory factory, b
...
+        }
+        // Last -2 body = content + CR but no delimiter
+        byte[] previousLastbody = new byte[bytesLastChunk + 1];
+        Arrays.fill(previousLastbody, (byte) 1);
+        previousLastbody[bytesLastChunk] = HttpConstants.CR;
+        ByteBuf content2 = Unpooled.wrappedBuffer(previousLastbody, 0, previousLastbody.length);
+        decoder.offer(new DefaultHttpContent(content2));
+        assertNotNull(decoder.currentPartialHttpData());
+        content2.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:416]: same question as above

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 6]
```diff
@@ -358,4 +358,121 @@ private void commonNotBadReleaseBuffersDuringDecoding(HttpDataFactory factory, b
...
+        // Last -1 body = LF+delimiter+CR but no LF
+        content2 = Unpooled.wrappedBuffer(bsuffixReal, 0, bsuffixReal.length);
+        decoder.offer(new DefaultHttpContent(content2));
+        assertNull(decoder.currentPartialHttpData());
+        content2.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:421]: same question as above

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 7]
```diff
@@ -358,4 +358,121 @@ private void commonNotBadReleaseBuffersDuringDecoding(HttpDataFactory factory, b
...
+        // Last (LF)
+        content2 = Unpooled.wrappedBuffer(lastbody, 0, lastbody.length);
+        decoder.offer(new DefaultHttpContent(content2));
+        assertNull(decoder.currentPartialHttpData());
+        content2.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:426]: same question as above

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 2 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:363]: OK, I follow the same way than the other test in the very same Junit class. I will change this one to static.

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 3 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:396]: As it is out of any "Netty Handler" (as `SimpleChannelInboundHandler`), the test shall do as a normal handler acts, implying that buffer is released as the handler shall do.
The decoder takes ownership but on a copy, not the original one.
So, AFAIK, there should not be any confusion there.

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 4 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:407]: same

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 5 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:416]: same

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 6 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:421]: same

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 7 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:426]: same

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 2 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java]: Done for both sub methods private (existing one and new one) ;-)

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 3 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:396]: The previous change done on the decoder was about the "copied" buffer, not the original one. So it was a good catch since this buffer (copied from original) could be lost while not released.

Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:396]: If you're OK, please resolve these points ;-)

Comment (chrisvest) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:396]: Perhaps it would be clearer if the test kept around variables with the `DefaultHttpContent` and released _that_, instead of the buffer. The `DefaultHttpContent` _is_ meant to own its buffer.

Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:396]: I can try to change to this way (releasing `DefaultHttpContent`) to not introduce incomprehension (I shall then correct "all" tests, not only this one).

Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java]: Change done to `DefaultHttpContent.release()` instead to ensure comprehension.

**Comment by fredericBregier** [comment]
@normanmaurer I hope the changes are OK for you?

**Comment by fredericBregier** [comment]
Finally, the tests passed (no relation with this PR) ;-)

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@fredericBregier thanks a lot!
