### PR TITLE
Replace `ClosedChannelException` with `StacklessClosedChannelException`

### LINKED ISSUE #16504: Proposal: Replace `ClosedChannelException` with `StacklessClosedChannelException`
`SslHandler.channelInactive` allocates `ClosedChannelException`, which collects the stacktrace.
In a high-load environment, with a large number of connections being opened/closed, this introduces GC pressure:
Image

We can replace this exception with `StacklessClosedChannelException`, which will reduce pressure by eliminating the allocation of the `StackTraceElement[]` array for the stack trace.

### PR DESCRIPTION
**Pull request by Munoon**
Motivation:

`SslHandler.channelInactive` allocates `ClosedChannelException`, which collects the stacktrace.
In a high-load environment, with a large number of connections being opened/closed, this introduces GC pressure:
Image

Modification:

Replaced this exception with `StacklessClosedChannelException`, which will reduce pressure by eliminating the allocation of the `StackTraceElement[]` array for the stack trace.

Result:

Fixes #16504.

### CODE REVIEW

**Comment by normanmaurer** [comment]
This make sense... The only downside is that we now need to expose this as public. Not a big deal tho.

File: transport/src/main/java/io/netty/channel/StacklessClosedChannelException.java [hunk 1]
```diff
@@ -22,7 +22,7 @@
 /**
  * Cheap {@link ClosedChannelException} that does not fill in the stacktrace.
  */
-final class StacklessClosedChannelException extends ClosedChannelException {
+public final class StacklessClosedChannelException extends ClosedChannelException {
```
Comment (chrisvest) [inline transport/src/main/java/io/netty/channel/StacklessClosedChannelException.java:27]: Let's also annotate if with `@UnstableApi`, because we might want to hide this again in 5.0.

Comment (normanmaurer) [reply transport/src/main/java/io/netty/channel/StacklessClosedChannelException.java:27]: @Munoon can you do this ?

Comment (Munoon) [reply transport/src/main/java/io/netty/channel/StacklessClosedChannelException.java:27]: sure, done
