### PR TITLE
Fix HttpContentEncoder does not handle multiple Accept-Encoding 

### LINKED ISSUE #9553: HttpContentEncoder does not handle multiple Accept-Encoding headers correctly
### Expected behavior

When a request contains multiple `Accept-Encoding` headers, their values will be treated as if they had been sent as the comma-separated values of a single `Accept-Encoding` header.

### Actual behavior

Only the first `Accept-Encoding` header is considered and all subsequent `Accept-Encoding` headers are ignored.

### Steps to reproduce

Configure an HTTP server with `HttpContentCompressor` in its pipeline and send a request with multiple `Accept-Encoding` headers. Using curl that would look something like this:

```
 curl -H "Accept-Encoding: unknown" -H "Accept-Encoding: gzip" localhost:8080
```

Observe that the response is not gzipped.

### Minimal yet complete reproducer code (or URL to code)

```java
package com.example.demo;

import static io.netty.handler.codec.http.HttpHeaderNames.CONNECTION;
import static io.netty.handler.codec.http.HttpHeaderNames.CONTENT_LENGTH;
import static io.netty.handler.codec.http.HttpHeaderNames.CONTENT_TYPE;
import static io.netty.handler.codec.http.HttpHeaderValues.CLOSE;
import static io.netty.handler.codec.http.HttpHeaderValues.KEEP_ALIVE;
import static io.netty.handler.codec.http.HttpHeaderValues.TEXT_PLAIN;
import static io.netty.handler.codec.http.HttpResponseStatus.OK;

import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.SimpleChannelInboundHandler;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.http.DefaultFullHttpResponse;
import io.netty.handler.codec.http.FullHttpResponse;
import io.netty.handler.codec.http.HttpContentCompressor;
import io.netty.handler.codec.http.HttpObject;
import io.netty.handler.codec.http.HttpRequest;
import io.netty.handler.codec.http.HttpServerCodec;
import io.netty.handler.codec.http.HttpServerExpectContinueHandler;
import io.netty.handler.codec.http.HttpUtil;

public final class HttpHelloWorldServer {

    public static void main(String[] args) throws Exception {
        EventLoopGroup bossGroup = new NioEventLoopGroup(1);
        EventLoopGroup workerGroup = new NioEventLoopGroup();
        try {
            ServerBootstrap b = new ServerBootstrap();
            b.option(ChannelOption.SO_BACKLOG, 1024);
            b.group(bossGroup, workerGroup)
             .channel(NioServerSocketChannel.class)
             .childHandler(new HttpHelloWorldServerInitializer());
            Channel ch = b.bind(8080).sync().channel();
            ch.closeFuture().sync();
        } finally {
            bossGroup.shutdownGracefully();
            workerGroup.shutdownGracefully();
        }
    }
    
    static final class HttpHelloWorldServerInitializer extends ChannelInitializer<SocketChannel> {

        @Override
        public void initChannel(SocketChannel ch) {
            ChannelPipeline p = ch.pipeline();
            p.addLast(new HttpServerCodec());
            p.addLast(new HttpContentCompressor());
            p.addLast(new HttpServerExpectContinueHandler());
            p.addLast(new HttpHelloWorldServerHandler());
        }
        
    }
    
    static final class HttpHelloWorldServerHandler extends SimpleChannelInboundHandler<HttpObject> {
    	
        private static final byte[] CONTENT = { 'H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd' };

        @Override
        public void channelReadComplete(ChannelHandlerContext context) {
            context.flush();
        }

        @Override
        public void channelRead0(ChannelHandlerContext context, HttpObject message) {
            if (message instanceof HttpRequest) {
                HttpRequest req = (HttpRequest) message;

                boolean keepAlive = HttpUtil.isKeepAlive(req);
                FullHttpResponse response = new DefaultFullHttpResponse(req.protocolVersion(), OK, Unpooled.wrappedBuffer(CONTENT));
                response.headers().set(CONTENT_TYPE, TEXT_PLAIN).setInt(CONTENT_LENGTH, response.content().readableBytes());

                if (keepAlive) {
                    if (!req.protocolVersion().isKeepAliveDefault()) {
                        response.headers().set(CONNECTION, KEEP_ALIVE);
                    }
                } else {
                    // Tell the client we're going to close the connection.
                    response.headers().set(CONNECTION, CLOSE);
                }

                ChannelFuture f = context.write(response);

                if (!keepAlive) {
                    f.addListener(ChannelFutureListener.CLOSE);
                }
            }
        }

        @Override
        public void exceptionCaught(ChannelHandlerContext context, Throwable ex) {
            ex.printStackTrace();
            context.close();
        }
        
    }
    
}
```

### Netty version

4.1.39

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)
```

### OS version (e.g. `uname -a`)

Darwin Andys-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:
At the current moment `HttpContentEncoder` handle only first value of multiple `accept-encoding` headers.

Modification:

Join multiple `accept-encoding` headers to one separated by comma.

Result:

Fixes #9553

### CODE REVIEW

**Comment by amizurov** [comment]
@normanmaurer @wilkinsona, please check.

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java [hunk 1]
```diff
@@ -73,9 +76,15 @@ public boolean acceptOutboundMessage(Object msg) throws Exception {
...
+        CharSequence acceptedEncoding;
+        List<String> acceptEncodingHeaders = msg.headers().getAll(ACCEPT_ENCODING);
+        if (acceptEncodingHeaders.isEmpty()) {
             acceptedEncoding = HttpContentDecoder.IDENTITY;
+        } else if (acceptEncodingHeaders.size() == 1) {
+            acceptedEncoding = acceptEncodingHeaders.get(0);
+        } else {
+            // Multiple message-header fields https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
+            acceptedEncoding = StringUtil.join(",", acceptEncodingHeaders.iterator());
         }
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java]: nit: maybe we should make this:

```java
switch (acceptedEncodingHeaders.size()) {
    case 0:
        acceptedEncoding = HttpContentDecoder.IDENTITY;
        break;
    case 1: 
        acceptedEncoding = acceptEncodingHeaders.get(0);
        break;
    default:
        // Multiple message-header fields https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
       acceptedEncoding = StringUtil.join(",", acceptEncodingHeaders.iterator());
       break;

}
```

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java [hunk 2]
```diff
@@ -500,6 +500,39 @@ public void testCompressThresholdNotCompress() throws Exception {
...
+    @Test
+    public void testMultipleAcceptEncodingHeaders() {
+        FullHttpRequest request = newRequest();
+        request.headers().set(HttpHeaderNames.ACCEPT_ENCODING, "unknown")
+               .add(HttpHeaderNames.ACCEPT_ENCODING, "gzip")
+               .add(HttpHeaderNames.ACCEPT_ENCODING, "deflate");
+
+        EmbeddedChannel ch = new EmbeddedChannel(new HttpContentCompressor());
+
+        ch.writeInbound(request);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java]: assert return value

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java [hunk 3]
```diff
@@ -500,6 +500,39 @@ public void testCompressThresholdNotCompress() throws Exception {
...
+
+        FullHttpResponse res = new DefaultFullHttpResponse(
+                HttpVersion.HTTP_1_1, HttpResponseStatus.OK,
+                Unpooled.copiedBuffer("Gzip Win", CharsetUtil.US_ASCII));
+        ch.writeOutbound(res);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java]: assert return value

File: common/src/main/java/io/netty/util/internal/StringUtil.java [hunk 4]
```diff
@@ -597,6 +598,30 @@ public static CharSequence trimOws(CharSequence value) {
...
 
+    /**
+     * Returns a new string that contains all {@code elements} joined by a given separator.
+     *
+     * @param separator for each element
+     * @param elements to join together
+     *
+     * @return a string joined by a given separator.
+     */
+    public static CharSequence join(CharSequence separator, Iterator<? extends CharSequence> elements) {
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/internal/StringUtil.java]: maybe just make this `Iterable` ?

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: common/src/main/java/io/netty/util/internal/StringUtil.java [hunk 5]
```diff
@@ -597,6 +598,30 @@ public static CharSequence trimOws(CharSequence value) {
...
+        ObjectUtil.checkNotNull(separator, "separator");
+        ObjectUtil.checkNotNull(elements, "elements");
+
+        if (!elements.hasNext()) {
+            return EMPTY_STRING;
+        }
+
+        StringBuilder builder = new StringBuilder().append(elements.next());
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/internal/StringUtil.java]: I wonder if we should optimise this a but to only build the StringBuilder etc when there are at least 2 elements in ?

Comment (njhill) [reply common/src/main/java/io/netty/util/internal/StringUtil.java]: This could also be simplified to just `new StringBuilder(elements.next())`.

File: common/src/main/java/io/netty/util/internal/StringUtil.java [hunk 6]
```diff
@@ -597,6 +598,30 @@ public static CharSequence trimOws(CharSequence value) {
...
+        while (elements.hasNext()) {
+            builder.append(separator).append(elements.next());
+        }
+
+        return builder.toString();
```
Comment (njhill) [inline common/src/main/java/io/netty/util/internal/StringUtil.java]: Better to just return `builder`, no need to copy to a `String` yet

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java [hunk 7]
```diff
@@ -73,9 +76,15 @@ public boolean acceptOutboundMessage(Object msg) throws Exception {
     @Override
     protected void decode(ChannelHandlerContext ctx, HttpRequest msg, List<Object> out)
             throws Exception {
-        CharSequence acceptedEncoding = msg.headers().get(HttpHeaderNames.ACCEPT_ENCODING);
-        if (acceptedEncoding == null) {
+        CharSequence acceptedEncoding;
+        List<String> acceptEncodingHeaders = msg.headers().getAll(ACCEPT_ENCODING);
```
Comment (njhill) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java]: It's a shame that `HttpHeaders` doesn't have `get`/`getAll` methods which return `CharSequence`s rather than `String`s. These would be quite easy to add I think and would help cut down on copying and garbage.

(this is a passing comment and not directly related to the PR change!)

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java (hunk 1 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java]: Don't mind, done

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java (hunk 2 above)
Comment (amizurov) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java]: Done

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java (hunk 3 above)
Comment (amizurov) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java]: Done

File: common/src/main/java/io/netty/util/internal/StringUtil.java (hunk 4 above)
Comment (amizurov) [reply common/src/main/java/io/netty/util/internal/StringUtil.java]: Done

File: common/src/main/java/io/netty/util/internal/StringUtil.java (hunk 5 above)
Comment (amizurov) [reply common/src/main/java/io/netty/util/internal/StringUtil.java]: All done :)

File: common/src/main/java/io/netty/util/internal/StringUtil.java (hunk 6 above)
Comment (amizurov) [reply common/src/main/java/io/netty/util/internal/StringUtil.java]: Done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@wilkinsona would you please check this one as well ?

**Comment by normanmaurer** [comment]
@amizurov thanks a lot!
