### PR TITLE
Fix ZstdEncoder not producing data when source is smaller than block size

### LINKED ISSUE #15340: ZstdEncoder not producing data when source is smaller than block size
If the size of the input buffer is smaller than the configured block size (64 KB by default), then `ZstdEncoder.write` only produces an empty buffer. With the default sizes, this makes the encoder unusable for variable size content.

The actual size should be around 25 bytes.

```bash
$ echo -n 'Hello, World'|zstd -v|hexdump -C
*** Zstandard CLI (64-bit) v1.5.5, by Yann Collet ***
/*stdin*\            :208.33%   (    12 B =>     25 B, /*stdout*\)
00000000  28 b5 2f fd 04 58 61 00  00 48 65 6c 6c 6f 2c 20  |(./..Xa..Hello, |
00000010  57 6f 72 6c 64 51 c7 d3  f2                       |WorldQ...|
00000019
```

Of the following tests, only the first test is successful.

```java
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.Unpooled;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.VoidChannelPromise;
import io.netty.channel.embedded.EmbeddedChannel;
import io.netty.handler.codec.compression.ZstdEncoder;
import java.nio.charset.StandardCharsets;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class ZstdEncoderTest {
	static String TEST_CONTENT = "Hello, World";

	@Mock
	private ChannelHandlerContext ctx;

	@BeforeEach
	public void setup() {
		when(ctx.alloc()).thenReturn(ByteBufAllocator.DEFAULT);
	}

	@Test
	void testEncodeWithSmallBlockSize() throws Exception {
		int length = TEST_CONTENT.getBytes(StandardCharsets.UTF_8).length;
		// block size <= size of TEST_CONTENT
		testEncoder(new ZstdEncoder(length, 1024));
	}

	@Test
	void testEncodeWithLargerBlockSize() throws Exception {
		int length = TEST_CONTENT.getBytes(StandardCharsets.UTF_8).length;
		// block size > size of TEST_CONTENT
		testEncoder(new ZstdEncoder(length + 1, 1024));
	}

	@Test
	void testEncodeWithDefaults() throws Exception {
		// default block size of 64kb
		testEncoder(new ZstdEncoder());
	}

	void testEncoder(ZstdEncoder encoder) throws Exception {
		var in = Unpooled.copiedBuffer(TEST_CONTENT, StandardCharsets.UTF_8);
		var chan = new EmbeddedChannel();
		encoder.handlerAdded(ctx);
		var promise = new VoidChannelPromise(chan, true);
		encoder.write(ctx, in, promise);
		
		var outCaptor = ArgumentCaptor.forClass(ByteBuf.class);
		verify(ctx).write(outCaptor.capture(), eq(promise));
		
		var out = outCaptor.getValue();
		assertThat(out.readableBytes()).isPositive();
		out.release();
	}
}
```

### PR DESCRIPTION
**Pull request by skyguard1**
Motivation:
If the size of the input buffer is smaller than the configured block size (64 KB by default), then ZstdEncoder.write only produces an empty buffer. With the default sizes, this makes the encoder unusable for variable size content. This is for fixing the issue(https://github.com/netty/netty/issues/15340)

Modification:

Return the uncompressed data if for small size data

Result:

Fixes #15340

### CODE REVIEW

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 1]
```diff
@@ -75,6 +88,22 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
         testCompressionOfBatchedFlow(data);
     }
 
+    @ParameterizedTest
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: Just use `@Test` as you only will execute this with one input anyway

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 2]
```diff
@@ -75,6 +88,22 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
...
+    @MethodSource("tinyData")
+    public void testCompressionOfTinyData(final ByteBuf data) throws Exception {
+        ZstdEncoder encoder = new ZstdEncoder();
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: Consider using `EmbeddedChannel` and not using mocks

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java [hunk 3]
```diff
@@ -141,6 +141,9 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf in, ByteBuf out) {
                 flushBufferedData(out);
             }
         }
+        if (buffer.isReadable()) {
```
Comment (normanmaurer) [inline codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java:146]: Please add a comment

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java (hunk 1 above)
Comment (skyguard1) [reply codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: Done

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java (hunk 2 above)
Comment (skyguard1) [reply codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: Done

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java (hunk 3 above)
Comment (skyguard1) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java:146]: Done

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 4]
```diff
@@ -21,22 +21,31 @@
 import io.netty.buffer.ByteBufInputStream;
 import io.netty.buffer.Unpooled;
 import io.netty.channel.ChannelHandlerContext;
+import io.netty.channel.VoidChannelPromise;
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 5]
```diff
@@ -21,22 +21,31 @@
...
 import io.netty.channel.embedded.EmbeddedChannel;
+import io.netty.util.CharsetUtil;
 import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
 import org.junit.jupiter.params.ParameterizedTest;
 import org.junit.jupiter.params.provider.MethodSource;
+import org.mockito.ArgumentCaptor;
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 6]
```diff
@@ -21,22 +21,31 @@
...
 import org.mockito.Mock;
 import org.mockito.MockitoAnnotations;
 
+import static org.assertj.core.api.Assertions.assertThat;
 import static org.junit.jupiter.api.Assertions.assertEquals;
 import static org.junit.jupiter.api.Assertions.assertTrue;
+import static org.mockito.ArgumentMatchers.eq;
+import static org.mockito.Mockito.verify;
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 7]
```diff
@@ -21,22 +21,31 @@
...
 import org.junit.jupiter.params.ParameterizedTest;
 import org.junit.jupiter.params.provider.MethodSource;
+import org.mockito.ArgumentCaptor;
 import org.mockito.Mock;
 import org.mockito.MockitoAnnotations;
 
+import static org.assertj.core.api.Assertions.assertThat;
 import static org.junit.jupiter.api.Assertions.assertEquals;
 import static org.junit.jupiter.api.Assertions.assertTrue;
+import static org.mockito.ArgumentMatchers.eq;
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 8]
```diff
@@ -75,6 +84,19 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
         testCompressionOfBatchedFlow(data);
     }
 
+    @Test
+    public void testCompressionOfTinyData() throws Exception {
+        ByteBuf data = Unpooled.copiedBuffer(TEST_CONTENT, CharsetUtil.UTF_8);
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
        ByteBuf data = Unpooled.copiedBuffer("Hello, World", CharsetUtil.UTF_8);
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 9]
```diff
@@ -21,22 +21,31 @@
...
+import static org.mockito.Mockito.verify;
 import static org.mockito.Mockito.when;
 
 public class ZstdEncoderTest extends AbstractEncoderTest {
 
     @Mock
     private ChannelHandlerContext ctx;
 
+    private static String TEST_CONTENT = "Hello, World";
+
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 10]
```diff
@@ -75,6 +84,19 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
         testCompressionOfBatchedFlow(data);
     }
 
+    @Test
+    public void testCompressionOfTinyData() throws Exception {
+        ByteBuf data = Unpooled.copiedBuffer(TEST_CONTENT, CharsetUtil.UTF_8);
+        assertTrue(channel.writeOutbound(data.retain()));
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
        assertTrue(channel.writeOutbound(data));
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 11]
```diff
@@ -75,6 +84,19 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
...
+        assertTrue(channel.finish());
+
+        ByteBuf out = channel.readOutbound();
+        assertThat(out.readableBytes()).isPositive();
+
+        out.release();
+        data.release();
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
        asssertNull(out.readOutbound());
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 12]
```diff
@@ -75,6 +84,19 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
...
 
+    @Test
+    public void testCompressionOfTinyData() throws Exception {
+        ByteBuf data = Unpooled.copiedBuffer(TEST_CONTENT, CharsetUtil.UTF_8);
+        assertTrue(channel.writeOutbound(data.retain()));
+        assertTrue(channel.finish());
+
+        ByteBuf out = channel.readOutbound();
+        assertThat(out.readableBytes()).isPositive();
+
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 13]
```diff
@@ -22,12 +22,15 @@
...
 import org.junit.jupiter.api.BeforeEach;
+import org.junit.jupiter.api.Test;
 import org.junit.jupiter.params.ParameterizedTest;
 import org.junit.jupiter.params.provider.MethodSource;
 import org.mockito.Mock;
 import org.mockito.MockitoAnnotations;
 
+import static org.assertj.core.api.Assertions.assertThat;
 import static org.junit.jupiter.api.Assertions.assertEquals;
 import static org.junit.jupiter.api.Assertions.assertTrue;
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java:36]:
```suggestion
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
```

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 14]
```diff
@@ -75,6 +79,18 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
...
+    @Test
+    public void testCompressionOfTinyData() throws Exception {
+        ByteBuf data = Unpooled.copiedBuffer("Hello, World", CharsetUtil.UTF_8);
+        assertTrue(channel.writeOutbound(data));
+        assertTrue(channel.finish());
+
+        ByteBuf out = channel.readOutbound();
+        assertThat(out.readableBytes()).isPositive();
+        out.release();
+        asssertNull(out.readOutbound());
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
        asssertNull(channel.readOutbound());
```

**Comment by skyguard1** [comment]
Need to add import to fix this build

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 15]
```diff
@@ -75,6 +79,18 @@ public void testCompressionOfSmallBatchedFlow(final ByteBuf data) throws Excepti
...
+    @Test
+    public void testCompressionOfTinyData() throws Exception {
+        ByteBuf data = Unpooled.copiedBuffer("Hello, World", CharsetUtil.UTF_8);
+        assertTrue(channel.writeOutbound(data));
+        assertTrue(channel.finish());
+
+        ByteBuf out = channel.readOutbound();
+        assertThat(out.readableBytes()).isPositive();
+        out.release();
+        asssertNull(channel.readOutbound());
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
        assertNull(channel.readOutbound());
```

**Comment by normanmaurer** [comment]
> Need to add import to fix this build

had a typo... fixed

**Comment by normanmaurer** [comment]
@yawkat PTAL as well

**Review by yawkat — APPROVED** [review]
