### PR TITLE
    Correctly handle client side http2 upgrades when Http2FrameCodec …(9495)

### LINKED ISSUE #9495: NullPointerException during Client Side ClearText Upgrade with new Http2MultiplexHandler.java
When cleartext upgrade is implemented in client side using **HttpClientUpgradeHandler** there is no way to pass the newly created **Http2MultiplexHandler**. 

It seems like we need a way to correctly add Http2MultiplexHandler to the pipeline before calling Http2FrameCodec.onHttpClientUpgrade(...). Since this special case is not handled in HttpClientUpgradeHandler (but seems like this case is correctly taken care in Http2ServerUpgradeCodec). This did lead to the situation that we did not correctly receive the event on the Http2MultiplexHandler and so did not correctly created the Http2StreamChannel for the upgrade stream. Because of this we ended up with an NPE if a frame was dispatched to the upgrade stream later on.

Following is the exception I am receiving when I setup the Http2MultiplexHandler after the upgrade is taken place

va.lang.NullPointerException
        at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$1.visit(AbstractHttp2StreamChannel.java:64) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2FrameCodec$2.visit(Http2FrameCodec.java:200) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.forEachActiveStream(DefaultHttp2Connection.java:971) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.DefaultHttp2Connection.forEachActiveStream(DefaultHttp2Connection.java:208) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2FrameCodec.forEachActiveStream(Http2FrameCodec.java:196) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2ChannelDuplexHandler.forEachActiveStream(Http2ChannelDuplexHandler.java:83) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2MultiplexHandler.channelWritabilityChanged(Http2MultiplexHandler.java:199) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:436) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]

My Code looks something like this
```java
    Http2ClientUpgradeCodec upgradeCodec = new Http2ClientUpgradeCodec(
        "Http2Codec",
        Http2FrameCodecBuilder
        .forClient()
        .initialSettings(createHttp2Settings())
        .build()
        );

    channel.pipeline().addLast(sourceCodec);
    channel.pipeline().addLast(new HttpClientUpgradeHandler(sourceCodec, upgradeCodec, _maxContentLength));
    channel.pipeline().addLast(new Http2ProtocolUpgradeHandler(upgradePromise));
```
I add the Http2MultiplexHandler inside my Http2ProtocolUpgradeHandler during success of cleartext upgrade (as I dont have any other way to add it along with upgradecodec).

Netty Version I used : 4.1.39

When I follow the same approach to fix the serverside upgrade issue as mentioned in 
https://github.com/netty/netty/issues/9314 - it works perfectly form me.

@normanmaurer , @trustin  - let me know if this is a known bug and we are good with my proposed fix. I can give a pull request !

### PR DESCRIPTION
**Pull request by nizarm**
Correctly handle client side http2 upgrades when Http2FrameCodec is used together with Http2MultiplexHandler (#9495)

    Motivation:

    In the release (4.1.37) we introduced Http2MultiplexHandler as a
    replacement of Http2MultiplexCodec. This did split the frame parsing from
    the multiplexing to allow a more flexible way to handle frames and to make
    the code cleaner. Unfortunally we did miss to special handle this in
    Http2ClientUpgradeCodec and so did not correctly add Http2MultiplexHandler
    to the pipeline before calling Http2FrameCodec.onHttpClientUpgrade(...).
    This did lead to the situation that we did not correctly receive the event
    on the Http2MultiplexHandler and so did not correctly created the
    Http2StreamChannel for the upgrade stream. Because of this we ended up
    with an NPE if a frame was dispatched to the upgrade stream later on.

    Modifications:

    - Correctly add Http2MultiplexHandler to the pipeline before calling Http2FrameCodec.onHttpClientUpgrade(...)

    Result:

    Fixes #9495

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nizarm thanks I will have a look... that said can you sign our ICLA in the meantime: https://netty.io/s/icla

File: codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java [hunk 1]
```diff
@@ -74,37 +87,63 @@ public Http2ClientUpgradeCodec(Http2ConnectionHandler connectionHandler) {
...
+
+    /**
+     * Creates the codec providing an upgrade to the given handler for HTTP/2.
+     *
+     * @param handlerName the name of the HTTP/2 connection handler to be used in the pipeline,
+     *                    or {@code null} to auto-generate the name
+     * @param connectionHandler the HTTP/2 connection handler
+     */
+    public Http2ClientUpgradeCodec(String handlerName, Http2ConnectionHandler connectionHandler,
+        Http2MultiplexHandler http2MultiplexHandler) {
```
Comment (normanmaurer) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java]: I wonder if we should make this more consistent with what we have on the server side:

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ServerUpgradeCodec.java#L107

Basically:

public Http2ClientUpgradeCodec(Http2FrameCodec http2Codec, ChannelHandler... handlers) {
     ...
}

File: codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java [hunk 2]
```diff
@@ -74,37 +87,63 @@ public Http2ClientUpgradeCodec(Http2ConnectionHandler connectionHandler) {
...
+        throws Exception {
+        try {
+            // Add the handler to the pipeline.
+            ctx.pipeline().addAfter(ctx.name(), handlerName, upgradeToHandler);
+
+            // Add the Http2 Multiplex handler as this handler handle events produced by the connectionHandler.
+            // See https://github.com/netty/netty/issues/9495
+            if (http2MultiplexHandler != null) {
+                final String name = ctx.pipeline().context(connectionHandler).name();
+                ctx.pipeline().addAfter(name, null, http2MultiplexHandler);
```
Comment (normanmaurer) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java]: See above .... I think we want to make this more consistent with what we have in the server handler:

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ServerUpgradeCodec.java#L152

**Comment by nizarm** [comment]
> @nizarm thanks I will have a look... that said can you sign our ICLA in the meantime: https://netty.io/s/icla

Thanks, I have already submitted ICLA.

**Comment by normanmaurer** [comment]
@nizarm thanks a lot... let me know once you addressed my comments and I will have a look again.

File: codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java (hunk 2 above)
Comment (nizarm) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java]: In fact I did try this approach initially and realized I will be breaking existing public constructor of Http2ClientUpgradeCodec. For example, contrary to Http2ServerUpgradeCodec, the Http2ClientUpgradeCodec has a public constructor that allow users to specify a separate ChannelHandler for upgradeTo as shown bleow

```java
public Http2ClientUpgradeCodec(Http2FrameCodec frameCodec, ChannelHandler upgradeToHandler)
```
I havent used this signature personnally - but not sure if other users of netty out there will be leveraging this to pass separate upgradeToHandler other than the frameCodec.

Adding the above proposed approach will introduce ambiguity to upradeToHandler unless we strongly type. 

Let me know your thoughts, if we are okay breaking this constructor - I will go ahead and  make the change consistent with Http2ServerUpgradeCodec

Comment (normanmaurer) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java]: ah yeah you are right. I did not realise it... Then its ok as it is. Just please add an extra test case to `Http2ClientUpgradeCodecTest`.

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodecTest.java [hunk 3]
```diff
@@ -33,33 +33,52 @@
...
+        }
+
         codec.setUpgradeHeaders(ctx, request);
         // Flush the channel to ensure we write out all buffered data
         channel.flush();
 
         codec.upgradeTo(ctx, null);
         assertNotNull(channel.pipeline().get("connectionHandler"));
 
+        if(multiplexer != null) {
```
Comment (normanmaurer) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodecTest.java]: Missing space after if

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@mosesn thanks for the review and feedback :)

**Comment by nizarm** [comment]
Thanks @normanmaurer  and @mosesn for approving these changes. Since I dont have write access, who will help merge this change? The merging of this change is automatically taken care?

**Comment by normanmaurer** [comment]
@nizarm thanks a lot! I just merged it...
