### PR TITLE
codec-http2: Better keep track of nameLength in HpackDecoder.decode

### LINKED ISSUE #7511: double counting header name length in http/2
### Expected behavior

A header with a name of length X and a value of length Y gets considered as being length X + Y in total.

### Actual behavior

A header with a name of length X and a value of length Y gets considered as being length 2X + Y in total.  I think this is where the bug is:

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java#L262

### Steps to reproduce

Use hpack decoder to decode a header.

### Netty version

4.1.16.Final

### JVM version (e.g. `java -version`)

jdk8

### PR DESCRIPTION
**Pull request by mosesn**
Motivation:

http/2 counts header sizes somewhat inconsistently.  Sometimes, headers
which are substantively less than the header list size will be measured
as longer than the header list size.

Modifications:

Keep better track of the nameLength of a given name, so that we don't
accidentally end up reusing a nameLength.

Result:

More consistent measurement of header list size.

Fixes #7511.

### CODE REVIEW

File: codec-http2/src/test/java/io/netty/handler/codec/http2/HpackDecoderTest.java [hunk 1]
```diff
@@ -455,4 +455,28 @@ public void testDecodeLargerThanMaxHeaderListSizeButSmallerThanMaxHeaderListSize
...
+            HpackEncoder hpackEncoder = new HpackEncoder(true);
+
+            // encode headers that are slightly larger than maxHeaderListSize
+            // but smaller than maxHeaderListSizeGoAway
+            Http2Headers toEncode = new DefaultHttp2Headers();
+            toEncode.add(String.format("%03000d", 0).replace('0', 'f'), "value");
+            toEncode.add("accept", "value");
+            hpackEncoder.encodeHeaders(1, in, toEncode, NEVER_SENSITIVE);
+
+            // decode the headers, we should get an exception, but
```
Comment (normanmaurer) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/HpackDecoderTest.java]: this comment is a bit confusing... when we "get an exception" shouldn't we need to catch it ?

Comment (mosesn) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/HpackDecoderTest.java]: oh, I just copy/pasted this from the previous test.  I'll just delete it.

Comment (mosesn) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/HpackDecoderTest.java]: update, PTAL

**Comment by Scottmitch** [comment]
thanks @mosesn !
