### PR TITLE
Fix client_max_window_bits parameter handling in permessage-deflate extension

### LINKED ISSUE #16005: WebSocketServerExtensionHandler ignore client_max_window_bits parameters
In `PerMessageDeflateServerExtensionHandshaker` ignores the  `client_max_window_bits` parameter,
```
 if (CLIENT_MAX_WINDOW.equalsIgnoreCase(parameter. getKey())) {
// use preferred clientWindowSize because client is compatible with customization
clientWindowSize = preferredClientWindowSize;
} 
```
just use the preferredClientWindowSize. And in `PerMessageDeflateClientExtensionHandshaker` uses  `Integer.parseInt()` parsing `client_max_window_bits` parameters
```
clientWindowSize = Integer.parseInt(parameter.getValue());
if (clientWindowSize > MAX_WINDOW_SIZE || clientWindowSize < MIN_WINDOW_SIZE) {
succeed = false;
}
```
, But in the https://datatracker.ietf.org/doc/html/rfc7692#section-7.1.2 write 
```
A client MAY include the "client_max_window_bits" extension parameter
in an extension negotiation offer.  This parameter has no value or a
decimal integer value without leading zeroes between 8 to 15.
``` 
So a `NumberFormatException` might be thrown here. I don't know why `PerMessageDeflateClientExtensionHandshaker` can parse `server_max_window_bits` but  in `PerMessageDeflateServerExtensionHandshaker` the `client_max_window_bits` were ignored. I can not found this in the rfc document. I think we need to fix this

### PR DESCRIPTION
**Pull request by nikitanagar08**
Fixes #16005

Per RFC 7692 section 7.1.2.1, the client_max_window_bits parameter may have a value or no value.

**Problem:**
- Server-side: Always ignored client's requested value, using preferredClientWindowSize instead
- Client-side: Threw NumberFormatException when parameter had no value (null)

**Changes:**
- PerMessageDeflateServerExtensionHandshaker: Parse client_max_window_bits value when present
- PerMessageDeflateClientExtensionHandshaker: Handle null value gracefully to avoid NumberFormatException

**Tests:**
- All existing tests pass (13 tests total)
- Added 4 new regression tests

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nikitanagar08 did you sign our ICLA yet ? https://netty.io/s/icla

**Comment by nikitanagar08** [comment]
@normanmaurer Yes

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateClientExtensionHandshaker.java [hunk 1]
```diff
@@ -232,10 +232,19 @@ public WebSocketClientExtension handshakeExtension(WebSocketExtensionData extens
...
+                    // RFC 7692: client_max_window_bits may have a value or no value
+                    String value = parameter.getValue();
+                    if (value != null) {
+                        try {
+                            clientWindowSize = Integer.parseInt(value);
+                            if (clientWindowSize > MAX_WINDOW_SIZE || clientWindowSize < MIN_WINDOW_SIZE) {
+                                succeed = false;
+                            }
+                        } catch (NumberFormatException e) {
+                            succeed = false;
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateClientExtensionHandshaker.java:241]: shouldn't we let it bubble up in this case ? If there is a value it should be valid and if not we should report it.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateServerExtensionHandshaker.java [hunk 2]
```diff
@@ -220,8 +220,21 @@ public WebSocketServerExtension handshakeExtension(WebSocketExtensionData extens
...
+                // RFC 7692: client_max_window_bits may have a value or no value
+                String value = parameter.getValue();
+                if (value != null) {
+                    try {
+                        clientWindowSize = Integer.parseInt(value);
+                        if (clientWindowSize > MAX_WINDOW_SIZE || clientWindowSize < MIN_WINDOW_SIZE) {
+                            deflateEnabled = false;
+                        }
+                    } catch (NumberFormatException e) {
+                        deflateEnabled = false;
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateServerExtensionHandshaker.java:229]: Again I think we should let this exception bubble up.

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateClientExtensionHandshaker.java (hunk 1 above)
Comment (nikitanagar08) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateClientExtensionHandshaker.java:241]: Fixed - removed try-catch block to let NumberFormatException bubble up as requested.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateServerExtensionHandshaker.java (hunk 2 above)
Comment (nikitanagar08) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateServerExtensionHandshaker.java:229]: Fixed - removed try-catch block to let NumberFormatException bubble up as requested.

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@nikitanagar08 thanks!
