### PR TITLE
JdkZlibEncoder can use pooled heap buffers for deflater input

### LINKED ISSUE #11890: JdkZlibEncoder: heap allocated arrays for deflater input generate memory pressure under load
### Expected behavior

I am writing a high-throughput client for a custom protocol over TCP;  the protocol has the option of compressing contents using zlib encoding,  In order to reach performance targets I accumulate encoded frames into batches stored in off-heap pooled ByteBufs and then write the contents to the Netty Channel.  When running load tests with compression enabled I expected very little GC activity.

### Actual behavior

When running load tests with compression enabled I see a lot of GC activity.  This is due to byte arrays allocated on the heap to provide input to zlib Deflater.  When the incoming ByteBuf is direct, we allocate a byte array on the heap and copy the contents into it.

### Steps to reproduce

- Create a Netty client that uses a ZlibEncoder
- Write direct ByteBufs to the Channel in a loop
- Observe the increase in memory consumption (using system tools or a profiler)

### Netty version
```
4.1.70.Final
```

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

### OS version (e.g. `uname -a`)
```Linux peso 5.10.0-1051-oem #53-Ubuntu SMP Thu Oct 28 08:11:53 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

### PR DESCRIPTION
**Pull request by dferstay**
Motivation:

Previously, when the input ByteBuf was not heap allocated we copied the
input into a new byte array allocated on the heap for every encode() call.
This puts high-throughput clients that use the JdkZlibEncoder under memory
pressure.

Modifications:

Now, when the input ByteBuf is not heap allocated we copy the input into a
heap ByteBuf allocated from the configured ByteBufAllocator (which might be pooled), releasing it after
the encode() has completed.

Result:

The result is less heap allocation and GC activity when the PooledByteBufAllocator is used (which is the default)

Fixes #11890

Signed-off-by: Daniel Ferstay <dferstay@splunk.com>

### CODE REVIEW

**Comment by dferstay** [comment]
Below is a memory profile before the change.

jdkzlibencoder_heap_alloc

**Comment by dferstay** [comment]
After the change `JdkZlibEncoder.encode` is not burning so bright.

jdkzlibencoder_pooled_heap_alloc

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java [hunk 1]
```diff
@@ -200,42 +201,50 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf uncompressed, ByteBuf o
...
+        ByteBuf heapBuf = null;
+        try {
+            if (uncompressed.hasArray()) {
+                // if it is backed by an array we not need to do a copy at all
+                inAry = uncompressed.array();
+                offset = uncompressed.arrayOffset() + uncompressed.readerIndex();
+                // skip all bytes as we will consume all of them
+                uncompressed.skipBytes(len);
+            } else {
+                heapBuf = PooledByteBufAllocator.DEFAULT.heapBuffer(len, len);
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:213]:
```suggestion
                heapBuf = ctx.alloc().heapBuffer(len, len);
```

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java [hunk 2]
```diff
@@ -200,42 +201,50 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf uncompressed, ByteBuf o
...
+                deflate(out);
+                if (deflater.needsInput()) {
+                    // Consumed everything
+                    break;
+                } else {
+                    if (!out.isWritable()) {
+                        // We did not consume everything but the buffer is not writable anymore. Increase the capacity to
+                        // make more room.
+                        out.ensureWritable(out.writerIndex());
+                    }
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:241]: Please revert the formatting changes.

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java [hunk 3]
```diff
@@ -200,42 +201,50 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf uncompressed, ByteBuf o
...
 
-        if (writeHeader) {
-            writeHeader = false;
-            if (wrapper == ZlibWrapper.GZIP) {
-                out.writeBytes(gzipHeader);
+            if (writeHeader) {
+                writeHeader = false;
+                if (wrapper == ZlibWrapper.GZIP) {
+                    out.writeBytes(gzipHeader);
+                }
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:223]: please revert formatting changes

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java [hunk 4]
```diff
@@ -200,42 +201,50 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf uncompressed, ByteBuf o
...
             }
-        }
 
-        if (wrapper == ZlibWrapper.GZIP) {
-            crc.update(inAry, offset, len);
-        }
+            if (wrapper == ZlibWrapper.GZIP) {
+                crc.update(inAry, offset, len);
+            }
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:228]: please revert formatting changes

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java [hunk 5]
```diff
@@ -200,42 +201,50 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf uncompressed, ByteBuf o
...
-            inAry = uncompressed.array();
-            offset = uncompressed.arrayOffset() + uncompressed.readerIndex();
-            // skip all bytes as we will consume all of them
-            uncompressed.skipBytes(len);
-        } else {
-            inAry = new byte[len];
-            uncompressed.readBytes(inAry);
-            offset = 0;
-        }
+        ByteBuf heapBuf = null;
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:204]: make this final and assign in the `if / else ` blocks

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Comment by normanmaurer** [comment]
Also please sign or ICLA: https://netty.io/s/icla

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java (hunk 1 above)
Comment (dferstay) [reply codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java]: Thank you; done.

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java (hunk 5 above)
Comment (dferstay) [reply codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:203]: @normanmaurer ,
> make this final and assign in the if / else blocks

I introduced a `try / finally` so that we would not leak the reference to the allocated heap buffer; this accounts for the formatting changes above, and it also confuses the Java compiler when making `heapBuf` final; see attached screenshot.
Screenshot from 2021-12-06 10-00-16

**Comment by dferstay** [comment]
> Also please sign or ICLA: https://netty.io/s/icla

Signed :)

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java (hunk 5 above)
Comment (normanmaurer) [reply codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:203]: got it...

**Comment by normanmaurer** [comment]
@dferstay can you please revert the formatting changes ?

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java (hunk 2 above)
Comment (dferstay) [reply codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:240]: @normanmaurer ,
Are you referring to the additional indentation?  If so, it is due to the addition of the `try / finally` block to ensure that the allocated heapBuf is released on method return.  Do do you want me to remove the `try / finally`?

Comment (normanmaurer) [reply codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:240]: Check the checkstyle errors

Comment (dferstay) [reply codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:240]: Got it; the checkstyle errors should now be addressed.

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java [hunk 6]
```diff
@@ -200,42 +200,50 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf uncompressed, ByteBuf o
...
-            if (deflater.needsInput()) {
-                // Consumed everything
-                break;
-            } else {
-                if (!out.isWritable()) {
-                    // We did not consume everything but the buffer is not writable anymore. Increase the capacity to
-                    // make more room.
-                    out.ensureWritable(out.writerIndex());
+            deflater.setInput(inAry, offset, len);
+            for (; ; ) {
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java]:
```suggestion
            for (;;) {
```

File: codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java [hunk 7]
```diff
@@ -200,42 +200,50 @@ protected void encode(ChannelHandlerContext ctx, ByteBuf uncompressed, ByteBuf o
...
-            if (deflater.needsInput()) {
-                // Consumed everything
-                break;
-            } else {
-                if (!out.isWritable()) {
-                    // We did not consume everything but the buffer is not writable anymore. Increase the capacity to
-                    // make more room.
-                    out.ensureWritable(out.writerIndex());
+            deflater.setInput(inAry, offset, len);
+            for (; ;) {
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/JdkZlibEncoder.java:230]:
```suggestion
            for (;;) {
```

**Comment by normanmaurer** [comment]
@dferstay thanks a lot ! Would be cool if you can add details to the adopters page: https://netty.io/wiki/adopters.html

**Comment by dferstay** [comment]
> @dferstay thanks a lot ! Would be cool if you can add details to the adopters page: https://netty.io/wiki/adopters.html

@normanmaurer,
Cheers; will do! :+1:
