### PR TITLE
Fixed #11379, validate fixed header bits.

### LINKED ISSUE #11379: [codec-mqtt] Netty tries to interpret QOS level on CONNECT package
The MQTT CONNECT package FIXED header contains only the MQTT Control Packet type in the first 4 bits. The remaining bits in the first byte are reserved. ([SPEC](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180841))
Currently, the MqttDecoder parses the fixed header the same for all packet types, and thus tries to interpret the reserved bits of the fixed header in the CONNECT packet:
https://github.com/netty/netty/blob/c78afbc4f13ac4d6cb488fb14b31379960f03fff/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L166
 https://github.com/netty/netty/blob/c78afbc4f13ac4d6cb488fb14b31379960f03fff/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L185 

Apparently, the HiveMQ client sets the remaining bits to all 1, resulting the MqttDecoder to try to interpret bits 2 + 3 of the reserved bits as "QOS 3" resulting in an exception.

### Expected behavior
Ignore reserved bits

### Actual behavior
tries to interpret reserved bits, resulting in an exception.
Caused by: java.lang.IllegalArgumentException: invalid QoS: 3

### Steps to reproduce
Send a CONNECT packet with the reserved bits set to 1

### Minimal yet complete reproducer code (or URL to code)
Working on it

### Netty version
netty-4.1.65

### JVM version (e.g. `java -version`)
11

### OS version (e.g. `uname -a`)
Linux

### PR DESCRIPTION
**Pull request by hylkevds**
Motivation:
The MQTT spec states that the bits in the fixed header must be set to specific values depending on message type. If a client sends a message with the wrong bits, the server must treat the message as malformed. Netty did not check the value of the reserved bits in the fixed header.

See:
MQTT3.1.1: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180835
MQTT 5.0: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901023

Modification:
Add validation checks to MqttDecoder.java
Add unit tests to MqttCodecTest.java 
Fixed two instances where messages were generated for other unit tests with an incorrect fixed header.

Result:
Fixes #11379.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@hylkevds did you sign our ICLA ? 

https://netty.io/s/icla

**Comment by normanmaurer** [comment]
Please fix:

```
Error:  codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java:[160,9] (extension) NoHttp: http:// URLs are not allowed but got 'http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html'. Use https:// instead.
```

File: codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java [hunk 1]
```diff
@@ -153,7 +153,11 @@ private MqttMessage invalidMessage(Throwable cause) {
     }
 
     /**
-     * Decodes the fixed header. It's one byte for the flags and then variable bytes for the remaining length.
+     * Decodes the fixed header. It's one byte for the flags and then variable
+     * bytes for the remaining length.
+     *
+     * @see
+     * http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180841
```
Comment (normanmaurer) [inline codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java:160]:
```suggestion
     * https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180841
```

**Comment by hylkevds** [comment]
I just signed the ICLA.

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@hylkevds thanks a lot!
