### PR TITLE
Do not fail on runtime when an older version of Log4J2 is on the clas…

### LINKED ISSUE #8217: Log4J2LoggerFactory depends on a log4j2 version which does not work on Java 6
### Expected behavior
Netty logging works via log4j2 while on Java 6

### Actual behavior
Log4j2 2.4+ depends on Java 7. Netty depends on log4j2 methods which are present only in newer versions. When older log4j2 version is on a classpath then Netty fails to initialize itself due `AbstractMethodError` while logging. 

### Steps to reproduce
Have Netty 4.1.27 and log4j2 on a classpath and run `InternalLoggerFactory.getInstance("foo").debug("bar", new Object));`

### Minimal yet complete reproducer code (or URL to code)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>info.jerrinot</groupId>
    <artifactId>netty-logging-issue-reproducer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>4.1.27.Final</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.3</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
    </dependencies>
</project>
```

```java
package info.jerrinot.nettyloggingissue;

import io.netty.util.internal.logging.InternalLoggerFactory;
import org.junit.Test;

public class ReproducerTest {

    @Test
    public void testNettyLogging() {
        InternalLoggerFactory.getInstance("foo").debug("bar", new Object());
    }
}
```

### Netty version
4.1.27

### JVM version (e.g. `java -version`)
irrelevant
### OS version (e.g. `uname -a`)
irrelevant

### PR DESCRIPTION
**Pull request by normanmaurer**
…spath.

Motivation:

At the moment we will just assume the correct version of log4j2 is used when we find it on the classpath. This may lead to an AbstractMethodError at runtime. We should not use log4j2 if the version is not correct.

Modifications:

Check on class loading if we can use Log4J2 or not.

Result:

Fixes #8217.

### CODE REVIEW

File: common/src/main/java/io/netty/util/internal/logging/Log4J2Logger.java [hunk 1]
```diff
@@ -16,101 +16,193 @@
...
 
-    /** {@linkplain AbstractInternalLogger#EXCEPTION_MESSAGE} */
-    private static final String EXCEPTION_MESSAGE = "Unexpected exception:";
+    private final Logger logger;
 
     Log4J2Logger(Logger logger) {
-        super((ExtendedLogger) logger, logger.getName(), logger.getMessageFactory());
+        super(logger.getName());
+        if (VARARGS_ONLY) {
+            throw new UnsupportedOperationException("Log4J2 version missmatch");
```
Comment (carl-mastrangelo) [inline common/src/main/java/io/netty/util/internal/logging/Log4J2Logger.java]: mismatch*

**Comment by normanmaurer** [comment]
@ejona86 just because it is cleaner to wrap and not extend and depend on the fact that their method signature match ours. Let me separate the change tho.

**Comment by normanmaurer** [comment]
@ejona86 nevermind I was wrong... We need to extend ExtendedLoggerWrapper to have `%F` work correctly. Let me revert most of this pr.

**Comment by normanmaurer** [comment]
@ejona86 adjusted...

**Comment by normanmaurer** [comment]
Let me pull this in... we can do a followup if we feel this is needed.
