### PR TITLE
Merge WebSocket extensions, close #10792

### LINKED ISSUE #10792: WebSocketClientExtensionHandler doesn't check if extensions are already present in sec-websocket-extensions header
### Expected behavior

Netty verifies that extensions are not already present in sec-websocket-extensions header before appending them.

### Actual behavior

Netty doesn't check, possibly resulting in duplicated values.

### Steps to reproduce

Just read existing code: https://github.com/netty/netty/blob/netty-4.1.54.Final/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketClientExtensionHandler.java#L65-L73

### Netty version

4.1.54

### JVM version (e.g. `java -version`)

Irrelevant

### OS version (e.g. `uname -a`)

Irrelevant

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

We currently append extensions to the user defined "sec-websocket-extensions" headers. This can cause duplicated entries.

Modifications:

* Replace existing `WebSocketExtensionUtil#appendExtension` private helper with a new `computeMergeExtensionsHeaderValue`. User defined parameters have higher precedence.
* Add tests (existing method wasn't tested)
* Reuse code for both client and server side (code was duplicated).

Result:

No more duplicated entries when user defined extensions overlap with the ones Netty generated.

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java [hunk 1]
```diff
@@ -147,8 +147,8 @@ public void operationComplete(ChannelFuture future) {
                     }
                 });
 
-                if (headerValue != null) {
-                    headers.set(HttpHeaderNames.SEC_WEBSOCKET_EXTENSIONS, headerValue);
+                if (newHeaderValue != null) {
```
Comment (slandelle) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java:150]: @normanmaurer This was missing in the previous PR.

**Comment by slandelle** [comment]
CI looks fine and tests are successful locally on my side.
