### PR TITLE
Fixed the haproxy message mem leak issue

### LINKED ISSUE #9201: HAProxyMessage memory leak due unreleased TLVs
`HAProxyMessage` isn't a `ReferencedCounted` object. 
A component consuming an `HAProxyMessage` object and not passing it further might not release it, while it should be released as it contains a list of TLVs created in the static function `readNextTLV`:

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java#L235-L241

Notice that this function retains a slice of the original header ByteBuf increasing its refCnt and causing a possible memory leak if one forgets to release them explicitly:

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java#L296

I would expect `HAProxyMessage` to implement `ReferencedCounted` and release the TLVs in a similar fashion to: `haProxyMessage.tlvs().forEach(tlv -> tlv.release());` 

We have found this issue only after we had leaks.

Furthermore, it seems that slices are purposely retained as seen in Netty tests, am I missing something?

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-haproxy/src/test/java/io/netty/handler/codec/haproxy/HAProxyMessageDecoderTest.java#L642-L650

### Netty version
4.1.36

### PR DESCRIPTION
**Pull request by qeesung**
Motivation:

`HAProxyMessage` should be released as it contains a list of TLV which hold a `ByteBuf`, otherwise, it may cause memory leaks.

Modification:

Let `HAProxyMessage` inherit `ByteBufHolder` and override `ByteBufHolder`'s method so that it can release itself as well as TLV list

Result:

Fixes #9201

### CODE REVIEW

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 1]
```diff
@@ -117,16 +98,15 @@ private HAProxyMessage(
...
-        }
-
+    static HAProxyMessage decodeStructHeader(ByteBuf header) {
+        checkNotNull(header, "header");
         if (header.readableBytes() < 16) {
             throw new HAProxyProtocolException(
                     "incomplete header: " + header.readableBytes() + " bytes (expected: 16+ bytes)");
         }
 
+        ByteBuf rawContent = header.retain();
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: imho we should call `retain` as last method to ensure we can not leak

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 2]
```diff
@@ -306,17 +286,18 @@ private static HAProxyTLV readNextTLV(final ByteBuf header) {
      * @return                           {@link HAProxyMessage} instance
      * @throws HAProxyProtocolException  if any portion of the header is invalid
      */
-    static HAProxyMessage decodeHeader(String header) {
-        if (header == null) {
+    static HAProxyMessage decodeStringHeader(ByteBuf header) {
+        String headerStr = header.toString(CharsetUtil.US_ASCII);
+        if (headerStr == null) {
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: `toString(...)` will never return null so this does not look correct. Maybe it should check if the buffer is empty ?

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 3]
```diff
@@ -519,4 +498,93 @@ public int destinationPort() {
...
     }
+
+    private HAProxyMessage copyMessage(List<HAProxyTLV> tlvs, ByteBuf content) {
+        return new HAProxyMessage(protocolVersion, command, proxiedProtocol, sourceAddress,
+                                  destinationAddress, sourcePort, destinationPort, tlvs, content);
+    }
+
+    @Override
+    public HAProxyMessage copy() {
+        List<HAProxyTLV> copiedTLVs = new LinkedList<HAProxyTLV>();
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: why not an `ArrayList` to reduce the GC ?

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 4]
```diff
@@ -519,4 +498,93 @@ public int destinationPort() {
...
+        for (HAProxyTLV tlv : tlvs) {
+            copiedTLVs.add(tlv.copy());
+        }
+        return copyMessage(copiedTLVs, content().copy());
+    }
+
+    @Override
+    public ByteBufHolder duplicate() {
+        List<HAProxyTLV> duplicatedTLVs = new LinkedList<HAProxyTLV>();
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: why not an `ArrayList` to reduce the GC ?

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 5]
```diff
@@ -519,4 +498,93 @@ public int destinationPort() {
...
+        for (HAProxyTLV tlv : tlvs) {
+            duplicatedTLVs.add(tlv.duplicate());
+        }
+        return copyMessage(duplicatedTLVs, content().duplicate());
+    }
+
+    @Override
+    public ByteBufHolder retainedDuplicate() {
+        List<HAProxyTLV> retainedDuplicatedTLVs = new LinkedList<HAProxyTLV>();
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: why not an `ArrayList` to reduce the GC ?

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 6]
```diff
@@ -519,4 +498,93 @@ public int destinationPort() {
...
+    public ByteBufHolder duplicate() {
+        List<HAProxyTLV> duplicatedTLVs = new LinkedList<HAProxyTLV>();
+        for (HAProxyTLV tlv : tlvs) {
+            duplicatedTLVs.add(tlv.duplicate());
+        }
+        return copyMessage(duplicatedTLVs, content().duplicate());
+    }
+
+    @Override
+    public ByteBufHolder retainedDuplicate() {
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Should return `HAProxyMessage `.

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 7]
```diff
@@ -519,4 +498,93 @@ public int destinationPort() {
...
+    public HAProxyMessage copy() {
+        List<HAProxyTLV> copiedTLVs = new LinkedList<HAProxyTLV>();
+        for (HAProxyTLV tlv : tlvs) {
+            copiedTLVs.add(tlv.copy());
+        }
+        return copyMessage(copiedTLVs, content().copy());
+    }
+
+    @Override
+    public ByteBufHolder duplicate() {
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Should return `HAProxyMessage `.

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 1 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done :-)

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 2 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 3 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 4 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 5 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 6 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 7 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 8]
```diff
@@ -25,32 +26,12 @@
...
-            HAProxyProtocolVersion.V2, HAProxyCommand.PROXY, HAProxyProxiedProtocol.UNKNOWN, null, null, 0, 0);
-
-    /**
-     * Version 2 proxy protocol message for local requests. Per spec, we should use an unspecified protocol and family
-     * for 'LOCAL' commands. Per spec, when the proxied protocol is 'UNKNOWN' we must discard all other header values.
-     */
-    private static final HAProxyMessage V2_LOCAL_MSG = new HAProxyMessage(
-            HAProxyProtocolVersion.V2, HAProxyCommand.LOCAL, HAProxyProxiedProtocol.UNKNOWN, null, null, 0, 0);
-
+public final class HAProxyMessage extends DefaultByteBufHolder {
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: imho we should not extend `DefaultByteBufHolder` but `AbstractReferenceCounted`. There is no need to hold a reference to the "original" `ByteBuf` here.

Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: I like this idea, I think if `HAProxyMessage` inherits `AbstractReferenceCounted`, then maybe we can make the implementation a bit simpler. Just overwrite the `AbstractReferenceCounted.deallocate()` method and release the TLV list in this method, like this:
```java
class HAProxyMessage extends AbstractReferenceCounted {
    @Override
    public HAProxyMessage retain() {
        return (HAProxyMessage) super.retain();
    }
    // overwrite other methods...

    @Override
    protected void deallocate() {
       for (HAProxyTLV tlv : this.tlvs){
           tlv.release();
       }
    }
}
```
In this case, the TLV list will be released together when `HAProxyMessage` is released, but when `HAProxyMessage refCnt` is increased, the TLV `refCnt` will not increase with `HAProxyMessage`.

@normanmaurer What do you think of this? Will it cause other additional problems?

By the way, I found that this is also the case in DNSMessage:
https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-dns/src/main/java/io/netty/handler/codec/dns/AbstractDnsMessage.java#L378-L388

Comment (normanmaurer) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: @qeesung good question...Let me think about it but in general I would say it is fine.

Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: @normanmaurer It's done in this way. Could you please review it again :-)?

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 9]
```diff
@@ -519,4 +516,40 @@ public int destinationPort() {
...
+    }
+
+    @Override
+    public HAProxyMessage retain() {
+        return (HAProxyMessage) super.retain();
+    }
+
+    @Override
+    public HAProxyMessage retain(int increment) {
+        return (HAProxyMessage) super.retain(increment);
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: I think you also want to call `leak.record`  in the other `touch`, `retain` and `release` methods.

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 10]
```diff
@@ -519,4 +516,40 @@ public int destinationPort() {
...
+    }
+
+    @Override
+    protected void deallocate() {
+        for (HAProxyTLV tlv : tlvs) {
+            tlv.release();
+        }
+
+        final ResourceLeakTracker<HAProxyMessage> leak = this.leak;
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: put all of this in a finally block, just in case.

Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java (hunk 9 above)
Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 11]
```diff
@@ -519,4 +516,67 @@ public int destinationPort() {
...
+            leak.record(hint);
+        }
+        return this;
+    }
+
+    @Override
+    public HAProxyMessage retain() {
+        if (leak != null) {
+            leak.record();
+        }
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: you can move this to a method and re-use....


```
private void tryRecord() {
    if (leak != null) {
        leak.record();
    }
}
```

Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done!

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 12]
```diff
@@ -519,4 +516,61 @@ public int destinationPort() {
...
+
+    @Override
+    public HAProxyMessage touch() {
+        tryRecord();
+        return (HAProxyMessage) super.touch();
+    }
+
+    @Override
+    public HAProxyMessage touch(Object hint) {
+        tryRecord();
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: for this you need to duplicate the code as you should pass down the `hint`.

Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: I am sorry for my carelessness. Done!

File: codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java [hunk 13]
```diff
@@ -358,30 +365,20 @@ static HAProxyMessage decodeHeader(String header) {
...
-            sb.append(Integer.toHexString(header.readUnsignedShort()));
-            sb.append(':');
-            sb.append(Integer.toHexString(header.readUnsignedShort()));
-            sb.append(':');
-            sb.append(Integer.toHexString(header.readUnsignedShort()));
+            for (int i = 0; i < ipv6Len; i++) {
+                sb.append(Integer.toHexString(header.readUnsignedShort()));
+                sb.append(':');
+            }
+            sb.setLength(sb.length() - 1);
```
Comment (normanmaurer) [inline codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: nit... you can move this out of this block and so remove the same code above.

Comment (qeesung) [reply codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java]: Done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by qeesung** [comment]
@normanmaurer Three more changes have been added. Cloud you please review them again?

1.  Remove all static unknown `HAProxyMessages` and replace calling static methods to generate a new one. This avoids the problem of users releasing static unknown `HAProxyMessages`.
2. After checking the validity of all the construction parameters of `HAProxyMessage`, the `ResourceLeakDetector` is used to trace the message, which can avoid the memory leak alarm when the constructor throws an exception.
3. Fix memory leaks that `HAProxyMessage` is not released in test cases

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by qeesung** [comment]
@netty-bot test this please

**Comment by qeesung** [comment]
@normanmaurer It seems that a test case failed because of address conflict. How can I trigger the Jenkins build again?

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by qeesung** [comment]
@normanmaurer Do you have time to help check why there is address conflict in Java 11? I can't find any problems. Is it possible that the Jenkins machine has a TCP connection in the `TIME_WAIT` state?

**Comment by normanmaurer** [comment]
This is the "in-vm" transport.. Not sure why this happens. I think it is safe to just merge this PR and I will investigate.

**Comment by normanmaurer** [comment]
@qeesung thanks a lot!
