### PR TITLE
Fix support for optional encoders errors in HttpContentCompressor

### LINKED ISSUE #11581: HttpContentCompressor doesn't handle optional encoders
Hi,

Following #11480 and the use of `CompressionOptions` it appears the `HttpContentCompressor` doesn't handle optional encoders such as Brotli and Zstd properly when using `CompressionOptions`. 

For instance, if brotli4j is missing at runtime, Http compression is actually  completely broken as the constructor always tries to create `BrotliOptions` even if not specified which result in an `IllegalStateException`.

Then, if zstd-jni is missing at runtime, a request with `accept-encoding: gzip, deflate, zstd` will fail since `determineEncoding()` still returns zstd resulting in a `NoClassDefFoundError` when the `beginEncode()` method is invoked.

This behaviour is actually quite different than what's implemented in `CompressorHttp2ConnectionEncoder` which only considers the encoders for which `CompressionOptions` have been specified.

### Expected behavior

When using the `HttpContentCompressor` with `CompressionOptions` without brotly4j or zstd-jni at runtime, we expect the brotly and zstd encoding to be ignored, fallbacking to another encoding or to no encoding following `accept-encoding` HTTP header rules.

For instance:
`accept-encoding: gzip, br` should result in a response compressed in gzip
`accept-encoding: br, zstd` should result in an uncompressed response

In general, the `HttpContentCompressor` should only consider the encodings corresponding to the `CompressionOptions` provided to the constructor.

For instance, if the `HttpContentCompressor` is created with `GzipOptions` only, then only gzip encoding should be accepted and a response to a request with different accept encodings should be uncompressed. This behaviour is the same as for `CompressorHttp2ConnectionEncoder`.

### Actual behavior

Using the `HttpContentCompressor` without the brotli4j results in a `IllegalStateException: "Brotli is not available"` thrown when it tries to create default `BrotliOptions` in the constructor.

Using the `HttpContentCompressor` without zstd-jni results in a `NoClassDefFoundError` thrown when it tries to encode a response in zstd encoding.

When creating a `HttpContentCompressor` with a single `CompressionOptions` such as `GzipOptions`, the constructor actually sets default options for the other encodings and as a result, a response can be compressed using deflate, brotli or zstd encoders event if we didn't want it.

### Steps to reproduce

- Define a `HttpContentCompressor` with `GzipOptions` in a HTTP server
- Run the server without brotli or zstd-jni
- query the server with various `accept-encoding` headers: `accept-encoding: gzip`, `accept-encoding: br`, `accept-encoding: deflate`...  

### Netty version

4.1.66.Final

### JVM version (e.g. `java -version`)

openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by jkuhn1**
Motivation:

- Fix `HttpContentCompressor` errors due to missing optional compressor libraries such as Brotli and Zstd at runtime.
- Improve support for optional encoders by only considering the `CompressionOptions` provided to the constructor and ignoring those for which the encoder is unavailable.

Modification:

The `HttpContentCompressor` constructor now only creates encoder factories for the CompressionOptions passed to the constructor when the encoder is available which must be checked for Brotli and Zstd. In case of Brotli, it is not possible to create BrotliOptions if brotly4j is not available so there's actually nothing to check. In case of Zstd, I had to create class `io.netty.handler.codec.compression.Zstd` similar to `io.netty.handler.codec.compression.Brotli` which is used to check that zstd-jni is availabie at runtime.

The `determineEncoding()` method had to change as well in order to ignore encodings for which there's no `CompressionEncoderFactory` instance.

When the HttpContentCompressor is created using deprecated constructor (ie. with no CompressionOptions), we consider all available encoders.

Result:

Fixes #11581. 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

File: codec/src/main/java/io/netty/handler/codec/compression/Zstd.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+        }
+    }
+
+    /**
+     *
+     * @return true when zstd-jni is in the classpath
+     * and native library is available on this platform and could be loaded
+     */
+    public static boolean isAvailable() {
+        return CNFE == null && Brotli4jLoader.isAvailable();
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/Zstd.java:63]: This looks wrong ;)

File: codec/src/main/java/io/netty/handler/codec/compression/Zstd.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+    /**
+     * Throws when zstd support is missing from the classpath or is unavailable on this platform
+     * @throws Throwable a ClassNotFoundException if zstd-jni is missing
+     * or a UnsatisfiedLinkError if zstd native lib can't be loaded
+     */
+    public static void ensureAvailability() throws Throwable {
+        if (CNFE != null) {
+            throw CNFE;
+        }
+        Brotli4jLoader.ensureAvailability();
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/Zstd.java:75]: This looks wrong

File: codec/src/main/java/io/netty/handler/codec/compression/Zstd.java (hunk 1 above)
Comment (hyperxpro) [inline codec/src/main/java/io/netty/handler/codec/compression/Zstd.java:63]: I think you need to write a 'ZstdLoader' class for loading libraries.

**Comment by jkuhn1** [comment]
Bad copy/paste sorry about that...

**Comment by skyguard1** [comment]
@jkuhn1 Thanks for fixing this

File: codec/src/main/java/io/netty/handler/codec/compression/Zstd.java [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+    /**
+     * Throws when zstd support is missing from the classpath or is unavailable on this platform
+     * @throws Throwable a ClassNotFoundException if zstd-jni is missing
+     * or a UnsatisfiedLinkError if zstd native lib can't be loaded
+     */
+    public static void ensureAvailability() throws Throwable {
+        if (CNFE != null) {
+            throw CNFE;
+        }
+        if(cause != null) {
```
Comment (hyperxpro) [inline codec/src/main/java/io/netty/handler/codec/compression/Zstd.java:74]:
```suggestion
        if (cause != null) {
```

File: codec/src/main/java/io/netty/handler/codec/compression/Zstd.java [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+import com.github.luben.zstd.util.Native;
+
+import io.netty.util.internal.PlatformDependent;
+import io.netty.util.internal.logging.InternalLogger;
+import io.netty.util.internal.logging.InternalLoggerFactory;
+
+public final class Zstd {
+
+    private static final InternalLogger logger = InternalLoggerFactory.getInstance(Zstd.class);
+    private static final ClassNotFoundException CNFE;
```
Comment (hyperxpro) [inline codec/src/main/java/io/netty/handler/codec/compression/Zstd.java:28]: I think we can remove `ClassNotFoundException` and use `Throwable cause` only.

**Comment by hyperxpro** [comment]
@normanmaurer Can you approve the GH Actions workflow?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Comment by jkuhn1** [comment]
I've modified `Zstd` based on your comments. Since `Native.load()` is actually performed in a static block in `com.github.luben.zstd.Zstd`, there's no need to do it after loading the class which is why we can use a single try-catch block and catch `ClassNotFoundException`, `ExceptionInInitializerError` (log the cause) and finally a Throwable which should normally never happen.

File: codec/src/main/java/io/netty/handler/codec/compression/Zstd.java [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+
+        try {
+            Class.forName("com.github.luben.zstd.Zstd", false,
+                PlatformDependent.getClassLoader(Zstd.class));
+        } catch (ClassNotFoundException e) {
+            t = e;
+            logger.debug(
+                "zstd-jni not in the classpath; Zstd support will be unavailable.");
+        } catch (ExceptionInInitializerError e) {
+            t = e.getCause();
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/Zstd.java:39]: I think we should not unwrap this one...  Which all omeans we could just remove the catch block as it will be handled in `catch Throwable`

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec/src/main/java/io/netty/handler/codec/compression/Zstd.java (hunk 5 above)
Comment (jkuhn1) [reply codec/src/main/java/io/netty/handler/codec/compression/Zstd.java]: My only concern here was to make sure we have an `UnsatisfiedLinkError` instead of an `ExceptionInInitializerError` as cause but clearly this made things a bit redundant.

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java [hunk 6]
```diff
@@ -314,21 +314,21 @@ protected String determineEncoding(String acceptEncoding) {
...
                 return "gzip";
-            } else if (deflateQ != -1.0f) {
+            } else if (deflateQ != -1.0f && this.deflateOptions != null) {
                 return "deflate";
             }
         }
         if (starQ > 0.0f) {
-            if (brQ == -1.0f) {
-                return Brotli.isAvailable() ? "br" : null;
+            if (brQ == -1.0f && Brotli.isAvailable()) {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java:328]: you could make this a bit more consistent by using `&& this.brotliOptions != null`. Same is true for the change below.

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java (hunk 6 above)
Comment (jkuhn1) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java]: Indeed!

**Review by normanmaurer — APPROVED** [review]

**Review by hyperxpro — APPROVED** [review]
Looks good. :)

**Comment by hyperxpro** [comment]
@jkuhn1 Please sign our ICLA and let us know when done.

https://netty.io/s/icla

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
Thanks a lot !
