### PR TITLE
adjust validation logic when websocket server check starts with '/'(#…

### LINKED ISSUE #11190: WebSocket checkStartWith behave not good when set websocket path to '/'
### Expected behavior
when create an websocket handler like this
```java
WebSocketServerProtocolHandler h = new WebSocketServerProtocolHandler("/",true);
```

i expected:
`/` return true 
`/my-sub-path` return true
### Actual behavior
from [https://github.com/netty/netty/issues/10582#issue-702625436](https://github.com/netty/netty/issues/10582#issue-702625436)
only these path can be passed
`/`
`//my-sub-path`
path like `/my-sub-path` is rejected,which is counter-intuitive

### Steps to reproduce
just run a websocket server with this handler
```java
WebSocketServerProtocolHandler h = new WebSocketServerProtocolHandler("/",true);
```
### Minimal yet complete reproducer code (or URL to code)
```java
/**
 * @author w00464553
 * @date 2020/5/25
 */
public class Application {
    public static void main(String[] args) {
        EmbeddedChannel channel = new EmbeddedChannel(
                new HttpServerCodec(),
                new HttpObjectAggregator(65536),
                new WebSocketServerCompressionHandler(),
                new WebSocketServerProtocolHandler("/", true));

        DefaultFullHttpRequest request = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.GET,
                //this path will be rejected by handler,change to '/' or '//v1/my-path' to see
                //a successful handshake
                "/v1/my-path");
        request.headers().set("upgrade", "websocket");
        request.headers().set("sec-websocket-key", "dGhlIHNhbXBsZSBub25jZQ==");
        request.headers().set("sec-websocket-version", "13");

        channel.writeInbound(request);
        Object o = channel.readOutbound();
        if (o instanceof ByteBuf) {
            ByteBuf bb = ((ByteBuf) o);
            byte[] buf = new byte[bb.readableBytes()];
            bb.readBytes(buf);
            //if success, an 101 Switching Protocols will be printed
            System.out.println(new String(buf));
        } else {
            //or null
            System.out.println(o);
        }
    }
}
```
### Netty version
4.1.63.Final

### PR DESCRIPTION
**Pull request by roycarser**
…11190)

Motivation:

When create a WebSocketServerProtocolConfig to check URI path starts from '/',
only '/' or '//subPath' can be passed by the checker,but '/subPath' should be
passed as well

Modifications:

in `WebSocketServerProtocolHandshakeHandler.isWebSocketPath()` treat '/' a special case

Result:
'/subPath' can be passed

Fixes #11190.

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandshakeHandler.java [hunk 1]
```diff
@@ -117,7 +117,7 @@ private boolean isWebSocketPath(FullHttpRequest req) {
         String websocketPath = serverConfig.websocketPath();
         String uri = req.uri();
         boolean checkStartUri = uri.startsWith(websocketPath);
-        boolean checkNextUri = checkNextUri(uri, websocketPath);
+        boolean checkNextUri = "/".equals(websocketPath) ? true : checkNextUri(uri, websocketPath);
```
Comment (terrarier2111) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandshakeHandler.java:120]:
```suggestion
boolean checkNextUri = "/".equals(websocketPath) || checkNextUri(uri, websocketPath);
```
This can be simplified

Comment (roycarser) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandshakeHandler.java]: fixed

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
Thanks a lot @roycarser
