### PR TITLE
Close eventfd shutdown/wakeup race by closely tracking epoll edges

### LINKED ISSUE #9362: Shutdown race in EpollEventLoop
In 4.1.38, there is an fd race in EpollEventLoop.  The loop thread, while trying to shutdown, closes the eventFd.    The outside thread that calls shutdownGracefully, tries to wake up the loop to notice that it wants it to shutdown.   There is a race where the wakeup() call can write to an eventfd that has been closed already, resulting in the possibility of writing to the wrong fd.

The sequence of events loops like:

1.  T1:  eventLoop.shutdownGracefully()
2.  T1:  state = ST_SHUTDOWN
2.  T2:  reads state == ST_SHUTDOWN
2.  T1:  Enters  EpollEventLoop.wakeup()
2.  T2:  Exits loop, enters EpollEventLoop.cleanup() 
2.  T2:  Closes eventFd.
2.  T1: Wins race to by setting wakenUp to 1
2.  T1: Calls Native.eventFdWrite(eventFd.intValue(), 1L);

The easiest way I can see to fix this race is to use a synchronized block in wakeup(), after the thread has won the wakenUp = 1 race:

```java
    @Override
    protected void wakeup(boolean inEventLoop) {
        if (!inEventLoop && WAKEN_UP_UPDATER.getAndIncrement(this) == 0) {
            // write to the evfd which will then wake-up epoll_wait(...)
            synchronized (eventFd) {
                if (!isShutdown()) {
                    Native.eventFdWrite(eventFd.intValue(), 1L);
                }
            }
        }
    }
```

 Additionally, in EpollEventLoop.cleanup, acquire a lock before closing the eventFd, synchronize the close:

```java
            synchronized (eventFd) {
                try {
                    eventFd.close();
                } catch (IOException e) {
                    logger.warn("Failed to close the event fd.", e);
                }
            }
```

This is kind of unfortunate, but the race makes it possible that another FD is opened after closing the eventFd, and the wakeUp call writes to the wrong FD.  The main downside of my proposed patch is probably the risk of deadlocks (because I dont know what locks I hold), as well as some performance penalty.   

Ideas on how to not pay this cost are welcome, but I think the danger is enough to merit fixing this.

cc @ejona86 @normanmaurer

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation

This is another iteration of #9476.

Modifications

Instead of maintaining a count of all writes performed and then using
reads during shutdown to ensure all are accounted for, just set a flag
after each write and don't reset it until the corresponding event has
been returned from epoll_wait.

This requires that while a write is still pending we don't reset
wakenUp, i.e. continue to block writes from the wakeup() method.

Result

Race condition eliminated. Fixes #9362

Co-authored-by: Norman Maurer <norman_maurer@apple.com>

### CODE REVIEW

**Comment by normanmaurer** [comment]
@johnou FYI...

"re-reverted" another one...

File: transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java [hunk 1]
```diff
@@ -329,11 +332,35 @@ protected void run() {
...
+                                break;
+                            }
+                            // fall-through
                         }
-                        if (!hasTasks()) {
-                            strategy = epollWait();
+
+                        // Ordered store is sufficient here since the only access outside this
+                        // thread is a getAndSet in the wakeup() method
+                        wakenUp.lazySet(0);
```
Comment (johnou) [inline transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java]: was lazySet safe here based on what @njhill said the other day?

Comment (njhill) [reply transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java]: @johnou good question. To distil the problem, say we have fields
```java
final AtomicInteger x = new AtomicInteger(1), y = new AtomicInteger(0);
```
Thread 1 program order:
```java
x.lazySet(0);
if (y.get() == 0) { print("sleep"); }
```
Thread 2 program order:
```java
y.compareAndSet(0, 1); // (always succeeds)
if (x.compareAndSet(0, 1)) { print("wake"); }
```
Is it possible for "sleep" to be printed without "wake" also being printed? I now think the answer is yes, even more so after reading [this](https://groups.google.com/forum/#!msg/mechanical-sympathy/yeBNqThRtdU/weQY0Cy5PhcJ). Which means that `lazySet` _isn't_ safe, but would be good to get confirmation from others... @franz1981?? :)

**Comment by njhill** [comment]
I pushed a commit to change the `lazySet` to `set` (can revert based on other feedback if necessary). Also added a warning log message in the case we timeout when expecting to receive an imminent eventfd EPOLLIN event (this was suggested before by @ejona86 the first time around but I forgot to add it then).

File: transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java (hunk 1 above)
Comment (franz1981) [reply transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java]: You've said right: it isn't safe and set would be a better choice for a total ordered operation (among the others) :)

Comment (normanmaurer) [reply transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java]: @franz1981 please review the rest as well

**Comment by njhill** [comment]
Just pushed another commit 8523b5a91f42d397252104f308d0295f29bad2d2:
- It's better not to touch the timerfd when doing the "timeboxed" wait and instead rely on epoll's own timeout (this is what the original version did but that was mingled with changes from the reverted timerfd-decoupling PRs).
- Simplified the preexisting native epollWait method which resets timerfd - there's no need to read from it after it fires in ET mode

@normanmaurer would be good to sanity test again with these updates when you have a chance!

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@njhill all works... just merged

**Comment by njhill** [comment]
@normanmaurer would you like me to port this and #9397 to master?

**Comment by normanmaurer** [comment]
@njhill yep please

**Comment by njhill** [comment]
@normanmaurer here is master-based commit for this one: 8ed2222089c7bb8da8a21786b716d38ebeb73571, I see you had actually already done #9397.

**Comment by njhill** [comment]
@normanmaurer should I open a PR from the above or will you cherrypick?

**Comment by normanmaurer** [comment]
@njhill pr please... thanks
