### PR TITLE
Use network byte order when encoding ipv4 address and port for Socks codecs

### LINKED ISSUE #13426: Socks encoder/decoder do not always follow RFC regarding port
### Expected behavior
According to RFC1918 regarding Socks5 proxy protocol, destination port must be represented in `network byte order`. I didn't find a similar information for Socks4 proxy implementations but I would think the requirement is the same (and it seems that OpenJDK socks implementation follow that convention as well: https://github.com/openjdk/jdk/blob/5cd8af7622a93afb32f5f3fccdc453096992453c/test/jdk/java/net/Socks/SocksServer.java#L200)

Netty implementation should also obey the requirement, independently of the buffer internal order

### Actual behavior

When an application uses byte buffers with little endian order, Netty socks encoder/decoder do not write the port information correctly, resulting in refused connection for example.

### Steps to reproduce

0/ Setup a socks proxy (using `ssh -D` or `mitmproxy`)
1/ Write a small pipeline to connect to a remote system with a socks proxy handler
2/ Configure the pipeline to use an allocator to generate LE byte buffers
3/ Try and attempt to connect to the remote system 

### Netty version
4.1.89

### JVM version (e.g. `java -version`)
```
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10)
OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)
```
### OS version (e.g. `uname -a`)
Darwin  xxx.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64

### PR DESCRIPTION
**Pull request by laurentgo**
Motivation:

Socks codecs do not always use network byte ordering when encoding/decoding socks messages resulting in connection issues

Modification:

Use BE methods to properly read/write socks messages

Result:

Fixes #13426

### CODE REVIEW

File: codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java [hunk 1]
```diff
@@ -62,4 +65,14 @@ static String readUsAscii(ByteBuf buffer, int length) {
         buffer.skipBytes(length);
         return s;
     }
+
+    public static int readUnsignedShortBE(ByteBuf buf) {
```
Comment (normanmaurer) [inline codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java:69]: I wonder if we should move these to `ByteBufUtil` to keep things consistent ?

Comment (normanmaurer) [reply codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java:69]: Also please add javadocs to public methods

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java (hunk 1 above)
Comment (laurentgo) [reply codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java:69]: > I wonder if we should move these to `ByteBufUtil` to keep things consistent ?

I can definitively do that. I wasn't sure if adding new `*BE` methods in the generic `ByteBufUtil` was still accepted.

> Also please add javadocs to public methods

Will address

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java [hunk 2]
```diff
@@ -286,6 +286,56 @@ public void writeMediumBE(BufferType bufferType) {
         buf.release();
     }
 
+    @SuppressWarnings("deprecation")
+    @ParameterizedTest(name = PARAMETERIZED_NAME)
+    @MethodSource("noUnsafe")
+    public void readUnsignedShortBE(BufferType bufferType) {
+        int shortValue = 0x1234;
```
Comment (chrisvest) [inline buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java:293]: Would be good to also test with a value that would be negative if the short was signed, to make sure there are no overflow bugs.

File: codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java [hunk 3]
```diff
@@ -19,7 +19,7 @@
 import io.netty.util.CharsetUtil;
 import io.netty.util.internal.StringUtil;
 
-final class SocksCommonUtils {
+public final class SocksCommonUtils {
```
Comment (chrisvest) [inline codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java:22]: Why public?

Comment (laurentgo) [reply codec-socks/src/main/java/io/netty/handler/codec/socks/SocksCommonUtils.java:22]: oh, good catch. I can revert since methods have been moved to `ByteBufUtil`

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java (hunk 2 above)
Comment (laurentgo) [reply buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java]: Yes, should have done that :) Added a test and fixed one overflow issue

**Comment by normanmaurer** [comment]
@laurentgo did you sign our ICLA yet ? https://netty.io/s/icla

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java [hunk 4]
```diff
@@ -286,6 +286,78 @@ public void writeMediumBE(BufferType bufferType) {
...
+    @MethodSource("noUnsafe")
+    public void readUnsignedShortBE(BufferType bufferType) {
+        int shortValue = 0x1234; // unsigned short
+        int swappedShortValue = 0x3412; // swapped version of the value above
+
+        ByteBuf buf = buffer(bufferType, 2).order(ByteOrder.BIG_ENDIAN);
+        buf.writeShort(shortValue);
+        assertEquals(shortValue, ByteBufUtil.readUnsignedShortBE(buf));
+        buf.resetReaderIndex();
+        buf.resetWriterIndex();
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java:300]:
```suggestion
        buf.clear();
```

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java [hunk 5]
```diff
@@ -286,6 +286,78 @@ public void writeMediumBE(BufferType bufferType) {
...
+        buf.writeShortLE(shortValue);
+        assertEquals(swappedShortValue, ByteBufUtil.readUnsignedShortBE(buf));
+        buf.release();
+
+        buf = buffer(bufferType, 2).order(ByteOrder.LITTLE_ENDIAN);
+        buf.writeShort(shortValue);
+        assertEquals(swappedShortValue, ByteBufUtil.readUnsignedShortBE(buf));
+        buf.resetReaderIndex();
+        buf.resetWriterIndex();
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java:309]:
```suggestion
        buf.clear();
```

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java [hunk 6]
```diff
@@ -286,6 +286,78 @@ public void writeMediumBE(BufferType bufferType) {
...
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java:330]:
```suggestion
        buf.clear();
```

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java [hunk 7]
```diff
@@ -286,6 +286,78 @@ public void writeMediumBE(BufferType bufferType) {
...
+    @ParameterizedTest(name = PARAMETERIZED_NAME)
+    @MethodSource("noUnsafe")
+    public void readIntBE(BufferType bufferType) {
+        int intValue = 0x12345678;
+
+        ByteBuf buf = buffer(bufferType, 4).order(ByteOrder.BIG_ENDIAN);
+        buf.writeInt(intValue);
+        assertEquals(intValue, ByteBufUtil.readIntBE(buf));
+        buf.resetReaderIndex();
+        buf.resetWriterIndex();
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java:346]:
```suggestion
        buf.clear();
```

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java [hunk 8]
```diff
@@ -286,6 +286,78 @@ public void writeMediumBE(BufferType bufferType) {
...
+        buf.writeIntLE(intValue);
+        assertEquals(ByteBufUtil.swapInt(intValue), ByteBufUtil.readIntBE(buf));
+        buf.release();
+
+        buf = buffer(bufferType, 4).order(ByteOrder.LITTLE_ENDIAN);
+        buf.writeInt(intValue);
+        assertEquals(ByteBufUtil.swapInt(intValue), ByteBufUtil.readIntBE(buf));
+        buf.resetReaderIndex();
+        buf.resetWriterIndex();
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java:355]:
```suggestion
        buf.clear();
```

File: codec-socks/src/test/java/io/netty/handler/codec/socks/SocksCmdRequestTest.java [hunk 9]
```diff
@@ -121,7 +123,32 @@ public void testIDNEncodeToAsciiForDomain() {
...
+        CharBuffer asciiHost = CharBuffer.wrap(host);
+        short port = 10000;
+
+        SocksCmdRequest rq = new SocksCmdRequest(SocksCmdType.BIND, SocksAddressType.DOMAIN, host, port);
+        assertEquals(host, rq.host());
+
+        ByteBuf buffer = Unpooled.buffer(24).order(ByteOrder.LITTLE_ENDIAN);
+        rq.encodeAsByteBuf(buffer);
+
+        buffer.resetReaderIndex();
```
Comment (normanmaurer) [inline codec-socks/src/test/java/io/netty/handler/codec/socks/SocksCmdRequestTest.java:143]:
```suggestion
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java (hunk 5 above)
Comment (laurentgo) [reply buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java]: fixed

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java (hunk 7 above)
Comment (laurentgo) [reply buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java]: fixed

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java (hunk 8 above)
Comment (laurentgo) [reply buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java]: fixed

File: codec-socks/src/test/java/io/netty/handler/codec/socks/SocksCmdRequestTest.java (hunk 9 above)
Comment (laurentgo) [reply codec-socks/src/test/java/io/netty/handler/codec/socks/SocksCmdRequestTest.java]: fixed

File: buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java (hunk 6 above)
Comment (laurentgo) [reply buffer/src/test/java/io/netty/buffer/ByteBufUtilTest.java]: fixed

**Review by chrisvest — APPROVED** [review]
