### PR TITLE
Avoid possible comparison contract violation

### LINKED ISSUE #9881: IllegalArgumentException when sorting cookies in ClientCookieEncoder
We use Netty to crawl a lot of websites, and from time to time get the following exception:

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
java.base/java.util.TimSort.mergeHi(TimSort.java:903)
java.base/java.util.TimSort.mergeAt(TimSort.java:520)
java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
java.base/java.util.TimSort.sort(TimSort.java:254)
java.base/java.util.Arrays.sort(Arrays.java:1441)
io.netty.handler.codec.http.cookie.ClientCookieEncoder.encode(ClientCookieEncoder.java:165)
```

I tried to write a testcase to reproduce the behavior, but since TimSort only throws this exception under some circumstance, I failed. 

However, I think I can spot the cause. The code in question uses this comparator (io/netty/handler/codec/http/cookie/ClientCookieEncoder.java:91):

```
   /**
     * Sort cookies into decreasing order of path length, breaking ties by sorting into increasing chronological
     * order of creation time, as recommended by RFC 6265.
     */
    private static final Comparator<Cookie> COOKIE_COMPARATOR = (c1, c2) -> {
        String path1 = c1.path();
        String path2 = c2.path();
        // Cookies with unspecified path default to the path of the request. We don't
        // know the request path here, but we assume that the length of an unspecified
        // path is longer than any specified path (i.e. pathless cookies come first),
        // because setting cookies with a path longer than the request path is of
        // limited use.
        int len1 = path1 == null ? Integer.MAX_VALUE : path1.length();
        int len2 = path2 == null ? Integer.MAX_VALUE : path2.length();
        int diff = len2 - len1;
        if (diff != 0) {
            return diff;
        }
        // Rely on Java's sort stability to retain creation order in cases where
        // cookies have same path length.
        return -1;
    };
```

If I pass two cookies C1 and C2 with the same path length to this function it would return C1 < C2 and C2 < C1. This - in my eyes  - is a violation of contract. And I suspect, this is causing the exception.

Returning 0 instead of -1 should fix this.

### Expected behavior

Cookies are always sorted by path

### Actual behavior

Sorting cookies by path sometimes throws an exception

### Steps to reproduce

Difficult. Depends on the concrete cookies set, since TimSort contract violation detection is a byproduct which is triggered occasionally. TimSort does not actively looks for contract violations.

### Minimal yet complete reproducer code (or URL to code)

Not available

### Netty version

4.1.43.Final

### JVM version (e.g. `java -version`)

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-62-generic x86_64)

### PR DESCRIPTION
**Pull request by gerdriesselmann**
The current implementation would violate comparison contract for two cookies C1 and C2 with same path length, since C1 < C2 and C2 < C1. Returning 0 (equality) does not since C1 == C2 and C2 == C1. See #9881

Motivation:

The current implementation causes IllegalArgumetExceptions to be thrown on Java 11.

Modification:

Return equality instead of less than on same path length.

Result:

Fixes #9881.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@gerdriesselmann can't you add a test case that validates `0` is returned in this case ?

**Comment by normanmaurer** [comment]
@gerdriesselmann also please sign our icla if you didn't already: https://netty.io/s/icla

**Comment by gerdriesselmann** [comment]
@normanmaurer icla was signed. 

Regarding a test: since this is a private class of ClientCookieEncoder, I have no real idea how to write a test against it.

**Comment by normanmaurer** [comment]
@gerdriesselmann make it package-private :)

**Comment by gerdriesselmann** [comment]
@normanmaurer To be honest, I'm doing Scala, but am rather alienated by the Java language and its tooling in general and Maven especially. I tried to execute the existing ClientCookieEncoderTest within IntelliJ, but can't compile against Java 11, and get "Unrecognized option: --illegal-access=deny" against Java 8. Additionally, as soon as I'm changing something (like adding a test case), a CheckStyle plugin jumps in and stops me from progressing. I can't even figure out what exactly it complains about... 

Sorry to be of no further help here...

File: codec-http/src/main/java/io/netty/handler/codec/http/cookie/ClientCookieEncoder.java [hunk 1]
```diff
@@ -109,7 +109,7 @@ public int compare(Cookie c1, Cookie c2) {
             }
             // Rely on Java's sort stability to retain creation order in cases where
             // cookies have same path length.
-            return -1;
+            return 0;
```
Comment (njhill) [inline codec-http/src/main/java/io/netty/handler/codec/http/cookie/ClientCookieEncoder.java]: This might be problematic since ordering of same-length cookies will be inconsistent/non-deterministic. Cookies could also be "lost" if added to a `SortedMap`. Interestingly the current logic contradicts the javadoc above 
`breaking ties by sorting into increasing chronological order of creation time, as recommended by RFC 6265. order of creation time, as recommended by RFC 6265.` ... maybe that was the original intention but found to be not possible because creation time isn't stored in the Cookie objects.

I would suggest at minimum something like `return c1.name().compareTo(c2.name());` instead, but to be completely correct additional tiebreaks should be done using the path and domain fields' content too...

Comment (njhill) [reply codec-http/src/main/java/io/netty/handler/codec/http/cookie/ClientCookieEncoder.java]: (but thank you for finding the bug @gerdriesselmann, -1 is not correct either!)

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/cookie/ClientCookieEncoder.java]: @njhill can you prepare a PR ?

Comment (njhill) [reply codec-http/src/main/java/io/netty/handler/codec/http/cookie/ClientCookieEncoder.java]: @gerdriesselmann, @normanmaurer apologies I think my suggestion was bad ... since this is a private comparator used in specific places for `Arrays#sort()` only, the concerns I have are not really applicable.

I.e. the original author's intended approach seems reasonable and this is the correct fix for that. My only remaining suggestion would be to amend the comment above to say that it's relying on `Arrays.sort`'s stability rather than "Java".

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/cookie/ClientCookieEncoder.java]: ok lets do this...

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@gerdriesselmann I will add a unit test as followup once this is in. Thanks!

**Comment by normanmaurer** [comment]
@gerdriesselmann merged... thanks a lot.
