### PR TITLE
Return null in HttpPostRequestEncoder

### LINKED ISSUE #9351: NullPointerException in HttpPostRequestEncoder encodeNextChunkUrlEncoded
### Expected behavior
No `NullPointerException`.

### Actual behavior
When given a certain input size, the `encodeNextChunkUrlEncoded` throws a `NullPointerException` in the following line
```
if (currentBuffer.readableBytes() >= HttpPostBodyUtil.chunkSize) {
```
because the `currentBuffer` is null (which was set to the `delimiter` which was null). There seems to have been a similar issue in the past: https://github.com/netty/netty/issues/5478.

### Steps to reproduce / Minimal yet complete reproducer code (or URL to code)
```
@Test
public void testWriteChunkedContent() throws Exception {
    EmbeddedChannel ch = new EmbeddedChannel(new ChunkedWriteHandler());
    HttpRequest req = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/");
    HttpPostRequestEncoder encoder = new HttpPostRequestEncoder(req, false);

    int length = 8077 + 8096;
    char[] array = new char[length];
    Arrays.fill(array, 'a');
    String longText = new String(array);

    encoder.addBodyAttribute("data", longText);
    encoder.addBodyAttribute("moreData", "abcd");

    HttpRequest finalRequest = encoder.finalizeRequest();

    ch.writeOutbound(finalRequest);
    ch.writeOutbound(encoder);
    ch.flushOutbound();
}
```

### Netty version
4.1

### JVM version (e.g. `java -version`)
java version "1.8.0_111"

### OS version (e.g. `uname -a`)
Darwin Kernel Version 18.6.0

### PR DESCRIPTION
**Pull request by emlittleworth**
Motivation:

If the encoded value of a form element happens to exactly hit the chunk limit (8096 bytes), the post request encoder will throw a NullPointerException.

Modification:

Catch the null case and return.

Result:

Fixes #9351.

### CODE REVIEW

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java [hunk 1]
```diff
@@ -443,4 +447,25 @@ private static void checkNextChunkSize(HttpPostRequestEncoder encoder, int sizeW
...
+        char[] array = new char[length];
+        Arrays.fill(array, 'a');
+        String longText = new String(array);
+
+        encoder.addBodyAttribute("data", longText);
+        encoder.addBodyAttribute("moreData", "abcd");
+
+        HttpRequest finalRequest = encoder.finalizeRequest();
+
+        ch.writeOutbound(finalRequest);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java]: add assert for return value

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java [hunk 2]
```diff
@@ -443,4 +447,25 @@ private static void checkNextChunkSize(HttpPostRequestEncoder encoder, int sizeW
...
+        ch.writeOutbound(encoder);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java]: add assert for return value

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java [hunk 3]
```diff
@@ -443,4 +447,25 @@ private static void checkNextChunkSize(HttpPostRequestEncoder encoder, int sizeW
...
+        ch.flushOutbound();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java]: call `ch.finish()` and assert return value .

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java [hunk 4]
```diff
@@ -443,4 +447,25 @@ private static void checkNextChunkSize(HttpPostRequestEncoder encoder, int sizeW
                 + readable, expectedSize);
         httpContent.release();
     }
+
+    @Test
+    public void testEncodeChunkedContent() throws Exception {
+        EmbeddedChannel ch = new EmbeddedChannel(new ChunkedWriteHandler());
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java]: why is the `ChunkedWriteHandler` needed ?

Comment (emlittleworth) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java]: That was the closest thing I could find to the logic in Finagle. I just changed it though.

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java [hunk 5]
```diff
@@ -443,4 +445,27 @@ private static void checkNextChunkSize(HttpPostRequestEncoder encoder, int sizeW
...
+        Arrays.fill(array, 'a');
+        String longText = new String(array);
+
+        encoder.addBodyAttribute("data", longText);
+        encoder.addBodyAttribute("moreData", "abcd");
+
+        assertNotNull(encoder.finalizeRequest());
+
+        while (!encoder.isEndOfInput()) {
+            encoder.readChunk((ByteBufAllocator) null);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java]: you need to also release the `HttpContent` returned by this method as otherwise the test will leak memory:

`encoder.readChunk(...).release()`

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@emlittleworth thanks a lot!
