### PR TITLE
Avoid CancellationException construction in DefaultPromise

### LINKED ISSUE #9522: Performance regression introduced in 4.1.35 and later
While upgrading netty version from `4.1.33` to `4.1.39` in our application, we observed performance regression in the newer versions.

After narrowing down, the client performance seems gradually degraded since `4.1.35`. We are using JMH to measure throughput for our netty client code and starting from `4.1.37`, the throughput has been decreased by around 10%.  The degradation occurred for both H1 and H2 code path.

Are you aware of anything between those versions that could cause performance degradation? Are there any performance tests in place to catch regressions?

### PR DESCRIPTION
**Pull request by njhill**
Motivation

#9152 reverted some static exception reuse optimizations due to the problem with `Throwable#addSuppressed()` raised in #9151. This introduced a performance issue when promises are cancelled at a high frequency due to the construction cost of `CancellationException` at the time that `DefaultPromise#cancel()` is called.

Modifications

- Reinstate the prior static `CANCELLATION_CAUSE_HOLDER` but use it just as a sentinel to indicate cancellation, constructing a new `CancellationException` only if/when one needs to be explicitly returned/thrown
- Subclass `CancellationException`, overriding `fillInStackTrace()` to minimize the construction cost in these cases

Result

Promises are much cheaper to cancel. Fixes #9522.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: common/src/main/java/io/netty/util/concurrent/DefaultPromise.java [hunk 1]
```diff
@@ -131,9 +135,26 @@ public boolean isCancellable() {
...
+        public String toString() {
+            return CancellationException.class.getName();
+        }
+    }
+
     @Override
     public Throwable cause() {
         Object result = this.result;
+        if (result == CANCELLATION_CAUSE_HOLDER) {
+            throw new LeanCancellationException();
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: this is not correct... I would have hoped we have unit tests for this :). This method should return the `cause()` and not throw it.

File: common/src/main/java/io/netty/util/concurrent/DefaultPromise.java [hunk 2]
```diff
@@ -301,8 +322,7 @@ public V getNow() {
      */
     @Override
     public boolean cancel(boolean mayInterruptIfRunning) {
-        if (RESULT_UPDATER.get(this) == null &&
-                RESULT_UPDATER.compareAndSet(this, null, new CauseHolder(new CancellationException()))) {
+        if (RESULT_UPDATER.compareAndSet(this, null, CANCELLATION_CAUSE_HOLDER)) {
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: taking this above comment into account I think this should be:

```java
if (RESULT_UPDATER.compareAndSet(this, null, new CauseHolder(new LeanCancellationException())) {
```

And then the above change in `cause()` should are removed all together.

File: common/src/main/java/io/netty/util/concurrent/DefaultPromise.java (hunk 1 above)
Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: @njhill please add a unit test for this :)

Comment (njhill) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: LOL oops I think this was part of a last min refactor, the `throw` was meant to be `return` of course... will fix and add unit test

File: common/src/main/java/io/netty/util/concurrent/DefaultPromise.java (hunk 2 above)
Comment (njhill) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: @normanmaurer this would defeat the primary purpose of the PR which is to not allocate anything at all when the promise is cancelled. I expect it's very common to cancel a promise/future which is no longer needed, and never subsequently call `cause()` or `get()` on it. For example cancelling a task that was scheduled on the event loop - I think that's the use case in #9522.

Note that `isCancelled()` also still works correctly without having to allocate the exception.

Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: Well the question is if cancel() is more often called then cause() as otherwise you allocate a new object on each cause() call

Comment (njhill) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: My guess is that it would be rare for `cause()` to be called more than once on cancelled promises, especially relative to those cases that it's never called. For other kinds of exception, a new `ExcecutionException` is allocated every time `cause()` is called, and j.u.c. futures allocate a new `CancellationException` every time you call `get()` on a cancelled future (e.g. see source of `j.u.c.FutureTask`.

However if you're concerned about that then it's also easily solvable by just replacing `result` with the new exception wrapped in a `new CauseHolder` before returning from `cause()`. If you're also concerned with possible duplicates then it could be CASed.

Comment (njhill) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: e.g.
```java
    public Throwable cause() {
        Object result = this.result;
        if (result == CANCELLATION_CAUSE_HOLDER) {
            CancellationException ce = new LeanCancellationException();
            RESULT_UPDATER.lazySet(this, ce);
            return ce;
        }
        return (result instanceof CauseHolder) ? ((CauseHolder) result).cause : null;
    }
```

Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: @njhill tis sounds like a good idea! Go for it and let me know once you are done :)

File: common/src/test/java/io/netty/util/concurrent/DefaultPromiseTest.java [hunk 3]
```diff
@@ -114,6 +115,14 @@ public void testCancellationExceptionIsThrownWhenBlockingGetWithTimeout() throws
         promise.get(1, TimeUnit.SECONDS);
     }
 
+    @Test
+    public void testCancellationExceptionIsReturnedAsCause() throws InterruptedException,
+    ExecutionException, TimeoutException {
+        final Promise<Void> promise = new DefaultPromise<Void>(ImmediateEventExecutor.INSTANCE);
+        promise.cancel(false);
```
Comment (normanmaurer) [inline common/src/test/java/io/netty/util/concurrent/DefaultPromiseTest.java]: please also assert return value

Comment (njhill) [reply common/src/test/java/io/netty/util/concurrent/DefaultPromiseTest.java]: done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by njhill** [comment]
@normanmaurer I'm fine with keeping it like this but fwiw I still prefer it without updating `result` since we're penalizing the (presumably more common) case where it's called once.

I think it's also  _technically_ not threadsafe to throw the shared exception object - for example if two threads call `get()` on the cancelled promise at the same time and both call `addSuppressed` on the thrown exception (though I realize that this is unlikely enough to not care about!).

**Comment by normanmaurer** [comment]
@njhill after reading your comment I would even argue that we need to use a compareAndSet(...) to ensure the same instance is always returned to make it work in a consistent way to promises that are failed via setFailure(...)

**Comment by njhill** [comment]
@normanmaurer I'm not sure I follow why that's important but happy to change it... you mean do a `compareAndSet` instead of `lazySet` in `cause()`?

**Comment by normanmaurer** [comment]
Yes

**Comment by normanmaurer** [comment]
@njhill also honestly I think a `compareAndSet` here is ok (even performance wise) as it really only happens if the future was canceled and you try to access the `cause()`. This combination should be super rare anyway.

**Comment by njhill** [comment]
@normanmaurer done, PTAL!

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: common/src/main/java/io/netty/util/concurrent/DefaultPromise.java (hunk 2 above)
Comment (johnou) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: Why was the get removed? Isn't it cheaper than CAS?

Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/DefaultPromise.java]: @johnou the get was only there before because creating the exception isn't cheap which is not a problem anymore

**Comment by normanmaurer** [comment]
@njhill thanks a lot!
