### PR TITLE
remove usages of security manager (and related apis)

### LINKED ISSUE #15194: [Netty 5] Remove security manager usages (and related apis)
The security manager api (and related such as AccessController) were [deprecated for removal](https://openjdk.org/jeps/411) in jdk 17, introducing a change to the system property `java.security.manager`, which started to issue a warning when the flag was used. This also happened for all calls to `System.setSecurityManager`.
In JDK 18 the default value of `java.security.manager` was [changed to `disallow`](https://bugs.openjdk.org/browse/JDK-8270380) meaning that calls to `System.setSecurityManager` would fail with an exception.
In JDK 24 all security manager APIs [were completely disabled](https://openjdk.org/jeps/486) with a scheduled removal of these apis in a future jdk release.

I would like to know if there is interest in removing all calls to these apis (such as `System.setSecurityManager`, `System.getSecurityManager`, `AccessController.doPrivileged`) in netty 5. The current target java version 22 still has "support" for the security manager (it can still be set) but this support is already heavily restricted and clearly marked for removal. Removing them would 1. simplify the codebase and 2. eliminate future maintenance work around compatibility once these APIs are fully removed in a later JDK version.

This issue is meant to get some feedback on this, but I would be more than happy to help removing these bits of code if there is interest in doing so.

### PR DESCRIPTION
**Pull request by derklaro**
Motivation:
The security manager api (and related such as AccessController) were [deprecated for removal](https://openjdk.org/jeps/411) in jdk 17, introducing a change to the system property `java.security.manager`, which started to issue a warning when the flag was used. This also happened for all calls to `System.setSecurityManager`.
In JDK 18 the default value of `java.security.manager` was [changed to `disallow`](https://bugs.openjdk.org/browse/JDK-8270380) meaning that calls to `System.setSecurityManager` would fail with an exception.
In JDK 24 all security manager APIs [were completely disabled](https://openjdk.org/jeps/486) with a scheduled removal of these apis in a future jdk release.

Modification:
Remove all usages of `System.getSecurityManager`, `System.setSecurityManager`, `AccessController.doPrivileged`, catches of `SecurityException` (where applicable), and maybe some others. I tried to keep the diff as small as possible, some more cleanups to the changed code parts will be possible in the future.

Result:
No more usages of the deprecated security manager related apis.

Resolves #15194

### CODE REVIEW

File: common/src/main/java/io/netty5/util/internal/PlatformDependent0.java [hunk 1]
```diff
@@ -811,29 +779,19 @@ static int hashCodeAsciiSanitize(byte value) {
...
     }
 
+    @Deprecated
     static ClassLoader getSystemClassLoader() {
-        if (System.getSecurityManager() == null) {
-            return ClassLoader.getSystemClassLoader();
-        } else {
-            return AccessController.doPrivileged((PrivilegedAction<ClassLoader>) ClassLoader::getSystemClassLoader);
-        }
+        return ClassLoader.getSystemClassLoader();
```
Comment (chrisvest) [inline common/src/main/java/io/netty5/util/internal/PlatformDependent0.java:794]: We can inline these three into their usage sites. And honestly we don't need the versions in `PlatformDependent` either. Is this part of the later cleanup you're planning?

File: common/src/test/java/io/netty5/util/concurrent/DefaultThreadFactoryTest.java [hunk 2]
```diff
@@ -34,85 +32,51 @@ public class DefaultThreadFactoryTest {
     @Test
     @Timeout(value = 2000, unit = TimeUnit.MILLISECONDS)
     public void testDescendantThreadGroups() throws InterruptedException {
-        final SecurityManager current = System.getSecurityManager();
-
-        boolean securityManagerSet = false;
-        try {
+        // holder for the thread factory, plays the role of a global singleton
```
Comment (chrisvest) [inline common/src/test/java/io/netty5/util/concurrent/DefaultThreadFactoryTest.java:35]: I don't think this test makes any sense anymore. We can delete it.

**Review by chrisvest — COMMENTED** [review]
Nice clean-up!

File: common/src/main/java/io/netty5/util/internal/PlatformDependent0.java (hunk 1 above)
Comment (derklaro) [reply common/src/main/java/io/netty5/util/internal/PlatformDependent0.java:794]: Yes, exactly, I didn't want to introduce more noise in this PR - I will remove the deprecated methods from `PlatformDependent`, `PlatformDependent0` and `SocketUtils` in a follow up.

**Review by chrisvest — APPROVED** [review]

**Comment by normanmaurer** [comment]
@derklaro thanks
