### PR TITLE
`AdaptiveByteBufAllocator` will not use threadlocal magazine if `FastThreadLocalThread.willCleanupFastThreadLocals()` returns false

### LINKED ISSUE #14483: Method `AdaptiveByteBufAllocator.usedHeapMemory()` does not return right value with customized `FastThreadLocalThread` thread
### Expected behavior
The return value of method `AdaptiveByteBufAllocator.usedHeapMemory()` should be greater than 0.
### Actual behavior
The return value is 0, as following output on my laptop:

> alloc.usedHeapMemory():0, Thread[Thread-0,5,main]
> alloc.usedHeapMemory():0, Thread[main,5,main]

### Steps to reproduce
Run the `main` method:
```
import io.netty.buffer.AdaptiveByteBufAllocator;
import io.netty.util.concurrent.FastThreadLocalThread;
import io.netty.util.internal.ObjectUtil;

public class T20241121 {

    static class CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals extends FastThreadLocalThread 
                         implements Runnable {
       
        private final Runnable runnable;

        private CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals(Runnable runnable) {
            this.runnable = ObjectUtil.checkNotNull(runnable, "runnable");
        }

        @Override
        public boolean willCleanupFastThreadLocals() {
            return false;
        }

        @Override
        public void run() {
            runnable.run(); // Without calling `FastThreadLocal.removeAll()`.
        }
    }

    public static void main(String[] args) throws InterruptedException {

        final AdaptiveByteBufAllocator[] alloc = new AdaptiveByteBufAllocator[1];
        
        Runnable task = new Runnable() {
            @Override
            public void run() {
                alloc[0] = new AdaptiveByteBufAllocator(false, true);
                alloc[0].heapBuffer(1024, 1024);
                System.out.println("alloc.usedHeapMemory():" + alloc[0].usedHeapMemory() + ", " + Thread.currentThread());
            }
        };
        
        Thread customizefastThreadLocalThread = new CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals(task);
        customizefastThreadLocalThread.start();
        customizefastThreadLocalThread.join();
        System.out.println("alloc.usedHeapMemory():" + alloc[0].usedHeapMemory() + ", " + Thread.currentThread());
    }
}
```

### Netty version
4.1.115.Final
### JVM version (e.g. `java -version`)
Does not matter.
### OS version (e.g. `uname -a`)
Does not matter.

### PR DESCRIPTION
**Pull request by laosijikaichele**
Motivation:

The method `AdaptiveByteBufAllocator.usedHeapMemory()` does not return a correct value when `FastThreadLocalThread.willCleanupFastThreadLocals(Thread.currentThread()) == false` by using a customized  `FastThreadLocalThread` thread.

Modification:

If `FastThreadLocalThread.willCleanupFastThreadLocals(Thread.currentThread()) == false`, then we will NOT use threadLocal magazine.

Result:

Fixes #14483.

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]
LGTM! well done!

File: buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java [hunk 1]
```diff
@@ -145,13 +148,15 @@ enum MagazineCaching {
...
                     if (cachedMagazinesNonEventLoopThreads || ThreadExecutorMap.currentExecutor() != null) {
-                        Magazine mag = new Magazine(AdaptivePoolingAllocator.this, false);
-
-                        if (FastThreadLocalThread.willCleanupFastThreadLocals(Thread.currentThread())) {
-                            // Only add it to the liveMagazines if we can guarantee that onRemoval(...) is called,
-                            // as otherwise we might end up holding the reference forever.
-                            liveMagazines.add(mag);
+                        if (!FastThreadLocalThread.willCleanupFastThreadLocals(Thread.currentThread())) {
+                            // To prevent potential leak, we will not use thread-local magazine.
+                            logger.warn("Thread-local magazine will NOT be used, since the current thread:{} " +
```
Comment (normanmaurer) [inline buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java:153]: is warn really the right level here ?

File: buffer/src/test/java/io/netty/buffer/AdaptiveByteBufAllocatorUseCacheForNonEventLoopThreadsTest.java [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+        assertNull(throwable.get());
+    }
+
+    private static final class CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals
+            extends FastThreadLocalThread implements Runnable {
+        private final Runnable runnable;
+        private CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals(Runnable runnable) {
+            this.runnable = ObjectUtil.checkNotNull(runnable, "runnable");
+        }
+        @Override
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/AdaptiveByteBufAllocatorUseCacheForNonEventLoopThreadsTest.java:64]:
```suggestion

        @Override
```

File: buffer/src/test/java/io/netty/buffer/AdaptiveByteBufAllocatorUseCacheForNonEventLoopThreadsTest.java [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+        Thread customizefastThreadLocalThread = new CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals(task);
+        customizefastThreadLocalThread.start();
+        customizefastThreadLocalThread.join();
+        assertNull(throwable.get());
+    }
+
+    private static final class CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals
+            extends FastThreadLocalThread implements Runnable {
+        private final Runnable runnable;
+        private CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals(Runnable runnable) {
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/AdaptiveByteBufAllocatorUseCacheForNonEventLoopThreadsTest.java:61]:
```suggestion

        private CustomizeFastThreadLocalThreadWithoutCleanupFastThreadLocals(Runnable runnable) {
```

File: buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java (hunk 1 above)
Comment (chrisvest) [reply buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java:153]: Honestly, I don't think we need any logging.

**Review by chrisvest — COMMENTED** [review]
I don't think the logging is necessary. Remove that and add Norma's style suggestions and this will be good to go.

**Comment by laosijikaichele** [comment]
Done the suggestion change, thanks for the review.

**Review by chrisvest — APPROVED** [review]
