### PR TITLE
Fix AutoScalingEventExecutorChooser scale down when executor is not started

### LINKED ISSUE #15758: AutoScalingEventExecutorChooserFactory doesn’t scale when threads are in ST_NOT_STARTED state
Hi

First of all — thanks for adding the **active thread count metric** in [#15617](https://github.com/netty/netty/issues/15617)
It’s been very helpful for tracking how auto-scaling behaves in production 

While testing it, we noticed one edge case:
When the server starts but no requests have come in yet, some `SingleThreadEventExecutor`s stay in `ST_NOT_STARTED`, and the scaling logic doesn’t kick in.
Basically, `activeExecutorCount` never updates until the first task runs.

Here’s what seems to be happening inside `trySuspend()`:

```java
@Override
public boolean trySuspend() {
    if (supportSuspension) {
        if (STATE_UPDATER.compareAndSet(this, ST_STARTED, ST_SUSPENDING)) {
            wakeup(inEventLoop());
            return true;
        }
        int currentState = state;
        return currentState == ST_SUSPENDED || currentState == ST_SUSPENDING;
    }
    return false;
}
```

Since the CAS only works from `ST_STARTED → ST_SUSPENDING`, it fails when the executor is still `ST_NOT_STARTED`.

Ideally, executors in ST_NOT_STARTED should not be counted as active in the active executor count,
so that the scaling logic can accurately reflect how many threads are actually running.

### PR DESCRIPTION
**Pull request by leonchen83**
Motivation:

After the addition of the active executor count metric in [#15617](https://github.com/netty/netty/issues/15617),
we noticed that the metric and scaling logic behave incorrectly when some `SingleThreadEventExecutor` remain in the `ST_NOT_STARTED` state.

In this case, the executors are counted as active even though they have never started.
As a result, auto-scaling may not behave correctly (e.g., scaling down logic not triggered).

Modification:

Updated `SingleThreadEventExecutor.trySuspend()` to handle the `ST_NOT_STARTED` case:

```java
@Override
public boolean trySuspend() {
    if (supportSuspension) {
        if (STATE_UPDATER.compareAndSet(this, ST_STARTED, ST_SUSPENDING)) {
            wakeup(inEventLoop());
            return true;
        } else if (STATE_UPDATER.compareAndSet(this, ST_NOT_STARTED, ST_SUSPENDED)) {
            return true;
        }
        int currentState = state;
        return currentState == ST_SUSPENDED || currentState == ST_SUSPENDING;
    }
    return false;
}
```

This ensures that not-started executors can be properly transitioned into a suspended state
without requiring them to start first.

Result:

Fixes #15758.

### CODE REVIEW

File: common/src/test/java/io/netty/util/concurrent/SingleThreadEventExecutorTest.java [hunk 1]
```diff
@@ -142,6 +142,32 @@ void testSuspension() throws Exception {
...
+        Thread currentThread = threadFactory.threads.take();
+        assertFalse(executor.isSuspended());
+        task1.await();
+
+        executor.shutdownGracefully(0, 0, TimeUnit.MILLISECONDS).syncUninterruptibly();
+        currentThread.join();
+        assertFalse(executor.isSuspended());
+        assertTrue(executor.isShutdown());
+
+        // Guarantee that al tasks were able to die...
```
Comment (normanmaurer) [inline common/src/test/java/io/netty/util/concurrent/SingleThreadEventExecutorTest.java]:
```suggestion
        // Guarantee that all threads were able to die...
```

**Comment by leonchen83** [comment]
Signed just now.

**Review by franz1981 — APPROVED** [review]
