### PR TITLE
Make public API specify explicit maxAllocation to prevent OOM

### LINKED ISSUE #6663: WebSocket compression can increase data size, even when this exceeds max frame size
### Expected behavior

"Compressing" WebSocket frames with `io.netty.handler.codec.http.websocketx.extensions.compression.WebSocketServerCompressionHandler` will never increase packet size because, otherwise, there is no way to know when data that is "compressed" to a larger size that will exceed the max frame size.

### Actual behavior

"Compressing" WebSocket frames with `io.netty.handler.codec.http.websocketx.extensions.compression.WebSocketServerCompressionHandler` will never increase packet size when the deflated version happens to be larger than the source.  The can result in protocol violations that close the channel.

### Steps to reproduce

Create a WebSocket client and server with compression enabled.  Create a WebSocket frame equal to the max frame size that "compresses" to a size larger than the input and send it from the client.  Send the frame.  The server will close the connection with a protocol violation.

### Minimal yet complete reproducer code (or URL to code)

PR fixing this, with tests, forthcoming.  Need to get contributor agreement signed, first.

### Netty version

4.1.9

### JVM version (e.g. `java -version`)

Any.

### OS version (e.g. `uname -a`)

Any.

### PR DESCRIPTION
**Pull request by DeviLab**
Motivation:

The current `ZLibCodecFactory` provides `newZlibDecoder` methods without an option to specify a maximum memory limit for decompression. These methods are utilized in various parts of the project, such as the per-message WebSocket extension. As a result, a client could send a small, maliciously crafted compressed message that, upon decompression, would consume all available memory. This can lead to an `OutOfMemoryError` scenario, which can easily be reproduced as follows:

```
Exception in thread "io-compute-15" java.lang.OutOfMemoryError: Java heap space
	at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:326)
	at io.netty.buffer.PoolArena$HeapArena.newByteArray(PoolArena.java:628)
	at io.netty.buffer.PoolArena$HeapArena.newUnpooledChunk(PoolArena.java:652)
	at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:224)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:142)
	at io.netty.buffer.PoolArena.reallocate(PoolArena.java:317)
	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:123)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:333)
	at io.netty.handler.codec.compression.ZlibDecoder.prepareDecompressBuffer(ZlibDecoder.java:74)
	at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:265)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:348)
	at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder.decompressContent(DeflateDecoder.java:119)
	at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder.decode(DeflateDecoder.java:80)
	at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:87)
	at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:31)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
java.lang.OutOfMemoryError: Java heap space
	at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:326)
	at io.netty.buffer.PoolArena$HeapArena.newByteArray(PoolArena.java:628)
	at io.netty.buffer.PoolArena$HeapArena.newUnpooledChunk(PoolArena.java:652)
```

Modification:

- Introduced new `newZlibDecoder` methods within `ZlibCodecFactory` that include an explicit `maxAllocation` parameter to specify the maximum allowed memory during decompression.
- The older methods have been deprecated in favor of the new ones.
- Public APIs that invoke `newZlibDecoder` now require the `maxAllocation` parameter as well.

Result:

This change does not modify the public API behavior, but it encourages users to adopt the updated methods, which include the explicit `maxAllocation` argument, providing more control over memory usage during decompression.

Fixes #6663.

### CODE REVIEW

**Comment by DeviLab** [comment]
The the problem is that I as a third-party developer can't stop their user from sending 10 GB repeating string, which is compressed into a couple of kilobytes. I got the stacktrace above exactly with such manipulations. There only way to prevent it is to limit maximum decompressed size. It has been done before in `ZlibDecoder`, but for some reason its constructor with `maxAllocation` is not used. As a result, the buffer size can be much higher than the heap size.

**Comment by DeviLab** [comment]
I checked why the pipeline failed. It looks like unrelated to my change: JVM is suddenly crashed on `io.netty.channel.uring.IoUringBufferRingSocketSslClientRenegotiateTest`. Locally this test passes. Could you please restart the pipeline?

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateFrameClientExtensionHandshaker.java [hunk 1]
```diff
@@ -61,16 +110,19 @@ public DeflateFrameClientExtensionHandshaker(int compressionLevel, boolean useWe
...
-            WebSocketExtensionFilterProvider extensionFilterProvider) {
+            WebSocketExtensionFilterProvider extensionFilterProvider, int maxAllocation) {
         if (compressionLevel < 0 || compressionLevel > 9) {
             throw new IllegalArgumentException(
                     "compressionLevel: " + compressionLevel + " (expected: 0-9)");
         }
         this.compressionLevel = compressionLevel;
         this.useWebkitExtensionName = useWebkitExtensionName;
         this.extensionFilterProvider = checkNotNull(extensionFilterProvider, "extensionFilterProvider");
+        this.maxAllocation = maxAllocation;
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateFrameClientExtensionHandshaker.java:125]: Should we check that this is >= 0 ?. There are utilities in `ObjectUtils` for this. This is true for all constructors

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java [hunk 2]
```diff
@@ -104,27 +104,42 @@ public static ZlibEncoder newZlibEncoder(int compressionLevel, int windowBits, i
         }
     }
 
+    @Deprecated
     public static ZlibDecoder newZlibDecoder() {
+        return newZlibDecoder(0);
+    }
+
+    public static ZlibDecoder newZlibDecoder(int maxAllocation) {
```
Comment (chrisvest) [inline codec-compression/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java:112]: Please add javadocs, here and elsewhere, that explain the parameters.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/WebSocketClientCompressionHandler.java [hunk 3]
```diff
@@ -27,12 +27,14 @@
 @ChannelHandler.Sharable
 public final class WebSocketClientCompressionHandler extends WebSocketClientExtensionHandler {
 
+    private static final int MAX_ALLOCATION = 1024 * 1024 * 10;
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/WebSocketClientCompressionHandler.java:30]: Why was 10 MiB chosen as the limit? Is this something people might want to make configurable?

**Review by chrisvest — COMMENTED** [review]
Thanks for doing this work!

I had some comments.

File: codec-http2/src/main/java/io/netty/handler/codec/http2/DelegatingDecompressorFrameListener.java [hunk 4]
```diff
@@ -52,16 +52,30 @@ public class DelegatingDecompressorFrameListener extends Http2FrameListenerDecor
...
+        this(connection, listener, true, maxAllocation);
+    }
+
+    @Deprecated
+    public DelegatingDecompressorFrameListener(Http2Connection connection, Http2FrameListener listener,
+                                               boolean strict) {
+        this(connection, listener, strict, 0);
+    }
+
+    public DelegatingDecompressorFrameListener(Http2Connection connection, Http2FrameListener listener,
```
Comment (idelpivnitskiy) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/DelegatingDecompressorFrameListener.java:73]: Consider adding javadoc for all constructors

File: example/src/main/java/io/netty/example/factorial/FactorialClientInitializer.java [hunk 5]
```diff
@@ -43,7 +43,7 @@ public void initChannel(SocketChannel ch) {
 
         // Enable stream compression (you can remove these two if unnecessary)
         pipeline.addLast(ZlibCodecFactory.newZlibEncoder(ZlibWrapper.GZIP));
-        pipeline.addLast(ZlibCodecFactory.newZlibDecoder(ZlibWrapper.GZIP));
+        pipeline.addLast(ZlibCodecFactory.newZlibDecoder(ZlibWrapper.GZIP, 65536));
```
Comment (idelpivnitskiy) [inline example/src/main/java/io/netty/example/factorial/FactorialClientInitializer.java:46]: Consider using a static constant to make it easier for readers of all examples to understand what this number means

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java [hunk 6]
```diff
@@ -104,27 +104,42 @@ public static ZlibEncoder newZlibEncoder(int compressionLevel, int windowBits, i
...
         if (noJdkZlibDecoder) {
-            return new JZlibDecoder();
+            return new JZlibDecoder(maxAllocation);
         } else {
-            return new JdkZlibDecoder(true);
```
[the remark this answers is not in the document]
Comment (DeviLab) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java:111]: Deprecated both

File: codec-http2/src/main/java/io/netty/handler/codec/http2/DelegatingDecompressorFrameListener.java (hunk 4 above)
Comment (DeviLab) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/DelegatingDecompressorFrameListener.java:111]: Added

File: example/src/main/java/io/netty/example/factorial/FactorialClientInitializer.java (hunk 5 above)
Comment (DeviLab) [reply example/src/main/java/io/netty/example/factorial/FactorialClientInitializer.java]: Moved to a static constant

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateFrameClientExtensionHandshaker.java (hunk 1 above)
Comment (DeviLab) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateFrameClientExtensionHandshaker.java]: Added to all public constructors

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java (hunk 2 above)
Comment (DeviLab) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java:124]: Added to every `newZlibDecoder` method

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/WebSocketClientCompressionHandler.java (hunk 3 above)
Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/WebSocketClientCompressionHandler.java:30]: I think we should deprecate the `public static final WebSocketClientCompressionHandler INSTANCE = new WebSocketClientCompressionHandler();` and then just add another constructor that takes the max allocation size as the constructor 
`

**Review by normanmaurer — APPROVED** [review]

**Review by chrisvest — APPROVED** [review]

**Comment by normanmaurer** [comment]
@DeviLab thanks!
