### PR TITLE
Prefer `/etc/resolv.conf` on Linux and Mac

### LINKED ISSUE #13883: Allow looking up DNS servers, even if JNDI is disabled
Context is [this Quarkus issue](https://github.com/quarkusio/quarkus/issues/23519), TL;DR Quarkus disables JNDI by default (can't use an `(Initial)Context(Factory)` [at all](https://github.com/quarkusio/quarkus/blob/2fa75a15e9b5c73990a7ca01ca2678161c0d3e3d/independent-projects/bootstrap/runner/src/main/java/io/quarkus/bootstrap/naming/DisabledInitialContext.java)), but that breaks the (default) DNS servers lookup in [DirContextUtils](https://github.com/netty/netty/blob/85cee9d1a8881a93e7c43a02baefea75b6ade2b5/resolver-dns/src/main/java/io/netty/resolver/dns/DirContextUtils.java), so DNS lookups default to the public Google DNS servers. This means, that looking up k8s service names isn't possible without either enabling JNDI, which is not such a great option, or specifying DNS servers manually (oh my).

Naively, one could instantiate `com.sun.jndi.dns.DnsContextFactory`, but nah - JPMS gets in the way there (which is fine IMO).

OTOH `sun.net.dns.ResolverConfigurationImpl` doesn't do anything else than reading `/etc/resolv.conf` (at least on Linux + macOS).

WDYT about adding a fallback to `DirContextUtils` that if the lookup of the DNS servers via JNDI fails, it reads `/etc/resolv.conf` directly? Doesn't feel to be a huge ton of work, can contribute a PR for that.

/cc @geoand @cescoffier

### PR DESCRIPTION
**Pull request by snazy**
Quarkus disables JNDI by default, which breaks the (default) DNS servers lookup in `DirContextUtils`, so DNS lookups default to the public Google DNS servers. This means, that looking up k8s service names, or any internal names, isn't possible without either enabling JNDI, which is not such a great option, or specifying DNS servers manually, which is awkward, since there is `/etc/resolv.conf`.

This change prefers reading the nameservers from `/etc/resolv.conf` over looking those up on JNDI on Linux + macOS. This is effectively a noop-change when JNDI is enabled, because the nameservers available via JNDI are read from `/etc/resolv.conf`. Behavior for Windows (still requires JNDI) and Android (neither JNDI nor `/etc/resolv.conf`) is not changed.

Fixes #13883

### CODE REVIEW

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+import java.io.IOException;
+import java.net.InetSocketAddress;
+import java.util.ArrayList;
+import java.util.Collections;
+import java.util.List;
+
+/**
+ * Looks up the {@code nameserver}s from the {@code /etc/resolv.conf} file, intended for Linux and macOS.
+ */
+public final class ResolvConf {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:29]:
```suggestion
final class ResolvConf {
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+     */
+    public static ResolvConf fromReader(BufferedReader reader) throws IOException {
+        return new ResolvConf(reader);
+    }
+
+    /**
+     * Reads the given file and extracts the {@code nameserver}s using the syntax of the
+     * {@code /etc/resolv.conf} file, see {@code man resolv.conf}.
+     */
+    public static ResolvConf fromFile(String file) throws IOException {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:44]:
```suggestion
   static ResolvConf fromFile(String file) throws IOException {
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+        } finally {
+            fileReader.close();
+        }
+    }
+
+    /**
+     * Returns the {@code nameserver}s from the {@code /etc/resolv.conf} file. The file is only read once
+     * during the lifetime of this class.
+     */
+    public static ResolvConf system() {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:58]:
```suggestion
   static ResolvConf system() {
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java [hunk 4]
```diff
@@ -52,7 +52,12 @@ public final class DefaultDnsServerAddressStreamProvider implements DnsServerAdd
         if (!PlatformDependent.isAndroid()) {
             // Only try to use when not on Android as the classes not exists there:
             // See https://github.com/netty/netty/issues/8654
-            DirContextUtils.addNameServers(defaultNameServers, DNS_PORT);
+            if (!PlatformDependent.isWindows()) {
+                // /etc/resolv.conf exists on Linux + macOS, but not on Android
+                defaultNameServers.addAll(ResolvConf.system().getNameservers());
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java:57]: Should we only fallback if `DirContextUtils` fails ?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java (hunk 4 above)
Comment (snazy) [reply resolver-dns/src/main/java/io/netty/resolver/dns/DefaultDnsServerAddressStreamProvider.java:57]: Not sure it's worth it, because it does the same thing under the covers.

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java [hunk 5]
```diff
@@ -0,0 +1,100 @@
+/*
+ * Copyright 2018 The Netty Project
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:2]:
```suggestion
 * Copyright 2024 The Netty Project
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+     */
+    static ResolvConf fromFile(String file) throws IOException {
+        FileReader fileReader = new FileReader(file);
+        try {
+            BufferedReader reader = new BufferedReader(new FileReader(file));
+            return fromReader(reader);
+        } finally {
+            fileReader.close();
+        }
+    }
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:52]: Seems like `fileReader` is not used at all.

```suggestion
    static ResolvConf fromFile(String file) throws IOException {
        return fromReader(new BufferedReader(new FileReader(file)));
    }
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+
+/**
+ * Looks up the {@code nameserver}s from the {@code /etc/resolv.conf} file, intended for Linux and macOS.
+ */
+final class ResolvConf {
+    private final List<InetSocketAddress> nameservers;
+
+    /**
+     * Reads from the given reader and extracts the {@code nameserver}s using the syntax of the
+     * {@code /etc/resolv.conf} file, see {@code man resolv.conf}.
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:34]: Maybe clarify that the given `BufferedReader` is not closed or maybe even close it ?

File: resolver-dns/src/test/java/io/netty/resolver/dns/ResolvConfTest.java [hunk 8]
```diff
@@ -0,0 +1,88 @@
+/*
+ * Copyright 2018 The Netty Project
```
Comment (normanmaurer) [inline resolver-dns/src/test/java/io/netty/resolver/dns/ResolvConfTest.java:2]:
```suggestion
 * Copyright 2024 The Netty Project
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java [hunk 9]
```diff
@@ -0,0 +1,100 @@
...
+            }
+        }
+        this.nameservers = Collections.unmodifiableList(nameservers);
+    }
+
+    List<InetSocketAddress> getNameservers() {
+        return nameservers;
+    }
+
+    static final class ResolvConfLazy {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:87]:
```suggestion
    private static final class ResolvConfLazy {
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java (hunk 6 above)
Comment (snazy) [reply resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:52]: Updated this one to always close the `FileReader`. Had a try-with-resources here initially, but the Java 1.6 refactoring "broke" this :(

File: resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java (hunk 7 above)
Comment (snazy) [reply resolver-dns/src/main/java/io/netty/resolver/dns/ResolvConf.java:34]: added

**Comment by normanmaurer** [comment]
@snazy seems like there needs to be some changes for Graal:

```
2024-03-06T18:49:37.0250646Z [netty-testsuite-native-image-client:45791]     analysis:  17,178.48 ms,  1.73 GB
2024-03-06T18:49:37.0282068Z Error: No instances of java.net.Inet4Address are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.net.Inet4Address.
2024-03-06T18:49:37.0284558Z Detailed message:
2024-03-06T18:49:37.0285256Z Trace: Object was reached by 
2024-03-06T18:49:37.0286116Z 	reading field java.net.InetSocketAddress$InetSocketAddressHolder.addr of
2024-03-06T18:49:37.0287313Z 		constant java.net.InetSocketAddress$InetSocketAddressHolder@772827a0 reached by 
2024-03-06T18:49:37.0288313Z 	reading field java.net.InetSocketAddress.holder of
2024-03-06T18:49:37.0289152Z 		constant java.net.InetSocketAddress@2adf00cb reached by 
2024-03-06T18:49:37.0290121Z 	indexing into array
2024-03-06T18:49:37.0290707Z 		constant java.lang.Object[]@1be7100 reached by 
2024-03-06T18:49:37.0291472Z 	reading field java.util.ArrayList.elementData of
2024-03-06T18:49:37.0292456Z 		constant java.util.ArrayList@78b418c5 reached by 
2024-03-06T18:49:37.0293346Z 	reading field java.util.Collections$UnmodifiableCollection.c of
2024-03-06T18:49:37.0294486Z 		constant java.util.Collections$UnmodifiableRandomAccessList@8639235 reached by 
2024-03-06T18:49:37.0295618Z 	reading field io.netty.resolver.dns.ResolvConf.nameservers of
2024-03-06T18:49:37.0296621Z 		constant io.netty.resolver.dns.ResolvConf@7217133e reached by 
2024-03-06T18:49:37.0297790Z 	scanning method io.netty.resolver.dns.ResolvConf.system(ResolvConf.java:62)
2024-03-06T18:49:37.0298987Z Call path from entry point to io.netty.resolver.dns.ResolvConf.system(): 
2024-03-06T18:49:37.0300200Z 	no path found from entry point to target method
2024-03-06T18:49:37.0300697Z 
2024-03-06T18:49:37.0300716Z 
2024-03-06T18:49:37.0301474Z Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
2024-03-06T18:49:37.0725682Z Error: Image build request failed with exit status 1
```

**Comment by snazy** [comment]
> @snazy seems like there needs to be some changes for Graal:

Hm, true. That was quite a journey w/ Graal native images...
Anyway, it eventually complained also about `io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider`, so I added that class as well. Just wonder, why it worked before, because that also referenced `java.net.InetSocketAddress`.

**Comment by snazy** [comment]
Hm - guess that build error is unrelated?
```
2024-03-07T17:34:51.7020567Z [ERROR] Failed to execute goal me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5:fuzzingclient (default) on project netty-testsuite-autobahn: Unable to start server: InvocationTargetException: Address already in use -> [Help 1]
```
