### PR TITLE
Fix performance regression on HttpPost RequestDecoder

### LINKED ISSUE #10508: HttpPostMultipartRequestDecoder performance regression
### Expected behavior

#10226 improves performance.

### Actual behavior

The decoder is now at least 100x slower than before iff it is offered a direct buffer.

If the decoder is offered a direct buffer it now creates a bunch of 64b direct buffers during parsing, where before it always used heap buffers.
Using a `PooledByteBufAllocator` that prefers direct buffers did not solve the issue.
Using a `(Un)PooledByteBufAllocator` that prefers heap buffers normalizes performance again.

Given that this issue was not listed in the announcement under important, I would think that this was not intentional.

### Steps to reproduce

Create a HttpPostMultipartRequestDecoder and offer around a 1000 chunks (64k); in 4.1.49 this runs in seconds, whereas in 4.1.50 it takes minutes.

### Minimal yet complete reproducer code (or URL to code)

We have [this](https://github.com/apache/flink/blob/e991de19337591cde444fbede010cb8bdc7f118f/flink-runtime/src/test/java/org/apache/flink/runtime/rest/FileUploadHandlerTest.java) test in Apache Flink that exhibits the problem.
I can try to write a minimal reproducer if requested; may take some time to figure out how to correctly create the requests :/

### Netty version

4.1.50

### JVM version (e.g. `java -version`)

8

### OS version (e.g. `uname -a`)

Windows 10, but we also saw it on ubuntu linux

### PR DESCRIPTION
**Pull request by fredericBregier**
Fix issue #10508 where PARANOID mode slow down about 1000 times compared to ADVANCED.

Motivation:

Too many `readByte()` method calls while other ways exist (such as keep in memory the last scan position when trying to find a delimiter or using `bytesBefore(firstByte)` instead of looping externally).

Modification:

Changes done:
- major change on way buffer are parsed: instead of read byte per byte until found delimiter, try to find the delimiter using `bytesBefore()` and keep the last unfound position to skeep already parsed parts (algorithms are kept the same but scan implementations are different, minimizing access to the `undecodedChunk` buffer)

A benchmark is added to show the behavior of the various cases (one big item, such as File upload, and many items) and various level of detection (Disabled, Simple, Advanced, Paranoid). This benchmark is intend to alert if new implementations make too many differences (such as the previous version where about PARANOID gives about 1000 times slower than other levels, while it is now about at most 10 times).

Result:

Observations using Async-Profiler:
==========================

1) Without optimizations, most of the time (more than 95%) is through `readByte()` method within `loadDataMultipartStandard` method.
2) With using `bytesBefore(byte)` instead of `readByte()` to find various delimiter, the `loadDataMultipartStandard` method is going down to 19 to 33% depending on the test used. the `readByte()` method or equivalent `getByte(pos)` method are going down to 15% (from 95%).

Times are confirming those profiling:
============================
- 1 vs 2: With optimizations, in SIMPLE mode about 82% better, in ADVANCED mode about 79% better and in PARANOID mode about 99% better (most of the duplicate read accesses are removed or make internally through `bytesBefore(byte)` method)

Extract of Benchmark run:
====================

Run complete. Total time: 00:13:27

Benchmark                                                                           Mode  Cnt  Score   Error   Units
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigAdvancedLevel   thrpt    6  2,925 ± 0,233  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigDisabledLevel   thrpt    6  3,498 ± 1,484  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigParanoidLevel   thrpt    6  1,443 ± 0,027  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigSimpleLevel     thrpt    6  2,983 ± 0,103  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighAdvancedLevel  thrpt    6  1,690 ± 0,060  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighDisabledLevel  thrpt    6  1,935 ± 0,030  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighParanoidLevel  thrpt    6  0,201 ± 0,005  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighSimpleLevel    thrpt    6  1,858 ± 0,055  ops/ms

### CODE REVIEW

**Comment by fredericBregier** [comment]
Additional notes:
Replacing `buf.alloc().buffer(buf.readableBytes(), buf.readableBytes()).writeBytes(buf)` 
- when using `buf.copy()` or `buf.retainedSlice()` or `buf.retainedDuplicate()` give worst result (300ms more, so 700ms)

Also, PARANOID seems to be a bit less than first tests (520ms), probably measures, even if repeated, are not that stable.

**Comment by fredericBregier** [comment]
I remove the `wrapped`, getting back to original code, but still replace the allocation of other buffers with explicit upper bound, since they cannot be greater than lower bound.
I change the test using the given one by the end user. Note that I feel like this tests shall not be kept since it does nothing except performance check.
This gives great results, with a speedup on usual condition (not PARANOID) about twice better at most, but 100 times better using PARANOID mode, giving back the ability for the user pointing out this issue to use again the PARANOID mode is their tests.

WDYT @zentol @normanmaurer

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java [hunk 1]
```diff
@@ -1035,7 +1035,7 @@ private static String readLine(ByteBuf undecodedChunk, Charset charset) {
         }
         SeekAheadOptimize sao = new SeekAheadOptimize(undecodedChunk);
         int readerIndex = undecodedChunk.readerIndex();
-        ByteBuf line = undecodedChunk.alloc().heapBuffer(64);
+        ByteBuf line = undecodedChunk.alloc().heapBuffer(64, 64);
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1038]: @fredericBregier can you explain why setting an upper limit improves things here ?

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1038]: @normanmaurer 
I don't have any real clue, but it seems it does. That's why I'm asking you to look at this why. 

The change is huge on performances in PARANOID mode (using the example test given by the final user), about 10 times better... I test several times, and without it, the times are about 1000ms, while with it, it gives about 100ms.

Using my old test (a bit different, where a lot of items, about 6000, are passed and not only one file), the improvement is there also on PARANOID mode, but not that much (not 10 times better, comparing 146.000 old code vs 105.000 new code). 
There, the issue (and change) is on the `undecodedChunk.write(buf)`.
But if I change it to something like `wrappedBuffers(undecodedChunk, buf)`, the time is close to 1000ms again in PARANOID mode, but increases sensibly in other modes (500ms against 200ms without any change).


It was strange for me to see that comparing:
- `undecodedChunk = isLast? ... : buf.alloc.buffer(buf.readableSize(), buf.readableSize()).write(buf)` and `undecodedChunk = Unpooled.wrapped(undecodedChunk, buf.alloc.buffer(buf.readableSize(), buf.readableSize()).write(buf))`
- vs original ones (still in place at lines 338 and 340

gives impact performances (better for PARANOID, about 1000 times, but worst in other modes, about 2 times). I feel like it was the same in both cases (allocation and writing), but it seems not. Note that in current code, `undecodedChunk` in line 338 is still allocated using no upper bound.

The main "same root cause" seems to be "no upper bound for buffer" when using PARANOID mode, but in different ways.


I feel like this proposal is safe as it enhances a bit the general performances and takes down the PARANOID issue, at least for the user's example.
But I feel also that there is something else, since in my test (high number of items) this is really not enough.

So the reason I try to test it and produce at least this in order to get help.

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java]: @normanmaurer 

I added a fake commit to let you run the different cases at once:

This commit is only intend to show the result on tests using 3 cases:
- HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 1: original case
- HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 2: where only upper bound is modified
- HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 3: where write is replaced by wrapped and the last "no upper bounded" buffer is replaced too

Test to run is `testRegressionMultipleLevelLeakDetector`.

On my side results are:

Timer: DISABLED NotUsingDisk1 => 220.995585
**Timer: SIMPLE NotUsingDisk1 => 222.134248**
Timer: ADVANCED NotUsingDisk1 => 208.68989
**_Timer: PARANOID NotUsingDisk1 => 100044.293876_**
Timer: DISABLED UsingDisk1 => 707.480873
Timer: DISABLED UsingDisk1 => 518.695771
Timer: SIMPLE UsingDisk1 => 522.790849
Timer: ADVANCED UsingDisk1 => 585.759164
Timer: PARANOID UsingDisk1 => 105090.135276

Timer: DISABLED NotUsingDisk2 => 136.461289
**Timer: SIMPLE NotUsingDisk2 => 126.793194**
Timer: ADVANCED NotUsingDisk2 => 129.771282
**_Timer: PARANOID NotUsingDisk2 => 973.38734_**
Timer: DISABLED UsingDisk2 => 74.279745
Timer: DISABLED UsingDisk2 => 71.332363
Timer: SIMPLE UsingDisk2 => 114.811827
Timer: ADVANCED UsingDisk2 => 89.290387
Timer: PARANOID UsingDisk2 => 1155.278418

Timer: DISABLED NotUsingDisk3 => 1829.364849
**Timer: SIMPLE NotUsingDisk3 => 1949.512746**
Timer: ADVANCED NotUsingDisk3 => 2120.573799
**_Timer: PARANOID NotUsingDisk3 => 2073.506771_**
Timer: DISABLED UsingDisk3 => 1998.837595
Timer: DISABLED UsingDisk3 => 1952.342478
Timer: SIMPLE UsingDisk3 => 2099.951834
Timer: ADVANCED UsingDisk3 => 2058.028121
Timer: PARANOID UsingDisk3 => 2295.847557

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java]: Last fake commit:

This commit is only intend to show the result on tests using 3 cases:
    - HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 1: original case
    - HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 2: where only upper bound is modified
    - HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 3: where temptative to reuse more the existing ByteBuf is done
    
Test to run is `testRegressionMultipleLevelLeakDetectorNoDisk` or `testHighNumberCheckLeakDetectorVersions`
    
Current results (stability is correct but numbers depend on host)

I've done various tests:
- using `wrapped` (or through `buf.alloc().compositeByteBuf()`): worst timers
- using fixed allocation (but high enough to fit,the necessary elements, just for test): not good timers (probably because the size is too huge for a lot of cases, and whatever, it is not acceptable to have fixed size, it was just for testing purpose)
- using various ways to discard read bytes: it gives a bit improvement (TEST_TEMP_ITEM=3): almost best results, but not that much

In particular, in the "big" test (testHighNumberCheckLeakDetectorVersions where more than 16000 items are sent, while the other test is only one item from a big file), I am not able to reduce the timer in PARANOID mode, while in "unique" item test ( testRegressionMultipleLevelLeakDetectorNoDisk), the PARANOID decreases a lot.

Even if I cannot understand why setting the upper bound brings such a better improvement, I feel like this is at least a good change.
However, for the other try using discardReadBytes (or tries using wrapped buffers), it seems to not enhanced the timers.

@normanmaurer If you have any clue to continue, I will. I would propose to at least have the minimal change (upper bounds) in order to fix a bit this issue in PARANOID mode (and does not changed a lot, better or worst, for other levels).

_Here are my results (I tried to use profiling to understand the reasons, but the profiling just kill all results, therefore I was unable to deep in buffer implementations to see where is the main difference)._


testHighNumberCheckLeakDetectorVersions
=======================================

HighItemNumberDISABLED1=506.43838600000004, 
HighItemNumberDISABLED2=496.729877, 
HighItemNumberDISABLED3=503.72193200000004, 

**_HighItemNumberSIMPLE1=460.46265600000004, 
HighItemNumberSIMPLE2=475.950721, 
HighItemNumberSIMPLE3=467.69606699999997,_** 

HighItemNumberADVANCED1=465.508472, 
HighItemNumberADVANCED2=611.797092, 
HighItemNumberADVANCED3=467.812221, 

**HighItemNumberPARANOID1=304098.68770899996, 
HighItemNumberPARANOID2=304140.256149, 
HighItemNumberPARANOID3=303301.14581200003,** 

BigItemDISABLED1=426.205971, 
BigItemDISABLED2=441.343974, 
BigItemDISABLED3=420.528978, 

**_BigItemSIMPLE1=420.825118, 
BigItemSIMPLE2=432.968082, 
BigItemSIMPLE3=418.955781,_** 

BigItemADVANCED1=420.391646, 
BigItemADVANCED2=445.089119, 
BigItemADVANCED3=428.97732599999995, 

**BigItemPARANOID1=318339.78715600003
BigItemPARANOID2=319121.713933
BigItemPARANOID3=316866.262051**

testRegressionMultipleLevelLeakDetectorNoDisk
=============================================

Timer: DISABLED NotUsingDisk1 => 195.185296
Timer: DISABLED NotUsingDisk2 => 206.28149
Timer: DISABLED NotUsingDisk3 => 142.354934

**_Timer: SIMPLE NotUsingDisk1 => 185.459894
Timer: SIMPLE NotUsingDisk2 => 82.243331
Timer: SIMPLE NotUsingDisk3 => 83.65489_**

Timer: ADVANCED NotUsingDisk1 => 175.245971
Timer: ADVANCED NotUsingDisk2 => 214.114222
Timer: ADVANCED NotUsingDisk3 => 89.005829

**Timer: PARANOID NotUsingDisk1 => 119286.301819
Timer: PARANOID NotUsingDisk2 => 1604.135822
Timer: PARANOID NotUsingDisk3 => 2489.555437**

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java [hunk 2]
```diff
@@ -306,6 +308,7 @@ public InterfaceHttpData getBodyHttpData(String name) {
         return null;
     }
 
+    public static int TEST_TEMP_ITEM = 1;
```
Comment (franz1981) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:311]: Use final here, it would change a lot how the JIT would optimize it.
Use a sys property to set this and just use different runs with different JVMs (probably using a good profiler + JMH bench would be ideal to be use of the impact/meaning of changes)

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:311]: @franz1981 Thank you !
I agree that making it final shall be done to achieve final checks. This variable was only intend to allow 3 kinds of tests, not to be keeped of course in final code (and if final, I couldn't change the value of course).

Now, using a final here, 3 different runs (changing value of course) and a good profiler could be far better and ideal, I agree. 

However, as I said, when using a profiler (the one I have is from Oracle - VisualVM-, and I believe it is not the best around, but the only one I've got), the performances drop severely (even in DISCARDED mode), therefore nothing to look at correctly. For my other tasks, this one is great, giving the information I need and with not that much impact. But there, the performances are almost all at the same level than PARANOID, even in DISCARDED or SIMPLE mode.

Can you suggest some tools (free, sadly) that could help in this research?

Comment (franz1981) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:311]: Sure!

https://github.com/jvm-profiling-tools/async-profiler is probably one of the most complete, accurate and cheap (;)) ones I know.
Highly suggested to add -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints

**Comment by njhill** [comment]
@fredericBregier a couple of JVM args that might be worth trying that _might_ help to shed some light on the cause:
- `-XX:MaxInlineLevel=24` (number kind of arbitrary but should be big)
- `-XX:-TieredCompilation`

Also I'm sure @franz1981 is about to answer this but for profiling you should use [async profiler](https://github.com/jvm-profiling-tools/async-profiler).

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java (hunk 2 above)
Comment (franz1981) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:311]: @njhill now you read my mind bud?:)

**Comment by fredericBregier** [comment]
Well, I have to say that I make it totally wrong. Hopefully, your advices were good to help me (using async profile) that the behavior was totally different.

My mistake was assuming upper bounds are correct. In fact, they are not (at least for the 64 length item). Therefore it changed the decoding.
Now reverting this does not change the behavior.
I still need some time to check if some improvements can be done since the timer differences between other levels and PARANOID are huge (x 1000):
- allocating a bit more than 64 (since headers in multipart are very often larger than this, but not that much, for instance 128) to give a chance to not fragmented the memory
- try some optimizations on already allocated buffers, in order to keep as small as possible reallocation
- I will retry also to use wrapped buffers, even if my previous tests show decreased performances

However, using the tests show me something strange:
- while the algorithm should used only one `undecodedChunk` buffer, retained only once (whatever from original buffer or from a new allocated one), the `refCnt` keep increasing (therefore the final `destroy()`, calling `release()` is not ok).

I need time to investigate this. Maybe a side effect of testing (the way tests are done, not through network but direct offer calls), maybe not...

Whatever, this MR has to be considered as wrong, but still need investigation.

Thank you all @normanmaurer @njhill @franz1981

**Comment by fredericBregier** [comment]
To @normanmaurer @njhill @franz1981 
I finally get the main reason, using the tool you point me out.

Fix issue #10508 where PARANOID mode slow down about 1000 times compared to ADVANCED.

Reasons were:

- Too many `readByte()` method calls while other ways exist (such as keep in memory the last scan position when trying to find a delimiter or using `bytesBefore(firstByte)` instead of looping externally). (huge gain)
- In addition, try to reuse as much as possible already allocated buffers. (less gain but still)

This commit is only intend to show the result on tests using 3 cases:
- HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 1: original case
- HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 2: where only undecodedChunk temptatives of reusing already allocated buffers are made
- HttpPostMultipartRequestDecoder.TEST_TEMP_ITEM = 3: where change on way buffer are parsed: instead of read byte per byte until found delimiter, try to find the delimiter using bytesBefore() and keep the last unfound position to skeep already parsed parts

Test to run is `testRegressionMultipleLevelLeakDetectorNoDisk` or `testHighNumberCheckLeakDetectorVersions`

Current results:

testHighNumberCheckLeakDetectorVersions
=======================================

{BigItemSIMPLE1=4100, BigItemADVANCED1=4100, BigItemDISABLED1=4100, HighItemNumberADVANCED1=4500, HighItemNumberSIMPLE1=4500, HighItemNumberDISABLED1=4100, HighItemNumberPARANOID1=1480000, BigItemPARANOID1=1450000}

{BigItemDISABLED2=2339, BigItemADVANCED2=2345, BigItemSIMPLE2=2383, HighItemNumberDISABLED2=2840, HighItemNumberSIMPLE2=2864, HighItemNumberADVANCED2=3048, HighItemNumberPARANOID2=1511640, BigItemPARANOID2=1588672}

Without optim level 2
{BigItemDISABLED3=423, BigItemADVANCED3=429, BigItemSIMPLE3=453, HighItemNumberSIMPLE3=834, HighItemNumberDISABLED3=936, HighItemNumberADVANCED3=978, BigItemPARANOID3=2720, HighItemNumberPARANOID3=17182}

With Optim level 2
{BigItemDISABLED3=420, BigItemSIMPLE3=422, BigItemADVANCED3=451, HighItemNumberSIMPLE3=821, HighItemNumberDISABLED3=930, HighItemNumberADVANCED3=1003, BigItemPARANOID3=2660, HighItemNumberPARANOID3=16712}

testRegressionMultipleLevelLeakDetectorNoDisk
=============================================

Timer: DISABLED NotUsingDisk1 => 1903.912934
Timer: SIMPLE NotUsingDisk1 => 1926.971844
Timer: ADVANCED NotUsingDisk1 => 26489.845075
Timer: PARANOID NotUsingDisk1 => 1082819.185679

Timer: DISABLED NotUsingDisk2 => 1538.593234
Timer: SIMPLE NotUsingDisk2 => 1590.055765
Timer: ADVANCED NotUsingDisk2 => 1538.786221
Timer: PARANOID NotUsingDisk2 => 1132602.00827

Timer: DISABLED NotUsingDisk3 => 653.744671
Timer: SIMPLE NotUsingDisk3 => 785.152185
Timer: ADVANCED NotUsingDisk3 => 572.136954
Timer: PARANOID NotUsingDisk3 => 1039.148579

Observations using Async-Profiler:

1) Without optimizations, most of the time (more than 95%) is through `readByte()` method within `loadDataMultipartStandard` method.
2) With level 2 (reusing as much as possible already allocated buffers and limit the allocation as small as possible), about 0.2% less within `readByte()` for only 0.01% more in `offer()` method (where reusing buffer, possibly rewriting internally using `discardReadBytes()` ).
3) With level 3 (using `bytesBefore(byte)` instead of `readByte()` to find the delimiter), the `loadDataMultipartStandard` method is going down to 19 to 33% depending on the test used. the `readByte()` method or equivalent `getByte(pos)` method are going down to 15% (from 95%).

Times are confirming those profiling:
- V1 vs V2: In SIMPLE mode about 37% better, in ADVANCED mode about 32% better and in PARANOID mode about -2% worst (most of the read access and implicit stacktrace creation are masking the benefit)
- V1 vs V3: In SIMPLE mode about 82% better, in ADVANCED mode about 79% better and in PARANOID mode about 99% better (most of the duplicate read accesses are removed or make internally through `bytesBefore(byte)` method)


Of course, I will clean the code once I've got your review and comments.

Thank you !! I learned a cool tool !

**Comment by chrisvest** [comment]
I don't think you have to wait for review comments before cleaning up the code. If there are changes you know should happen, then you can do those right away.

Some of the tests look like benchmarks. It would be good to have those reimplemented in the `microbench` module, with JMH as the driver instead of JUnit.

**Comment by normanmaurer** [comment]
+1 to what @chrisvest said...

**Comment by fredericBregier** [comment]
OK, I will ;-)
It was just to be able to compare running codes. Once done, it will not anymore be possible (except not getting last commit of course).
I will try to do a JMH (I have to learn it, nice ;-) ).

**Comment by fredericBregier** [comment]
To @normanmaurer @njhill @franz1981
Cleaning done and benchmark added too.
I try to rewrite the description in a cleaner way and adapted to the current implementation.

**Comment by chrisvest** [comment]
@netty-bot test this please

**Review by chrisvest — CHANGES_REQUESTED** [review]
3 quick comments. Looks like there are test failures too.

File: microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java [hunk 3]
```diff
@@ -0,0 +1,202 @@
+/*
+ * Copyright 2019 The Netty Project
```
[the remark this answers is not in the document]
Comment (fredericBregier) [reply microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java:2]: OK

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 4]
```diff
@@ -689,7 +695,9 @@ public void destroy() {
         destroyed = true;
 
         if (undecodedChunk != null && undecodedChunk.refCnt() > 0) {
-            undecodedChunk.release();
+            while (undecodedChunk.refCnt() > 0) {
+                undecodedChunk.release();
+            }
```
[the remark this answers is not in the document]
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:700]: Indeed, and I did not found why in some cases I have a huge number of refCnt(), so this.
However, I will remove it, going back to previous situation (probably bad programming on my side).

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java [hunk 5]
```diff
@@ -1290,96 +1159,89 @@ private static String readDelimiter(ByteBuf undecodedChunk, String delimiter) {
...
         }
-        if (prevByte == HttpConstants.CR) {
-            lastRealPos--;
+        // found delimiter but still need to check if CRLF before
+        int startDelimiter = newOffset;
+        if (undecodedChunk.getByte(startReaderIndex + startDelimiter - 1) ==
+            HttpConstants.LF) {
+            startDelimiter--;
+            if (undecodedChunk.getByte(startReaderIndex + startDelimiter - 1) ==
+                HttpConstants.CR) {
```
[the remark this answers is not in the document]
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1231]: Right, wrong indentation through IJ

**Comment by fredericBregier** [comment]
My bad ! I didn't check (lack of time and too confident) the test units.
Now I have.

I have made the corrections.

I found out that:
- rewriting buffer `undecodedChunk` was not a good idea since most of the implementation relies on the fact that this buffer is kept as is (at most, it is discard but not rewritten)
- one special case was not handled (when the `findDelimiter` has not found it but still at position `0`, now it throws as usual a `NotEnoughDataDecoderException` and is handled correctly later on)


However, my first issue (the fact that changing `undecodedChunk` by calling `undecodedChunk.discardReadBytes()`) is giving me a cold threat: 
- some lines below, there is the very same call (from long time ago, not my changed) that do exactly the same when a limit condition is encountered, meaning that if this condition is true, then all results might be wrong (10 MB today).

I believe that copying the buffer before registering the new HttpData has to be made, in order to not get into this issue.
The changes could be done but I do not know yet the impact (memory speeking and of course performances speaking) since it shall brings a lot of memory allocation and duplication (which this implementation tries to not do).
Another way, of course, could be to remove this guard, but if it is there, I'm sure it is also for a good reason (memory limit).

WDYT?

**Comment by fredericBregier** [comment]
To @normanmaurer @njhill @franz1981
I work on the (rare but real) bug I found incidently on the existing implementation and I finally got a way to clean it.

Fix `undecodedChunk` usage of `discardReadBytes()`

`undecodedChunk` was rewritten using `discardReadBytes()` method but the underlying `HttpData` were using original buffer values, therefore when this method is called, previously `HttpData` are corrupted.

This method was called originally when a certain amount of data is reached (10 MB), so the **_rare_** occurence.
However I found it through my previous implementation (doing the same, but more frequently) and I realized that even if I removed this change, this bug still remained (and was there for long).

This commit makes copy of `undecodedChunk` instead for each `HttpData` and also tries to optimize while reusing allocated buffer.

New results are almost the same than previously but without this pending (rare) bug.

New results:

Run complete. Total time: 00:13:27

Benchmark                                                                           Mode  Cnt  Score   Error   Units
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigAdvancedLevel   thrpt    6  2,940 ± 0,268  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigDisabledLevel   thrpt    6  2,696 ± 0,059  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigParanoidLevel   thrpt    6  1,360 ± 0,098  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigSimpleLevel     thrpt    6  2,806 ± 0,216  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighAdvancedLevel  thrpt    6  1,671 ± 0,165  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighDisabledLevel  thrpt    6  1,900 ± 0,041  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighParanoidLevel  thrpt    6  0,191 ± 0,008  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighSimpleLevel    thrpt    6  1,826 ± 0,411  ops/ms

Let me know if there is something wrong.

**Comment by fredericBregier** [comment]
@netty-bot test this please

**Comment by chrisvest** [comment]
@netty-bot test this please

**Comment by fredericBregier** [comment]
Checks are reported to have failed but not...

**Comment by chrisvest** [comment]
@fredericBregier 

```
17:39:28 [INFO] --- maven-checkstyle-plugin:3.1.0:check (check-style) @ netty-microbench ---
17:39:29 [INFO] Starting audit...
17:39:29 [ERROR] /code/microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java:1: Missing package-info.java file. [JavadocPackage]
17:39:29 Audit done.
```

**Comment by fredericBregier** [comment]
@chrisvest Ah, ok! Thank you! I will add this file.

**Comment by fredericBregier** [comment]
@chrisvest Done ;-)

**Comment by chrisvest** [comment]
@netty-bot test this please

**Comment by fredericBregier** [comment]
`Netty/Transport/BlockHound/Tests` failed once (Java 12, but not others) (but out of scope of this commit and not known link to it

**Comment by fredericBregier** [comment]
I believe the main idea behind (using `bytesBefore(byte)` instead of `readByte()` to find one delimiter) could be used in other places in Netty. This seems to behave better than just iterating on `buffer.readByte()` and after resetting if not found the read position.

I may have some time to check in other placed where it could be applied and verify the improvements, if any (while I believe there will be). Of course, in another MR...

**Comment by chrisvest** [comment]
@netty-bot test this please

**Comment by fredericBregier** [comment]
@chrisvest  Probably a recent change in check on http link since it was ok on previous tests.
Fixed it.

File: microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java [hunk 6]
```diff
@@ -0,0 +1,202 @@
+/*
+ * Copyright 2020 The Netty Project
+ *
+ * The Netty Project licenses this file to you under the Apache License,
+ * version 2.0 (the "License"); you may not use this file except in compliance
+ * with the License. You may obtain a copy of the License at:
+ *
+ *   http://www.apache.org/licenses/LICENSE-2.0
```
Comment (chrisvest) [inline microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java:8]:
```suggestion
 *   https://www.apache.org/licenses/LICENSE-2.0
```

Comment (fredericBregier) [reply microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java:8]: Already done ;-)

File: microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java [hunk 7]
```diff
@@ -0,0 +1,202 @@
...
+      ResourceLeakDetector.setLevel(Level.SIMPLE);
+      return testHighNumberChunks(true, true);
+    } finally {
+      ResourceLeakDetector.setLevel(level);
+    }
+  }
+
+  @Benchmark
+  public double multipartRequestDecoderHighAdvancedLevel() {
+    final Level level = ResourceLeakDetector.getLevel();
```
Comment (normanmaurer) [inline microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java:160]: nit: we use 4 spaces ... Please change everywhere to be consistent with our code-styling

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 8]
```diff
@@ -438,7 +441,7 @@ private void parseBodyAttributesStandard() {
                     if (read == '&') {
                         currentStatus = MultiPartStatus.DISPOSITION;
                         ampersandpos = currentpos - 1;
-                        setFinalBuffer(undecodedChunk.retainedSlice(firstpos, ampersandpos - firstpos));
+                        setFinalBuffer(undecodedChunk.copy(firstpos, ampersandpos - firstpos));
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:444]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 9]
```diff
@@ -461,7 +464,7 @@ private void parseBodyAttributesStandard() {
                     } else if (read == HttpConstants.LF) {
                         currentStatus = MultiPartStatus.PREEPILOGUE;
                         ampersandpos = currentpos - 1;
-                        setFinalBuffer(undecodedChunk.retainedSlice(firstpos, ampersandpos - firstpos));
+                        setFinalBuffer(undecodedChunk.copy(firstpos, ampersandpos - firstpos));
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:467]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 10]
```diff
@@ -475,16 +478,15 @@ private void parseBodyAttributesStandard() {
                 // special case
                 ampersandpos = currentpos;
                 if (ampersandpos > firstpos) {
-                    setFinalBuffer(undecodedChunk.retainedSlice(firstpos, ampersandpos - firstpos));
+                    setFinalBuffer(undecodedChunk.copy(firstpos, ampersandpos - firstpos));
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:481]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 11]
```diff
@@ -475,16 +478,15 @@ private void parseBodyAttributesStandard() {
...
                 } else if (!currentAttribute.isCompleted()) {
                     setFinalBuffer(Unpooled.EMPTY_BUFFER);
                 }
                 firstpos = currentpos;
                 currentStatus = MultiPartStatus.EPILOGUE;
             } else if (contRead && currentAttribute != null && currentStatus == MultiPartStatus.FIELD) {
                 // reset index except if to continue in case of FIELD getStatus
-                currentAttribute.addContent(undecodedChunk.retainedSlice(firstpos, currentpos - firstpos),
-                                            false);
+                currentAttribute.addContent(undecodedChunk.copy(firstpos, currentpos - firstpos), false);
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:489]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 12]
```diff
@@ -558,7 +560,7 @@ private void parseBodyAttributes() {
                     if (read == '&') {
                         currentStatus = MultiPartStatus.DISPOSITION;
                         ampersandpos = currentpos - 1;
-                        setFinalBuffer(undecodedChunk.retainedSlice(firstpos, ampersandpos - firstpos));
+                        setFinalBuffer(undecodedChunk.copy(firstpos, ampersandpos - firstpos));
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:563]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 13]
```diff
@@ -569,7 +571,7 @@ private void parseBodyAttributes() {
                                 currentStatus = MultiPartStatus.PREEPILOGUE;
                                 ampersandpos = currentpos - 2;
                                 sao.setReadPosition(0);
-                                setFinalBuffer(undecodedChunk.retainedSlice(firstpos, ampersandpos - firstpos));
+                                setFinalBuffer(undecodedChunk.copy(firstpos, ampersandpos - firstpos));
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:574]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 14]
```diff
@@ -587,7 +589,7 @@ private void parseBodyAttributes() {
                         currentStatus = MultiPartStatus.PREEPILOGUE;
                         ampersandpos = currentpos - 1;
                         sao.setReadPosition(0);
-                        setFinalBuffer(undecodedChunk.retainedSlice(firstpos, ampersandpos - firstpos));
+                        setFinalBuffer(undecodedChunk.copy(firstpos, ampersandpos - firstpos));
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:592]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 15]
```diff
@@ -604,16 +606,15 @@ private void parseBodyAttributes() {
                 // special case
                 ampersandpos = currentpos;
                 if (ampersandpos > firstpos) {
-                    setFinalBuffer(undecodedChunk.retainedSlice(firstpos, ampersandpos - firstpos));
+                    setFinalBuffer(undecodedChunk.copy(firstpos, ampersandpos - firstpos));
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:609]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 16]
```diff
@@ -604,16 +606,15 @@ private void parseBodyAttributes() {
...
                 } else if (!currentAttribute.isCompleted()) {
                     setFinalBuffer(Unpooled.EMPTY_BUFFER);
                 }
                 firstpos = currentpos;
                 currentStatus = MultiPartStatus.EPILOGUE;
             } else if (contRead && currentAttribute != null && currentStatus == MultiPartStatus.FIELD) {
                 // reset index except if to continue in case of FIELD getStatus
-                currentAttribute.addContent(undecodedChunk.retainedSlice(firstpos, currentpos - firstpos),
-                                            false);
+                currentAttribute.addContent(undecodedChunk.copy(firstpos, currentpos - firstpos), false);
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:617]: hmm... retainedSlice(...) should be fine. This will do an extra memory copy which I think is not needed.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java [hunk 17]
```diff
@@ -661,7 +662,7 @@ private static ByteBuf decodeAttribute(ByteBuf b, Charset charset) {
             return null; // nothing to decode
         }
 
-        ByteBuf buf = b.alloc().buffer(b.readableBytes());
+        ByteBuf buf = b.alloc().buffer(b.readableBytes(), b.readableBytes());
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:665]: I think the `b.readable()` for the second arg is not needed.

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java (hunk 7 above)
Comment (fredericBregier) [reply microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java:160]: OK, I will double check.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java (hunk 8 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:444]: As I wrote, there is a "old" bug, rarely catched, when the buffer `undecodedChunk` exceed the memory limit. When it reached this limit, there is a call to `undecodedChunk.discardReadBytes();`. I found this bug accidently, through my other new calls to the very same methods and errors in unit testing.

When this call occurs, the underlying buffers are changed, changing all HttpData values (of course, incorrectly).
To prevent this, I propose to copy it. I know this is higher in memory copy, but correct from final values, instead of current status.
Also, I changed this "high limit only" call to "each time it is relevant" (when new data can be added while there are enough space within the current buffer to fill it with this new data).

Another way would be to igonre totally this high limit and therefore not calling, nowhere, this `undecodedChunk.discardReadBytes();`, in order to keep final consistency.

WDYT?

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java (hunk 17 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:665]: Not mandatory, but there, it is valid (there is no need to allocate more than this in this specific case).
If you prefer, I could remove it (while valid).

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java (hunk 8 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:444]: Of course, the second option (no more calls to `discardReadBytes()`) would lead to higher memory usage since the underlying buffer will be kept until the end.
Using "to disk" (or mixed way) management of HttpData can decrease this memory pressure, espcially for File upload (but not limited to), but as in mixed way, some HttpData could stay using the original undecodedChunk, this could lead in wrong data at the end, so my original proposition.

Any direction or idea ?

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:444]: I think we should only call `undecoded.discardReadBytes()` if `refCnt() == 1`.

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java:444]: It could be a good idea !
I know this will be almost never true (due to `retainedSlice()` that will increment `refCnt()`), but at least, it will give a chance for it (as with `SeekAhead` algorithm that is almost never usable) and obviously limits the copy as much as possible.

I will git it a try. Thanks @normanmaurer for this idea !

File: microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java (hunk 7 above)
Comment (fredericBregier) [reply microbench/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoderBenchmark.java]: Done

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java (hunk 8 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostStandardRequestDecoder.java]: Done:

New benchmark results:
Benchmark                                                                           Mode  Cnt  Score   Error   Units
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigAdvancedLevel   thrpt    6  2,248 ± 0,198  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigDisabledLevel   thrpt    6  2,067 ± 1,219  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigParanoidLevel   thrpt    6  1,109 ± 0,038  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigSimpleLevel     thrpt    6  2,326 ± 0,314  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighAdvancedLevel  thrpt    6  1,444 ± 0,226  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighDisabledLevel  thrpt    6  1,462 ± 0,642  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighParanoidLevel  thrpt    6  0,159 ± 0,003  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighSimpleLevel    thrpt    6  1,522 ± 0,049  ops/ms

Almost the same as in previous code.

**Comment by fredericBregier** [comment]
New benchmarks result after applying @normanmaurer 's idea (keep `retainedSlice` instead of `copy` but limiting therefore `discardReadBytes` when `refCnt == 1`):

Benchmark                                                                           Mode  Cnt  Score   Error   Units
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigAdvancedLevel   thrpt    6  2,248 ± 0,198  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigDisabledLevel   thrpt    6  2,067 ± 1,219  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigParanoidLevel   thrpt    6  1,109 ± 0,038  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigSimpleLevel     thrpt    6  2,326 ± 0,314  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighAdvancedLevel  thrpt    6  1,444 ± 0,226  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighDisabledLevel  thrpt    6  1,462 ± 0,642  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighParanoidLevel  thrpt    6  0,159 ± 0,003  ops/ms
HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighSimpleLevel    thrpt    6  1,522 ± 0,049  ops/ms

**Comment by chrisvest** [comment]
@netty-bot test this please

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java [hunk 18]
```diff
@@ -704,6 +710,7 @@ public void testDecodeMalformedEmptyContentTypeFieldParameters() throws Exceptio
         assertTrue(part1 instanceof FileUpload);
         FileUpload fileUpload = (FileUpload) part1;
         assertEquals("tmp-0.txt", fileUpload.getFilename());
+        req.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:713]: seems like a leak in the test that was not related to your change... correct ?

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java [hunk 19]
```diff
@@ -427,6 +432,7 @@ public void testMultipartRequestWithoutContentTypeBody() {
         // Create decoder instance to test without any exception.
         final HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(inMemoryFactory, req);
         assertFalse(decoder.getBodyHttpDatas().isEmpty());
+        req.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:435]: seems like a leak in the test that was not related to your change... correct ?

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java [hunk 20]
```diff
@@ -397,6 +401,7 @@ public void testFilenameContainingSemicolon2() throws Exception {
         assertTrue(part1 instanceof FileUpload);
         FileUpload fileUpload = (FileUpload) part1;
         assertEquals("tmp 0.txt", fileUpload.getFilename());
+        req.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:404]: seems like a leak in the test that was not related to your change... correct ?

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java [hunk 21]
```diff
@@ -368,6 +371,7 @@ public void testFilenameContainingSemicolon() throws Exception {
         // Create decoder instance to test.
         final HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(inMemoryFactory, req);
         assertFalse(decoder.getBodyHttpDatas().isEmpty());
+        req.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:374]: seems like a leak in the test that was not related to your change... correct ?

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java [hunk 22]
```diff
@@ -211,6 +213,7 @@ public void testQuotedBoundary() throws Exception {
...
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:216]: seems like a leak in the test that was not related to your change... correct ?

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java [hunk 23]
```diff
@@ -178,6 +179,7 @@ public void testMultipartCodecWithCRasEndOfAttribute() throws Exception {
             assertNotNull(datar);
             assertEquals(datas[i].getBytes(CharsetUtil.UTF_8).length, datar.length);
 
+            req.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:182]: seems like a leak in the test that was not related to your change... correct ?

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java [hunk 24]
```diff
@@ -132,6 +132,7 @@ public void testFullHttpRequestUpload() throws Exception {
         // Create decoder instance to test.
         final HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(inMemoryFactory, req);
         assertFalse(decoder.getBodyHttpDatas().isEmpty());
+        req.release();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:135]: seems like a leak in the test that was not related to your change... correct ?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java (hunk 18 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:713]: Yes, not related. I was just getting from time to time (before and after changes) an error in PARANOID mode, so I tried to fix as much as possible the tests to be more coherent. 
The reason is: as the test is not going through network but directly, so there is no handler that take care of incoming messages, there is no clean of the request after receiving it by the main handler as it should.

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java (hunk 20 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:404]: Same answear: not related, just fix the test

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java (hunk 19 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:435]: Same answear: not related, just fix the test

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java (hunk 21 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:374]: Same answear: not related, just fix the test

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java (hunk 22 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:216]: Same answear: not related, just fix the test

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java (hunk 23 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:182]: Same answear: not related, just fix the test

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java (hunk 24 above)
Comment (fredericBregier) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java:135]: Same answear: not related, just fix the test

**Review by chrisvest — APPROVED** [review]
Complicated code to review, but at least the new stuff is both simpler and faster 👍

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@fredericBregier this is ready to go... could just just please squash and adjust the commit message to include everything that should go in :) Sorry for the slow turnaround

**Comment by fredericBregier** [comment]
@normanmaurer I rewrite the commit message and squash all commits.
No change done since all is relevant.
No problem for the delay, I know how it works... ;-)
