### PR TITLE
Chunked HTTP length decoding should account for whitespaces/ctrl chars (Fixes #13273)

### LINKED ISSUE #13273: HttpObjectDecoder.getChunkedSize trips over whitespace
### Expected behavior
the chunked size is calculated correctly

### Actual behavior
java.lang.NumberFormatException is thrown

### Steps to reproduce

See code below.

Please be aware that I'm not at all familiar with the netty code. Added a few comments in the code below.

### Minimal yet complete reproducer code (or URL to code)

```
import io.netty.util.internal.StringUtil;
import java.nio.charset.StandardCharsets;

public class JavaTester {

     private static int getChunkSizeNewFixed(byte[] hex, int start, int length) {
        // byte[] is produced by LineParse::parseLine that already skip ISO CTRL and Whitespace chars
        // COMMENT: ^ I could see handling for control chars but not whitespaces ^, but maybe I'm missing something.
        int result = 0;
        for (int i = 0; i < length; i++) {
            final int digit = StringUtil.decodeHexNibble(hex[start + i]);
            if (digit == -1) {
                // COMMENT: Until version 4.1.87.final the whitespace and control char checks where in there
                if (hex[start + i] == ';' || Character.isWhitespace(hex[start + i])) {
                    return result;
                }
                throw new NumberFormatException();
            }
            result *= 16;
            result += digit;
        }
        return result;
    }

    private static int getChunkSizeNew(byte[] hex, int start, int length) {
        // byte[] is produced by LineParse::parseLine that already skip ISO CTRL and Whitespace chars
        int result = 0;
        for (int i = 0; i < length; i++) {
            final int digit = StringUtil.decodeHexNibble(hex[start + i]);
            if (digit == -1) {
                // uncommon path
                if (hex[start + i] == ';') {
                    return result;
                }
                throw new NumberFormatException();
            }
            result *= 16;
            result += digit;
        }
        return result;
    }

    public static void main(String... args) {
        String toTest = "BDC Cookie: NSC_wTfswfs_c2cjoufhsbujpo=ffffffff099b5f1f45525d5f4f58455e445a4a42378b;expires=Mon, 13-Mar-2023 14:16:06 GMT;path=/;secure;httponly";
        System.out.println(getChunkSizeNewFixed(toTest.getBytes(StandardCharsets.UTF_8), 0, 4));
        System.out.println(getChunkSizeNew(toTest.getBytes(StandardCharsets.UTF_8), 0, 4)); <-- throws NumberFormatException
    }
}
```

### Netty version

from 4.1.88 onwards.

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)

### OS version (e.g. `uname -a`)
MacOS and Ubuntu

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

#12321 introduces the assumption that whitespaces/ctrl chars are already stripped out hex chars of HTTP chunk length. It was a wrong assumption.

Modifications:

Correctly check for whitespace and ctrl chars and re-introduce whitespace (leading) trim

Result:

Fixes #13273

### CODE REVIEW

**Comment by franz1981** [comment]
@normanmaurer I've already verified that the previous decoder implementation (before #13273) can run the additional tests without problems, but...creating tons of `String`s, hence this version is now correct and faster/less memory hungry.
Sorry for the introduced bug; hope the additional tests will help for the future!

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java [hunk 1]
```diff
@@ -1127,4 +1149,8 @@ public boolean process(byte value) {
             return ISO_CONTROL_OR_WHITESPACE[128 + value];
         }
     };
+
+    private static boolean isControlOrWhitespaceAsciiChar(byte b) {
+        return ISO_CONTROL_OR_WHITESPACE[128 + b];
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java:1154]: Do we need to ensure this will not throw an IndexOutOfBoundsException ?

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java [hunk 2]
```diff
@@ -799,16 +799,38 @@ private LastHttpContent readTrailingHeaders(ByteBuf buffer) {
     protected abstract HttpMessage createMessage(String[] initialLine) throws Exception;
     protected abstract HttpMessage createInvalidMessage();
 
+    private static int skipWhiteSpaces(byte[] hex, int start, int length) {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java:802]: please provide some javadoc / comments to explain what exactly it returns

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java [hunk 3]
```diff
@@ -799,16 +799,38 @@ private LastHttpContent readTrailingHeaders(ByteBuf buffer) {
...
     private static int getChunkSize(byte[] hex, int start, int length) {
-        // byte[] is produced by LineParse::parseLine that already skip ISO CTRL and Whitespace chars
+        // trim the leading bytes if white spaces, if any
+        final int skipped = skipWhiteSpaces(hex, start, length);
+        if (skipped == length) {
+            // empty case
+            throw new NumberFormatException();
+        }
+        start = start + skipped;
+        length = length - skipped;
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java:819]:
```suggestion
        start += skipped;
        length -= skipped;
```

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpResponseDecoderTest.java [hunk 4]
```diff
@@ -147,6 +147,118 @@ public void testResponseChunked() {
...
+
+        // Write the last chunk.
+        ch.writeInbound(Unpooled.copiedBuffer("0\r\n\r\n", CharsetUtil.US_ASCII));
+
+        // Ensure the last chunk was decoded.
+        LastHttpContent lastContent = ch.readInbound();
+        assertFalse(lastContent.content().isReadable());
+        lastContent.release();
+
+        ch.finish();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpResponseDecoderTest.java:218]:
```suggestion
        assertFalse(ch.finish());
```

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpResponseDecoderTest.java [hunk 5]
```diff
@@ -147,6 +147,118 @@ public void testResponseChunked() {
...
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpResponseDecoderTest.java:258]:
```suggestion
        assertFalse(ch.finish());
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java (hunk 1 above)
Comment (franz1981) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java:1154]: It cannot, in theory, the array should be big enough to cover the full spectrum of byte values (but let me check)

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java [hunk 6]
```diff
@@ -799,16 +799,41 @@ private LastHttpContent readTrailingHeaders(ByteBuf buffer) {
...
+                return i;
+            }
+        }
+        return length;
+    }
+
     private static int getChunkSize(byte[] hex, int start, int length) {
-        // byte[] is produced by LineParse::parseLine that already skip ISO CTRL and Whitespace chars
+        // trim the leading bytes if white spaces, if any
+        final int skipped = skipWhiteSpaces(hex, start, length);
```
Comment (jchrys) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java:816]: very tiny thing, but could you consider `countLeadingWhiteSpaces`? IMHO, it might make its purpose clear.

**Comment by normanmaurer** [comment]
@franz1981 do we need a PR for main as well ?

**Comment by franz1981** [comment]
Nope because for @normanmaurer I haven't yet ported the speedup of HTTP 1.1: both decoding/encoding are still WIP in my mind, but probably it's time I can do it for the decoding part at least
