### PR TITLE
Stomp over WebSocket Chat example

### LINKED ISSUE #9383: netty-codec-stomp server and client for stomp.js example
### Steps to reproduce
server: stomp codec
ChannelPipeline pipeline = ch.pipeline();
pipeline.addLast("decoder", new StompSubframeDecoder());
pipeline.addLast("encoder", new StompSubframeEncoder());
pipeline.addLast("aggregator", new StompSubframeAggregator(65536));
pipeline.addLast("handler", new StompServerHandler());
client: stomp.js,html
var stompClient = Stomp.client("ws://127.0.0.1:8083");
stompClient.connect({userName: "张三", userId: "test1"}, function(frame) {
       console.error("连接成功");
});

### Minimal yet complete reproducer code (or URL to code)
stomp codec
### Netty version
4.1.37

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
w10

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:

Often people want to use `stomp-codec` with WebSocket transport or other but cannot figure out how can do this staff on Netty.

Modification:

Create example for demonstrating integration between STOMP and WebSocket.
Inspired by https://github.com/jmesnil/stomp-websocket

Result:

Fixes #9383

### CODE REVIEW

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 1]
```diff
@@ -0,0 +1,193 @@
...
+import static io.netty.buffer.ByteBufUtil.*;
+import static io.netty.handler.codec.stomp.StompHeaders.*;
+import static io.netty.util.CharsetUtil.*;
+
+@Sharable
+public class StompChatHandler extends SimpleChannelInboundHandler<StompFrame> {
+
+    static final StompChatHandler INSTANCE = new StompChatHandler();
+
+    private final ConcurrentHashMap<String, Set<StompSubscription>> CHAT_DESTINATIONS =
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java]: wouldn't it be better to make this non static and create one instance of the handler that is shared at the end ? This way we ensure at least stuff can be GC'ed.

Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java]: `ConcurrentMap`...

File: example/src/main/java/io/netty/example/stomp/websocket/StompVersion.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+    STOMP_V11("1.1", "v11.stomp"),
+
+    STOMP_V12("1.2", "v12.stomp");
+
+    public static final AttributeKey<StompVersion> CHANNEL_ATTRIBUTE_KEY = AttributeKey.valueOf("stomp_version");
+    public static final String SUB_PROTOCOLS;
+
+    static {
+        ArrayList<String> subProtocols = new ArrayList<String>(values().length);
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompVersion.java]: `List`

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 1 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java]: Do you mean something like this:
```
@Sharable
public class StompWebSocketProtocolCodec extends MessageToMessageCodec<WebSocketFrame, ByteBuf> {

    private final StompChatHandler stompChatHandler = new StompChatHandler();

    @Override
    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
        if (evt instanceof WebSocketServerProtocolHandler.HandshakeComplete) {
            StompVersion stompVersion = StompVersion.findBySubProtocol(((HandshakeComplete) evt).selectedSubprotocol());
            ctx.channel().attr(StompVersion.CHANNEL_ATTRIBUTE_KEY).set(stompVersion);
            String ctxName = ctx.name();
            ctx.pipeline()
               .addAfter(ctxName, "stompChatHandler", stompChatHandler)
               .addAfter(ctxName, "stompAggregator", new StompSubframeAggregator(65536))
               .addAfter(ctxName, "stompEncoder", new StompSubframeEncoder())
               .addAfter(ctxName, "stompDecoder", new StompSubframeDecoder())
               .remove(StompWebSocketClientPageHandler.INSTANCE);
        } else {
            super.userEventTriggered(ctx, evt);
        }
        super.userEventTriggered(ctx, evt);
    }
```

File: example/src/main/java/io/netty/example/stomp/websocket/StompVersion.java (hunk 2 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompVersion.java]: Ooops !!

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 1 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java]: Thx again

Comment (normanmaurer) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:46]: yep... that said in your example you call `userEventTriggered` two times ;)

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 3]
```diff
@@ -0,0 +1,193 @@
...
+        case DISCONNECT:
+            onDisconnect(inboundFrame, ctx);
+            break;
+        default:
+            sendErrorFrame("unsupported command",
+                           "Received unsupported command " + inboundFrame.command(), ctx);
+        }
+    }
+
+    private void onConnect(StompFrame inboundFrame, ChannelHandlerContext ctx) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:80]: nit: I would make `ChannelHandlerContext` the first argument for all methods to be consistent with the rest of netty.

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 4]
```diff
@@ -0,0 +1,193 @@
...
+        String subscriptionId = inboundFrame.headers().getAsString(ID);
+
+        if (destination == null || subscriptionId == null) {
+            sendErrorFrame("missed header", "Required 'destination' or 'id' header missed", ctx);
+            return;
+        }
+
+        Set<StompSubscription> subscriptions =
+                CHAT_DESTINATIONS.putIfAbsent(destination, new HashSet<StompSubscription>());
+        if (subscriptions == null) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:108]: can this ever be null ? I mean you use ´.putIfAbsent´ just before.

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 5]
```diff
@@ -0,0 +1,193 @@
...
+    private void onSend(StompFrame inboundFrame, ChannelHandlerContext ctx) {
+        String destination = inboundFrame.headers().getAsString(DESTINATION);
+        if (destination == null) {
+            sendErrorFrame("missed header", "required 'destination' header missed", ctx);
+            return;
+        }
+
+        Set<StompSubscription> subscriptions = CHAT_DESTINATIONS.get(destination);
+        for (StompSubscription subscription : subscriptions) {
+            subscription.channel().writeAndFlush(transformToMessage(inboundFrame, subscription));
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:144]: imho you can just call `write(...)` and only flush at the end once you iterated over all of these.

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 6]
```diff
@@ -0,0 +1,193 @@
...
+            ctx.close();
+            return;
+        }
+
+        StompFrame receiptFrame = new DefaultStompFrame(StompCommand.RECEIPT);
+        receiptFrame.headers().set(RECEIPT_ID, receiptId);
+        ctx.writeAndFlush(receiptFrame).addListener(ChannelFutureListener.CLOSE);
+    }
+
+    private StompFrame transformToMessage(StompFrame sendFrame, StompSubscription subscription) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:173]: static ?

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 7]
```diff
@@ -0,0 +1,193 @@
...
+        StompFrame messageFrame = new DefaultStompFrame(StompCommand.MESSAGE, sendFrame.content().retainedDuplicate());
+        String id = UUID.randomUUID().toString();
+        messageFrame.headers()
+                    .set(MESSAGE_ID, id)
+                    .set(SUBSCRIPTION, subscription.id());
+        return messageFrame;
+    }
+
+    private void sendErrorFrame(String message, String description, ChannelHandlerContext ctx) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:182]: static ?

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 8]
```diff
@@ -0,0 +1,193 @@
...
+        StompFrame errorFrame = new DefaultStompFrame(StompCommand.ERROR);
+        errorFrame.headers().set(MESSAGE, message);
+
+        if (description != null) {
+            ByteBuf content = encodeString(ctx.alloc(), CharBuffer.wrap(description), UTF_8);
+            errorFrame.content().writeBytes(content);
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:188]: you need to release the `content`.

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 9]
```diff
@@ -0,0 +1,193 @@
...
+            while (iterator.hasNext()) {
+                StompSubscription subscription = iterator.next();
+                if (subscription.id().equals(subscriptionId) && subscription.channel().equals(ctx.channel())) {
+                    iterator.remove();
+                }
+            }
+        }
+    }
+
+    private void onDisconnect(StompFrame inboundFrame, ChannelHandlerContext ctx) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:161]: static

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 10]
```diff
@@ -0,0 +1,193 @@
...
+            return;
+        }
+
+        Set<StompSubscription> subscriptions = CHAT_DESTINATIONS.get(destination);
+        for (StompSubscription subscription : subscriptions) {
+            subscription.channel().writeAndFlush(transformToMessage(inboundFrame, subscription));
+        }
+    }
+
+    private void onUnsubscribe(StompFrame inboundFrame, ChannelHandlerContext ctx) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:148]: static

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 11]
```diff
@@ -0,0 +1,193 @@
...
+
+        String receiptId = inboundFrame.headers().getAsString(RECEIPT);
+        if (receiptId != null) {
+            StompFrame receiptFrame = new DefaultStompFrame(StompCommand.RECEIPT);
+            receiptFrame.headers().set(RECEIPT_ID, receiptId);
+            ctx.writeAndFlush(receiptFrame);
+        }
+    }
+
+    private void onSend(StompFrame inboundFrame, ChannelHandlerContext ctx) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:135]: static

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 12]
```diff
@@ -0,0 +1,193 @@
...
+
+        StompFrame connectedFrame = new DefaultStompFrame(StompCommand.CONNECTED);
+        connectedFrame.headers()
+                      .set(VERSION, handshakeAcceptVersion.version())
+                      .set(SERVER, "Netty-Server")
+                      .set(HEART_BEAT, "0,0");
+        ctx.writeAndFlush(connectedFrame);
+    }
+
+    private void onSubscribe(StompFrame inboundFrame, ChannelHandlerContext ctx) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:97]: static

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 3 above)
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:80]: static

File: example/src/main/java/io/netty/example/stomp/websocket/StompSubscription.java [hunk 13]
```diff
@@ -0,0 +1,75 @@
...
+ * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+ * License for the specific language governing permissions and limitations
+ * under the License.
+ */
+package io.netty.example.stomp.websocket;
+
+import io.netty.channel.Channel;
+import io.netty.util.internal.ObjectUtil;
+
+public class StompSubscription {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompSubscription.java:21]: final

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java [hunk 14]
```diff
@@ -0,0 +1,122 @@
...
+
+import static io.netty.handler.codec.http.HttpHeaderNames.*;
+import static io.netty.handler.codec.http.HttpHeaderValues.KEEP_ALIVE;
+import static io.netty.handler.codec.http.HttpHeaderValues.*;
+import static io.netty.handler.codec.http.HttpResponseStatus.*;
+import static io.netty.handler.codec.http.HttpVersion.*;
+
+@Sharable
+public class StompWebSocketClientPageHandler extends SimpleChannelInboundHandler<FullHttpRequest> {
+
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:47]: add private constructor and make it final

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java [hunk 15]
```diff
@@ -0,0 +1,122 @@
...
+            ctx.fireChannelRead(request.retain());
+            return;
+        }
+
+        if (!sendResource(request, ctx)) {
+            FullHttpResponse notFound = new DefaultFullHttpResponse(request.protocolVersion(), NOT_FOUND);
+            notFound.headers().set(CONTENT_TYPE, TEXT_PLAIN);
+            String payload = "Requested resource " + request.uri() + " not found";
+            notFound.content()
+                    .writeBytes(ByteBufUtil.encodeString(ctx.alloc(), CharBuffer.wrap(payload), CharsetUtil.UTF_8));
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:62]: Why can't you use `writeCharSequence(...)` ?

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java [hunk 16]
```diff
@@ -0,0 +1,122 @@
...
+            HttpUtil.setContentLength(notFound, notFound.content().readableBytes());
+            sendResponse(notFound, ctx, true);
+        }
+    }
+
+    private boolean sendResource(FullHttpRequest request, ChannelHandlerContext ctx) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:68]: static

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 5 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:142]: `ctx.flush()`, Does it mean flush for all channels ? I need broadcast to each channel and after it do flush for each or I'm wrong ?

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 3 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:78]: ok

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 4 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:106]: If this first attempt it's return null (`map.put(k,v)`)

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 1 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java]: Good caught 👍

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 6 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:171]: Done

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java (hunk 14 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:47]: Done

File: example/src/main/java/io/netty/example/stomp/websocket/StompSubscription.java (hunk 13 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompSubscription.java:21]: Done

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java (hunk 16 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:68]: Done

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 3 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:78]: Done

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java (hunk 15 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:62]: Fixed

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 3 above)
Comment (normanmaurer) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:78]: seems like you didn't push this yet

Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java]: Yes just pushed, also some fixes added in `StompWebSocketClientPageHandler.java`

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 17]
```diff
@@ -0,0 +1,189 @@
...
+        String subscriptionId = inboundFrame.headers().getAsString(ID);
+
+        if (destination == null || subscriptionId == null) {
+            sendErrorFrame("missed header", "Required 'destination' or 'id' header missed", ctx);
+            return;
+        }
+
+        Set<StompSubscription> subscriptions =
+                chatDestinations.putIfAbsent(destination, new HashSet<StompSubscription>());
+        if (subscriptions == null) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:87]: I see.. that said I think we should check with get first and then call putIfAbstent to ensure we not allocate a new `HashSet` all the time

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 5 above)
Comment (normanmaurer) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:123]: You are right... sorry I missed that there a different Channels.

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 17 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:87]: Got it

**Comment by amizurov** [comment]
@normanmaurer squashed commits

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 18]
```diff
@@ -0,0 +1,191 @@
...
+        if (destination == null || subscriptionId == null) {
+            sendErrorFrame("missed header", "Required 'destination' or 'id' header missed", ctx);
+            return;
+        }
+
+        Set<StompSubscription> subscriptions = chatDestinations.get(destination);
+        if (subscriptions == null) {
+            subscriptions = new HashSet<StompSubscription>();
+            if (chatDestinations.putIfAbsent(destination, subscriptions) != null) {
+                subscriptions = chatDestinations.get(destination);
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:89]: ni: there is no need to call get again... `putIfAbsent` will return the subscription already so just store it in another var and re-assign

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketChatServerInitializer.java [hunk 19]
```diff
@@ -0,0 +1,44 @@
...
+    }
+
+    @Override
+    protected void initChannel(SocketChannel channel) throws Exception {
+        channel.pipeline()
+               .addLast(new HttpServerCodec())
+               .addLast(new HttpObjectAggregator(65536))
+               .addLast(StompWebSocketClientPageHandler.INSTANCE)
+               .addLast(new WebSocketServerProtocolHandler(chatPath, StompVersion.SUB_PROTOCOLS))
+               .addLast("stompWebSocketProtocolCodec", stompWebSocketProtocolCodec);
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketChatServerInitializer.java:42]: nit: why specify an explicit name here ? We dont do this for the other handlers as well.

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java [hunk 20]
```diff
@@ -0,0 +1,132 @@
...
+            contentType = "text/html; charset=UTF-8";
+        } else if (requestResource.endsWith("css")) {
+            contentType = "text/css; charset=UTF-8";
+        } else if (requestResource.endsWith("js")) {
+            contentType = "application/javascript";
+        }
+
+        response.headers().set(CONTENT_TYPE, contentType);
+        sendResponse(response, ctx, false);
+        ctx.write(new DefaultFileRegion(raf.getChannel(), 0, fileLength), ctx.voidPromise());
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:112]: why explicit use `voidPromise` here ?

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java [hunk 21]
```diff
@@ -0,0 +1,67 @@
...
+    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
+        if (evt instanceof WebSocketServerProtocolHandler.HandshakeComplete) {
+            StompVersion stompVersion = StompVersion.findBySubProtocol(((HandshakeComplete) evt).selectedSubprotocol());
+            ctx.channel().attr(StompVersion.CHANNEL_ATTRIBUTE_KEY).set(stompVersion);
+            String ctxName = ctx.name();
+            ctx.pipeline()
+               .addAfter(ctxName, "stompChatHandler", stompChatHandler)
+               .addAfter(ctxName, "stompAggregator", new StompSubframeAggregator(65536))
+               .addAfter(ctxName, "stompEncoder", new StompSubframeEncoder())
+               .addAfter(ctxName, "stompDecoder", new StompSubframeDecoder())
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java:47]: why specify a name when adding to the pipeline ? Consider just not doing this

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java [hunk 22]
```diff
@@ -0,0 +1,132 @@
...
+            raf = new RandomAccessFile(resourceUrl.getFile(), "r");
+            fileLength = raf.length();
+        } catch (IOException io) {
+            System.out.println("File not found " + io.getMessage());
+            return false;
+        } finally {
+            if (fileLength < 0 && raf != null) {
+                try {
+                    raf.close();
+                } catch (Exception io) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:92]: IOException

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java [hunk 23]
```diff
@@ -0,0 +1,132 @@
...
+        if (resourceUrl == null) {
+            return false;
+        }
+
+        RandomAccessFile raf = null;
+        long fileLength = -1L;
+        try {
+            raf = new RandomAccessFile(resourceUrl.getFile(), "r");
+            fileLength = raf.length();
+        } catch (IOException io) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:85]: Should this be `FileNotFoundException` ?

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java [hunk 24]
```diff
@@ -0,0 +1,132 @@
...
+            notFound.headers().set(CONTENT_TYPE, TEXT_PLAIN);
+            String payload = "Requested resource " + request.uri() + " not found";
+            notFound.content().writeCharSequence(payload, CharsetUtil.UTF_8);
+            HttpUtil.setContentLength(notFound, notFound.content().readableBytes());
+            sendResponse(notFound, ctx, true);
+        }
+    }
+
+    private static boolean sendResource(FullHttpRequest request, ChannelHandlerContext ctx) {
+        String requestResource = request.uri().substring(1);
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:70]: I think we need to check that `!....uri().isEmpty()` as otherwise it may produce an `IndexOutOfBoundsException` above.

Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:70]: Done

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java (hunk 23 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:100]: Handled a both possible exception

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java (hunk 22 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java]: Fixed

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java (hunk 21 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java]: Changed over addLast()

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java (hunk 20 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java]: Removed

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketChatServerInitializer.java (hunk 19 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketChatServerInitializer.java]: Removed all codec names

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 18 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java]: Done

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java [hunk 25]
```diff
@@ -0,0 +1,199 @@
...
+        }
+    }
+
+    private void onUnsubscribe(ChannelHandlerContext ctx, StompFrame inboundFrame) {
+        String subscriptionId = inboundFrame.headers().getAsString(SUBSCRIPTION);
+        for (Entry<String, Set<StompSubscription>> entry : chatDestinations.entrySet()) {
+            Iterator<StompSubscription> iterator = entry.getValue().iterator();
+            while (iterator.hasNext()) {
+                StompSubscription subscription = iterator.next();
+                if (subscription.id().equals(subscriptionId) && subscription.channel().equals(ctx.channel())) {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: hmm... shouldn't this also take the destination somehow into account to match `StompSubscription.equals(...)` ?

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 25 above)
Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: By spec only `id` required for `UNSUBSCRIBE` command.

**Comment by normanmaurer** [comment]
@amizurov please check style:

```
16:37:54 [ERROR] /code/example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:78: an empty line before } [RegexpMultiline]
```

**Comment by amizurov** [comment]
> @amizurov please check style:
> 
> ```
> 16:37:54 [ERROR] /code/example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketClientPageHandler.java:78: an empty line before } [RegexpMultiline]
> ```

Fixed

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java (hunk 25 above)
Comment (llm163520) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: chat destination There is a fuzzy match;
Example: 
chat client destination: /topic/test/*
Whether the server can adapt better

Comment (llm163520) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: @amizurov @normanmaurer 
After the test found that the client port is not detected by the server

Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: > chat destination There is a fuzzy match;
> Example:
> chat client destination: /topic/test/*
> Whether the server can adapt better
> @amizurov @normanmaurer

Just for clarify, this is only example how you can integrate (WS and subProtocol(STOMP)). So fuzzy match is business feature if you think that is really needed you can provide a PR. IMHO.

Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: > @amizurov @normanmaurer
> After the test found that the client port is not detected by the server

I think we can handle index.html differently from resources (js, cs) with some simple templating. WDYT @normanmaurer

Comment (normanmaurer) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: At the end I think this is just an example and we should not over-complicate things.

Comment (llm163520) [reply example/src/main/java/io/netty/example/stomp/websocket/StompChatHandler.java:136]: @normanmaurer 
If the example can be close to the actual application scenario, the integration cost can be reduced;
I added some supplements to the above example to see if integration is needed;
image
image

**Comment by llm163520** [comment]
@normanmaurer 
I made a java chat client, I do n’t know if there is a better way to disconnect and reconnect; refer to the following example:
image

WebsocketStompClientTest:
public class WebsocketStompClientTest {

    public static void main(String[] args) throws Exception {
        stompClientTest();
    }

    private static void stompClientTest() throws Exception {
        WebSocketClientHandshaker handshaker = WebSocketClientHandshakerFactory.newHandshaker(websocketURI, WebSocketVersion.V13, StompVersion.STOMP_V12.subProtocol(), true, httpHeaders, maxContentLength);
        EventLoopGroup group = new NioEventLoopGroup();
        Bootstrap boot = new Bootstrap();
        boot.option(ChannelOption.SO_KEEPALIVE, true)
                .option(ChannelOption.TCP_NODELAY, true)
                .group(group)
                .handler(new LoggingHandler(LogLevel.INFO))
                .channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<SocketChannel>() {
                    protected void initChannel(SocketChannel socketChannel) throws Exception {
                        ChannelPipeline p = socketChannel.pipeline();
                        p.addLast(new ChannelHandler[]{new HttpClientCodec(), new HttpObjectAggregator(maxContentLength)});
                        p.addLast(new WebSocketClientProtocolHandler(handshaker));
                        p.addLast(new StompClientSubProtocolInitializer(maxContentLength, webSocketChannel -> {
                            //connected send message
                            Thread text = new Thread(new Runnable() {
                                public void run() {
                                    int i = 0;
                                    StompFrame frame = null;
                                    while (i < 5) {
                                        if (i == 0) {
                                            frame = new DefaultStompFrame(StompCommand.CONNECT, Unpooled.copiedBuffer("connect test: " + i, CharsetUtil.UTF_8));
                                            frame.headers()
                                                    .set(ACCEPT_VERSION, StompVersion.STOMP_V12.version())
                                                    .set(HEART_BEAT, "0, 0")
                                                    .set(CONTENT_LENGTH, Integer.toString(frame.content().readableBytes()));
                                        } else if (i == 4) {
                                            frame = new DefaultStompFrame(StompCommand.DISCONNECT, Unpooled.copiedBuffer("delete test: " + i, CharsetUtil.UTF_8));
                                        } else {
                                            frame = new DefaultStompFrame(StompCommand.SEND, Unpooled.copiedBuffer("send test: " + i, CharsetUtil.UTF_8));
                                            frame.headers().set(DESTINATION, "/topic/todoTask/open");
                                            frame.headers().set(CONTENT_LENGTH, Integer.toString(frame.content().readableBytes()));
                                        }
                                        System.out.println("text send " + frame.command() + ": " + i);
                                        webSocketChannel.writeAndFlush(frame).addListener(new ChannelFutureListener() {
                                            public void operationComplete(ChannelFuture channelFuture) throws Exception {
                                                if (channelFuture.isSuccess()) {
                                                    System.out.println("text send success");
                                                } else {
                                                    System.out.println("text send failed  " + channelFuture.cause().getMessage());
                                                }
                                            }
                                        });
                                        try {
                                            Thread.sleep(1000 * 1);
                                        } catch (Exception ex) {

                                        } finally {
                                            i++;
                                        }
                                    }

                                }
                            });
                            text.start();
                        }));
                    }
                });
        boot.connect(websocketURI.getHost(), websocketURI.getPort()).addListener(channelFutureListener).sync();
    }

    static {
        try {
            websocketURI = new URI("ws://localhost:8083/chat");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static URI websocketURI;
    private final static HttpHeaders httpHeaders = new DefaultHttpHeaders();
    private final static Integer maxContentLength = 1024 * 1024 * 64;

    private final static ChannelFutureListener channelFutureListener = new ChannelFutureListener() {

        @Override
        public void operationComplete(ChannelFuture channelFuture) throws Exception {
            if (channelFuture.isSuccess()) {
                // channel = futureListener.channel();
                System.out.println("Connect to server successfully!");
                channelFuture.channel().closeFuture().addListener(future -> {
                    System.out.println("close error");
                    if (future.isSuccess()) {
                        stompClientTest();
                    }
                });
            } else {
                System.out.println("Failed to connect to server, try connect after 10s");
                channelFuture.channel().eventLoop().schedule(() -> {
                    System.out.println("connect error");
                    try {
                        stompClientTest();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }, 10, TimeUnit.SECONDS);
            }
        }
    };

}
StompClientSubProtocolInitializer:
public class StompClientSubProtocolInitializer extends ChannelInitializer<SocketChannel> {

    private final Consumer<Channel> consumer;
    private final Integer maxContentLength;

    public StompClientSubProtocolInitializer(int maxContentLength, Consumer<Channel> consumer) {
        this.consumer = consumer;
        this.maxContentLength = maxContentLength;
    }

    @Override
    protected void initChannel(SocketChannel channel) throws Exception {
        channel.pipeline().addLast(new MessageToMessageCodec<WebSocketFrame, ByteBuf>() {
            @Override
            public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
                if (evt instanceof WebSocketClientProtocolHandler.ClientHandshakeStateEvent && evt == WebSocketClientProtocolHandler.ClientHandshakeStateEvent.HANDSHAKE_COMPLETE) {
                    ctx.pipeline()
                            .addLast("decoder", new StompSubframeDecoder())
                            .addLast("encoder", new StompSubframeEncoder())
                            .addLast("aggregator", new StompSubframeAggregator(maxContentLength))
                            .addLast("handler", new StompClientHandler());
                    if (consumer != null) {
                        consumer.accept(ctx.channel());
                    }
                } else {
                    super.userEventTriggered(ctx, evt);
                }
            }

            @Override
            protected void encode(ChannelHandlerContext ctx, ByteBuf stompFrame, List<Object> out) {
                out.add(new TextWebSocketFrame(stompFrame.retain()));
            }

            @Override
            protected void decode(ChannelHandlerContext ctx, WebSocketFrame webSocketFrame, List<Object> out) {
                if (webSocketFrame instanceof TextWebSocketFrame) {
                    out.add(webSocketFrame.content().retain());
                } else {
                    ctx.close();
                }
            }

        });
    }
}
StompClientHandler:
public class StompClientHandler extends SimpleChannelInboundHandler<StompFrame> {


    @Override
    protected void channelRead0(ChannelHandlerContext ctx, StompFrame inboundFrame) throws Exception {
        DecoderResult decoderResult = inboundFrame.decoderResult();
        if (decoderResult.isFailure()) {
            System.out.println("error msg: " + decoderResult.toString());
            return;
        }
        System.out.println("test: " + inboundFrame.content().toString());
    }
}
StompVersion: 
public enum StompVersion {

    STOMP_V11("1.1", "v11.stomp"),

    STOMP_V12("1.2", "v12.stomp");

    public static final AttributeKey<StompVersion> CHANNEL_ATTRIBUTE_KEY = AttributeKey.valueOf("stomp_version");
    public static final String SUB_PROTOCOLS;

    static {
        List<String> subProtocols = new ArrayList<String>(values().length);
        for (StompVersion stompVersion : values()) {
            subProtocols.add(stompVersion.subProtocol);
        }

        SUB_PROTOCOLS = StringUtil.join(",", subProtocols).toString();
    }

    private final String version;
    private final String subProtocol;

    StompVersion(String version, String subProtocol) {
        this.version = version;
        this.subProtocol = subProtocol;
    }

    public String version() {
        return version;
    }

    public String subProtocol() {
        return subProtocol;
    }

    public static StompVersion findBySubProtocol(String subProtocol) {
        if (subProtocol != null) {
            for (StompVersion stompVersion : values()) {
                if (stompVersion.subProtocol().equals(subProtocol)) {
                    return stompVersion;
                }
            }
        }
        throw new IllegalArgumentException("Not found StompVersion for '" + subProtocol + "'");
    }
}

**Comment by normanmaurer** [comment]
@llm163520 please don't hi-jack discussions. Use stack overflow for questions

**Comment by normanmaurer** [comment]
@amizurov seems like we can merge this now... anything you want to change before I do so ?

**Comment by amizurov** [comment]
> @amizurov seems like we can merge this now... anything you want to change before I do so ?

No, we can merge this.

**Comment by normanmaurer** [comment]
@amizurov thanks a lot...
