### PR TITLE
SslHandler#unwrap must send fireChannelRead event after a notification for a handshake success

### LINKED ISSUE #11201: `SslHandler#unwrap` sends `fireChannelRead` event BEFORE a notification for a handshake success
With change 0ef2f05373be323f8a70a8e343473cf9e6f49683 in some cases `fireChannelRead` event is sent BEFORE a notification for a handshake success

https://github.com/netty/netty/blob/3657805711668ff1249b4c19e227bedb94d55417/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1359-L1371

In the comment above the code it is stated that the `fireChannelRead` should be sent AFTER a notification for a  handshake success, however the code never checks for `handshakeStatus`.

The issue is visible only with `SslProvider.OPENSSL`

### Expected behavior

`fireChannelRead` event is sent AFTER a notification for a  handshake success

### Actual behavior

`fireChannelRead` event is sent BEFORE a notification for a handshake success

### Steps to reproduce

Start `io.netty.example.http2.helloworld.server.Http2Server` and `io.netty.example.http2.helloworld.client.Http2Client` where the `SslProvider` is `SslProvider.JDK` => the example is working as expected.

Change the `SslProvider` to `SslProvider.OPENSSL` and ensure that there is a dependency to `netty-tcnative-boringssl-static` => the example is not working anymore.

### Netty version

4.1.64.Final-SNAPSHOT

### JVM version (e.g. `java -version`)

adopt-openjdk-1.8.0_292

### OS version (e.g. `uname -a`)

Mac OS

### PR DESCRIPTION
**Pull request by violetagg**
Motivation:

In some use cases `SslHandler#unwrap` sends `fireChannelRead` event before a notification for a handshake success.
Such use case is a HTTP server that supports HTTP/1.1 and HTTP/2 via `ApplicationProtocolNegotiationHandler`,
in this case `fireChannelRead` is sent before `ApplicationProtocolNegotiationHandler` is able to setup properly the pipeline
depending on the negotiated protocol. The issue is visible when `SslProvider.OPENSSL` is configured.
This is a regression caused by #11156

Modifications:

- SslHandler#unwrap sends fireChannelRead event after a notification for a handshake success
- Add test

Result:

Fixes #11201

### CODE REVIEW

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java [hunk 1]
```diff
@@ -443,4 +444,131 @@ public void operationComplete(Future<Channel> future) {
...
+
+    @Test(timeout = 5000L)
+    public void testFireChannelReadAfterHandshakeSuccess_JDK() throws Exception {
+        assumeTrue(SslProvider.isAlpnSupported(SslProvider.JDK));
+        testFireChannelReadAfterHandshakeSuccess(SslProvider.JDK);
+    }
+
+    @Test(timeout = 5000L)
+    public void testFireChannelReadAfterHandshakeSuccess_OPENSSL() throws Exception {
+        assumeTrue(SslProvider.isAlpnSupported(SslProvider.OPENSSL));
```
Comment (normanmaurer) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java:456]:
```suggestion
        assumeTrue(OpenSsl.isAvailable());
        assumeTrue(SslProvider.isAlpnSupported(SslProvider.OPENSSL));
```

**Comment by normanmaurer** [comment]
@violetagg thanks a lot!

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java [hunk 2]
```diff
@@ -443,4 +445,132 @@ public void operationComplete(Future<Channel> future) {
...
+                                }
+                            }));
+                        }
+                    });
+                }
+            });
+            serverChannel = sb.bind(new InetSocketAddress(NetUtil.LOCALHOST, 0)).syncUninterruptibly().channel();
+
+            final SslContext clientCtx = SslContextBuilder.forClient()
+                    .sslProvider(SslProvider.OPENSSL)
```
Comment (violetagg) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java:513]:
```suggestion
                    .sslProvider(provider)
```

**Review by normanmaurer — APPROVED** [review]

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java (hunk 2 above)
Comment (violetagg) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java:513]: Sorry I missed that with the initial commit

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java [hunk 3]
```diff
@@ -443,4 +445,132 @@ public void operationComplete(Future<Channel> future) {
...
+                                           });
+                                    }
+                                    ReferenceCountUtil.release(msg);
+                                }
+                            }));
+                        }
+                    });
+                }
+            });
+            serverChannel = sb.bind(new InetSocketAddress(NetUtil.LOCALHOST, 0)).syncUninterruptibly().channel();
```
Comment (chrisvest) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java:510]: The test timeout will not be able to unblock the test thread when we use `syncUninterruptibly` here…

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java [hunk 4]
```diff
@@ -443,4 +445,132 @@ public void operationComplete(Future<Channel> future) {
...
+                                            }
+                                        }
+                                    });
+                                }
+                            }
+                        }
+                    });
+                }
+            });
+            clientChannel = bs.connect(serverChannel.localAddress()).syncUninterruptibly().channel();
```
Comment (chrisvest) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java:567]: … and here.

**Review by chrisvest — COMMENTED** [review]
Spotted two nits.

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java (hunk 3 above)
Comment (violetagg) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java:510]: Interesting
Do you mean that the exception will not be thrown or that the thread will not be interrupted?

https://github.com/netty/netty/blob/d22a35628db9b9bd473d7be76d989b05fdc7a12f/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L262-L290

```
org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds

	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:275)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
	at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:411)
	at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:125)
	at io.netty.channel.DefaultChannelPromise.syncUninterruptibly(DefaultChannelPromise.java:30)
	at io.netty.handler.codec.http2.Http2MultiplexTransportTest.testFireChannelReadAfterHandshakeSuccess(Http2MultiplexTransportTest.java:567)
```

Comment (normanmaurer) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java:510]: I think he means that the thread will not be interrupted.

Comment (violetagg) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTransportTest.java]: thanks - updated

File: handler/src/main/java/io/netty/handler/ssl/SslHandler.java [hunk 5]
```diff
@@ -1359,7 +1359,7 @@ private int unwrap(ChannelHandlerContext ctx, ByteBuf packet, int length) throws
                 // Dispatch decoded data after we have notified of handshake success. If this method has been invoked
                 // in a re-entry fashion we execute a task on the executor queue to process after the stack unwinds
                 // to preserve order of events.
-                if (decodeOut.isReadable()) {
+                if (decodeOut.isReadable() && handshakePromise.isDone()) {
```
Comment (Scottmitch) [inline handler/src/main/java/io/netty/handler/ssl/SslHandler.java:1362]: this may result in data being dropped, which is observed in the `SocketSslEchoTest`. I ran your tests against https://github.com/netty/netty/pull/11210 and this seems to fix the issue. can you verify this PR fixes the root cause and if so I would propose we merge https://github.com/netty/netty/pull/11210, then merge the unit tests from this PR.

Comment (violetagg) [reply handler/src/main/java/io/netty/handler/ssl/SslHandler.java:1362]: @Scottmitch Thanks a lot, with #11210 I do not see the issue anymore!

Comment (normanmaurer) [reply handler/src/main/java/io/netty/handler/ssl/SslHandler.java:1362]: @violetagg I just merged #11210 ... Can you please revert the change in this class and rebase ? This way we can pull in your unit test and also verify it passes on the CI.

Comment (violetagg) [reply handler/src/main/java/io/netty/handler/ssl/SslHandler.java]: done

**Comment by normanmaurer** [comment]
@violetagg thanks a lot!
