### PR TITLE
Fix ref-counting when CompositeByteBuf is used with retainedSlice()

### LINKED ISSUE #8495: Some new leak/reference counting busted in 4.1.32
I don't have much info yet and no local repro. I basically attempted to open up TLS 1.3 to a broader audience within our corp network and I started instantly getting `IllegalReferenceCountException` being thrown and and ERRORs from the `ResourceLeakDetector`. I don't think it's related to TLS 1.3 though.

1. I started out with your [ssl_cipher](https://github.com/netty/netty/pull/8485) branch. Broken.
2. I then took your branch and rebased it with latest 4.1. Still broken.
3. Disabled TLS 1.3. Still broken.

I think it's some change between 4.1.31 release and the ssl_cipher branche's branch point.

```java
2018-11-12 16:11:17,328 16928 [ConnectorThread-7] ResourceLeakDetector ERROR: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1919)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1292)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1211)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1245)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	java.lang.Thread.run(Thread.java:745)
```

```java
2018-11-12 15:48:37,180 54359 [HttpWorkerThread-4] ResourceLeakDetector ERROR: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:77)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:784)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	java.lang.Thread.run(Thread.java:745)
```

```java
2018-11-12 15:48:35,677 54359 [HttpsWorkerThread-5] ReferenceCountUtil WARN : Failed to release a message: UnpooledSlicedByteBuf(freed)
 io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:124) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:107) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:89) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:85) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndCompleteAll(AbstractCoalescingBufferQueue.java:338) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndFailAll(AbstractCoalescingBufferQueue.java:207) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.releaseAndFailAll(SslHandler.java:1586) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1580) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1545) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:201) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelWritabilityChanged(Http2ConnectionHandler.java:440) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1457) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:977) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.fireChannelWritabilityChanged(ChannelOutboundBuffer.java:607) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.setWritable(ChannelOutboundBuffer.java:573) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:194) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:259) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:338) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:319) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:522) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:525) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:423) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

```java
2018-11-12 15:48:40,119 54359 [HttpsWorkerThread-4] ReferenceCountUtil WARN : Failed to release a message: UnpooledSlicedByteBuf(freed)
 io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:124) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:107) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.CompositeByteBuf$Component.freeIfNecessary(CompositeByteBuf.java:1818) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.CompositeByteBuf.deallocate(CompositeByteBuf.java:2124) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:118) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:107) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractDerivedByteBuf.release0(AbstractDerivedByteBuf.java:89) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:85) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88) ~[netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndCompleteAll(AbstractCoalescingBufferQueue.java:338) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractCoalescingBufferQueue.releaseAndFailAll(AbstractCoalescingBufferQueue.java:207) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.releaseAndFailAll(SslHandler.java:1586) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1580) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1545) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:201) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelWritabilityChanged(Http2ConnectionHandler.java:440) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1457) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:977) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.fireChannelWritabilityChanged(ChannelOutboundBuffer.java:607) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.setWritable(ChannelOutboundBuffer.java:573) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:194) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:259) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:338) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:319) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:522) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:434) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:512) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:901) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1396) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.forceFlush(SslHandler.java:1808) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:797) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:774) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:201) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:1013) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:248) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at com.squarespace.echo.http2.streams.HttpToHttp2Handler.flush(HttpToHttp2Handler.java:92) [echo-http-2.37-20181112-rkapsi_netty-4.1.31-tcn-2.0.19-tls-1.3-30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at com.squarespace.echo.core.handler.scope.ScopeHandler.flush(ScopeHandler.java:321) [echo-core-2.37-20181112-rkapsi_netty-4.1.31-tcn-2.0.19-tls-1.3-30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at com.squarespace.echo.core.handler.scope.ScopeHandler.flush(ScopeHandler.java:321) [echo-core-2.37-20181112-rkapsi_netty-4.1.31-tcn-2.0.19-tls-1.3-30.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:38) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext$16.run(AbstractChannelHandlerContext.java:756) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.32.Final-SQSP-20181112-1.jar:4.1.32.Final-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

... and many many more.

### PR DESCRIPTION
**Pull request by njhill**
Motivation:

`ByteBuf.retainedSlice()` and similar methods produce sliced buffers with an independent refcount to the buffer that they wrap.

One of the optimizations in 10539f4dc738c48e8d63c46b72ca32906d7f40ec was to use a ref to the unwrapped buffer object for added slices, but this did not take into account the above special case when later releasing.

Thanks to @rkapsi for discovering this via #8495.

Modifications:

Since a reference to the slice is still kept in the `Component` class, just changed `Component.freeIfNecessary()` to release the slice in preference to the unwrapped buf.

Also added a unit test which reproduces the bug.

Result:

Fixes #8495

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by rkapsi** [comment]
Took the branch for a spin, no more Exceptions or ERRORs as reported in #8495 .

File: buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java [hunk 1]
```diff
@@ -1815,7 +1815,11 @@ ByteBuf duplicate() {
         }
 
         void freeIfNecessary() {
-            buf.release(); // We should not get a NPE here. If so, it must be a bug.
+            // Release the slice if present since it may have a different
+            // refcount to the unwrapped buf if it is a PooledSlicedByteBuf
+            ByteBuf s = slice;
+            (s != null ? s : buf).release();
+            // null out in both cases since it could be racy
```
Comment (normanmaurer) [inline buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java]: I think this would be easier to read like this:

```
ByteBuf buffer = s == null ? buf : s;
buffer.release();
```

File: buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java [hunk 2]
```diff
@@ -1144,6 +1144,36 @@ public void testReleasesItsComponents() {
         assertEquals(0, buffer.refCnt());
     }
 
+    @Test
+    public void testReleasesItsComponents2() {
+        ByteBuf buffer = PooledByteBufAllocator.DEFAULT.buffer(); // 1
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java]: Can you add a comment that using the PooledByteBufAllocator is important here ?

File: buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java [hunk 3]
```diff
@@ -1144,6 +1144,36 @@ public void testReleasesItsComponents() {
...
+
+        buffer.writeBytes(new byte[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10});
+
+        // use readRetainedSlice this time - produces different kind of slices
+        ByteBuf s1 = buffer.readRetainedSlice(2); // 2
+        ByteBuf s2 = s1.readRetainedSlice(2); // 3
+        ByteBuf s3 = s2.readRetainedSlice(2); // 4
+        ByteBuf s4 = s3.readRetainedSlice(2); // 5
+
+        ByteBuf composite = PooledByteBufAllocator.DEFAULT.compositeBuffer()
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java]: same as above

File: buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java [hunk 4]
```diff
@@ -1144,6 +1144,36 @@ public void testReleasesItsComponents() {
...
+            .addComponent(s1)
+            .addComponents(s2, s3, s4)
+            .order(ByteOrder.LITTLE_ENDIAN);
+
+        assertEquals(1, composite.refCnt());
+        assertEquals(2, buffer.refCnt());
+
+        // releasing composite should release the 4 components
+        ReferenceCountUtil.release(composite);
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java]: just use `composite.release()`

File: buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java [hunk 5]
```diff
@@ -1144,6 +1144,36 @@ public void testReleasesItsComponents() {
...
+        assertEquals(0, composite.refCnt());
+        assertEquals(1, buffer.refCnt());
+
+        // last remaining ref to buffer
+        ReferenceCountUtil.release(buffer);
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java]: just use `buffer.release()`

**Comment by normanmaurer** [comment]
@rkapsi thanks a lot!

File: buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java (hunk 3 above)
Comment (njhill) [reply buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java]: @normanmaurer Actually I don't think this one would make a difference since it's only used if/when the composite buffer gets expanded right?

Comment (normanmaurer) [reply buffer/src/test/java/io/netty/buffer/AbstractCompositeByteBufTest.java]: @njhill ah yeah true... then fix it please to use Unpooled.

File: buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java (hunk 1 above)
Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java]: @njhill I am confused... why did you need to to have `s` and `toRelease` here ? Which not just do what I suggested ? 

Which would be:

```
ByteBuf buffer = slice == null ? buf : slice;
buffer.release();
```

**Comment by njhill** [comment]
Thanks @normanmaurer, have pushed a commit addressing your comments.

Re the use of `ReferenceCountUtil.release(buf)` and pooled/unpooled `compositeBuffer()` - they seem to be used in many of the other tests, here I just copy/pasted the test above and changed `readSlice().retain()` to `readRetainedSlice()`. Just FYI that there's some inconsistency.

**Comment by normanmaurer** [comment]
@njhill I guess it would make sense to cleanup this stuff as a followup.

**Comment by normanmaurer** [comment]
@njhill also see https://github.com/netty/netty/pull/8497/files#r233174008

File: buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java (hunk 1 above)
Comment (njhill) [reply buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java]: @normanmaurer oh, sorry... I misinterpreted your original suggestion since it used `s`. Maybe I am being overly cautious, but just based on the fact that `slice` gets nulled after the component is released I thought it would be safer to do the check on a local var (I ack that it probably is only possible to hit an NPE problem if there is another bug or incorrect use though).

Happy to change it to use `slice` directly if you think that's fine...

Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java]: yeah I think I would go for the easier code or would at least not write it so compact to make it easier to understand

Comment (njhill) [reply buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java]: done - changed to use if/else, hopefully this is the most readable of all :)

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@njhill merged... thanks!
