### PR TITLE
#7756 Add @Sharable TYPE_USE support for inner class annotations

### LINKED ISSUE #7756: @Sharable should also support @Target(ElementType.TYPE_USE)
### Expected behavior
`@Sharable` should also be usable with anonymous inner types, so that it is no longer necessary to make named classes (top-level or nested) for sharable handlers. Since Java 8, this is possible with the new `ElementType` `TYPE_USE`.
The practical problem here is that either (a) Netty would have to, at some point, *require* Java 8 (don't think that's the case yet), or (b) an additional Java-8-specific `@Sharable` annotation would have to be introduced.

### Actual behavior
`@Sharable` only targets `ElementType` `TYPE` and requires a proper (i.e., named) class.

### Steps to reproduce
Add `@Sharable` annotation to inner class, observe compilation error.

### Minimal yet complete reproducer code (or URL to code)
```
ChannelInboundHandler echoHandler = new @Sharable ChannelInboundHandlerAdapter() {
      @Override
      public void channelRead(ChannelHandlerContext context, Object message) {
           context.write(message);
      }
}
```
### Netty version
4.1.22.Final

### JVM version (e.g. `java -version`)
1.8.0_152

### OS version (e.g. `uname -a`)
Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64 (MacOS 10.12.6)

### PR DESCRIPTION
**Pull request by kiril-me**
Motivation:

Make @Sharable annotation works with anonymous inner types. Add Java 8 ElementType.TYPE_USE feature that makes easy to use @Sharable annotation.

Modification:
* transport/src/main/java/io/netty/channel/ChannelHandler.java - Target ElementType.TYPE_USE added.
* transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java - isSharable method improved to verify AnnotatedSuperclass for annotation.
* transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java - Tests added.

Result:
```
ChannelInboundHandler handler = new @Sharable ChannelInboundHandlerAdapter() {
      @Override
      public void channelRead(ChannelHandlerContext context, Object message) {
           context.write(message);
      }
};
```

Note:
The following changes don't support local variable annotation:
 ChannelInboundHandler handler1 = new @Sharable ChannelInboundHandlerAdapter();
 @Sharable ChannelInboundHandler handler2 = new  ChannelInboundHandlerAdapter();

Fixes #7756

### CODE REVIEW

File: transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
+/*
+ * Copyright 2012 The Netty Project
```
Comment (normanmaurer) [inline transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java]: 2019

File: transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+import static org.junit.Assert.assertEquals;
+
+import org.junit.Test;
+
+import io.netty.channel.ChannelHandler.Sharable;
+
+public class ChannelHandlerAdapterTest {
+
+    @Sharable
+    private static class SharableChannelHandlerAdapter extends ChannelHandlerAdapter {
```
Comment (normanmaurer) [inline transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java]: nit: final

File: transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+    @Test
+    public void testSharable() {
+        ChannelHandlerAdapter handler = new SharableChannelHandlerAdapter();
+        assertEquals(true, handler.isSharable());
+    }
+
+    @Test
+    public void testInnerClassSharable() {
+        ChannelHandlerAdapter handler = new @Sharable ChannelHandlerAdapter() {
+        };
```
Comment (normanmaurer) [inline transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java]: nit: `new @Sharable ChannelHandlerAdapter() { };`

File: transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+        assertEquals(true, handler.isSharable());
+    }
+
+    @Test
+    public void testWithoutSharable() {
+        ChannelHandlerAdapter handler = new ChannelHandlerAdapter() {
+        };
```
Comment (normanmaurer) [inline transport/src/test/java/io/netty/channel/ChannelHandlerAdapterTest.java]: nit: `new ChannelHandlerAdapter() {};`

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java [hunk 5]
```diff
@@ -55,6 +56,10 @@ public boolean isSharable() {
         Boolean sharable = cache.get(clazz);
         if (sharable == null) {
             sharable = clazz.isAnnotationPresent(Sharable.class);
+            if (!sharable) {
```
Comment (doom369) [inline transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: Is this correct? Child class could be nonsharable, while it extends `@Sharable`.

Comment (normanmaurer) [reply transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: @doom369 not sure I understand you correctly.. but `@Sharable` uses `@Inherited` so if the super-class is sharable the child class should be as well.

Comment (doom369) [reply transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: @normanmaurer missed that. Anyway, in that case:

```
 * Indicates that an annotation type is automatically inherited.  If
 * an Inherited meta-annotation is present on an annotation type
 * declaration, and the user queries the annotation type on a class
 * declaration, and the class declaration has no annotation for this type,
 * then the class's superclass will automatically be queried for the
 * annotation type.  This process will be repeated until an annotation for this
 * type is found, or the top of the class hierarchy (Object)
 * is reached.  If no superclass has an annotation for this type, then
 * the query will indicate that the class in question has no such annotation.
```

```
    @ChannelHandler.Sharable
    private static class A {
    }
    private static class B extends A {
    }
    @Test
    public void aaa() {
        System.out.println(B.class.isAnnotationPresent(ChannelHandler.Sharable.class)); //prints true
    }
```

Comment (normanmaurer) [reply transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: @doom369 agree... so you are saying we do not need the extra "query" ? If so I think you are right... @kiril-me did you check if you really need it ?

Comment (doom369) [reply transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: @normanmaurer this check is useful only for the case when the class implements interface marked with `@Sharable`. I don't think this is real use case, however, for at least 1 more additional test case should be added.

Comment (normanmaurer) [reply transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: @kiril-me can you do this ?

Comment (kiril-me) [reply transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: @normanmaurer There are differences between annotation of the class and inner anonymous class annotation. 

> @Inherited JavaDoc
> Note that this meta-annotation type has no effect if the annotated
> type is used to annotate anything other than a class.  Note also
> that this meta-annotation only causes annotations to be inherited
> from superclasses; annotations on implemented interfaces have no
> effect.

As @doom369 mentioned, isAnnotationPresent(Sharable.class) looking for @Sharable annotation starting from current class till Object.

But this scenario doesn't work for isAnnotationPresent, because @Inherit does not apply directly to the class:
```
ChannelInboundHandler handler = new @Sharable ChannelInboundHandlerAdapter() {
      @Override
      public void channelRead(ChannelHandlerContext context, Object message) {
           context.write(message);
      }
};
```
Tests checking this. If you comment out following code, test will fails:
```
if (!sharable) {       
                AnnotatedType annotatedType = clazz.getAnnotatedSuperclass();
                sharable = annotatedType.isAnnotationPresent(Sharable.class);
 }
```

Comment (doom369) [reply transport/src/main/java/io/netty/channel/ChannelHandlerAdapter.java]: Thanks for the explanation.

**Comment by normanmaurer** [comment]
@kiril-me thanks a lot!
