### PR TITLE
Epoll: Fix excessive CPU usage when Channel is only registered but no…

### LINKED ISSUE #16240: Epoll channel register creates a busy-loop with high CPU usage
Following the discussion https://github.com/netty/netty/discussions/16236, I'm opening this issue to discuss a solution. When using the native Epoll implementation, I'm seeing a high CPU usage when a server channel is registered to the EventLoop but not yet bound to a port. After some investigation, I'm seeing the issue seems to lie in the `epollWait` [method](https://github.com/netty/netty/blob/81c1017c5f0ec5d0a03aef56af72002070d1357c/transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollIoHandler.java#L439) not waiting but returning every time with an EPOLLHUP event. I don't know a lot about the native Epoll side, but I'm assuming this is normal because the channel hasn't been bound to a port yet and so epoll generating the event makes sense to me based off what I have read. 

This behavior however, causes the eventloop thread to be constantly spinning with no work happening and from testing, this will always happen until the channel is bound to a port and will consume a lot of CPU. Does it make sense to treat is as an issue or is this working as designed? I have an alternative in mind to wait on registering inactive channels until they are active but I wanted to bring this up before I work on a PR.

### PR DESCRIPTION
**Pull request by normanmaurer**
…t bound / connected

Motivation:

We should only add a fd (Channel) to epoll onec it is considered active (connected) as otherwise we will receive EPOLLHUP events until it is active. This can lead to excessive CPU usage.

Modifications:

Delay adding of fd to epoll until it is considered active / connected.

Result:

Fixes https://github.com/netty/netty/issues/16240

### CODE REVIEW

**Comment by normanmaurer** [comment]
Also @isaacrivriv

**Comment by normanmaurer** [comment]
I need to check but I suspect we have the same issue in 4.1 and of course it also exists in the 5.0 branch.

File: transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollIoHandler.java [hunk 1]
```diff
@@ -248,24 +259,48 @@ public <T> T attachment() {
         public long submit(IoOps ops) {
             EpollIoOps epollIoOps = cast(ops);
             try {
-                if (!isValid()) {
-                    return -1;
+                for (;;) {
```
Comment (normanmaurer) [inline transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollIoHandler.java]: I wonder if I should just slap a `synchronized` around parts of `cancel()` and `submit(..)` and so get rid of all this dance... WDYT ?

Comment (franz1981) [reply transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollIoHandler.java]: synchronize all the things :dagger:

Comment (franz1981) [reply transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollIoHandler.java]: TBh is not so bad, but my sense of aestetic is a bit flawed :D

Comment (normanmaurer) [reply transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollIoHandler.java]: yeah let me do this... it is not expected to be called from different threads in a frequent manner any way

**Comment by isaacrivriv** [comment]
Thanks for getting a fix @normanmaurer! At first glance, this looks like it covers the issue since the fix I tried locally worked around the same areas with similar logic. I'll build this and try it with our use case locally to confirm.

**Comment by isaacrivriv** [comment]
I just finished building and testing locally and I'm not seeing the same behavior or high CPU usage so this should have fixed the issue!

**Comment by normanmaurer** [comment]
Added a unit test as well for epoll.

**Review by chrisvest — APPROVED** [review]
