### PR TITLE
Bugfix #9667: FlowControllerHandler swallows read-complete event when auto-read is disabled

### LINKED ISSUE #9667: FlowControllerHandler swallows read-complete event when auto-read is disabled
### Expected behavior

IdleStateHandler should trigger read-timeout events when registered after FlowControlHandler.

### Actual behavior

IdleStateHandler does NOT trigger read-timeout event.

### Steps to reproduce

Server pipeline:

    p.addLast("flow-control", new FlowControlHandler)
    p.addLast("keep-alive", new PingInactiveHandler(readTimeout))// extends IdleStateHandler
    p.addLast("handler", new AppHandler) // trigger read

When no upstream messages from the client within time limit, then READER_IDLE event should be triggered. However it does NOT happen.

### Netty version

* Version 4.1.31 - no problem, example code works.
* Version 4.1.39 - has a problem, example code does NOT work.

Seems like related to PR #9664 

### JVM version (e.g. `java -version`)

Oracle JDK 1.8.0_221-b27

### OS version (e.g. `uname -a`)

* Windows  7 Enterprise
* Linux gmafxu42 3.0.101-108.98-default #1 SMP Mon Jul 15 13:58:06 UTC 2019 (262a94d) x86_64 x86_64 x86_64 GNU/Linux

### How to fix

    @Override
    public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
    ---    // Don't relay completion events from upstream as they
    ---    // make no sense in this context. See dequeue() where
    ---    // a new set of completion events is being produced.
    +++    if (isQueueEmpty()) {
    +++        ctx.fireChannelReadComplete();
    +++    }
    }

### PR DESCRIPTION
**Pull request by ursaj**
### Modification:

* Fire read-complete event from flow controller, when it previously was swallowed
* New unit test to cover this case

### Result:

Fixes #9667: FlowControllerHandler swallows read-complete event when auto-read is disabled

### CODE REVIEW

File: handler/src/main/java/io/netty/handler/flow/FlowControlHandler.java [hunk 1]
```diff
@@ -154,9 +154,13 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception
 
     @Override
     public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
-        // Don't relay completion events from upstream as they
-        // make no sense in this context. See dequeue() where
-        // a new set of completion events is being produced.
+        if (isQueueEmpty()) {
+            ctx.fireChannelReadComplete();
+        //} else {
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/flow/FlowControlHandler.java]: just remove the `//`

File: handler/src/main/java/io/netty/handler/timeout/IdleStateEvent.java [hunk 2]
```diff
@@ -56,4 +57,9 @@ public IdleState state() {
     public boolean isFirst() {
         return first;
     }
+
+    @Override
+    public String toString() {
+        return StringUtil.simpleClassName(this) + "(" + state + (first ? ", first" : "") + ')';
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/timeout/IdleStateEvent.java]: revert ?

**Comment by normanmaurer** [comment]
@rkapsi Please take a look as well

**Comment by ursaj** [comment]
@normanmaurer all review notes were fixed

File: handler/src/main/java/io/netty/handler/timeout/IdleStateEvent.java (hunk 2 above)
Comment (ursaj) [reply handler/src/main/java/io/netty/handler/timeout/IdleStateEvent.java]: moved into separated PR #9695

File: handler/src/main/java/io/netty/handler/flow/FlowControlHandler.java (hunk 1 above)
Comment (ursaj) [reply handler/src/main/java/io/netty/handler/flow/FlowControlHandler.java]: done

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: handler/src/test/java/io/netty/handler/flow/FlowControlHandlerTest.java [hunk 3]
```diff
@@ -419,13 +423,68 @@ public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
...
+        channel.flushInbound();
+        assertEquals(Unpooled.EMPTY_BUFFER, channel.readInbound());
+
+        // Emulate 'no more messages in NIO channel' on the next read attempt.
+        channel.flushInbound();
+        assertNull(channel.readInbound());
+
+        Thread.sleep(delayMillis);
+        channel.runPendingTasks();
+        assertEquals(IdleStateEvent.FIRST_READER_IDLE_STATE_EVENT, userEvents.poll());
```
Comment (normanmaurer) [inline handler/src/test/java/io/netty/handler/flow/FlowControlHandlerTest.java]: nit: can you also call `assertFalse(channel.finish());` ?

Comment (ursaj) [reply handler/src/test/java/io/netty/handler/flow/FlowControlHandlerTest.java]: added

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@ursaj thanks a lot!
