### PR TITLE
Make "pinned memory" from PooledByteBufAllocator reflect buffers in use

### LINKED ISSUE #11984: PooledByteBufAllocator.pinnedDirectMemory is sometimes returning 0 even if some direct buffers are used
I'm trying to monitor the estimate of memory that is used by in-use direct buffers.
To do so, I'm trying to use the PooledByteBufAllocator.pinnedDirectMemory() method but sometimes, it seems that this method is returning 0 even if some buffers are currently allocated and used (not yet released).

### Expected behavior

PooledByteBufAllocator.pinnedDirectMemory() should not return 0 in case some buffers are currently allocated.

### Actual behavior

Sometimes, not always, it seems that the PooledByteBufAllocator.pinnedDirectMemory() is returning 0 even if some buffers are allocated.

### Steps to reproduce

Please check attached sample project: 

[netty.pinnedMemory.test.tar.gz](https://github.com/netty/netty/files/7835795/netty.pinnedMemory.test.tar.gz)

The Test class is allocating some buffers, and before releasing them, it displays the pinned direct memory. It also displays an estimate of used memory by traversing arena of direct buffers, and for each arena, it accumulates the diff between the  chunk size and the bytes that are not yet allocated by in-use buffers:

```
    static long usedMem(List<PoolArenaMetric> arenas) {
        long totalUsed = 0;
        for (PoolArenaMetric arenaMetrics : arenas) {
            for (PoolChunkListMetric arenaMetric : arenaMetrics.chunkLists()) {
                for (PoolChunkMetric chunkMetric : arenaMetric) {
                    // chunkMetric.chunkSize() returns maximum of bytes that can be served out of the chunk
                    // and chunkMetric.freeBytes() returns the bytes that are not yet allocated by in-use buffers
                    totalUsed += (chunkMetric.chunkSize() - chunkMetric.freeBytes());
                }
            }
        }
        return totalUsed;
    }
```
To run the program:

./gradlew jar
./gradlew runTest

The program displays many logs, like this:

```
used=1810432, pinned=1372971008
used=2097152, pinned=1373257728
used=1974272, pinned=1371643904
```

_used_ corresponds to the result of the _usedMem_ method shown above, and _pinned_ corresponds to the result of the call to alloc.pinnedDirectMemory().

Now, sometimes, you will notice that the pinned memory is zero:

```
used=2031616, pinned=1835008
used=1892352, pinned=188416
used=1916928, pinned=212992
used=1892352, pinned=0
used=2023424, pinned=0
used=2072576, pinned=0
...
used=2220032, pinned=2146779136
used=2310144, pinned=2146869248
used=1843200, pinned=2144354304
used=1974272, pinned=2144485376
used=2007040, pinned=2144518144
used=1998848, pinned=2143215616
used=2138112, pinned=2143354880
```

To stop, just press CTRL-C

### Minimal yet complete reproducer code (or URL to code)

Please see attached sample project above

### Netty version

4.1.72.Final

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.23-CA-macos-aarch64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.23-CA-macos-aarch64) (build 25.302-b08, mixed mode)

### OS version (e.g. `uname -a`)

MacOS M1:

Darwin xxx 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

The issue is also observed on linux Ubuntu:

Linux xxx 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
The pinned memory accounting was being done from a bad place.
Namely, it was being done at the same time as the PoolChunk free memory accounting was being done.
That means the thread local caching was messing up the accuracy of the numbers.

Modification:
Move pinned memory accounting to the PooledByteBuf init and deallocation methods, so it's tied to the buffer life cycle.

Result:
The pinned memory accounting is updated as part of the pooled buffer life cycle, and is no longer being tricked by the activities of the thread-local buffer cache.

Fixes #11984

### CODE REVIEW

File: buffer/src/main/java/io/netty/buffer/PoolChunk.java [hunk 1]
```diff
@@ -577,6 +582,17 @@ void initBufWithSubpage(PooledByteBuf<T> buf, ByteBuffer nioBuffer, long handle,
...
 
+    void incrementPinnedMemory(int delta) {
+        assert delta > 0;
+        int result = PINNED_UPDATER.addAndGet(this, delta);
+        assert result > 0;
+    }
+
+    void decrementPinnedMemory(int delta) {
+        assert delta > 0;
+        PINNED_UPDATER.addAndGet(this, -delta);
```
Comment (normanmaurer) [inline buffer/src/main/java/io/netty/buffer/PoolChunk.java:593]:
```suggestion
        int result = PINNED_UPDATER.addAndGet(this, -delta);
        assert result >= 0;
```

File: buffer/src/main/java/io/netty/buffer/PoolChunk.java [hunk 2]
```diff
@@ -130,6 +133,9 @@
  *
  */
 final class PoolChunk<T> implements PoolChunkMetric {
+    @SuppressWarnings("unchecked")
+    private static final AtomicIntegerFieldUpdater<PoolChunk<?>> PINNED_UPDATER = (AtomicIntegerFieldUpdater<PoolChunk<?>>)
+            (AtomicIntegerFieldUpdater<?>) newUpdater(PoolChunk.class, "pinnedBytes");
```
Comment (normanmaurer) [inline buffer/src/main/java/io/netty/buffer/PoolChunk.java:138]: nit: Not strong about this but we could also just use `AtomicInteger` directly here as I wouldn't expect a massive amount of these instances. That said I am not strong on it at all.

File: buffer/src/test/java/io/netty/buffer/PooledByteBufAllocatorTest.java [hunk 3]
```diff
@@ -821,4 +823,64 @@ private void testUsedHeapMemory(int initialCapacity) {
...
     }
+
+    @Test
+    public void pinnedMemoryMustReflectBuffersInUse() {
+        PooledByteBufAllocator alloc = newAllocator(true);
+        PooledByteBufAllocatorMetric metric = alloc.metric();
+        AtomicLong capSum = new AtomicLong();
+
+        for (long index = 0; index < 10000; index++) {
+            List<ByteBuf> buffers = new ArrayList<ByteBuf>();
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/PooledByteBufAllocatorTest.java:834]: nit: we could size it correctly from the start

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Comment by normanmaurer** [comment]
Also there is a check style error.

File: buffer/src/test/java/io/netty/buffer/PooledByteBufAllocatorTest.java [hunk 4]
```diff
@@ -821,4 +823,64 @@ private void testUsedHeapMemory(int initialCapacity) {
         trimCaches(allocator);
         assertEquals(0, allocator.pinnedDirectMemory());
     }
+
+    @Test
+    public void pinnedMemoryMustReflectBuffersInUse() {
+        PooledByteBufAllocator alloc = newAllocator(true);
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/PooledByteBufAllocatorTest.java:829]: I wonder if we want to run the test one time with cache enabled and one time without.

File: buffer/src/main/java/io/netty/buffer/PoolChunk.java (hunk 2 above)
Comment (chrisvest) [reply buffer/src/main/java/io/netty/buffer/PoolChunk.java:138]: I was mostly thinking about the number of memory indirections, tbh.

Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/PoolChunk.java:138]: I guess it not matters too much... That said I am not strong here like I said. So just keep it.

File: buffer/src/test/java/io/netty/buffer/PooledByteBufAllocatorTest.java (hunk 4 above)
Comment (chrisvest) [reply buffer/src/test/java/io/netty/buffer/PooledByteBufAllocatorTest.java]: Added a second test.

File: buffer/src/main/java/io/netty/buffer/PoolChunk.java (hunk 2 above)
Comment (chrisvest) [reply buffer/src/main/java/io/netty/buffer/PoolChunk.java]: Changed it anyway.

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
Ship it!

**Comment by pderop** [comment]
thanks for the quick fix !  

just a small nit: in the fix, what about using a LongAdder instead of an AtomicInteger ?

**Comment by pderop** [comment]
ignore my last comment ! sorry,
I've just been told that jdk6 was used.

**Comment by normanmaurer** [comment]
@pderop actually I think it was a good comment. See https://github.com/netty/netty/pull/11995
