### PR TITLE
Do not try to use Unsafe.staticFieldOffset() method under a native im…

### LINKED ISSUE #10051: Failure to run a service that uses a Netty library having built it with Graal native-image
### Expected behavior
Ability to build and run a service using Netty with GraalVM [native-image](https://www.graalvm.org/docs/reference-manual/native-image/).

### Actual behavior
It seems like Netty already has some support for GraalVM, but there still some issues. I can't find any reference to this error below, so maybe I'm doing something wrong! Any ideas would be greatly appreciated.

Failure during runtime:
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method of Unsafe
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at jdk.internal.misc.Unsafe.staticFieldOffset(Unsafe.java:230)
	at sun.misc.Unsafe.staticFieldOffset(Unsafe.java:662)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:281)
	at java.security.AccessController.doPrivileged(AccessController.java:81)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:266)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:272)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:222)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:209)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1406)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:47)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:72)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:74)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:269)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.create(EnhancedBigtableStub.java:163)
	at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:152)
```

### Steps to reproduce
Try building a service that uses a library that uses Netty under the hood (in my particular example, `google-cloud-bigtable`).

### Netty version
The library uses a shaded version of Netty `grpc-netty-shaded`, but using the latest version `1.27.1`, which I'm pretty sure it's Netty 4.1.44+ (but I don't know how to verify).

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
macOS Catalina

### PR DESCRIPTION
**Pull request by rpuch**
…age.

Motivation:

GraalVM's native images built with native-image tool do not support Unsafe.staticFieldOffset() method (at least, currently). If an application using Netty (and causing initialization of io.netty.util.internal.PlatformDependent0 class) is built into a native image and run, this results in the following error thrown during initialization:

Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method of Unsafe
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
	at jdk.internal.misc.Unsafe.staticFieldOffset(Unsafe.java:230)
	at sun.misc.Unsafe.staticFieldOffset(Unsafe.java:662)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:294)
	at java.security.AccessController.doPrivileged(AccessController.java:83)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:279)

This seems to be the reason of the behavior described in #10051.

Modification:

The idea of this commit is to only invoke Unsafe.staticFieldOffset() is we are not in a native image; if we are, behave like if we could not find the field at all.

GraalDetector is borrowed from Spring framework.

Result:

Fixes #10051

The resulting code works successfully in a native image (at least, on x86_64).

### CODE REVIEW

**Comment by rpuch** [comment]
Please note that this code **does not** build because line 20 in GraalDetector is too long and checkstyle fails the build. The line is basically a URL and it's not clear how it can be shortened (bit.ly? but why)? I did not find any way to suppress this violation as no generic suppression mechanism like Java annotations or comments is enabled in io/netty/checkstyle.xml, and it is not in this repository, so it's unclear how this can be sorted out.

Could please someone of maintainers advise how we should proceed with this checkstyle issue?

**Comment by rpuch** [comment]
Another approach would be to catch an `Error` occuring when invoking `Unsafe.staticFieldOffset()` and, if its simple name is 'UnsupportedFeatureError', ignore the error (otherwise, rethrow it).

**Comment by ninja-** [comment]
I am not sure that's the best way to fix it, we already have a lot of code for Graal support in Netty, so I am surprised there would be some regression that broke netty on startup?

**Comment by ninja-** [comment]
I see you opened a discussion on graal as well: https://github.com/oracle/graal/issues/2694

**Comment by rpuch** [comment]
> I am not sure that's the best way to fix it, we already have a lot of code for Graal support in Netty, so I am surprised there would be some regression that broke netty on startup?

Unfortunately, in my case an attempt to start in a native image failed, with both versions 4.1.51.Final (the most recent at the moment) and 4.1.50.Final. Actually, any code that causes initialization of `io.netty.util.internal.PlatformDependent` causes this failure. Probably earlier this code path was not activated, I'm not sure.

I'm looking at netty's code for the first time, could you please direct me to code that improves interoperability with Graal?

**Comment by rpuch** [comment]
> I see you opened a discussion on graal as well: [oracle/graal#2694](https://github.com/oracle/graal/issues/2694)

Yes, but noone has responded yet, so I don't even know whether this 'Unsafe.staticFieldOffset()' feature will work in native images in the future, so I took a liberty to propose a fix in Netty.

**Comment by ninja-** [comment]
@rpuch last time I used netty with native-image was around few months ago and it worked fine, I haven't been following changes since.
Netty has META-INF/native-image folders in each module with configuration for reflection etc.

**Comment by rpuch** [comment]
@ninja- Here is a project that demonstrates the problem: https://github.com/rpuch/netty-native-image-tests
The README.me contains the instructions, but basically you just:

1. Install GraalVM (Java 11!)
2. Run ./build.sh
3. Run target/app

Then the exception pops up.

The build does not do anything fancy, just builds a classpath string from all the dependencies and feeds it to `native-image`, no shading, so all `META-INF` directories are intact.

When I replace Netty version (4.1.51) with the version built from this PR branch, it works.

As for why it was working before and suddenly breaks now: please note that this `Unsafe.staticFieldOffset()` invocation only occurs on Java 9+. Could it be that earlier the positive expirience was obtained on Java 8?

**Comment by johnou** [comment]
@rpuch try setting -Dio.netty.noUnsafe=true when building your image.

**Comment by rpuch** [comment]
> @rpuch try setting -Dio.netty.noUnsafe=true when building your image.

@johnou `-Dio.netty.noUnsafe=true` added at run time (not build time) actually solves the problem. Thanks!

Still, the approach taken in this PR seems to be more programmer-friendly because it works automatically, without any special knowledge (which was required for `-Dio.netty.noUnsafe=true`).

**Comment by ninja-** [comment]
> As for why it was working before and suddenly breaks now: please note that this Unsafe.staticFieldOffset() invocation only occurs on Java 9+. Could it be that earlier the positive expirience was obtained on Java 8?

Ah, yeah. If I recall correctly I was unable to compile my app on > Java 8 Graal due to some compiler bugs....so I was on Java 8;...

File: common/src/main/java/io/netty/util/internal/GraalDetector.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
+ * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
+ * License for the specific language governing permissions and limitations
+ * under the License.
+ */
+package io.netty.util.internal;
+
+abstract class GraalDetector {
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/internal/GraalDetector.java:18]: @rpuch can we merge this directly to `PlatformDependent0` ? Seems overkill to add this class just for exposing one method etc

File: common/src/main/java/io/netty/util/internal/GraalDetector.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+
+    // See https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java
+    private static final boolean imageCode = System.getProperty("org.graalvm.nativeimage.imagecode") != null;
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/internal/GraalDetector.java:21]: Use `SystemPropertyUtils.`

File: common/src/main/java/io/netty/util/internal/GraalDetector.java (hunk 1 above)
Comment (rpuch) [reply common/src/main/java/io/netty/util/internal/GraalDetector.java]: I've moved the code to `PlatformDependent0` and removed `GraalDetector` class. Please let me know if it is ok now.

File: common/src/main/java/io/netty/util/internal/GraalDetector.java (hunk 2 above)
Comment (rpuch) [reply common/src/main/java/io/netty/util/internal/GraalDetector.java]: Done

**Comment by rpuch** [comment]
The problem with the long line (due to a URL in a comment) still remains. Should I just remove the comment?

**Comment by normanmaurer** [comment]
@rpuch just break the url up into two lines.. its a comment after all.

**Comment by rpuch** [comment]
> @rpuch just break the url up into two lines.. its a comment after all.

Done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@rpuch can you please sign our icla so I can pull this in ?

https://netty.io/s/icla

Please let me know once done

**Comment by rpuch** [comment]
> @rpuch can you please sign our icla so I can pull this in ?
> 
> https://netty.io/s/icla
> 
> Please let me know once done

@normanmaurer done

**Comment by normanmaurer** [comment]
@rpuch thanks a lot!
