### PR TITLE
Fix potential DNS cache invalidation across different EventLoops

### LINKED ISSUE #14046: DNSResolve: DNS Cache Not Working in Certain Scenarios
1. In k8s environment, the concatenation of the hostname and searchDomain, can cause the DNS cache to become ineffective. I think if searchDomains are concatenated during DNS resolution, we should iterate through and concatenate all searchDomains to obtain the cached results.

   eg. 
   hostname: k8s service name
image-20240510234145365

2. Each EpollEventLoop has its own DNS resolution cache, but when DNS resolution is executed in an EpollEventLoop that does not have a cached result, it can cause the DNS resolution cache to become ineffective.

This looks like a potential bug. Can it be assigned to me? I would like to try fixing it.

### Netty version
4.1.73.Final
### JVM version (e.g. `java -version`)
jdk8
### OS version (e.g. `uname -a`)
k8s 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by qnnn**
Motivation:

+ By default, `DnsAddressResolverGroup` sets up a separate `DNSCache` for each `EventLoop`. This can lead to cache invalidation when performing DNS resolution across different EventLoops due to the potential absence of cached DNS records. 

Modification:

+ I propose initializing the DNSCache in `DnsNameResolverBuilder` during `DnsAddressResolverGroup` initialization to enable sharing of DNSCache among EventLoops under the same `DnsAddressResolverGroup`.

Add unit test: testSharedDNSCacheAcrossEventLoops

Fixes #14046.

### CODE REVIEW

File: resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java [hunk 1]
```diff
@@ -2752,7 +2754,11 @@ public void testResolveACachedWithDotSearchDomain() throws Exception {
             assertEquals(1, cached.size());
             assertEquals(cached, cached2);
 
-            resolver.resolve("test").syncUninterruptibly();
+            DefaultPromise<List<InetAddress>> promise =
+                    new DefaultPromise<List<InetAddress>>(GlobalEventExecutor.INSTANCE);
```
Comment (normanmaurer) [inline resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java:2758]:
```suggestion
            Promise<List<InetAddress>> promise = GlobalEventExecutor.INSTANCE.newPromise();
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java [hunk 2]
```diff
@@ -1105,8 +1106,19 @@ static boolean doResolveAllCached(String hostname,
...
+        List<? extends DnsCacheEntry> cachedEntries = resolveCache.get(hostname, additionals);
+        if (searchDomains != null && ndots != 0 && !StringUtil.endsWith(hostname, '.')) {
+            for (String searchDomain : searchDomains) {
+                if (cachedEntries != null && !cachedEntries.isEmpty()) {
+                    break;
+                }
+                final String initialHostname = hostname + '.' + searchDomain;
+                cachedEntries = resolveCache.get(initialHostname, additionals);
+            }
+        }
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java:1121]: @qnnn I think we should do this as a separate PR as its a different problem / bug. Can you open an extra PR with just this change and a unit test ?

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java [hunk 3]
```diff
@@ -513,11 +513,17 @@ public DnsNameResolverBuilder ndots(int ndots) {
         return this;
     }
 
-    private DnsCache newCache() {
+    public DnsCache getOrNewCache() {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java:516]:
```suggestion
   DnsCache getOrNewCache() {
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java [hunk 4]
```diff
@@ -513,11 +513,17 @@ public DnsNameResolverBuilder ndots(int ndots) {
...
+        if (this.resolveCache != null) {
+            return this.resolveCache;
+        }
         return new DefaultDnsCache(intValue(minTtl, 0), intValue(maxTtl, Integer.MAX_VALUE), intValue(negativeTtl, 0));
     }
 
-    private AuthoritativeDnsServerCache newAuthoritativeDnsServerCache() {
+    public AuthoritativeDnsServerCache getOrNewAuthoritativeDnsServerCache() {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java:523]:
```suggestion
   AuthoritativeDnsServerCache getOrNewAuthoritativeDnsServerCache() {
```

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java [hunk 5]
```diff
@@ -530,7 +536,10 @@ private DnsServerAddressStream newQueryServerAddressStream(
         return new ThreadLocalNameServerAddressStream(dnsServerAddressStreamProvider);
     }
 
-    private DnsCnameCache newCnameCache() {
+    public DnsCnameCache getOrNewCnameCache() {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java:539]:
```suggestion
   DnsCnameCache getOrNewCnameCache() {
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolverGroup.java [hunk 6]
```diff
@@ -46,20 +46,27 @@ public class DnsAddressResolverGroup extends AddressResolverGroup<InetSocketAddr
 
     public DnsAddressResolverGroup(DnsNameResolverBuilder dnsResolverBuilder) {
         this.dnsResolverBuilder = dnsResolverBuilder.copy();
+        this.dnsResolverBuilder
+                .resolveCache(dnsResolverBuilder.getOrNewCache()).cnameCache(dnsResolverBuilder.getOrNewCnameCache())
+                .authoritativeDnsServerCache(dnsResolverBuilder.getOrNewAuthoritativeDnsServerCache());
     }
```
Comment (bryce-anderson) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolverGroup.java:52]: ffti: what you have is not incorrect but you could probably reduce some noise by adding a helper method that will perform all these cache setting operations for you which can be reused among the three different constructors. Maybe something like this:

```suggestion
    public DnsAddressResolverGroup(DnsNameResolverBuilder dnsResolverBuilder) {
        this.dnsResolverBuilder = withSharedCaches(dnsResolverBuilder.copy());
    }

    private static DnsNameResolverBuilder withSharedCaches(DnsNameResolverBuilder dnsResolverBuilder) {
        /// To avoid each member of the group having its own cache we either use the configured cache
        // or create a new one to share among the entire group.
        return dnsResolverBuilder.resolveCache(dnsResolverBuilder.getOrNewCache())
                .cnameCache(dnsResolverBuilder.getOrNewCnameCache())
                .authoritativeDnsServerCache(dnsResolverBuilder.getOrNewAuthoritativeDnsServerCache());
    }
```

**Review by bryce-anderson — APPROVED** [review]
This seems reasonable to me but I'm not an expert in this code so please head the advice of others. 🙂

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolverGroup.java (hunk 6 above)
Comment (qnnn) [reply resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolverGroup.java:52]: > ffti: what you have is not incorrect but you could probably reduce some noise by adding a helper method that will perform all these cache setting operations for you which can be reused among the three different constructors. Maybe something like this:

Sure, this version looks clearer in terms of semantics. Can I merge the suggested changes myself, or would you prefer to create a commit? It seems like this isn't quite finished yet.

**Comment by normanmaurer** [comment]
@qnnn I merged the commit of @bryce-anderson ... please do all remaining changes and ping me once done

**Comment by qnnn** [comment]
> @qnnn I merged the commit of @bryce-anderson ... please do all remaining changes and ping me once done

@normanmaurer Thanks! I've completed the remaining changes.

**Review by normanmaurer — APPROVED** [review]

**Review by idelpivnitskiy — APPROVED** [review]

**Comment by normanmaurer** [comment]
@qnnn thanks!
