### PR TITLE
Fix bug in method `AdaptivePoolingAllocator.allocateWithoutLock(...)`

### LINKED ISSUE #15028: AdaptivePoolingAllocator fails reallocation
Netty version 4.2.0-Final
```
java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.put(java.nio.ByteBuffer)" because "this.tmpNioBuf" is null
	at io.netty.buffer.AdaptivePoolingAllocator$AdaptiveByteBuf.capacity(AdaptivePoolingAllocator.java:1038)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:305)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
	at AdaptiveBufferTest.test(AdaptiveBufferTest.java:27)
	at AdaptiveBufferTest.lambda$main$0(AdaptiveBufferTest.java:12)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```
```java
import io.netty.buffer.AdaptiveByteBufAllocator;

import java.util.concurrent.ThreadLocalRandom;

public class AdaptiveBufferTest {

	public static void main(String[] args) throws Exception {
		for (int i = 0; i < 32; i++) {
			Thread.ofPlatform().start(() -> {
				for (int j = 0; j < 1024; j++) {
					try {
						test();
					} catch (Exception ex) {
						synchronized (AdaptiveBufferTest.class) {
							ex.printStackTrace();
							Runtime.getRuntime().halt(1);
						}
					}
				}
			});
		}
	}

	private static void test() {
		var buffer = AdaptiveByteBufAllocator.DEFAULT.heapBuffer(128);
		try {
			buffer.ensureWritable(ThreadLocalRandom.current().nextInt(512, 32768 + 1));
		} finally {
			buffer.release();
		}
	}
}
```
The faulty path (I think) is: https://github.com/netty/netty/blob/35333e57d30a2dce60f96afa8cdcf013598afca1/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L592-L605

`readInitInto` may not be called, not sure why that may be the case as I'm not familiar with the new adaptive allocator.
Our temporary solution to fix this is to revert to use of pooled allocator with `-Dio.netty.allocator.type=pooled`.

### PR DESCRIPTION
**Pull request by laosijikaichele**
Motivation:

There is a bug in method `AdaptivePoolingAllocator.allocateWithoutLock(...)`, which should return `false` if `curr.remainingCapacity() < size`.

Modification:

Return `false` if `curr.remainingCapacity() < size`.

Result:

Fixes #15028

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]
LGTM! Thanks!

File: buffer/src/test/java/io/netty/buffer/AdaptiveByteBufAllocatorTest.java [hunk 1]
```diff
@@ -113,4 +117,38 @@ void sliceOrDuplicateUnwrapLetNotEscapeRootParent(boolean slice) {
 
         assertTrue(buffer.release());
     }
+
+    // See https://github.com/netty/netty/issues/15028
```
Comment (franz1981) [inline buffer/src/test/java/io/netty/buffer/AdaptiveByteBufAllocatorTest.java:121]: No need to ref the issue here, got blame will tell us

Comment (laosijikaichele) [reply buffer/src/test/java/io/netty/buffer/AdaptiveByteBufAllocatorTest.java]: Done it.

**Comment by normanmaurer** [comment]
@laosijikaichele great catch!
