### PR TITLE
Fix issue if encoding is enabled but not used

### LINKED ISSUE #11357: IllegalReferenceCountException with compression enabled but not used if HttpResponse implements HttpContent and not LastHttpContent
Turns out my fix for https://github.com/netty/netty/issues/11092 was incomplete. It fixes the case where the content is compressed, but it will also fail if the client does not specify an Accept-Encoding.

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Motivation:

Fixes an IllegalReferenceCountException

Modification:

Retained the buffers so the encoder works correctly.

Result:

Fixes #11357

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I thought something else was wrong in https://github.com/netty/netty/pull/11093 but managed to convince myself that it was fine. Turns out that there are similar problems for HTTP/1.0 and requests that don't set an accept-encoding.

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java [hunk 1]
```diff
@@ -217,6 +219,65 @@ public void testChunkedContentWithAssembledResponse() throws Exception {
         assertThat(ch.readOutbound(), is(nullValue()));
     }
 
+    @org.junit.Test
```
Comment (trustin) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java:222]: Wrong annotation type
```suggestion
    @Test
```

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java [hunk 2]
```diff
@@ -217,6 +219,65 @@ public void testChunkedContentWithAssembledResponse() throws Exception {
...
+
+        chunk = ch.readOutbound();
+        assertThat(chunk.content().toString(StandardCharsets.UTF_8), is("orld"));
+        assertThat(chunk, is(instanceOf(LastHttpContent.class)));
+        chunk.release();
+
+        assertThat(ch.readOutbound(), is(nullValue()));
+    }
+
+    @org.junit.Test
```
Comment (trustin) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java:252]:
```suggestion
    @Test
```

**Review by trustin — COMMENTED** [review]
Thanks for fixing this, @stuartwdouglas. Left two nits.

**Comment by stuartwdouglas** [comment]
Fixed, no idea how that happened.

**Review by trustin — APPROVED** [review]

**Review by normanmaurer — APPROVED** [review]
Thanks a lot @stuartwdouglas
