### PR TITLE
Selective Message Aggregation

### LINKED ISSUE #8772: HttpObjectAggregator w/ isStartMessage: Bug or Feature?
Let's say you want to be very selective when and if to aggregate HttpRequests and Responses. Say you want to only aggregate responses with a content-type of application/json. Naturally I went with this:

```java
public class MyHttpObjectAggregator extends HttpObjectAggregator {
  
  public MyHttpObjectAggregator(int maxContentLength) {
    super(maxContentLength);
  }

  @Override
  protected boolean isStartMessage(HttpObject msg) throws Exception {
    if (msg instanceof HttpResponse) {
      HttpResponse response = (HttpResponse) msg;
      HttpHeaders headers = response.headers();
      
      String contentType = headers.get(HttpHeaderNames.CONTENT_TYPE);
      if (AsciiString.contentEqualsIgnoreCase(contentType, HttpHeaderValues.APPLICATION_JSON)) {
        return true;
      }
    }
    
    return false;
  }
}
```

... but it will not work due to the following two conditions

1) isContentMessage returns true for any HttpContent

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java#L99

2) Subsequently we enter decode(), isContentMessage returns again true but `currentMessage` is null and early exits. Leaving the aggregator in a bad state.

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java#L261-L265

My work around is to introduce a toggle flag in my aggregator that looks like this:

```java
public class MyHttpObjectAggregator extends HttpObjectAggregator {
  
  private boolean aggregating;
  
  public MyHttpObjectAggregator(int maxContentLength) {
    super(maxContentLength);
  }

  @Override
  protected boolean isStartMessage(HttpObject msg) throws Exception {
    if (msg instanceof HttpResponse) {
      HttpResponse response = (HttpResponse) msg;
      HttpHeaders headers = response.headers();
      
      String contentType = headers.get(HttpHeaderNames.CONTENT_TYPE);
      if (AsciiString.contentEqualsIgnoreCase(contentType, HttpHeaderValues.APPLICATION_JSON)) {
        aggregating = true;
        return true;
        
      } else {
        aggregating = false;
        return false;
      }
    }
    
    return false;
  }

  @Override
  protected boolean isContentMessage(HttpObject msg) throws Exception {
    return aggregating && super.isContentMessage(msg);
  }
}
```

I'm wondering if this is intended behavior or a bug?

### PR DESCRIPTION
**Pull request by rkapsi**
Motivation

Implementations of MessageAggregator (HttpObjectAggregator in particular) may wish to
selectively aggrerage requests and responses on a case-by-case basis such as for example
only POST requests or only responses of a certain content-type.

Modifications

Adding a flag to MessageAggregator that toggles between true/false depending on if aggregation
is desired for the current message or not.

Result

Fixes #8772

### CODE REVIEW

File: codec/src/main/java/io/netty/handler/codec/MessageAggregator.java [hunk 1]
```diff
@@ -96,7 +98,21 @@ public boolean acceptInboundMessage(Object msg) throws Exception {
...
+        if (isAggregated(in)) {
+            return false;
+        }
+
+        // NOTE: It's tempting to make this check only if aggregating is false. There are however
+        // side conditions in decode(...) in respect to large messages.
+        if (isStartMessage(in)) {
+            aggregating = true;
+            return true;
+
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/MessageAggregator.java]: nit: remove empty line

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 2]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+        };
+
+        EmbeddedChannel channel = new EmbeddedChannel(myPostAggregator);
+
+        // Aggregate: POST
+        HttpRequest request1 = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/");
+        HttpContent content1 = new DefaultHttpContent(Unpooled.copiedBuffer("Hello, World!", CharsetUtil.UTF_8));
+        request1.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);
+
+        channel.writeInbound(request1, content1, LastHttpContent.EMPTY_LAST_CONTENT);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: assert return value

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 3]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+
+        // Getting an aggregated response out
+        Object msg1 = channel.readInbound();
+        assertTrue(msg1 instanceof FullHttpRequest);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: release message

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 4]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+
+        // Don't aggregate: non-POST
+        HttpRequest request2 = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.PUT, "/");
+        HttpContent content2 = new DefaultHttpContent(Unpooled.copiedBuffer("Hello, World!", CharsetUtil.UTF_8));
+        request2.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);
+
+        channel.writeInbound(request2, content2, LastHttpContent.EMPTY_LAST_CONTENT);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: assert return value

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 5]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+
+        // Getting the same response objects out
+        assertSame(request2, channel.readInbound());
+        assertSame(content2, channel.readInbound());
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: ensure to release stuff

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 6]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+        assertSame(LastHttpContent.EMPTY_LAST_CONTENT, channel.readInbound());
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: call `channel.finish()` and assert return value

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 7]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+        HttpResponse response2 = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK);
+        HttpContent content2 = new DefaultHttpContent(Unpooled.copiedBuffer("{hello: 'world!'}", CharsetUtil.UTF_8));
+        response2.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.APPLICATION_JSON);
+
+        channel.writeInbound(response2, content2, LastHttpContent.EMPTY_LAST_CONTENT);
+
+        // Getting the same response objects out
+        assertSame(response2, channel.readInbound());
+        assertSame(content2, channel.readInbound());
+        assertSame(LastHttpContent.EMPTY_LAST_CONTENT, channel.readInbound());
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: call `channel.finish()` and assert return value

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 8]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+        // Getting an aggregated response out
+        Object msg1 = channel.readInbound();
+        assertTrue(msg1 instanceof FullHttpResponse);
+
+        // Don't aggregate: application/json
+        HttpResponse response2 = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK);
+        HttpContent content2 = new DefaultHttpContent(Unpooled.copiedBuffer("{hello: 'world!'}", CharsetUtil.UTF_8));
+        response2.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.APPLICATION_JSON);
+
+        channel.writeInbound(response2, content2, LastHttpContent.EMPTY_LAST_CONTENT);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: assert return value

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 9]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+        // Aggregate: text/plain
+        HttpResponse response1 = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK);
+        HttpContent content1 = new DefaultHttpContent(Unpooled.copiedBuffer("Hello, World!", CharsetUtil.UTF_8));
+        response1.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);
+
+        channel.writeInbound(response1, content1, LastHttpContent.EMPTY_LAST_CONTENT);
+
+        // Getting an aggregated response out
+        Object msg1 = channel.readInbound();
+        assertTrue(msg1 instanceof FullHttpResponse);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: release message

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java [hunk 10]
```diff
@@ -517,4 +520,93 @@ public void testReplaceAggregatedResponse() {
...
+        };
+
+        EmbeddedChannel channel = new EmbeddedChannel(myTextAggregator);
+
+        // Aggregate: text/plain
+        HttpResponse response1 = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK);
+        HttpContent content1 = new DefaultHttpContent(Unpooled.copiedBuffer("Hello, World!", CharsetUtil.UTF_8));
+        response1.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.TEXT_PLAIN);
+
+        channel.writeInbound(response1, content1, LastHttpContent.EMPTY_LAST_CONTENT);
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpObjectAggregatorTest.java]: assert return value

**Comment by normanmaurer** [comment]
@netty-bot test this please
