### PR TITLE
Bugfix #9257: WebSocketProtocolHandler does NOT support autoRead=false

### LINKED ISSUE #9257: WebSocketProtocolHandler does NOT support autoRead=false
### Expected behavior
WebSockets inbound flow could be controlled manually with autoRead=false

### Actual behavior
Inbound flow hangs on the first ping or pong message from the client.

### Steps to reproduce
Disable autoRead on the channel.
Request the next inbound message from the channel.
Send from the client two frames: ping and text.

**Expected:** my handler receives text frame.
**Actual:** no frames received ever.

### Netty version
4.1.29.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b25, mixed mode)

openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.1+12, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Windows 7

Darwin ursas-pro 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by ursaj**
**Motivation:**

I need to control WebSockets inbound flow manually, when autoRead=false

**Modification:**

Add missed `ctx.read()` call into `WebSocketProtocolHandler`, where read request has been swallowed.

**Result:**

Fixes #9257

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandlerTest.java [hunk 1]
```diff
@@ -45,6 +46,66 @@ public void testPingFrame() {
         assertFalse(channel.finish());
     }
 
+    @Test
+    public void testPingPongFlowControlWhenAutoReadIsDisabled() {
+        // Given
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandlerTest.java]: remove comments as these not really provide any value.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandler.java [hunk 2]
```diff
@@ -48,9 +48,15 @@ protected void decode(ChannelHandlerContext ctx, WebSocketFrame frame, List<Obje
         if (frame instanceof PingWebSocketFrame) {
             frame.content().retain();
             ctx.channel().writeAndFlush(new PongWebSocketFrame(frame.content()));
+            if (!ctx.channel().config().isAutoRead()) {
+                ctx.read();
+            }
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandler.java]: nit you could factor out this into a method and then just call the method:

```
private static void readIfNeeded(ChannelHandlerContext ctx) {
    if (!ctx.channel.config().isAutoRead()) {
        ctx.read();
    }
}
```

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandlerTest.java [hunk 3]
```diff
@@ -45,6 +46,66 @@ public void testPingFrame() {
...
+        String text3 = "Hello, world #3";
+        String text4 = "Hello, world #4";
+
+        EmbeddedChannel channel = new EmbeddedChannel();
+        channel.config().setAutoRead(false);
+        channel.pipeline().addLast(new FlowControlHandler());
+        channel.pipeline().addLast(new WebSocketProtocolHandler() { });
+
+        // When
+        channel.writeInbound(
```
[the remark this answers is not in the document]
Comment (ursaj) [reply codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandlerTest.java]: assertion added

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandlerTest.java (hunk 1 above)
Comment (ursaj) [reply codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandlerTest.java]: done

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandler.java (hunk 2 above)
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandler.java]: done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@ursaj thanks a lot!
