### PR TITLE
Only fall back to CNAME on A/AAAA queries

### LINKED ISSUE #11214: DNS resolver tries CNAME for non-A/AAAA queries
### Expected behavior

If querying an non-A/AAAA record type, such as SRV or NAPTR, the operation should not try CNAME if no records are found.

### Actual behavior

When querying a non-existent SRV record, Netty's DNS resolver falls back to trying to lookup the CNAME record of the same name. But this makes no sense, as the results of a CNAME query are only going to refer to A/AAAA records. There is no way for a CNAME to refer to an SRV record or other record types.

The fallback to CNAME should only happen if the requested record type is A or AAAA.
 
### Steps to reproduce

Lookup an SRV record that doesn't exist, and observe in logs or packet capture that a CNAME query is also performed.

### Minimal yet complete reproducer code (or URL to code)

https://gist.github.com/benevans/910e5dd451899135267d21420b72e4dd

### Netty version

4.1.63.Final

### JVM version (e.g. `java -version`)

   openjdk version "11.0.9.1" 2020-11-04
   OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
   OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### OS version (e.g. `uname -a`)

   Linux orogene 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by benevans**
Motivation:

DNS resolver falls back to trying CNAME if no records found, but should
only try this for A/AAAA queries. Does not make sense for other query
types, results in a redundant CNAME query that is just going to fail.

Modification:

Check query type before deciding to try CNAME. Only proceed if type is A
or AAAA.

Added unit test to verify CNAME is only tried after A/AAAA queries.

Result:

Fixes #11214.

### CODE REVIEW

File: resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java [hunk 1]
```diff
@@ -3286,6 +3287,68 @@ public void testSrvWithCnameNotCached() throws Exception {
...
+
+        DnsNameResolver resolver = null;
+        try {
+            resolver = newNonCachedResolver(ResolvedAddressTypes.IPV4_PREFERRED)
+                    .maxQueriesPerResolve(3)
+                    .nameServerProvider(new SingletonDnsServerAddressStreamProvider(dnsServer2.localAddress()))
+                    .build();
+
+            try {
+                resolver.resolveAll(new DefaultDnsQuestion("service.netty.io", SRV)).get();
```
Comment (normanmaurer) [inline resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java:3316]: should we better also verify the exception that was thrown ? Something like:

```
assertThat(instanceof(ExpectedExceptionType.class, 
    resolver.resolveAll(new DefaultDnsQuestion("service.netty.io", SRV)).sync().cause());
```

This is true for all the queries

**Comment by normanmaurer** [comment]
@benevans also there is a test failure:

```
[INFO] 
58327
[INFO] Results:
58328
[INFO] 
58329
Error:  Failures: 
58330
Error:    DnsNameResolverTest.testCNAMEOnlyTriedOnAddressLookups:3343 expected:<1> but was:<2>
58331
[INFO] 
58332
Error:  Tests run: 147, Failures: 1, Errors: 0, Skipped: 9
```

File: resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java (hunk 1 above)
Comment (benevans) [reply resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java:3316]: Thanks, will do.

Comment (normanmaurer) [reply resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java:3316]: @benevans ping we once ready for another review

**Comment by benevans** [comment]
@normanmaurer Fixed now. The test failure was due to the resolver's default config using the container's search domain, which caused extra lookups making the assertion fail. So I updated the test to use an empty search domains list.

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
Thanks a lot @benevans
