### PR TITLE
Fix #9770, last frame may contain trash that doesn't affect decompres…

### LINKED ISSUE #9770: Websoket frame failes if the frame content is deflated partial EOM (0,0,-1,-1) from Tomcat.
Scenario is when the tomcat communicates to netty with websocket connection. The frmae size is 8192 bytes.
Tomcat sends the compressed websocket data frames to netty. 
When tomcat sends the websocket frames to netty, every frame ends with the EOM byte sequence which is 0,0,-1,-1. 
There are four conditions now:
1. The compressed data is small enough that the complete content and the EOM is contained in one frame. 

2. The data is large that it takes multiple frames to complete and the last frame contains some part data and the complete EOM. 

3. The  data is such that the EOM is in the two frames. e.g. the data is 8189 bytes, so the EOM starts in one and spreads over the next one. 

4.  The data and the EOM totals the 8192bytes. even in this case a next frame is sent with 0 as the first byte.

The conditions 1and 2 passes but 3 and 4 fails. Becuase the frame that contains only the partial EOM of previous frame is unable to be deflated in the DeflateDecoder
io.netty.handler.codec.compression.JdkZlibDecoder.decode(ChannelHandlerContext, ByteBuf, List<Object>)

### Expected behavior
The websocket message should be successfully sent. 

### Actual behavior
The message fils with the below exception 
Caused by: io.netty.handler.codec.CodecException: cannot read uncompressed buffer
at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder.decode(DeflateDecoder.java:89)
at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:64)
at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:30)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)

### Steps to reproduce
Host a zip file in tomcat and transfer to netty application on a websocket connection.
But it is not reproducible with any zip file, only with the ones where content is not compressible by the java Deflater class. 

### Minimal yet complete reproducer code (or URL to code)
I have debugged in a complicated software, I am in process of creating a minimal code, but if the issue is crlear can we please get the fix. 

Though not in a perfect way, but I was able to fix the code by following changes in DeflateDecoder
[DeflateDecoder.txt](https://github.com/netty/netty/files/3828375/DeflateDecoder.txt)
:

boolean partialEOMFrame = true;
        for (int i = 0; i < msg.content().readableBytes(); i++) {
            byte contentAtI = msg.content().readByte();
            if (contentAtI != 0 && contentAtI != -1) {
                partialEOMFrame = false;
                break;
            }
        }
        msg.content().readerIndex(0);
;
;
;

if (!partialEOMFrame && readable && compositeUncompressedContent.numComponents() <= 0) {
            compositeUncompressedContent.release();
            throw new CodecException("cannot read uncompressed buffer");
        }

### Netty version
4.1.15
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
windows.

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:
Client can split data into different numbers of fragments and sometimes the last frame may contain trash data that doesn't affect decompression process.

Modification:
Added check if last frame is `ContinuationWebSocketFrame` and decompression data is empty
then don't throw an exception.

Also i'm not sure about https://github.com/netty/netty/issues/4348 is still relevant since not many cases left when it applicable. @normanmaurer WDYT ?

Result:
Fixes #9770

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java [hunk 1]
```diff
@@ -136,8 +136,12 @@ private ByteBuf decompressContent(ChannelHandlerContext ctx, WebSocketFrame msg)
         // Correctly handle empty frames
         // See https://github.com/netty/netty/issues/4348
         if (!emptyDeflateBlock && readable && compositeDecompressedContent.numComponents() <= 0) {
-            compositeDecompressedContent.release();
-            throw new CodecException("cannot read uncompressed buffer");
+            // Sometimes after fragmentation the last frame
+            // May contain trash that doesn't affect decompression
+            if (!(msg instanceof ContinuationWebSocketFrame)) {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: hmm... I am wondering if it is really a good idea to ignore stuff as long as its `ContinuationWebSocketFrame `.

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: Maybe not for all `ContinuationWebSocketFrame` fragments only for final. In most of implementation that i saw thety don't worry at all about decompressed payload is empty or not.

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: I am just wondering why we would receive trash... this does sounds very odd to me. What I am missing ?

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: @normanmaurer check test please, last frame may contain bytes which no longer affect the decompression result so `inflater.inflate(...)` return 0.

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: @amizurov even after looking at the test I don't understand it... Can you please expand the comment above to explain why it contains trash ? I am not even sure what "trash" means in this context

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: Also maybe you could also link to another compression implementation that does the same. Maybe this clears things up.

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: @normanmaurer sorry if i confused you maybe "trash" inappropriate word in this context, one of implementation you can look here [undertow](https://github.com/undertow-io/undertow/blob/b6bd4d2e6611f135e740d714cee2e811e9815ef8/core/src/main/java/io/undertow/websockets/extensions/PerMessageDeflateFunction.java#L165), the `output` can be empty buffer and this is ok in some cases.

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: @amizurov I see... yes maybe just fix the content to replace trash with "extra data" or something like that ?

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@amizurov please fix the leaks that are introduced after your PR:

```
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.135 s - in io.netty.handler.codec.http.HttpClientCodecTest
[INFO] Running io.netty.handler.codec.http.websocketx.WebSocket08EncoderDecoderTest
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /code/codec-http/target/surefire-reports/2019-12-10T11-38-45_434-jvmRun1.dumpstream
11:48:32.542 [Finalizer] DEBUG io.netty.buffer.PoolThreadCache - Freed 2 thread-local buffer(s) from thread: Finalizer
11:48:32.547 [Finalizer] DEBUG io.netty.buffer.PoolThreadCache - Freed 2 thread-local buffer(s) from thread: Finalizer
11:48:32.709 [main] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
	io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:271)
	io.netty.channel.embedded.EmbeddedChannel.doWrite(EmbeddedChannel.java:749)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.flush(EmbeddedChannel.java:845)
	io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:788)
	io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756)
	io.netty.handler.codec.compression.JdkZlibEncoder.finishEncode(JdkZlibEncoder.java:319)
	io.netty.handler.codec.compression.JdkZlibEncoder.close(JdkZlibEncoder.java:263)
	io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:620)
	io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:604)
	io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:994)
	io.netty.channel.AbstractChannel.close(AbstractChannel.java:268)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:568)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:555)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:503)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:483)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:385)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.retain(AdvancedLeakAwareByteBuf.java:36)
	io.netty.util.ReferenceCountUtil.retain(ReferenceCountUtil.java:40)
	io.netty.channel.embedded.EmbeddedChannel.doWrite(EmbeddedChannel.java:747)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.flush(EmbeddedChannel.java:845)
	io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:763)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:788)
	io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756)
	io.netty.handler.codec.compression.JdkZlibEncoder.finishEncode(JdkZlibEncoder.java:319)
	io.netty.handler.codec.compression.JdkZlibEncoder.close(JdkZlibEncoder.java:263)
	io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:620)
	io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:604)
	io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:994)
	io.netty.channel.AbstractChannel.close(AbstractChannel.java:268)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:568)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:555)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:503)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:483)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:385)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#3:
	Hint: 'DefaultChannelPipeline$HeadContext#0' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:784)
	io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756)
	io.netty.handler.codec.compression.JdkZlibEncoder.finishEncode(JdkZlibEncoder.java:319)
	io.netty.handler.codec.compression.JdkZlibEncoder.close(JdkZlibEncoder.java:263)
	io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:620)
	io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:604)
	io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:994)
	io.netty.channel.AbstractChannel.close(AbstractChannel.java:268)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:568)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:555)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:503)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:483)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:385)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newHeapBuffer(PooledByteBufAllocator.java:332)
	io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:168)
	io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:154)
	io.netty.handler.codec.compression.JdkZlibEncoder.finishEncode(JdkZlibEncoder.java:289)
	io.netty.handler.codec.compression.JdkZlibEncoder.close(JdkZlibEncoder.java:263)
	io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:620)
	io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:604)
	io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:994)
	io.netty.channel.AbstractChannel.close(AbstractChannel.java:268)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:568)
	io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:555)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:503)
	io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:483)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:385)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
11:48:32.711 [main] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.buffer.DefaultByteBufHolder.release(DefaultByteBufHolder.java:115)
	io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:370)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#2:
	Hint: 'PerMessageDeflateDecoder#0' will handle the message from this point.
	io.netty.buffer.DefaultByteBufHolder.touch(DefaultByteBufHolder.java:109)
	io.netty.handler.codec.http.websocketx.WebSocketFrame.touch(WebSocketFrame.java:106)
	io.netty.handler.codec.http.websocketx.ContinuationWebSocketFrame.touch(ContinuationWebSocketFrame.java:134)
	io.netty.handler.codec.http.websocketx.ContinuationWebSocketFrame.touch(ContinuationWebSocketFrame.java:26)
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:370)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#3:
	io.netty.buffer.DefaultByteBufHolder.release(DefaultByteBufHolder.java:115)
	io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:369)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#4:
	io.netty.buffer.DefaultByteBufHolder.release(DefaultByteBufHolder.java:115)
	io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:367)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#5:
	io.netty.buffer.AdvancedLeakAwareByteBuf.slice(AdvancedLeakAwareByteBuf.java:82)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:354)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#6:
	io.netty.buffer.AdvancedLeakAwareByteBuf.slice(AdvancedLeakAwareByteBuf.java:82)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:352)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#7:
	io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
	io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:113)
	io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:271)
	io.netty.channel.embedded.EmbeddedChannel.doWrite(EmbeddedChannel.java:749)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.flush(EmbeddedChannel.java:845)
	io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
	io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726)
	io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
	io.netty.channel.AbstractChannel.flush(AbstractChannel.java:242)
	io.netty.channel.embedded.EmbeddedChannel.flushOutbound0(EmbeddedChannel.java:474)
	io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:413)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:344)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#8:
	io.netty.buffer.AdvancedLeakAwareByteBuf.retain(AdvancedLeakAwareByteBuf.java:36)
	io.netty.util.ReferenceCountUtil.retain(ReferenceCountUtil.java:40)
	io.netty.channel.embedded.EmbeddedChannel.doWrite(EmbeddedChannel.java:747)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:897)
	io.netty.channel.embedded.EmbeddedChannel$EmbeddedUnsafe$1.flush(EmbeddedChannel.java:845)
	io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
	io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
	io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:726)
	io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
	io.netty.channel.AbstractChannel.flush(AbstractChannel.java:242)
	io.netty.channel.embedded.EmbeddedChannel.flushOutbound0(EmbeddedChannel.java:474)
	io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:413)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:344)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
#9:
	Hint: 'DefaultChannelPipeline$HeadContext#0' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:784)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
	io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:695)
	io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
	io.netty.channel.AbstractChannel.write(AbstractChannel.java:284)
	io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:410)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:344)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newHeapBuffer(PooledByteBufAllocator.java:332)
	io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:168)
	io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:159)
	io.netty.handler.codec.compression.JdkZlibEncoder.allocateBuffer(JdkZlibEncoder.java:258)
	io.netty.handler.codec.compression.JdkZlibEncoder.allocateBuffer(JdkZlibEncoder.java:36)
	io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:105)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:695)
	io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
	io.netty.channel.AbstractChannel.write(AbstractChannel.java:284)
	io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:410)
	io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoderTest.testFragmentedFrameWithTrashInLastFragment(PerMessageDeflateDecoderTest.java:344)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
: 38 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.
11:48:34.291 [nioEventLoopGroup-3-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 4 thread-local 
```

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateDecoderTest.java [hunk 2]
```diff
@@ -328,4 +328,62 @@ public void testEmptyFrameDecompression() {
...
+        ContinuationWebSocketFrame uncompressedTrash = decoderChannel.readInbound();
+        assertFalse(uncompressedTrash.content().isReadable());
+
+        ByteBuf uncompressedPayload = Unpooled.wrappedBuffer(uncompressedFrame1.content(), uncompressedFrame2.content(),
+                                      uncompressedFrame3.content(), uncompressedTrash.content());
+        assertEquals(originPayload, uncompressedPayload);
+
+        assertTrue(originPayload.release());
+        assertTrue(uncompressedPayload.release());
+        assertTrue(encoderChannel.finish());
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateDecoderTest.java]: you either need to release everything else by yourself after this returns `true` or you need to call `finishAndReleaseAll()`.

**Comment by normanmaurer** [comment]
@amizurov I pushed a new commit to fix the comment and memory leak. Once the CI passes I will merge this one

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by amizurov** [comment]
@normanmaurer thanks, very fast :)

**Comment by normanmaurer** [comment]
@amizurov I guess we both have different definitions of "very fast" here :D

**Comment by amizurov** [comment]
@normanmaurer also WDYT about update [autobahntestsuite-maven-plugin](https://github.com/normanmaurer/autobahntestsuite-maven-plugin) to latest test suite or maybe integrate new approach with test containers and autobahn docker [image](https://github.com/crossbario/autobahn-testsuite) ? I found some not passed test and they looks correct according a spec.

**Comment by normanmaurer** [comment]
@amizurov please open an extra issue for this... I would need to have a look. That said my time is currently very limited :/

**Comment by amizurov** [comment]
> @amizurov please open an extra issue for this... I would need to have a look. That said my time is currently very limited :/

No problem I'll do that

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@amizurov thanks a lot!
