### PR TITLE
Fix h2c upgrade failure when multiple connection headers are present in upgrade request

### LINKED ISSUE #8846: When more than one connection header is present in h2c upgrade request, upgrade fails
### Expected behavior
$subject occurs, with this change https://github.com/netty/netty/pull/7824. (@bryce-anderson and @normanmaurer )

Now that more than one connection header is allowed with this https://github.com/netty/netty/pull/7824,
 line https://github.com/netty/netty/blob/737519314153f9146eaf532cd4e945a621cf3fa5/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java#L295 returns false and the upgrade fails since the connection header value returned from this is not the upgrade but some other connection header value. 

If we are allowing multiple connection headers, then in HttpServerUpgradeHandler I think we need to check  whether any of the connection header value is upgrade and then remove other connection headers. https://tools.ietf.org/html/rfc7540#section-8.1.2.2

### Steps to reproduce
Send an upgrade request with multiple conection headers to HTTP/2 server and the request hangs.

Example request:
GET / HTTP/1.1
Host: localhost:9000
connection: keep-alive
forwarded: by=127.0.0.1
content-length: 0
upgrade: h2c
HTTP2-Settings: AAEAABAAAAIAAAABAAN_____AAQAAP__AAUAAEAAAAYAACAA
connection: HTTP2-Settings,upgrade

### Netty version
From 4.1.33.Final (This issue  started to occur from From 4.1.23.Final onwards)

### PR DESCRIPTION
**Pull request by arukshani**
Motivation:

When more than one connection header is present in h2c upgrade request, upgrade fails. This is to fix that. 

Modification:
In HttpServerUpgradeHandler's upgrade() method, check whether any of the connection header value is upgrade, not just the first header value which might return a different value other than upgrade. 

Result:
Fixes #8846. 

With this PR, now when multiple connection headers are sent with the upgrade request, upgrade will not fail.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@arukshani can you please sign our ICLA and let me know once done:

https://netty.io/s/icla

**Comment by arukshani** [comment]
@normanmaurer I have signed the license agreement.

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java [hunk 1]
```diff
@@ -284,7 +284,21 @@ private boolean upgrade(final ChannelHandlerContext ctx, final FullHttpRequest r
...
+
+        if (connectionHeaderValues == null) {
+            return false;
+        }
+
+        CharSequence connectionHeader = null;
+
+        for (CharSequence connectionHeaderValue : connectionHeaderValues) {
+            if (containsIgnoreCase(connectionHeaderValue, HttpHeaderNames.UPGRADE)) {
+                connectionHeader = connectionHeaderValue;
```
Comment (ejona86) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java]: This requires that Upgrade exists in the same Connection header value as requiredHeaders. But each value could be put in its own Connection header. It would be better to join all the values together with a `,` and then splitHeader(). @normanmaurer, is there not a utility to do that?

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java]: @ejona86 thats a good point... I think there is no such utility yet (or at least I could not remember and also could not find any). /cc @arukshani can you do the adjustment and also add a unit test for this ?

Comment (arukshani) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java]: @ejona86 and @normanmaurer I have done the necessary changes and added a unit test as well for that. Please review.

File: codec-http2/src/test/java/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandlerTest.java [hunk 2]
```diff
@@ -155,6 +155,99 @@ public void upgrade() throws Exception {
...
+    public void upgradeWithMultipleConnectionHeaders() {
+        setUpServerChannel();
+
+        String upgradeString = "GET / HTTP/1.1\r\n" +
+                "Host: example.com\r\n" +
+                "Connection: keep-alive\r\n" +
+                "Connection: Upgrade, HTTP2-Settings\r\n" +
+                "Upgrade: h2c\r\n" +
+                "HTTP2-Settings: AAMAAABkAAQAAP__\r\n\r\n";
+        ByteBuf upgrade = Unpooled.copiedBuffer(upgradeString, CharsetUtil.US_ASCII);
```
Comment (normanmaurer) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandlerTest.java]: @arukshani seems like the test code is completely identical except the different `upgradeString`. Consider moving all the code into an extra method and just pass in the `upgradeString` from both of the test methods to remove all the code-duplication

Comment (arukshani) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandlerTest.java]: Done

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java [hunk 3]
```diff
@@ -284,16 +284,22 @@ private boolean upgrade(final ChannelHandlerContext ctx, final FullHttpRequest r
...
+
+        if (connectionHeaderValues == null) {
             return false;
         }
 
+        final StringBuilder concatenatedConnectionValue = new StringBuilder(connectionHeaderValues.size() * 10);
+        for (CharSequence connectionHeaderValue : connectionHeaderValues) {
+            concatenatedConnectionValue.append(connectionHeaderValue).append(COMMA);
+        }
+
```
[the remark this answers is not in the document]
Comment (arukshani) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java]: @normanmaurer Done

File: codec-http2/src/test/java/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandlerTest.java [hunk 4]
```diff
@@ -115,44 +122,38 @@ public void upgrade() throws Exception {
...
+        validateClearTextUpgrade(upgradeString);
+    }
 
-        // Check that the preface was send (a.k.a the settings frame)
-        ByteBuf settingsBuffer = channel.readOutbound();
-        assertNotNull(settingsBuffer);
-        settingsBuffer.release();
+    @Test
+    public void requiredHeadersInSeparateConnectionHeaders() {
+        setUpServerChannel();
```
Comment (normanmaurer) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandlerTest.java]: nit: you could also move all the `setUpServerChannel()` calls

Comment (arukshani) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/CleartextHttp2ServerUpgradeHandlerTest.java]: Done

**Comment by normanmaurer** [comment]
@netty-bot test this please
