### PR TITLE
Fix DnsNameResolver TCP fallback test and message leaks

### LINKED ISSUE #9634: DNS Resolver leaking direct memory
### Expected behavior

DNS resolver does not leak direct memory when buffers are freed correctly.

### Actual behavior

Memory is leaked, JVM runs out of direct memory.

```
[error] Exception in thread "main" io.netty.resolver.dns.DnsNameResolverException: [/10.0.2.3:53] failed to send a query via UDP (no stack trace available)
[error] Caused by: io.netty.handler.codec.EncoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 234881024, max: 239075328)
```
full stacktrace: https://gist.github.com/dziemba/ffeb8f2c3b131a74c042746151ac05c0

### Steps to reproduce

- Use `DnsNameResolver.resolveAll` to query SRV records for a name that contains a lot of answers (e.g. `hugedns.test.dziemba.net`)
-  Run query repeatedly and `.release()` returned DNS records. 
- Watch java process memory usage increase until it finally throws with `io.netty.util.internal.OutOfDirectMemoryError`

It might be important that the DNS response is large so it gets truncated and then retried via TCP.

### Minimal yet complete reproducer code (or URL to code)

https://gist.github.com/dziemba/c904d227d105b6fc7cf00495257fbb40
- run with `-Xmx128m -XX:MaxDirectMemorySize=4m` to make it fail quickly
- will fail as described after around 100-200 iterations (with above settings)
- sometimes it fails with actual network errors, re-run a few times if that happens

### Netty version

`4.1.42.Final`

### JVM version (e.g. `java -version`)
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```

I was not able to reproduce this on Java 11 or 12.

### OS version (e.g. `uname -a`)

```
Darwin wopro3 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

I also tried to reproduce this on Linux. It shows the same error behavior (fails after 100 runs of the test script) but does not output the `OutOfDirectMemoryError` for some reason...

### PR DESCRIPTION
**Pull request by njhill**
Motivation

A memory leak related to DNS resolution was reported in #9634, specifically linked to the TCP retry fallback functionality that was introduced relatively recently. Upon inspection it's apparent that there
are some error paths where the original UDP response might not be fully released, and more significantly the TCP response actually leaks every time on the fallback success path.

It turns out that a bug in the unit test meant that the intended TCP fallback path was not actually exercised, so it did not expose the main leak in question.

Modifications

- Fix `DnsNameResolverTest#testTruncated0` dummy server fallback logic to first read transaction id of retried query and use it in replayed response
- Adjust semantic of internal `DnsQueryContext#finish` method to always take refcount ownership of passed in envelope
- Reorder some logic in `DnsResponseHandler` fallback handling to verify the context of the response is expected, and ensure that the query response are either released or propagated in all cases. This also reduces a number of redundant retain/release pairings

Result

Fixes #9634

### CODE REVIEW

**Comment by njhill** [comment]
The changes look bigger than they are due to some reordering and indentation changes, recommend viewing diff with `w=1` :)

File: resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java [hunk 1]
```diff
@@ -2759,6 +2760,25 @@ public void testTruncatedWithTcpFallbackBecauseOfMtu() throws IOException {
         testTruncated0(true, true);
     }
```
Comment (normanmaurer) [inline resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java]: @njhill can we also verify that this line returns false (add a `assertFalse`):
https://github.com/netty/netty/blob/a95d04bb2f6b5f9d000f22b4daa36b5b1f12935b/resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java#L2901

Comment (njhill) [reply resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java]: @normanmaurer do you mean that it should return true (no more refs left)? I just tried with false and it fails :)

Comment (normanmaurer) [reply resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java]: yes sorry... `true` :)

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@njhill please rebase

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java [hunk 2]
```diff
@@ -1199,129 +1198,111 @@ final DnsServerAddressStream newNameServerAddressStream(String hostname) {
...
+                                        (InetSocketAddress) ctx.channel().remoteAddress(),
+                                        (InetSocketAddress) ctx.channel().localAddress(),
+                                        response));
                             } else {
-                                if (logger.isDebugEnabled()) {
-                                    logger.debug("{} Unable to fallback to TCP [{}]", queryId, future.cause());
-                                }
+                                logger.warn("{} Received a DNS response with an unexpected ID: {}",
+                                        channel, queryId);
+                                response.release();
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java]: nit: release first before log.

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java [hunk 3]
```diff
@@ -1199,129 +1198,111 @@ final DnsServerAddressStream newNameServerAddressStream(String hostname) {
...
+                            }
+                        }
+
+                        @Override
+                        public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
+                            if (logger.isDebugEnabled()) {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java]: I think we should preserve the logic and fallback to the original truncated response if we did not receive a TCP response just like we did before:

https://github.com/netty/netty/pull/9647/files#diff-6678a05ef56f2434e7aa20acbe9d97e9L1277

Also beside this we should not log the exception if we received the response before. As the exception may be just a "connection reset" and so harmless. Also consider calling `ctx.close()` in any case to ensure the channel is closed in all cases.

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java [hunk 4]
```diff
@@ -181,30 +181,22 @@ public void run() {
         }
     }
 
+    // Takes ownership of passed envelope
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java]: why not make this a real java doc ?

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java [hunk 5]
```diff
@@ -181,30 +181,22 @@ public void run() {
...
-        Promise<AddressedEnvelope<DnsResponse, InetSocketAddress>> promise = this.promise;
-        @SuppressWarnings("unchecked")
-        AddressedEnvelope<DnsResponse, InetSocketAddress> castResponse =
-                (AddressedEnvelope<DnsResponse, InetSocketAddress>) envelope.retain();
-        if (!promise.trySuccess(castResponse)) {
-            // We failed to notify the promise as it was failed before, thus we need to release the envelope
-            envelope.release();
-        }
+    @SuppressWarnings("unchecked")
+    private boolean setSuccess(AddressedEnvelope<? extends DnsResponse, InetSocketAddress> envelope) {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java]: lets rename this to `trySuccess` as this is what it does ;)

**Comment by njhill** [comment]
@normanmaurer addressed comments, PTAL

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java (hunk 3 above)
Comment (njhill) [reply resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java]: Now fixed. I didn’t add an explicit close since the channel is closed immediately in the listener below.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@dziemba can you verify this one as well ?

**Comment by dziemba** [comment]
@normanmaurer I've built a local release from this branch (fa84a02fb) and ran the reproduction script and some additional internal test suites we have. 

Looks all good now, no more leaks 🎉 

Thanks a lot for the quick fix!

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java [hunk 6]
```diff
@@ -1199,129 +1198,112 @@ final DnsServerAddressStream newNameServerAddressStream(String hostname) {
...
-                                                // TCP fallback failed, just use the truncated response as
-                                                qCtx.finish(res);
-                                            }
-                                        }
-                                    });
-                                }
-                            });
-                    bs.connect(res.sender()).addListener(new ChannelFutureListener() {
+                    channel.pipeline().addLast(new TcpDnsResponseDecoder());
+                    channel.pipeline().addLast(new ChannelInboundHandlerAdapter() {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java]: nit: why not add these also in the `ChannelInitializer` above ?

Comment (njhill) [reply resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java]: @normanmaurer the latter one can't be done there since it references `tcpCtx` which is only created post-connect. But also none of the handlers are needed anyhow unless/until the channel connects successfully. I actually first tried to remove the `ChannelInitializer` completely, but `Bootstrap` requires at least one handler to be provided - maybe we could reconsider that requirement?

I did just realize though that the `ChannelInitializer` can be replaced with the single handler that it adds - a small simplification. I just pushed another commit to do that.

I'm also fine with adding it back along with the first two handlers if you would prefer that, but the last one needs to be here I think if we are to keep the query context verification.

**Comment by normanmaurer** [comment]
@netty-bot test this please
