### PR TITLE
Limit the number of bytes to use to copy the content of a direct buff…

### LINKED ISSUE #7804: Transferring a ByteBuf to Outputstream without duplicating memory
(running io.netty.buffer:4.1.21.Final)

I have a Java Output stream (java.io.OutputStream) I want to incrementally copy a ByteBuffer too.

The byte buffer is off heap and big.
I naively used:
    public abstract ByteBuf getBytes(int index, OutputStream out, int length) throws IOException;

assuming that it would copy all the data to the output stream.

It does, but to do so it copies the whole native buffer into the heap! I do not have that much heap, resulting in:

```
java.lang.OutOfMemoryError: Java heap space 
at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:200) ~[40:io.netty.common:4.1.21.Final] 
at io.netty.buffer.UnpooledUnsafeHeapByteBuf.allocateArray(UnpooledUnsafeHeapByteBuf.java:34) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.allocateArray(UnpooledByteBufAllocator.java:144) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:60) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledUnsafeHeapByteBuf.<init>(UnpooledUnsafeHeapByteBuf.java:29) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.<init>(UnpooledByteBufAllocator.java:139) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:166) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:157) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:572) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledUnsafeDirectByteBuf.getBytes(UnpooledUnsafeDirectByteBuf.java:365) ~[34:io.netty.buffer:4.1.21.Final] 
```

I checked io.netty.buffer.UnsafeByteBufUtil.getBytes(AbstractByteBuf, long, int, OutputStream, int)
and behold. It creates a heap bytebuffer of that size to copy the array into it and then to copy that to the output stream.

Bummer!

Shouldn't netty do this better by itself? it seems that I need to manually do this by using a (reasonably sized) byte array and read from byteBuf into that and flush that to my stream in a loop

### PR DESCRIPTION
**Pull request by normanmaurer**
…er to an Outputstream

Motivation:

Currently copying a direct ByteBuf copies it fully into the heap before writing it to an output stream.
The can result in huge memory usage on the heap.

Modification:

copy the bytebuf contents via an 8k buffer into the output stream

Result:

Fixes #7804

### CODE REVIEW

**Comment by normanmaurer** [comment]
@CodingFabian PTAL as well

File: buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java [hunk 1]
```diff
@@ -583,18 +583,35 @@ private static void setSingleBytes(final AbstractByteBuf buf, final long addr, f
...
-            try {
-                byte[] tmp = tmpBuf.array();
-                int offset = tmpBuf.arrayOffset();
-                PlatformDependent.copyMemory(addr, tmp, offset, length);
-                out.write(tmp, offset, length);
-            } finally {
-                tmpBuf.release();
+            int len = Math.min(length, ByteBufUtil.WRITE_CHUNK_SIZE);
+            if (buf.alloc().isDirectBufferPooled()) {
+                // if direct buffers are pooled changes are good that heap buffers are pooled as well.
```
Comment (trustin) [inline buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java]: changes -> chances

File: buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java [hunk 2]
```diff
@@ -583,18 +583,34 @@ private static void setSingleBytes(final AbstractByteBuf buf, final long addr, f
...
+                } finally {
+                    tmpBuf.release();
+                }
+            } else {
+                getBytes(addr, new byte[len], 0, len, out, length);
             }
         }
     }
 
+    private static void getBytes(long addr, byte[] array, int offset, int chunkLen, OutputStream out, int length)
```
Comment (trustin) [inline buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java]: How about:
- addr -> inAddr
- array -> in
- offset -> inOffset
- chunkLen -> inLen
- length -> outLen

File: buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java [hunk 3]
```diff
@@ -583,18 +583,34 @@ private static void setSingleBytes(final AbstractByteBuf buf, final long addr, f
...
         if (length != 0) {
-            ByteBuf tmpBuf = buf.alloc().heapBuffer(length);
-            try {
-                byte[] tmp = tmpBuf.array();
-                int offset = tmpBuf.arrayOffset();
-                PlatformDependent.copyMemory(addr, tmp, offset, length);
-                out.write(tmp, offset, length);
-            } finally {
-                tmpBuf.release();
+            int len = Math.min(length, ByteBufUtil.WRITE_CHUNK_SIZE);
```
Comment (trustin) [inline buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java]: Can we just do: `Math.min(Math.min(length, ByteBufUtil.WRITE_CHUNK_SIZE), length)`? This would eliminate the reason to pass 2 length parameters to the `getBytes()` below.

Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java]: hmm wouldn't we still need it ? I am confused why we not need it with this change ... Can you explain

File: buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java (hunk 2 above)
Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java]: done

File: buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java (hunk 3 above)
Comment (trustin) [reply buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java]: Because I'm an idiot? Didn't notice `outLen` is updated at the end of the loop. :-)

File: buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java [hunk 4]
```diff
@@ -491,21 +491,7 @@ private void getBytes(int index, OutputStream out, int length, boolean internal)
...
-            if (internal) {
-                tmpBuf = internalNioBuffer();
-            } else {
-                tmpBuf = buffer.duplicate();
-            }
-            tmpBuf.clear().position(index);
-            tmpBuf.get(tmp);
-            out.write(tmp);
-        }
+        ByteBufUtil.readBytes(internal ? internalNioBuffer() : buffer.duplicate(), index, length, out);
```
Comment (CodingFabian) [inline buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java]: when I tried to improve this I was wondering if we can avoid that duplicate call?

Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java]: @CodingFabian nope we can't... `internal` will be false if you use `get*`. This is needed as it may be called from multiple threads at the same time which should be fine as you not expect to do any internal updates on the indices. If you use a `get*` method there will be no duplicate invoked

File: buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java (hunk 3 above)
Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java]: lol ok that explains why =P

File: buffer/src/main/java/io/netty/buffer/ByteBufUtil.java [hunk 5]
```diff
@@ -1392,5 +1395,25 @@ private static boolean isUtf8(ByteBuf buf, int index, int length) {
...
 
+    /**
+     * Read bytes from the given {@link ByteBuffer} into the given {@link OutputStream} using the {@code position} and
+     * {@code length}. The position and limit of the given {@link ByteBuffer} may be adjusted.
+     */
+    static void readBytes(ByteBuffer buffer, int position, int length, OutputStream out) throws IOException {
+        if (buffer.hasArray()) {
+            out.write(buffer.array(), position + buffer.arrayOffset(), length);
+        } else {
+            byte[] tmp = new byte[Math.min(length, WRITE_CHUNK_SIZE)];
```
Comment (CodingFabian) [inline buffer/src/main/java/io/netty/buffer/ByteBufUtil.java]: so you decided against using alloc() to get this temp array?

Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/ByteBufUtil.java]: let me check if its possible here as well (in the `Unsafe` portion it is.

Comment (normanmaurer) [reply buffer/src/main/java/io/netty/buffer/ByteBufUtil.java]: fixed @CodingFabian
