### PR TITLE
Preserve order when using alternate event loops

### LINKED ISSUE #10067: HttpContentCompressor doesn't work when put on an alternate EventExecutor
### Expected behavior

The following isn't expected to mangle or lose the response content:

    pipeline.addLast(eventExecutor, new HttpContentCompressor());

### Actual behavior

The content may be mangled or completely lost.

### Steps to reproduce

`                        .addLast(compressorGroup, new HttpContentCompressor())`

### Minimal yet complete reproducer code (or URL to code)

https://github.com/atcurtis/netty/blob/e8dd352c8d17943df310ba1371329c0990e5bbb9/codec-http/src/test/java/io/netty/handler/codec/http/HttpContentCompressorTest.java#L281

### Netty version

I checked 4.1.42.Final and 4.1.46.Final

### JVM version (e.g. `java -version`)

Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
 3.10.0-957.21.3.el7.x86_64

### PR DESCRIPTION
**Pull request by atcurtis**
When the HttpContentCompressor is put on an alternate EventExecutor, the order of events should be
preserved so that the compressed content is correctly created. This is done by checking that
the executor in the ChannelHandlerContext is the same executor as the current executor when
evaluating if the handler should be skipped.

Motivation:

HttpContentCompressor shouldn't mangle the content when it is put on an alternate EventExecutor

Modification:

Describe the modifications you've done.

Checked the executor when examining if the handler could be skipped.

Result:

Fixes #10067

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@atcurtis please fix class cast exception.

File: transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java [hunk 1]
```diff
@@ -906,17 +906,21 @@ private boolean isNotValidPromise(ChannelPromise promise, boolean allowVoidPromi
...
     }
 
     private AbstractChannelHandlerContext findContextOutbound(int mask) {
         AbstractChannelHandlerContext ctx = this;
+        EventExecutor currentExecutor = executor();
         do {
             ctx = ctx.prev;
-        } while ((ctx.executionMask & mask) == 0);
+        } while (!ChannelHandlerMask.isOutbound(ctx.executionMask)
+            || (ctx.executionMask & mask) == 0 && ctx.executor() == currentExecutor);
```
Comment (normanmaurer) [inline transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java]: this is not correct (and also not the one above) as you will cause a `ClassCastException` later on if the `ChannelHandlerContext` does not wrap an `ChannelOutboundHandler`.

**Comment by atcurtis** [comment]
There's a negation in front of the isOutbound.
Perhaps I should change the method to isNotOutbound and remove the negation.

**Comment by normanmaurer** [comment]
@atcurtis see the test failures

**Comment by atcurtis** [comment]
Okay... I'll run all tests. (I admit I haven't yet)

**Comment by normanmaurer** [comment]
@atcurtis please check my latest commit here... this should fix it.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by atcurtis** [comment]
@normanmaurer  Oops, I didn't see that you had pushed your version... sorry!

comparing, your's looks cleaner.

**Comment by normanmaurer** [comment]
@atcurtis will squash our commits and merge... Thanks for the help!

**Comment by normanmaurer** [comment]
@netty-bot test this please
