### PR TITLE
Fix: Make ByteToMessageDecoder not call read() in channelReadComplete, if no channelRead fired.

### LINKED ISSUE #11965: WebSocket server loss one frame, maybe caused by ByteToMessageDecoder trigger a unexpected read() when readCompleted fired
We're creating a relay-like application with WebSocket. When the WebSocket client sends an upgrade request to the server, the server sets the channel's autoRead to false (or config child channel autoRead to false, and manually trigger first read()). When the upstream connection is ready (which is started by another type of client), and the relay handler would be ok, set autoRead to true.

### Expected behavior
No `channelRead` fired after setting autoRead to false

### Actual behavior
A frame was read and then discard in TailContext

### Steps to reproduce

See the following junit test:
1. start testWebsocketServer
2. start testWebsocketServerClient
3. watch the server's log
```
18:46:25.176 [nioEventLoopGroup-2-1] DEBUG i.n.channel.DefaultChannelPipeline - Discarded inbound message TextWebSocketFrame(data: PooledUnsafeDirectByteBuf(ridx: 0, widx: 7, cap: 7)) that reached at the tail of the pipeline. Please check your pipeline configuration.
18:46:25.176 [nioEventLoopGroup-2-1] DEBUG i.n.channel.DefaultChannelPipeline - Discarded message pipeline : [wsencoder, wsdecoder, io.netty.handler.codec.http.websocketx.Utf8FrameValidator, WebSocketServerProtocolHandler#0, DefaultChannelPipeline$TailContext#0]. Channel : [id: 0xc1bcc332, L:/127.0.0.1:8100 - R:/127.0.0.1:64710].
18:46:27.149 [nioEventLoopGroup-2-1] INFO  com.example.alexlx.WebSocketTest - read: hello 1
18:46:27.179 [nioEventLoopGroup-2-1] INFO  com.example.alexlx.WebSocketTest - read: hello 2
```

### Minimal yet complete reproducer code (or URL to code)

```java
package com.example.alexlx;

import io.netty.bootstrap.Bootstrap;
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.http.HttpClientCodec;
import io.netty.handler.codec.http.HttpObjectAggregator;
import io.netty.handler.codec.http.HttpServerCodec;
import io.netty.handler.codec.http.websocketx.TextWebSocketFrame;
import io.netty.handler.codec.http.websocketx.WebSocketClientProtocolConfig;
import io.netty.handler.codec.http.websocketx.WebSocketClientProtocolHandler;
import io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.TimeUnit;


public class WebSocketTest {
    private static final Logger log = LoggerFactory.getLogger(WebSocketTest.class);
    @Test
    public void testWebsocketServer() {
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        new ServerBootstrap()
                .group(group)
                .channel(NioServerSocketChannel.class)
                .childOption(ChannelOption.AUTO_READ, false)
                .childHandler(new ChannelInitializer<Channel>() {
                    @Override
                    protected void initChannel(Channel ch) throws Exception {
                        ChannelPipeline p = ch.pipeline();
                        p.addLast(
                                new HttpServerCodec(),
                                new HttpObjectAggregator(1024 * 1024),
                                new WebSocketServerProtocolHandler("/ws"),
                                new SimpleUserEventChannelHandler<WebSocketServerProtocolHandler.HandshakeComplete>() {
                                    @Override
                                    protected void eventReceived(ChannelHandlerContext ctx, WebSocketServerProtocolHandler.HandshakeComplete evt) throws Exception {
                                        log.info("handshake {}", evt);
                                        ctx.pipeline().remove(this);
                                        // Simulate the relay connection established in 3 seconds
                                        ctx.executor().schedule(
                                                new Runnable() {
                                                    @Override
                                                    public void run() {
                                                        ctx.channel().config().setAutoRead(true);
                                                        ctx.pipeline().addLast(new SimpleChannelInboundHandler<TextWebSocketFrame>() {
                                                            @Override
                                                            protected void channelRead0(ChannelHandlerContext ctx, TextWebSocketFrame msg) throws Exception {
                                                                log.info("read: " + msg.text());
                                                            }
                                                        });
                                                    }
                                                },
                                                3, TimeUnit.SECONDS
                                        );
                                    }
                                }
                        );
                        ch.read();

                    }
                })
                .bind(8100).syncUninterruptibly().channel().closeFuture().syncUninterruptibly();
    }

    @Test
    public void testWebsocketServerClient() {
        new Bootstrap()
                .group(new NioEventLoopGroup(1))
                .channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<Channel>() {
                    @Override
                    protected void initChannel(Channel ch) throws Exception {
                        ch.pipeline().addLast(
                                new HttpClientCodec(),
                                new HttpObjectAggregator(1024 * 1024),
                                new WebSocketClientProtocolHandler(
                                        WebSocketClientProtocolConfig.newBuilder()
                                                .webSocketUri("ws://127.0.0.1:8100/ws")
                                                .build()),
                                new SimpleUserEventChannelHandler<WebSocketClientProtocolHandler.ClientHandshakeStateEvent>() {
                                    @Override
                                    protected void eventReceived(ChannelHandlerContext ctx, WebSocketClientProtocolHandler.ClientHandshakeStateEvent evt) throws Exception {
                                        if (evt == WebSocketClientProtocolHandler.ClientHandshakeStateEvent.HANDSHAKE_COMPLETE) {
                                            log.info("HANDSHAKE_COMPLETE");
                                            ctx.channel().eventLoop()
                                                    .scheduleAtFixedRate(new Runnable() {
                                                        int i = 0;
                                                        @Override
                                                        public void run() {
                                                            log.info("write {}, writable={}", i, ch.isWritable());
                                                            ch.writeAndFlush(new TextWebSocketFrame("hello " + (i++)));
                                                            if (i >= 10) {
                                                                ctx.close();
                                                            }
                                                        }
                                                    }, 1, 1, TimeUnit.SECONDS);
                                        }
                                    }
                                }
                        );
                    }
                })
                .connect("127.0.0.1", 8100)
                .syncUninterruptibly()
                .channel().closeFuture().syncUninterruptibly();
    }
}
```

### Netty version
4.1.52
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
windows 10 or mac os x 10.14

### PR DESCRIPTION
**Pull request by alex-lx**
Motivation:

When ByteToMessageDecoder added in channelRead(), the following channelReadComplete() will lead ByteToMessageDecoder to call a read(),
which is not expected.

Modifications:

Add a field variable tracking the state of if ByteToMessageDecoder.channelRead() is fired after the handler is added. And if it was NOT fired, then the next channelReadComplete() would not call read()

Result:

ByteToMessageDecoder will no longer call read() in channelReadComplete() if no channelRead() fired.

Fixes #11965

### CODE REVIEW

**Comment by normanmaurer** [comment]
@alex-lx did you sign our icla yet ?

https://netty.io/s/icla

File: codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java [hunk 1]
```diff
@@ -162,6 +162,8 @@ public ByteBuf cumulate(ByteBufAllocator alloc, ByteBuf cumulation, ByteBuf in)
      */
     private boolean firedChannelRead;
 
+    private boolean selfFiredChannelRead = false;
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java:165]:
```suggestion
    private boolean selfFiredChannelRead;
```

File: codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java [hunk 2]
```diff
@@ -531,6 +534,11 @@ protected void decodeLast(ChannelHandlerContext ctx, ByteBuf in, List<Object> ou
         }
     }
 
+    @Override
+    public void handlerAdded(ChannelHandlerContext ctx) throws Exception {
+        selfFiredChannelRead = false;
+    }
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java:540]: This is not needed at all. Please remove

File: codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java [hunk 3]
```diff
@@ -538,4 +540,24 @@ protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) {
...
+                interceptor,
+                new SimpleChannelInboundHandler<ByteBuf>() {
+                    @Override
+                    protected void channelRead0(ChannelHandlerContext ctx, ByteBuf msg) throws Exception {
+                        ctx.pipeline().replace(this, "fix", new FixedLengthFrameDecoder(3));
+                    }
+                }
+        );
+
+        channel.writeInbound(Unpooled.wrappedBuffer(new byte[]{1}));
```
Comment (normanmaurer) [inline codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java:559]:
```suggestion
        assertFalse(channel.writeInbound(Unpooled.wrappedBuffer(new byte[]{1})));
```

File: codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java [hunk 4]
```diff
@@ -538,4 +540,24 @@ protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) {
...
+        assertEquals(0, interceptor.readsTriggered);
```
Comment (normanmaurer) [inline codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java:560]:
```suggestion
        assertEquals(0, interceptor.readsTriggered);
        assertNotNull(channel.pipeline().get(FixedLengthFrameDecoder.class));
        assertFalse(channel.finish());
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java (hunk 2 above)
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java:540]:
```suggestion
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java [hunk 5]
```diff
@@ -538,4 +540,26 @@ protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) {
...
+                        ctx.pipeline().replace(this, "fix", new FixedLengthFrameDecoder(3));
+                    }
+                }
+        );
+
+        assertFalse(channel.writeInbound(Unpooled.wrappedBuffer(new byte[]{1})));
+        assertEquals(0, interceptor.readsTriggered);
+        assertNotNull(channel.pipeline().get(FixedLengthFrameDecoder.class));
+        assertFalse(channel.finish());
+
```
Comment (normanmaurer) [inline codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java:563]:
```suggestion
```

File: codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java [hunk 6]
```diff
@@ -531,6 +534,8 @@ protected void decodeLast(ChannelHandlerContext ctx, ByteBuf in, List<Object> ou
         }
     }
 
+    @Override
+
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java:538]:
```suggestion
```

File: codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java [hunk 7]
```diff
@@ -434,17 +435,18 @@ public CompositeByteBuf addFlattenedComponents(boolean increaseWriterIndex, Byte
         }
     }
 
-    @Test
-    public void testDoesNotOverRead() {
-        class ReadInterceptingHandler extends ChannelOutboundHandlerAdapter {
-            private int readsTriggered;
+    private static class ReadInterceptingHandler extends ChannelOutboundHandlerAdapter {
```
Comment (normanmaurer) [inline codec/src/test/java/io/netty/handler/codec/ByteToMessageDecoderTest.java:438]:
```suggestion
    private static final class ReadInterceptingHandler extends ChannelOutboundHandlerAdapter {
```

**Review by normanmaurer — APPROVED** [review]

**Comment by alex-lx** [comment]
> @alex-lx did you sign our icla yet ?
> 
> https://netty.io/s/icla

Done

**Comment by normanmaurer** [comment]
@alex-lx thanks a lot!

**Comment by violetagg** [comment]
@normanmaurer @alex-lx With this PR I'm see an issue with missing `read`. (I'm trying to isolate a test case with vanilla Netty)
The stack is:

```
	at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelReadComplete(CombinedChannelDuplexHandler.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:336)
	at io.netty.channel.CombinedChannelDuplexHandler.channelReadComplete(CombinedChannelDuplexHandler.java:261)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
	at io.netty.handler.logging.LoggingHandler.channelReadComplete(LoggingHandler.java:272)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:390)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1415)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:397)
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:171)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by normanmaurer** [comment]
@violetagg keep me posted

**Comment by violetagg** [comment]
@normanmaurer I'm able to reproduce it with a small change in the Netty examples

https://github.com/violetagg/netty/commit/1ccbd2dfa5978720c5492f6fd9bb6678d2ce3312

1. Start WebSocketServer
2. Start WebSocketClient
3. In the `WebSocketClient` console type `test` for example. You will see that the client is able to receive the close frame.

```
WebSocket Client connected!
test
WebSocket Client received closing
WebSocket Client disconnected!
```

Now revert the changes in `ByteToMessageDecoder` and execute the same scenario. You should be able to see that the client hangs.

```
WebSocket Client connected!
test
```

**Comment by alex-lx** [comment]
Hi, @violetagg. The future that `WebSocketClientHandshaker#handshake(io.netty.channel.Channel)` returns is resolved after the upgrade request was sent, so the `channel.read()` would just read the handshake's response instead of the websocket frame.
```java
    @Override
    public void channelActive(ChannelHandlerContext ctx) {
        final Channel channel = ctx.channel();
        handshaker.handshake(channel)
                .addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(ChannelFuture future) {
                        // At this moment, the client has just sent the upgrade request, and is waiting server's handshake response.
                        channel.read();
                    }
                });
    }
```
```java
    @Override
    public void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
        Channel ch = ctx.channel();
        if (!handshaker.isHandshakeComplete()) {
            try {
                handshaker.finishHandshake(ch, (FullHttpResponse) msg);
                System.out.println("WebSocket Client connected!");
                // At this moment, the handshake is completed, than we can begin read the websocket frame here
                ch.read();
                handshakeFuture.setSuccess();
            } catch (WebSocketHandshakeException e) {
                System.out.println("WebSocket Client failed to connect");
                handshakeFuture.setFailure(e);
            }
            return;
        }
```

**Comment by violetagg** [comment]
yeah ... I understand ... this is kind of a change in the behaviour

Anyway I added addition read invocations on my side and now my scenario is working again.

**Comment by normanmaurer** [comment]
@violetagg yes it is but I think it is more correct. WDYT ?

**Comment by violetagg** [comment]
yeah go for it
