### PR TITLE
Http types slow path checks (Fixes #13268) 

### LINKED ISSUE #13268: Http types slow path checks
https://github.com/TechEmpower/FrameworkBenchmarks/pull/7942 and https://github.com/quarkusio/quarkus/issues/31716 reports 2 types of problems that can be mostly addressed within Netty itself:
- the former, related http encoders/decoders which accept concrete types with NOT implement specific interfaces
- the latter, related `WebSocketServerExtensionHandler` doing the same for both read/write events

In short, the problem, although can become a scalability bottleneck too (more on this later) as https://bugs.openjdk.org/browse/JDK-8180450 is first an efficiency issue dependent by the type check of a concrete type that doesn't implement a given interface type: according to https://github.com/openjdk/jdk11/blob/37115c8ea4aff13a8148ee2b8832b20888a5d880/src/hotspot/cpu/x86/macroAssembler_x86.cpp#L5514 this will cause a wasteful O(n) search among the implemented interfaces per check.
There are cases that can be solved by using type check against class types or failing fast thanks to singleton(s), known instance refs e.g. empty buffers, etc etc.

Similarly to https://bugs.openjdk.org/browse/JDK-8180450 falling into the interface slow path type check confuse profilers enough to not make profiling useful in any form to detect such issues and manual inspection of ASM is still the preferred choice to find performance deficiencies like these (more on this at https://github.com/async-profiler/async-profiler/issues/673 and https://redhatperf.github.io/post/type-check-scalability-issue/).

### PR DESCRIPTION
**Pull request by franz1981**
Motivation:

Http encoders/decoders and websocket handlers perform slow type checks
i.e. O(N) search among all implemented interfaces for non-implemented interfaces.

Modifications:

Perform instance exact matches and/or class type check vs common used types, while exposing
unstable APIs to allow users to do the same, if necessary.

Result:

Better performance of Http pipeline with/without websocket handler.
Fixes https://github.com/netty/netty/issues/13261

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpRequestDecoder.java [hunk 1]
```diff
@@ -301,4 +301,15 @@ protected HttpMessage createInvalidMessage() {
     protected boolean isDecodingRequest() {
         return true;
     }
+
+    @Override
+    protected boolean isContentAlwaysEmpty(final HttpMessage msg) {
+        // fast-path to save expensive O(n) checks; users can override createMessage
+        // and extends DefaultHttpRequest making implementing HttpResponse:
+        // this is why we cannot use instanceof DefaultHttpRequest here :(
+        if (msg.getClass() == DefaultHttpRequest.class) {
```
Comment (franz1981) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpRequestDecoder.java:310]: @normanmaurer 
It's not nice, but it would save the common path (not overridden `createMessage`) to be super fast. without checking the slow path (not implemented `HttoResponse` type check)

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseEncoder.java [hunk 2]
```diff
@@ -28,6 +28,10 @@ public class HttpResponseEncoder extends HttpObjectEncoder<HttpResponse> {
 
     @Override
     public boolean acceptOutboundMessage(Object msg) throws Exception {
+        // common fast path
+        if (msg.getClass() == DefaultFullHttpResponse.class) {
```
Comment (franz1981) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseEncoder.java:32]: @normanmaurer 
This is rather uncomplete: `HttpResponseEncoder` should check against many concrete types that can be produced by users (almost all default http types, including content(s)), but this one is a widely adopted one, hence should be enough.

Users not satisfied can still override this method and provide the checks based on the types they believe are more common among their users (including custom types). wdyt?

Comment (franz1981) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseEncoder.java:32]: @slandelle I haven't implemented many of the HTTP optimizations for clients, but should be trivial to add them and benchmark them based on micros similar to the one I'm attaching to this PR; feel free to open a PR to fix it

**Comment by franz1981** [comment]
The changes on `WebSocketServerExtensionHandler` enabling user code to optimize their own check require some attention, IMO

**Comment by franz1981** [comment]
IN term of performance improvement, the micros reports...
Without 6e1558f2390f95aebad5dbc17ca67dd5140ce722:
```
Benchmark                                  (websocket)   Mode  Cnt       Score       Error  Units
HttpRequestResponseBenchmark.netty                true  thrpt   20  747540.482 ±  5546.911  ops/s
HttpRequestResponseBenchmark.netty               false  thrpt   20  830114.142 ± 18724.768  ops/s
```
With 6e1558f2390f95aebad5dbc17ca67dd5140ce722:
```
Benchmark                                  (websocket)   Mode  Cnt       Score      Error  Units
HttpRequestResponseBenchmark.netty                true  thrpt   20  854429.400 ± 4088.882  ops/s
HttpRequestResponseBenchmark.netty               false  thrpt   20  888279.220 ± 6643.213  ops/s
```
that shows an improvement both with/without websocket handlers, as stated in the commit description.

**Comment by franz1981** [comment]
Done @chrisvest let me know if the code paths I've commented myself seems ok to you

File: microbench/src/main/java/io/netty/microbench/http/HttpRequestResponseBenchmark.java [hunk 3]
```diff
@@ -0,0 +1,274 @@
...
+            }
+        }
+
+        @Override
+        public ByteBuf buffer(int initialCapacity, int maxCapacity) {
+            if (initialCapacity <= capacity) {
+                return buffer();
+            } else {
+                throw new IllegalArgumentException();
+            }
```
Comment (normanmaurer) [inline microbench/src/main/java/io/netty/microbench/http/HttpRequestResponseBenchmark.java:97]:
```suggestion
            }
            throw new IllegalArgumentException();
```

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseEncoder.java (hunk 2 above)
Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseEncoder.java:32]: Can you extend the comment a bit to include the reason you outlined here ?

**Comment by franz1981** [comment]
@normanmaurer @trustin added the comments as requested:sorry for the delay and the bad coding :"( 
Sadly, differently from https://bugs.openjdk.org/browse/JDK-8180450 this perf issue won't be solved on OpenJDK (probably Graal uses a different implementation for type checks vs non implemented interfaces) and it affects performance (as benchs shows).

**Comment by franz1981** [comment]
@chrisvest addressed all the comments: I'm still quite unhappy about the changes, but I have no other solution to the slow path problem

**Review by chrisvest — APPROVED** [review]

**Comment by chrisvest** [comment]
@franz1981 Thanks!

Do you have plans for making similar PRs for Netty 5? I assume the type profiles will have to be looked at again to see what checks are potential hot spots.
