### PR TITLE
Fixed illegal reflective access by not relying on a sun.net.dns class. (#8318)

### LINKED ISSUE #8318: Illegal reflective access using Netty with Java 11
### Expected behavior
No warning about illegal reflective access.

### Actual behavior
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.resolver.dns.DnsNameResolver (file:/home/gamer/runner/lib/netty-resolver-dns-4.1.29.Final.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of io.netty.resolver.dns.DnsNameResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Steps to reproduce
Run any code that references the `DnsNameResolver` class.

### Minimal yet complete reproducer code
```
new DnsNameResolverBuilder();
```

### Netty version
4.1.29.Final

### JVM version (e.g. `java -version`)
```
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

### OS version (e.g. `uname -a`)
```
Linux ip-172-31-1-18 4.14.51-60.38.amzn1.x86_64 #1 SMP Tue Jun 26 23:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by mattayres**
### Motivation
Applications should not depend on internal packages with Java 9 and later. This cause a warning now, but will break in future versions of Java.

### Modification
This change adds methods to `UnixResolverDnsServerAddressStreamProvider` (following after #6844) that parse `/etc/resolv.conf` for `domain` and `search` entries. Then `DnsNameResolver` does not need to rely on `sun.net.dns.ResolverConfiguration` to do this.

### Result
Fixes #8318. Furthermore, at least in my testing with Java 11, this also makes multiple `search` entries work properly (previously I was only getting the first entry).

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java [hunk 1]
```diff
@@ -125,13 +125,7 @@
...
         String[] searchDomains;
         try {
-            Class<?> configClass = Class.forName("sun.net.dns.ResolverConfiguration");
-            Method open = configClass.getMethod("open");
-            Method nameservers = configClass.getMethod("searchlist");
-            Object instance = open.invoke(null);
-
-            @SuppressWarnings("unchecked")
-            List<String> list = (List<String>) nameservers.invoke(instance);
+            List<String> list = UnixResolverDnsServerAddressStreamProvider.parseEtcResolverSearchDomains();
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java]: @mattayres What about non unix like systems (for example windows) ?  Maybe we can use `PlatformDependent.isWindows()` and only use this if it returns false ?

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@mattayres can you sign our ICLA and ping me once done:

https://netty.io/s/icla

**Comment by mattayres** [comment]
@normanmaurer signed ICLA.

**Comment by normanmaurer** [comment]
@mattayres thanks!
