### PR TITLE
Asynchronously close pools in AbstractChannelPoolMap (#8238)

### LINKED ISSUE #8238: FixedChannelPool.close deadlock
This bug was discovered during testing Netty as both server and client sharing the same worker EventLoopGroup. The Netty client used AbstractChannelPoolMap with FixedChannelPool with persistent HTTP/1.1 connections.

During the test we saw an increasing number of not closed sockets for connections closed by the remote side. We discovered that the Netty client was blocking I/O threads that kept receiving new server connections, but haven't had chance to react on the remote close and to close the sockets.

The problem was traced back to a commit made for 4.1.26 Final https://github.com/netty/netty/commit/583fc272f26373ff5f51c0871d9730370cd39a3e that changed FixedChannelPool.close to a blocking call. The close operation is also called from AbstractChannelPoolMap.get when a new pool is not needed and being closed. Since we shared EventLoops between server and client, ChannelPoolMap.get was triggered from an I/O thread based on a request accepted by the server side and entered the blockin close, which was waiting for another I/O thread to complete the close, however the other thread was doing the same and multiple threads ended up in a deadlock situation.

An example scenario:

1.
Thread A1 calls ChannelPoolMap.get(A)
Thread A2 calls ChannelPoolMap.get(A)
Thread B1 calls ChannelPoolMap.get(B)
Thread B2 calls ChannelPoolMap.get(B)

2.
Thread A1 gets a new pool on eventexecutor thread X1 (anywhere but A2 or B2)
Thread B1 gets a new pool on eventexecutor thread X2 (anywhere but A2 or B2)
Thread A2 gets a new pool on eventexecutor thread B2
Thread B2 gets a new pool on eventexecutor thread A2

3.
Thread A1 succeeds on updating the map and moves on
Thread B1 succeeds on updating the map and moves on
Thread A2 fails to update the map and submits blocking close to thread B2
Thread B2 fails to update the map and submits blocking close to thread A2

At this point Threads A2 and B2 are in a deadlock situation

### Expected behavior

FixedChannelPool.close does not enter a blocking wait for other thread.

### Actual behavior

FixedChannelPool.close enters a blocking wait for an other thread which might be entering a wait for this thread and end up deadlocking each other.

### Steps to reproduce

Please see the reproducer code.

### Minimal yet complete reproducer code (or URL to code)

I have added barriers to ensure both eventloops are executing the tasks before executing the close, but I could quite reliably reproduce even without the barrier. Running both close operations on the same pool or each on their own works as expected, the problem is only when they get executed on the other pool's loop.

```java
import io.netty.bootstrap.Bootstrap;
import io.netty.channel.Channel;
import io.netty.channel.DefaultEventLoop;
import io.netty.channel.EventLoop;
import io.netty.channel.local.LocalAddress;
import io.netty.channel.local.LocalChannel;
import io.netty.channel.pool.AbstractChannelPoolHandler;
import io.netty.channel.pool.ChannelPool;
import io.netty.channel.pool.ChannelPoolHandler;
import io.netty.channel.pool.FixedChannelPool;
import io.netty.util.concurrent.Future;
import org.junit.Test;

import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

public class FixedChannelPoolDeadlockTest {

    @Test
    public void testFixedChannelDeadlock() throws Exception {
        EventLoop eventloop1 = new DefaultEventLoop();
        Bootstrap bootstrap1 = new Bootstrap()
                .channel(LocalChannel.class)
                .group(eventloop1)
                .localAddress(new LocalAddress("#1"));

        EventLoop eventloop2 = new DefaultEventLoop();
        Bootstrap bootstrap2 = new Bootstrap()
                .channel(LocalChannel.class)
                .group(eventloop2)
                .localAddress(new LocalAddress("#2"));

        ChannelPoolHandler handler = new AbstractChannelPoolHandler() {
            public void channelCreated(Channel ch) throws Exception {}
        };

        // assign eventloop1 to pool1 and eventloop2 to pool2
        final ChannelPool pool1 = new FixedChannelPool(bootstrap1, handler, 1);
        final ChannelPool pool2 = new FixedChannelPool(bootstrap2, handler, 1);

        // make sure both tasks are entered
        CyclicBarrier barrier = new CyclicBarrier(2);

        // execute pool1.close from eventloop2 and pool2.close from eventloop1
        Future<?> closeFuture1 = eventloop2.submit(() -> closePool(barrier, pool1));
        Future<?> closeFuture2 = eventloop1.submit(() -> closePool(barrier, pool2));

        try {
            // The expected scenario is that both pools close,
            // but instead they block each other and the below times out
            closeFuture1.get(1, TimeUnit.SECONDS);
            closeFuture2.get(1, TimeUnit.SECONDS);
        } catch (TimeoutException e) {
            // Fail the test on timeout to distinguish from other errors
            throw new AssertionError(e);
        } finally {
            eventloop1.shutdownGracefully(0, 0, TimeUnit.SECONDS);
            eventloop2.shutdownGracefully(0, 0, TimeUnit.SECONDS);
        }
    }

    private void closePool(CyclicBarrier barrier, ChannelPool pool) {
        try {
            barrier.await(100, TimeUnit.MILLISECONDS);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        pool.close();
    }

}
```

### Netty version

4.1.26 Final
4.1.27 Final
4.1.28 Final
4.1.29 Final

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)

Linux 3.2.50

### PR DESCRIPTION
**Pull request by mihalyr**
Motivation:

In certain scenarios mutliple concurrent AbstractChannelPoolMap
operations might be called from event loops that handle also
ChannelPool close operations. If the map uses synchronous close
it could end up blocking the event loop and if multiple threads
are waiting for each other a deadlock might occur.

Modifications:

Previously #9226 introduced a closeAsync operation for
FixedChannelPool, which is now extended to the ChannelPool interface.
The AbstractChannelPoolMap now uses the closeAsync operations when
closing redundant or removed ChannelPool instances.

Result:

The AbstractChannelPoolMap get/remove operations will not wait
until the pools are closed as they will happen asynchronously and
avoid situations that could cause the event loop being blocked in
deadlocks.

Fixes #8238

### CODE REVIEW

File: transport/src/main/java/io/netty/channel/pool/ChannelPool.java [hunk 1]
```diff
@@ -58,4 +58,11 @@
 
     @Override
     void close();
+
+    /**
+     * Closes the pool in an async manner.
+     *
+     * @return Future which represents completion of the close task
+     */
+    Future<Void> closeAsync();
```
Comment (normanmaurer) [inline transport/src/main/java/io/netty/channel/pool/ChannelPool.java]: Unfortunately we can not do this as this would be an API breaking change.

**Comment by mihalyr** [comment]
Ah right, and no default methods either here. I have pushed a new revision without the API change and checking for the implementation in the pool map, it's not ideal, but would work here.

Other thing I can think of ritght now without a breaking change would be adding new interfaces for the pools that support async pool close operations e.g.:
- Adding a new AsyncChannelPool interface with close methods returning futures, with AsyncChannelPoolMap with potentially async get/remove methods for the new AsyncChannelPools...

Not sure if these would be of any help here right now. I think an API change might be needed for a better solution. The root of the problem is that the current AbstractChannelPoolMap is not EventLoop "friendly" in the sense it can block and under high concurrency cause deadlocks and crashes. 

In our original case this happened all the time in the message splitter/router that got a message on an eventloop thread and then used a channelpoolmap from that thread to get the channels to write the outbound messages to. The quick fix on our side at the time was to create or own version of FixedChannelPool with an asynchronous close operation.

I'm not working on the project anymore and not using Netty these days, but have a little time to work on this if we can find a suitable solution.

File: transport/src/main/java/io/netty/channel/pool/ChannelPool.java (hunk 1 above)
Comment (mihalyr) [reply transport/src/main/java/io/netty/channel/pool/ChannelPool.java]: Pushed new revision without the interface change

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@mihalyr thanks a lot!

**Comment by sherman** [comment]
Hi, guys!

Seems, the problem is still exists (Netty version is 4.1.49).
So, I have an event loop group (AnotherTestPool). I have some code which is used it, under the hood.
When the AbstractChannelPoolMap.close() method is called often (cycle open/do smth/close) from the _same_ pool, I still have a deadlock. See the following thread dump.

```
"AnotherTestPool-3-2" #17 prio=5 os_prio=0 cpu=42.68ms elapsed=19.40s tid=0x00007febd5455800 nid=0x64b9 in Object.wait()  [0x00007feb598db000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.2/Native Method)
	- waiting on <0x000000071a4717b0> (a io.netty.util.concurrent.DefaultPromise)
	at java.lang.Object.wait(java.base@11.0.2/Object.java:328)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:274)
	- waiting to re-lock in wait() <0x000000071a4717b0> (a io.netty.util.concurrent.DefaultPromise)
	at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:410)
	at io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:35)
	at io.netty.channel.pool.AbstractChannelPoolMap.close(AbstractChannelPoolMap.java:150)
	at ru.yandex.misc.http.client.EventLoopAwareChannelPool.close(EventLoopAwareChannelPool.java:58)
	at ru.yandex.misc.http.client.HttpClient.close(HttpClient.java:338)
	at ru.yandex.yql.core.clusters.clients.clickhouse.ClickHouseClusterClientTest.lambda$executeQuery$1(ClickHouseClusterClientTest.java:251)
	at ru.yandex.yql.core.clusters.clients.clickhouse.ClickHouseClusterClientTest$$Lambda$127/0x0000000800363840.run(Unknown Source)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)


"globalEventExecutor-2-1" #18 prio=5 os_prio=0 cpu=3.16ms elapsed=19.39s tid=0x00007feb38002000 nid=0x64ba in Object.wait()  [0x00007feb597da000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.2/Native Method)
	- waiting on <0x000000071a4d6d30> (a io.netty.channel.DefaultChannelPromise)
	at java.lang.Object.wait(java.base@11.0.2/Object.java:328)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:274)
	- waiting to re-lock in wait() <0x000000071a4d6d30> (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
	at io.netty.channel.pool.SimpleChannelPool.close(SimpleChannelPool.java:402)
	at io.netty.channel.pool.SimpleChannelPool$8.call(SimpleChannelPool.java:416)
	at io.netty.channel.pool.SimpleChannelPool$8.call(SimpleChannelPool.java:413)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:96)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:243)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)
```

If I move the call of close() method to another thread pool, everything is working fine.
