### PR TITLE
Snappy: Use unsigned short to handle 2 ^ 16 input size instead of 2 ^ 15

### LINKED ISSUE #13226: Snappy compressor can't compress more than 32767 bytes
### Expected behavior
I expect the Snappy compressor to be able to compress a much larger amount than 32767 bytes.
### Actual behavior
An exception is thrown if the data is too large.
### Steps to reproduce
Try to compress a ByteBuf larger than 32767 bytes using the Snappy.encode method.
### Minimal yet complete reproducer code (or URL to code)
```java
public static void main(String[] args) {
    final byte[] random = new byte[40_000];
    ThreadLocalRandom.current().nextBytes(random);
    { // This should work
        final Snappy snappy = new Snappy();
        final ByteBuf data = Unpooled.wrappedBuffer(Arrays.copyOfRange(random, 0, 32767));
        final ByteBuf out = Unpooled.buffer();
        snappy.encode(data, out, data.readableBytes());
    }
    { // This does not work
        final Snappy snappy = new Snappy();
        final ByteBuf data = Unpooled.wrappedBuffer(random);
        final ByteBuf out = Unpooled.buffer();
        snappy.encode(data, out, data.readableBytes());
    }
}
```
### Netty version
4.1.89
### JVM version (e.g. `java -version`)
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
### OS version (e.g. `uname -a`)
Windows 10 x64 22H2 19045.2546

### PR DESCRIPTION
**Pull request by lucamolteni**
https://github.com/netty/netty/issues/13226

- Avoid iterating to create correct size hash table (limited to MAX_HT_SIZE)
- Configurable snappy frame size for the encoder
- Added static factory method for SnappyEncoder supporting 2 ^ 16 size frame slices
- Added integration test

Motivation:

See the attached issue

Modification:

Unsigned short casting

Result:

Fixes #13226 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by franz1981** [comment]
Thanks for the contribution :) 

The fix here look sound, let's see if the CI complains about changed in some public API or not and we can find a solution to that :+1:

File: codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameEncoder.java [hunk 1]
```diff
@@ -42,8 +50,21 @@ public class SnappyFrameEncoder extends MessageToByteEncoder<ByteBuf> {
         (byte) 0xff, 0x06, 0x00, 0x00, 0x73, 0x4e, 0x61, 0x50, 0x70, 0x59
     };
 
+    public SnappyFrameEncoder() {
+        this.sliceSize = SNAPPY_SLICE_SIZE;
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameEncoder.java:54]: nit:

```suggestion
        this(SNAPPY_SLICE_SIZE);
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]
just a nit... rest looks good to me

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec/src/main/java/io/netty/handler/codec/compression/Snappy.java [hunk 2]
```diff
@@ -16,6 +16,7 @@
 package io.netty.handler.codec.compression;
 
 import io.netty.buffer.ByteBuf;
+import org.jctools.util.Pow2;
```
[the remark this answers is not in the document]
Comment (franz1981) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java:19]: Copy code or we could do something to enforce the ci to fail if that happen again?

[the remark this answers is not in the document]
Comment (lucamolteni) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java]: I'll take a look at how to enforce it - also it seems like IntelliJ IDEA doesn't resolve shaded classes correctly due to https://youtrack.jetbrains.com/issue/IDEA-93855

File: codec/src/main/java/io/netty/handler/codec/compression/Snappy.java [hunk 3]
```diff
@@ -16,6 +16,7 @@
 package io.netty.handler.codec.compression;
 
 import io.netty.buffer.ByteBuf;
+import io.netty.util.internal.shaded.org.jctools.util.Pow2;
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/Snappy.java:19]: maybe we could also expose this via `PlatformDependent` and so remove the whole import of a shaded class here

Comment (lucamolteni) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java:19]: Tell me what you prefer, if we want to use the shaded jar then this fix provided [here](https://youtrack.jetbrains.com/issue/IDEA-93855/Please-add-support-for-maven-shade-plugin-renaming#focus=Comments-27-6055272.0-0) works

Comment (normanmaurer) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java:19]: I think I would add it to either PlatformDepend or MathUtil

Comment (lucamolteni) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java]: I've just realised there's already that method in MathUtill.findNextPositivePowerOfTwo 

let me use that

Comment (franz1981) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java]: https://github.com/netty/netty/blob/14e00f50d13d112a1a7a8eaa693c2363adeee629/common/src/main/java/io/netty/util/HashedWheelTimer.java#L337

at this point worth (or not?) changing this as well?

Comment (normanmaurer) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java]: yes... just lets use a separate PR

**Review by normanmaurer — APPROVED** [review]

File: codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameEncoder.java [hunk 4]
```diff
@@ -42,8 +50,21 @@ public class SnappyFrameEncoder extends MessageToByteEncoder<ByteBuf> {
         (byte) 0xff, 0x06, 0x00, 0x00, 0x73, 0x4e, 0x61, 0x50, 0x70, 0x59
     };
 
+    public SnappyFrameEncoder() {
+        this(SNAPPY_SLICE_SIZE);
+    }
+
+    public static SnappyFrameEncoder snappyEncoderWithJumboFrames() {
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameEncoder.java:57]: Can we add some javadocs as well ?

File: common/src/main/java/io/netty/util/internal/MathUtil.java [hunk 5]
```diff
@@ -14,6 +14,8 @@
  */
 package io.netty.util.internal;
 
+import org.jctools.util.Pow2;
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/internal/MathUtil.java:17]: remove this again ?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Review by normanmaurer — APPROVED** [review]

File: codec/src/main/java/io/netty/handler/codec/compression/Snappy.java (hunk 3 above)
Comment (lucamolteni) [reply codec/src/main/java/io/netty/handler/codec/compression/Snappy.java]: https://github.com/netty/netty/pull/13833

**Comment by normanmaurer** [comment]
@lucamolteni thanks a lot!
