### PR TITLE
Provide new client and server websocket handshake exceptions

### LINKED ISSUE #10277: [Improvement] Add Http status as a separate field in exception on not 101 HTTP response code during web socket handshake
### Reason
In my project (built on top of Spring Cloud Gateway https://github.com/spring-cloud/spring-cloud-gateway) to be able to properly proxy HTTP response (on not 101 Http response code) from the backend server to the client, I need to extract actual Http Status code. For now, it could be done only by parsing the exception's message.
To simplify such use cases I'd like to introduce the sub-class of the WebSocketHandshakeException and enrich it with actual Http status to avoid extra string parsing.
### Expected behavior
In the case of the wrong Http Status during Handshake throw WrongStatusWebSocketHandshakeException (for example) with Http status as an exception field
### Actual behavior
Actual Http status code could be only obtained by parsing exception's message of the WebSocketHandshakeException.
### Steps to reproduce
Try to establish a web-socket  connection with a server which returns not 101 HttpStatus code
### Minimal yet complete reproducer code (or URL to code)
I can create a reproducible  sample, but it seems obvious from the code
https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker13.java#L274
(same for other Handshaker implementations ).

I omitted versions since they are not relevant in this case.

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:

At the moment we have only one base `WebSocketHandshakeException` for handling WebSocket upgrade issues.
Unfortunately, this message contains only a string message about the cause of the failure, which is inconvenient in handling.

Modification:

Provide new `WebSocketClientHandshakeException` with `HttpResponse` field  and `WebSocketServerHandshakeException` with `HttpRequest` field both of them without content for avoid reference counting 
problems. 

Result:

More information for more flexible handling.

Fixes #10277 #4528 #10639.

### CODE REVIEW

**Comment by amizurov** [comment]
@normanmaurer, @slandelle PTAL when you have a time

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java [hunk 1]
```diff
@@ -144,13 +146,44 @@ protected WebSocketClientHandshaker(URI uri, WebSocketVersion version, String su
...
+     * @param maxFramePayloadLength
+     *            Maximum length of a frame's payload
+     * @param forceCloseTimeoutMillis
+     *            Close the connection if it was not closed by the server after timeout specified
+     * @param  absoluteUpgradeUrl
+     *            Use an absolute url for the Upgrade request, typically when connecting through an HTTP proxy over
+     *            clear HTTP
+     * @param  allowClientHandshakeException
+     *             Whether to return a basic {@link WebSocketHandshakeException}
+     *             or client {@link WebSocketClientHandshakeException} that contains a http response
```
Comment (philsttr) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java:174]: IMHO, I don't think the extra `allow*HandshakeException` flags are necessary, since both `WebSocketClientHandshakeException` and `WebSocketServerHandshakeException` extend `WebSocketHandshakeException`. I mean, `catch (WebSocketHandshakeException e)` and `e instanceof WebSocketHandshakeException` will still work. I hope no one is using `e.getClass() == WebSocketHandshakeException.class`. I think the extra flags just complicate the code without much benefit.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker00.java [hunk 2]
```diff
@@ -27,6 +27,7 @@
 import io.netty.handler.codec.http.HttpResponseStatus;
 import io.netty.handler.codec.http.HttpVersion;
 import io.netty.util.AsciiString;
+import sun.security.provider.certpath.OCSPResponse.ResponseStatus;
```
Comment (philsttr) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker00.java:30]: probably not desired

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java (hunk 1 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java:174]: I totally agree about code complication and most likely it not bring a benefit. I hope we can remove it to keep code simple if no one is against.

**Comment by chrisvest** [comment]
@netty-bot test this please

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java (hunk 1 above)
Comment (chrisvest) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java:174]: I agree, people should not rely on the concrete exception type such that we cannot throw a sub-class instead.

**Comment by amizurov** [comment]
So If everyone agrees with main concept i'll remove redundant flags for support old behaviour.

**Comment by amizurov** [comment]
@philsttr, @chrisvest PTAL again

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+                                               httpResponse.status(), httpResponse.headers());
+        } else {
+            response = null;
+        }
+    }
+
+    /**
+     * Returns a {@link HttpResponse response} if exception occurs during response validation otherwise {@code null}.
+     */
+    public HttpResponse response() {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:47]: I wonder if it would be better to expose the protocol, status and headers directly here. This would make it clear that this `HttpResponse` is never a `FullHttpResponse` and so not needs to be released. WDYT ?

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+ */
+package io.netty.handler.codec.http.websocketx;
+
+import io.netty.handler.codec.http.DefaultHttpResponse;
+import io.netty.handler.codec.http.HttpResponse;
+
+/**
+ * Client exception during handshaking process.
+ */
+public class WebSocketClientHandshakeException extends WebSocketHandshakeException {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:24]: final

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+ */
+package io.netty.handler.codec.http.websocketx;
+
+import io.netty.handler.codec.http.DefaultHttpRequest;
+import io.netty.handler.codec.http.HttpRequest;
+
+/**
+ * Server exception during handshaking process
+ */
+public class WebSocketServerHandshakeException extends WebSocketHandshakeException {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java:24]: final

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+                                             httpRequest.uri(), httpRequest.headers());
+        } else {
+            request = null;
+        }
+    }
+
+    /**
+     * Returns a {@link HttpRequest request} if exception occurs during request validation otherwise {@code null}.
+     */
+    public HttpRequest request() {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java:47]: Same comment as above

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java (hunk 3 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:47]: I thought about this, but we have situations when an exception occurs before receiving a response and we do not have this data and all fields will be null, which is inconvenient (need to check before use) or we can throw the different type of exceptions with response data and  without it.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java (hunk 6 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java:47]: Same thoughts above

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java (hunk 4 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:24]: done

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java (hunk 5 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java]: done

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java (hunk 3 above)
Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:47]: got it... maybe we should just add to the java docs that this will never be `ReferenceCounted` and so no special treatment is needed.

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:47]: Make sense, even that WebSocket Handshake request/response in theory should not contain payload, but this is not explicitly prohibited by the RFC 😲

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:52]: Added summary

**Comment by chrisvest** [comment]
@netty-bot test this please

**Comment by amizurov** [comment]
@chrisvest possible container hung problem for `centos6-java8` and looks like flaky test  in `centos6-java13`

**Comment by chrisvest** [comment]
It's the second time today I've seen that test fail on java13. Hopefully https://github.com/netty/netty/pull/10659/commits/5129b5687d1d9a690c5f8adfd811f67c4d681c76 will shed a bit of light on why it's failing.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by amizurov** [comment]
@normanmaurer, @chrisvest guys do i need merge https://github.com/netty/netty/pull/10659 to my PR for investigation the flaky test in `centos-java13` build  or we can go ?

**Comment by chrisvest** [comment]
@amizurov No need to wait for that.
@normanmaurer Do you think this is good to go in?

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java [hunk 7]
```diff
@@ -0,0 +1,55 @@
...
+
+import io.netty.handler.codec.http.DefaultHttpResponse;
+import io.netty.handler.codec.http.FullHttpResponse;
+import io.netty.handler.codec.http.HttpResponse;
+import io.netty.util.ReferenceCounted;
+
+/**
+ * Client exception during handshaking process.
+ *
+ *  <p><b>IMPORTANT</b>: This exception should not contains any {@link ReferenceCounted} fields
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:26]: `This exception does not contain ....`

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+
+import io.netty.handler.codec.http.DefaultHttpRequest;
+import io.netty.handler.codec.http.FullHttpRequest;
+import io.netty.handler.codec.http.HttpRequest;
+import io.netty.util.ReferenceCounted;
+
+/**
+ * Server exception during handshaking process.
+ *
+ * <p><b>IMPORTANT</b>: This exception should not contains any {@link ReferenceCounted} fields
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java:26]: `This exception does not contain any`

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+
+    private static final long serialVersionUID = 1L;
+
+    private final HttpRequest request;
+
+    public WebSocketServerHandshakeException(String message) {
+        this(message, null);
+    }
+
+    public WebSocketServerHandshakeException(String message, HttpRequest httpRequest) {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java:39]: let's make the constructors package-private and add:

```
assert !(httpRequest instanceof ReferenceCounted);
```

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+
+    private static final long serialVersionUID = 1L;
+
+    private final HttpResponse response;
+
+    public WebSocketClientHandshakeException(String message) {
+        this(message, null);
+    }
+
+    public WebSocketClientHandshakeException(String message, HttpResponse httpResponse) {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:39]: assert !(httpRequest instanceof ReferenceCounted); and make constructors package private for now

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java (hunk 10 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:39]: Hmm, we create our own `DefaultHttpResponse` in constructor, we don't set given response directly.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java (hunk 7 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:26]: done

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java (hunk 9 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java:39]: Hmm what kind of benefit for package-private constructors?, maybe user want to create it own exception `Server` or `Client` exception and handle it in common manner.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java (hunk 10 above)
Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshakeException.java:39]: true...

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java (hunk 9 above)
Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakeException.java:39]: I was thinking of make it more safe in terms of not pass in `ReferenceCounted` objects. That said as you mention before we copy it anyway so not a big deal

**Comment by normanmaurer** [comment]
@netty-bot test this please
