### PR TITLE
HPACK dynamic table size update must happen at the beginning of the h…

### LINKED ISSUE #12981: HPACK dynamic table size update must happen at the beginning of the header block
### Expected behavior

HPACK decoder accepts dynamic table size update at the beginning of the block.

Cf RFC 7531, section 4.2

### Actual behavior

HPACK decoder tolerates dynamic table size update anywhere in the block

`io.netty.handler.codec.http2.HpackDecoder` can be modified to only allow setDynamicTableSize to be called only if that is the first of the block processing and fail otherwise with a connection error like it does already.

### Steps to reproduce

Send an HTTP/2 header frame with a dynamic table size update anywhere, e.g at the end of the stream

### Minimal yet complete reproducer code (or URL to code)

N/A

### Netty version

4.1.84.Final

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

### PR DESCRIPTION
**Pull request by vietj**
…eader block

Motivation:

HpackDecoder accepts dynamic table size updates at any stage of a header block. Such modification should always happen before the table is modified as per RFC 7541.

Modifications:

Check the header block first for dynamic table size updates in a separate method. Then reject any table size update when processing unpacking the rest of the block. Dynamic table size update could have been done with the current switch/case but it requires to keep track of the modifications which is not hard but introduces complexity in the loop (a simple boolean that must be switched for any modification but the table size update). Instead a table size update is achieved first in a simpler loop and then any table size update is rejected.

Result:

Fixes #12981

### CODE REVIEW

File: codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java [hunk 1]
```diff
@@ -127,13 +126,27 @@ final class HpackDecoder {
     void decode(int streamId, ByteBuf in, Http2Headers headers, boolean validateHeaders) throws Http2Exception {
         Http2HeadersSink sink = new Http2HeadersSink(
                 streamId, headers, maxHeaderListSize, validateHeaders);
+        decodeDynamicTableSizeUpdates(in);
```
Comment (normanmaurer) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java:129]:
```suggestion
        // Check for dynamic table size updates, which must occur at the beginning:
        // https://www.rfc-editor.org/rfc/rfc7541.html#section-4.2
        decodeDynamicTableSizeUpdates(in);
```

File: codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java [hunk 2]
```diff
@@ -184,13 +197,8 @@ private void decode(ByteBuf in, Http2HeadersSink sink) throws Http2Exception {
...
                     } else if ((b & 0x20) == 0x20) {
                         // Dynamic Table Size Update
-                        index = b & 0x1F;
-                        if (index == 0x1F) {
-                            state = READ_MAX_DYNAMIC_TABLE_SIZE;
-                        } else {
-                            setDynamicTableSize(index);
-                            state = READ_HEADER_REPRESENTATION;
-                        }
+                        throw connectionError(COMPRESSION_ERROR, "Dynamic table size update must happen " +
```
Comment (normanmaurer) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java:200]:
```suggestion
                        // See https://www.rfc-editor.org/rfc/rfc7541.html#section-4.2
                        throw connectionError(COMPRESSION_ERROR, "Dynamic table size update must happen " +
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java (hunk 1 above)
Comment (vietj) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java:129]: can I commit this directly from github interface ?

Comment (normanmaurer) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java:131]: Yep... I just pressed the button for you :)

Comment (vietj) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java:131]: thanks :-D

**Comment by normanmaurer** [comment]
@vietj thanks a lot!

**Review by idelpivnitskiy — COMMENTED** [review]
Late LGTM, thanks @vietj!
