### PR TITLE
Netty Future no longer extends JDK Future

### LINKED ISSUE #7712: method `io.netty.util.concurrent.DefaultPromise#cancel` violates contrast?
### Expected behavior
According the contrast from method `java.util.concurrent.Future#cancel` :

> After this method returns, subsequent calls to isDone will always return true. 

the console should print `true`
### Actual behavior
console print `false`
### Steps to reproduce
please use following reproducer code
### Minimal yet complete reproducer code (or URL to code)
```
import io.netty.util.concurrent.GlobalEventExecutor;
import io.netty.util.concurrent.Promise;

public class DefaultPromiseIsDoneTest {

    private final Promise<?> defaultPromise = GlobalEventExecutor.INSTANCE.newPromise();

    public static void main(String args[]) {
        DefaultPromiseIsDoneTest main = new DefaultPromiseIsDoneTest();
        main.isDoneTest();
    }

    private void isDoneTest() {
        defaultPromise.setUncancellable();
        defaultPromise.cancel(false);
        boolean isDone = defaultPromise.isDone();
        System.out.println(isDone);
    }
}

```
### Netty version
4.1.21
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
MacOS

Does  Netty change the contrast inherited from `java.util.concurrent.Future#cancel`?
There are also a discussion about this contrast in stackoverflow:
https://stackoverflow.com/questions/30140463/future-cancel-method-documentation

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
It is important to avoid blocking method calls in an event loop thread, since that can stall the system.
Netty's Future interface was extending the JDK Future interface, which included a number of blocking methods of questionable use in Netty.
We wish to reduce the number of blocking methods on the Future API in order to discourage their use a little.
Further more, the Netty Future specification of the behaviour of the cancel() and isDone() methods are inconsistent with those of the JDK Future.
If Netty's Future stop extending the JDK Future interface, it will also no longer be bound by its specification.

Modification:
Make Netty's Future no longer extend the JDK Future interface.
Change the EvenExecutorGroup interface to no longer extend ScheduledExecutorService.
The EventExecutorGroup still extends Executor, because Executor does not dictate any return type of the `execute()` method — this is also useful in the DefaultFutureCompletionStage implementation.
The Netty ScheduledFuture interface has been removed since it provided no additional features that were actually used.
Numerous changes to use sites that previously relied on the JDK types.
Remove the `Future.cancel()` method that took a boolean argument — this argument was always ignored in our implementations, which was another spec deviation.
Various `invoke*` and `shutdown*` methods have been removed from the EvenExecutorGroup API since it no longer extends ScheduledExecutorService — these were either not used anywhere, or deprecated with better alternatives available.

Result:
Cleaner code, leaner API.

Fixes #7712, #8520

### CODE REVIEW

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: common/src/main/java/io/netty/util/concurrent/RunnableScheduledFutureAdapter.java [hunk 1]
```diff
@@ -100,6 +93,23 @@ public int compareTo(Delayed o) {
...
+        return Long.hashCode(id);
+    }
+
+    @Override
+    public boolean equals(Object obj) {
+        if (this == obj) {
+            return true;
+        }
+        if (obj instanceof RunnableScheduledFutureAdapter) {
+            var adaptor = (RunnableScheduledFutureAdapter<?>) obj;
```
[the remark this answers is not in the document]
Comment (chrisvest) [reply common/src/main/java/io/netty/util/concurrent/RunnableScheduledFutureAdapter.java:107]: It looked convenient with the cast, but I can revert it for now.

File: common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java [hunk 2]
```diff
@@ -46,22 +42,22 @@
     }
 
     @Override
-    public ScheduledFuture<?> schedule(Runnable command, long delay, TimeUnit unit) {
+    public Future<?> schedule(Runnable command, long delay, TimeUnit unit) {
```
Comment (NiteshKant) [inline common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: Should this and other methods taking a `Runnable` return `Future<Void>`?

**Review by NiteshKant — COMMENTED** [review]
LGTM after open comments are resolved

File: common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java (hunk 2 above)
Comment (chrisvest) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: Yeah, `Void` is a better choice than wildcard.

Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: While I also thing that `Void` is better I wonder why the JDK did choose `ScheduledFuture<?>`. Any idea ?

Comment (chrisvest) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: No, I don't know why they went with wildcards.

Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: Maybe something to ask for on the concurrency-interest mailing list just so we don't do something "stupid" ? That said this shouldn't block the PR

Comment (chrisvest) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: Looks like it somehow is a, or ended up being a convention for futures that "return no value".

**Comment by normanmaurer** [comment]
@chrisvest can you please rebase ?

File: common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java (hunk 2 above)
Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: hmm interesting.. Any pointers to this ?

Comment (chrisvest) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: It's been like this from the start: http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/concurrent/ExecutorService.java?r1=1.7&r2=1.8
I think wildcard was chosen at the time because they specified the future to return "an arbitrary value".

I don't find any discussion of this from the beginning of the concurrency-interest list until 2004, when searching for all the relevant keywords I could come up with.

Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: Can you ask on the ml and link it here ? Just so we can decide later on what to do. For now let's just use `Void`.

Comment (chrisvest) [reply common/src/main/java/io/netty/util/concurrent/AbstractEventExecutorGroup.java:45]: Asked: http://cs.oswego.edu/pipermail/concurrency-interest/2021-September/017420.html

**Comment by chrisvest** [comment]
@normanmaurer @NiteshKant Updated, please take a look.

File: common/src/main/java/io/netty/util/concurrent/EventExecutorGroup.java [hunk 3]
```diff
@@ -34,61 +29,77 @@
...
+
+    /**
+     * Returns {@code true} if all {@link EventExecutor}s managed by this {@link EventExecutorGroup} are
+     * {@linkplain #isShutdown() shut down}, and all of their tasks have completed.
+     *
+     * @return {@code true} if all executors in this group have terminated.
+     */
+    boolean isTerminated();
+
+    default boolean awaitTermination(long timeout, TimeUnit unit) throws InterruptedException {
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/concurrent/EventExecutorGroup.java:67]: nit: add javadocs.

File: common/src/main/java/io/netty/util/concurrent/EventExecutorGroup.java [hunk 4]
```diff
@@ -34,61 +29,77 @@
...
+     */
+    boolean isShutdown();
+
+    /**
+     * Returns {@code true} if all {@link EventExecutor}s managed by this {@link EventExecutorGroup} are
+     * {@linkplain #isShutdown() shut down}, and all of their tasks have completed.
+     *
+     * @return {@code true} if all executors in this group have terminated.
+     */
+    boolean isTerminated();
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/concurrent/EventExecutorGroup.java:65]:
```suggestion
    default boolean isTerminated() {
        return terminationFuture.isDone();
    }
```

File: common/src/main/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutor.java [hunk 5]
```diff
@@ -84,94 +88,97 @@ public boolean isShuttingDown() {
...
-    public Future<?> submit(Runnable task) {
-        return (Future<?>) super.submit(task);
+    public Future<Void> submit(Runnable task) {
+        return (Future<Void>) executor.submit(task);
     }
 
     @Override
     public <T> Future<T> submit(Runnable task, T result) {
-        return (Future<T>) super.submit(task, result);
+        return (Future<T>) executor.submit(task, result);
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutor.java:145]: As `Future.executor()` exists I think we need to take special action to ensure the returned `Future` actually return `UnorderedThreadPoolEventExecutor` and not the "inner" executor. Same is true for all the other methods.

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: common/src/main/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutor.java (hunk 5 above)
Comment (chrisvest) [reply common/src/main/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutor.java:145]: This is already the case because of how the inner executor decorates tasks. I have added a test for this.

**Comment by chrisvest** [comment]
@normanmaurer Comments addressed, please take a look.

File: common/src/test/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutorTest.java [hunk 6]
```diff
@@ -105,4 +105,40 @@ public String call() {
...
+
+            future.cancel();
+            future = executor.submit(runnable);
+            assertSame(executor, future.executor());
+
+            future.cancel();
+            future = executor.submit(callable);
+            assertSame(executor, future.executor());
+        } finally {
+            future.cancel();
```
Comment (normanmaurer) [inline common/src/test/java/io/netty/util/concurrent/UnorderedThreadPoolEventExecutorTest.java:141]:
```suggestion
            future.cancel();
            executor.shutdownGracefully();
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]
One thing... after that :shipit:

File: common/src/main/java/io/netty/util/concurrent/Future.java [hunk 7]
```diff
@@ -257,7 +257,24 @@ default V get() throws InterruptedException, ExecutionException {
...
+     * @param timeout The non-negative maximum amount of time, in terms of the given time unit, to wait for the
+     *                completion of the future.
+     * @param unit The time unit for the timeout.
+     * @return The value of the successfully completed future.
+     * @throws InterruptedException If this call was blocking and this thread got
+     * {@linkplain Thread#interrupt() interrupted}.
+     * @throws ExecutionException If the task failed, either by throwing an exception, or through cancellation.
+     * @throws TimeoutException If the future did not complete within the specified timeout.
+     */
     default V get(long timeout, TimeUnit unit) throws InterruptedException, ExecutionException, TimeoutException {
```
Comment (NiteshKant) [inline common/src/main/java/io/netty/util/concurrent/Future.java:278]: Not in this PR but wondering if we should remove blocking methods from the `Future`. If at all blocking is required which I believe would be for test/examples then `asJdkFuture()` can be used to get to blocking methods.

**Review by NiteshKant — APPROVED** [review]
