### PR TITLE
Sanitize all multibyte chars in HpackHuffmanEncoder

### LINKED ISSUE #13540: Unexpected characters are synthesized by DefaultHttp2HeadersDecoder when Huffman encoding is enabled in HpackEncoder
### What happened?
1. Create a header `DefaultHttp2Headers` with a certain value that exceeds certain size and contain non-ASCII characters, 
2. Encode the header using `DefaultHttp2HeadersEncoder`.
3. Decode the encoded header using `DefaultHttp2HeadersDecoder`.
4. If Huffman encoding is enabled in the `HpackDecoder` (used inside `DefaultHttp2HeadersDecoder`), unexpected character(s) magically show up in the decoded string. 

"Unexpected characters" means:
1. They are not in the original header value which is encoded.
2. Their unicode code points are smaller than 32.

Please note that different header value input can yield different unexpected characters. In the below repro code, `NULL (U+0000)` is the unexpected character. We also have header value (which contains company-specific information) that would yield `\r` as unexpected characters.

IMO the first thing is to confirm that there is indeed a bug in the HPACK implementation (and/or any other components).

### Steps to reproduce
Please refer to the below code.

### Minimal yet complete reproducer code (or URL to code)
```scala
test("NULL character is magically synthesized by DefaultHttp2HeadersDecoder when Huffman encoding is enabled in HpackEncoder") {
 import io.netty.handler.codec.http2.DefaultHttp2Headers
 import io.netty.handler.codec.http2.DefaultHttp2HeadersEncoder
 import io.netty.buffer.Unpooled
 import io.netty.handler.codec.http2.DefaultHttp2HeadersDecoder

 val headers = new DefaultHttp2Headers
 val badHeaderValue =
   "{\"xxxx\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\"xxxxxxx\":\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\"xxxx\":\"x\",\"xxxxxxx\":\"xxxxxxxxxxxxxxxxxxxxxxxxxx\",\"xxxxxxxxxxxxxx\":\"我们在Netty中发现了一个bug_ми знайшли проблему в_123мынашлипроблемув_우리는에서문제를발견했습니다Saturday10311031UsersVlad@Alex_ver10311031Sharedで問題が見つかりましたIAPKI_ActivityVlad@Alex우리는에서문제를발견했습니다BatchWeFound_10311031UsersVlad@Alex_ver10311031Shared\",\"xxxxxx\":\"xxxxxxxx\",\"xxxxxxxx\":\"xxxxxx-87\",\"xxxxxxxxx\":\"xxxxxx.xxxxxx.xxxxxx.xxxxxx.24hgjbu2g2hgwoejf231Xxxxxxx/Xxxx\"}"
 headers.set("some-key", badHeaderValue)

 val neverSensitive: SensitivityDetector = new SensitivityDetector() {
   override def isSensitive(name: CharSequence, value: CharSequence) = false
 }
 val enableHuffmanEncoding = true
 // Use the below threshold to control whether Huffman encoding is enabled for the above header value at runtime.
 val huffCodeThreshold: Int = if (enableHuffmanEncoding) 512 else 51200

 val encoder = new DefaultHttp2HeadersEncoder(
   neverSensitive,
   false, // ignoreMaxHeaderListSize, same value as default.
   64, // dynamicTableArraySizeHint, same value as default.
   huffCodeThreshold
 )
 val buf = Unpooled.buffer(10000)
 encoder.encodeHeaders(1, headers, buf)

 val decoder = new DefaultHttp2HeadersDecoder()
 val decodedHeader = decoder.decodeHeaders(1, buf)
 val decodedHeaderValue: String = decodedHeader.get("some-key").toString
 val nullChar: Char = 0.toChar

 assert(!badHeaderValue.contains(nullChar)) // `Null` is not in the original header value.
 if (enableHuffmanEncoding) {
   // 👇👇👇 Unexpected 'Null' character gets synthesized in the header value 🫢
   assert(decodedHeaderValue.contains(nullChar))
 } else {
   // Huffman encoding is disabled.
   assert(!decodedHeaderValue.contains(nullChar))
 }

 val scalaVersion: String = scala.util.Properties.scalaPropOrElse("version.number", "unknown")
 println(s"Scala version: $scalaVersion") // 2.12.15
 val javaVersion: String = System.getProperty("java.version")
 println(s"Java version number: $javaVersion") // 11.0.10
 val javaVendor: String = System.getProperty("java.vendor")
 println(s"Java vendor: $javaVendor") // Azul Systems, Inc
}
```

### Netty version
`4.1.86.Final`

### JVM version (e.g. `java -version`)
```
Scala version: 2.12.15
Java version number: 11.0.10
Java vendor: Azul Systems, Inc
```

### PR DESCRIPTION
**Pull request by Lincong**
Motivation:

To fix the following problem: during encoding, Huffman encoded headers are sanitized differently compared to non-Huffman encoded headers in `HpackEncoder`. As a result, characters with code point values higher than 0xFF which could be decoded to an unexpected control chars instead of `'?'`.

Modification:

Change how each character is sanitized in `HpackHuffmanEncoder`. Specifically, use the new approach [1] to replace the old approach [2].

[1] `AsciiString.c2b(aChar) & 0xFF`
[2] `aChar & 0xFF`

Expected output is `0` if `aChar > 0xFF`. But with the old approach, if `aChar == 0x4E01`, `0x4E01 & 0xFF == 1` which is incorrect.

Result:
All characters with code point values higher than 0xFF are decoded to `?`s regardless of whether Huffman encoding was used during encoding.

Fixes #13540

### CODE REVIEW

File: codec-http2/src/main/java/io/netty/handler/codec/http2/HpackHuffmanEncoder.java [hunk 1]
```diff
@@ -87,7 +87,7 @@ private void encodeSlowPath(ByteBuf out, CharSequence data) {
         int n = 0;
 
         for (int i = 0; i < data.length(); i++) {
-            int b = data.charAt(i) & 0xFF;
+            int b = sanitizeChar(data.charAt(i));
```
Comment (Lincong) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/HpackHuffmanEncoder.java:90]: We cannot directly use `AsciiString.c2b(...)` here because this function does 2 things:

1. Sanitize the given input char.
2. Cast the sanitized char to a `byte`.

Then we cast the returned `byte` to `int b`. Overall, we are doing `sanitizedChar.toByte.toInt` and it could yield negative value which cannot be used as array index. For example `128.toByte.toInt == -128`.

Comment (Lincong) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/HpackHuffmanEncoder.java]: Updated it to `AsciiString.c2b(data.charAt(i)) & 0xFF` as `0xFF` can produce unsigned int which is what we want here.

**Review by vkostyukov — APPROVED** [review]

File: codec-http2/src/test/java/io/netty/handler/codec/http2/HpackEncoderTest.java [hunk 2]
```diff
@@ -204,6 +204,44 @@ public void testManyHeaderCombinations() throws Http2Exception {
         }
     }
 
+    @Test
+    public void testSanitization() throws Http2Exception {
```
Comment (bryce-anderson) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/HpackEncoderTest.java:208]: My understanding of the small value is that it wont sanitize anything since it will never yield a value greater than 255, making it not a very interesting test. The 300 case should cover what we're really interested in wrt ensuring we don't get wrap-around values of null etc.
A second type of test is that would be valuable is that we should get the same result whether we perform the Huffman encoding or not. What if we just test the size 300 and test it twice: once with the encoded set to 512 (the default I believe) and once super short such to force Huffman encoding, then make sure they both yield the same results?

Comment (Lincong) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/HpackEncoderTest.java:208]: Thanks Bryce for the suggestion. I think it's a good idea and I have updated this PR with this idea implemented. PTAL.

**Review by bryce-anderson — APPROVED** [review]
Thank you @Lincong!

**Comment by Lincong** [comment]
Thanks @bryce-anderson  for the suggestion to improve the commit message. I have updated and PTAL before we merge this PR!

Thanks @normanmaurer for fixing style violation ([here](https://github.com/netty/netty/pull/13546/commits/5bd128db26ad77f034133a5cfb374f74bbf708c0)). I have not completely set up my dev environment yet so that some style violation cannot be caught locally. I will make sure I am able to catch and fix such issues in my future PRs.

**Comment by Lincong** [comment]
Thanks @normanmaurer  for merging this PR! 

Do you know an ETA for `4.1.97.Final` release (including this change)?

**Comment by Lincong** [comment]
> @Lincong I think sometime next week

I am not sure if this is something appropriate to ask for, but it will be super nice if `4.1.97.Final` release can land by the end of  next Wed (8/23/2023). Thanks! @normanmaurer
