### PR TITLE
fixes #10929

### LINKED ISSUE #10929: mqtt-codec: negative packet-ids
### Behavior
It looks like it's not possible to create an mqtt message (with packetId) through the provided _builder classes_ in `io.netty.handler.codec.mqtt.MqttMessageBuilders`

The reason why this is happening is because the internal representation of the packetId (in `PubAckBuilder`, `SubAckBuilder` and `UnsubAckBuilder`) is a `short`, not an `int`.
So this means that whatever value >32767 is converted to negative when entering the builder classes, and remains a negative `int` in the underlying `MqttMessageIdVariableHeader` of the message.

### Steps to reproduce
Just try to create an mqtt SubAck message using `io.netty.handler.codec.mqtt.SubAckBuilder` with `.packetId(36000)`
It will throw an exception saying the packetId needs to be between 1 and 65535.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/pull/10930

### Netty version
4.1.58.Final

### JVM version (e.g. `java -version`)
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

### OS version (e.g. `uname -a`)
```
Linux  5.8.0-36-generic #40~20.04.1-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by duke-bartholomew**
Motivation:

Exception occurs in the MQTT message builder class (`io.netty.handler.codec.mqtt.MqttMessageBuilders`) when trying to create a message with packetId > 32767

Modification:

refactor the `short` packetId into `int`
as the underlying `MqttMessageIdVariableHeader` of the message treats it as an `int` anyway.

Result:
see unit-test: `MqttMessageBuildersPacketIdTest`

Fixes #10929 .

### CODE REVIEW

**Comment by duke-bartholomew** [comment]
it looks like changing the function signature is not allowed.
I could refactor it so that the builder functions still take a `short`, but in my opinion it makes more sense to align this with the underlying _variable header_ (which takes an `int`) ?

File: codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java [hunk 1]
```diff
@@ -536,7 +536,7 @@ public PubAckBuilder reasonCode(byte reasonCode) {
             return this;
         }
 
-        public PubAckBuilder packetId(short packetId) {
+        public PubAckBuilder packetId(int packetId) {
```
Comment (normanmaurer) [inline codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java:539]: I think we need to keep the old as well as otherwise it will be a breaking change.

File: codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java [hunk 2]
```diff
@@ -546,25 +546,25 @@ public PubAckBuilder properties(MqttProperties properties) {
...
-        private short packetId;
+        private int packetId;
         private MqttProperties properties;
         private final List<MqttQoS> grantedQoses = new ArrayList<MqttQoS>();
 
         SubAckBuilder() {
         }
 
-        public SubAckBuilder packetId(short packetId) {
+        public SubAckBuilder packetId(int packetId) {
```
Comment (normanmaurer) [inline codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java:567]: I think we need to keep the old method as well as otherwise this would be a breaking change

File: codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java [hunk 3]
```diff
@@ -604,14 +604,14 @@ public MqttSubAckMessage build() {
...
-        private short packetId;
+        private int packetId;
         private MqttProperties properties;
         private final List<Short> reasonCodes = new ArrayList<Short>();
 
         UnsubAckBuilder() {
         }
 
-        public UnsubAckBuilder packetId(short packetId) {
+        public UnsubAckBuilder packetId(int packetId) {
```
Comment (normanmaurer) [inline codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttMessageBuilders.java:614]: I think we need to keep the old method as well as otherwise this would be a breaking change

**Review by normanmaurer — CHANGES_REQUESTED** [review]
```
Error:  Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp (default) on project netty-codec-mqtt: There is at least one incompatibility: io.netty.handler.codec.mqtt.MqttMessageBuilders$PubAckBuilder.build():METHOD_RETURN_TYPE_CHANGED,io.netty.handler.codec.mqtt.MqttMessageBuilders$PubAckBuilder.packetId(short):METHOD_REMOVED,io.netty.handler.codec.mqtt.MqttMessageBuilders$SubAckBuilder.packetId(short):METHOD_REMOVED,io.netty.handler.codec.mqtt.MqttMessageBuilders$UnsubAckBuilder.packetId(short):METHOD_REMOVED -> [Help 1]
```

**Comment by duke-bartholomew** [comment]
@normanmaurer I changed it back again to take the `packetId` in as a `short`.
But wouldn't it be more generic to actually change that API to work with an `int` (as is done in other mqtt-message methods)?
Now you will always have to convert between `int` and `short` whenever you use these builders.

Anyway, this PR should solve the issue now that a `packetId` > 32767 would result in a negative one when pushed through these builder classes.

**Comment by normanmaurer** [comment]
@duke-bartholomew I was actually suggesting that you add the `int` methods but keep the short as well.

**Comment by duke-bartholomew** [comment]
@normanmaurer sorry about the misunderstanding ... new commit adds them back (and deprecates the ones that take in a `short`)

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@duke-bartholomew did you sign our ICLA ?

https://netty.io/s/icla

**Comment by duke-bartholomew** [comment]
> @duke-bartholomew did you sign our ICLA ?
> 
> https://netty.io/s/icla

Yes, I did

**Comment by normanmaurer** [comment]
@duke-bartholomew thanks a lot
