### PR TITLE
Fix get charset from content-type header with multiple parameters, cl…

### LINKED ISSUE #8273: Resolve charset from ContentType header for SOAP 1.2 requests
Hello, there is a problem with charset resolution from `ContentType` header for SOAP 1.2 using `io.netty.handler.codec.http.HttpUtils` class. SOAP 1.2 could have action parameter in `ContentType` header and method `getCharsetAsSequence(CharSequence contentTypeValue)` from `io.netty.handler.codec.http.HttpUtils` class just finds charset word and take whole string from this word end to the end.

### Expected behavior
Resolve charset from `ContentType` header with value `text/xml; charset=utf-8; action="someaction"` as UTF-8

### Actual behavior
Resolve charset substring from `ContentType` header with value `text/xml; charset=utf-8; action="someaction"` as `utf-8; action="someaction"`. And then you will get an exception `java.nio.charset.IllegalCharsetNameException`

### Steps to reproduce

Resolve charset from any request which contains action parameter in `ContentType` header value

### Netty version

4.1.19

### JVM version (e.g. `java -version`)

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)

Linux 4.15.0-33-generic Ubuntu 18

### PR DESCRIPTION
**Pull request by amizurov**
Close Resolve charset from ContentType header for SOAP 1.2 requests.

Motivation:

Get charset from Content-Type header even it contains multiple parameters.

Modification:

Extract charset value from the charset parameter if it is not last.

Result:

Fixes #8273

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java [hunk 1]
```diff
@@ -459,13 +462,23 @@ public static CharSequence getCharsetAsSequence(CharSequence contentTypeValue) {
...
+            return null;
+        }
+
+        int indexOfEncoding = indexOfCharset + CHARSET_EQUALS.length();
+        if (indexOfEncoding < contentTypeValue.length()) {
+            CharSequence charsetCandidate = contentTypeValue.subSequence(indexOfEncoding, contentTypeValue.length());
+            int indexOfSemicolon = AsciiString.indexOfIgnoreCaseAscii(charsetCandidate, SEMICOLON, 0);
+            if (indexOfSemicolon == AsciiString.INDEX_NOT_FOUND) {
+                return charsetCandidate;
+            } else {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java]: nit: You can remove the `else` here as you return in the if block.

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java [hunk 2]
```diff
@@ -60,12 +60,13 @@ public static boolean isAsteriskForm(URI uri) {
...
      * Returns {@code true} if and only if the connection can remain open and
      * thus 'kept alive'.  This methods respects the value of the.
+     *
      * {@code "Connection"} header first and then the return value of
      * {@link HttpVersion#isKeepAliveDefault()}.
      */
     public static boolean isKeepAlive(HttpMessage message) {
         CharSequence connection = message.headers().get(HttpHeaderNames.CONNECTION);
-        if (connection != null && HttpHeaderValues.CLOSE.contentEqualsIgnoreCase(connection)) {
+        if (HttpHeaderValues.CLOSE.contentEqualsIgnoreCase(connection)) {
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java]: @amizurov can you add comment that passing null into `contentEqualsIngoreCase` is fine ?

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java (hunk 1 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java]: Thanks, done

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java (hunk 2 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java]: If we passed null to ```contentEqulasIgnoreCase(...)``` this always return false, null safe method.

**Comment by normanmaurer** [comment]
@amizurov thanks a lot!
