### PR TITLE
Fix remove 'WebSocketServerExtensionHandler' from pipeline after upgrade 

### LINKED ISSUE #9939: WebSocketServerExtensionHandler not removed from pipeline if client has not selected any extensions
### Expected behavior
After successful WebSocket handshake `WebSocketServerExtensionHandler` should be removed from pipeline to keep it short as possible.

### Actual behavior
If client has not selected any extensions (e.g compression)`WebSocketServerExtensionHandler` still present in pipeline after upgrade.

### Netty version
4.1.44.Final

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:

We should remove`WebSocketServerExtensionHandler` from pipeline after successful WebSocket upgrade even if the client has not selected any extensions.

Fixes #9939.

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java [hunk 1]
```diff
@@ -103,36 +103,46 @@ public void channelRead(ChannelHandlerContext ctx, Object msg)
...
-        if (msg instanceof HttpResponse &&
-                WebSocketExtensionUtil.isWebsocketUpgrade(((HttpResponse) msg).headers()) && validExtensions != null) {
-            HttpResponse response = (HttpResponse) msg;
-            String headerValue = response.headers().getAsString(HttpHeaderNames.SEC_WEBSOCKET_EXTENSIONS);
-
-            for (WebSocketServerExtension extension : validExtensions) {
-                WebSocketExtensionData extensionData = extension.newReponseData();
-                headerValue = WebSocketExtensionUtil.appendExtension(headerValue,
-                        extensionData.name(), extensionData.parameters());
+        if (msg instanceof HttpResponse && WebSocketExtensionUtil.isWebsocketUpgrade(((HttpResponse) msg).headers())) {
```
Comment (doom369) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java]: Can we split this condition on 2 separate if's? So we can perform only class cast:

`((HttpResponse) msg).headers()`

`HttpResponse response = (HttpResponse) msg;`

Also, `response.headers()` could be moved to variable.

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java]: no problem

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java [hunk 2]
```diff
@@ -103,35 +103,48 @@ public void channelRead(ChannelHandlerContext ctx, Object msg)
...
                 }
-            });
 
-            if (headerValue != null) {
-                response.headers().set(HttpHeaderNames.SEC_WEBSOCKET_EXTENSIONS, headerValue);
+                promise.addListener(new ChannelFutureListener() {
+                    @Override
+                    public void operationComplete(ChannelFuture future) {
+                        if (future.isSuccess()) {
+                            ctx.pipeline().remove(ctx.name());
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java]: nit: use `ctx.pipeline().remove(WebSocketServerExtensionHandler.this);`

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandlerTest.java [hunk 3]
```diff
@@ -190,4 +198,28 @@ public void testNoneExtensionMatchingSuccess() {
...
+
+        HttpResponse res = newUpgradeResponse(null);
+        ChannelPromise failurePromise = ch.newPromise();
+        ch.writeOneOutbound(res, failurePromise);
+        failurePromise.setFailure(new IOException("Cannot write response"));
+
+        // test
+        assertNull(ch.readOutbound());
+        assertNotNull(ch.pipeline().context(extensionHandler));
+    }
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandlerTest.java]: call `ch.finish()` and assert return value.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java (hunk 2 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandler.java]: done

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandlerTest.java (hunk 3 above)
Comment (amizurov) [reply codec-http/src/test/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtensionHandlerTest.java]: done

**Comment by normanmaurer** [comment]
@netty-bot test this please
