### PR TITLE
Handle content-type optional parameters other than charset (netty#12663)

### LINKED ISSUE #12663: Parsing multipart/form-data requests with form-data content-type including optional parameters uses last parameter as content-type
### Expected behavior
When passed a content type header with optional parameter, content type should be correctly set and optional parameters should be attributes.

e.g. 

contnet-type: audio/ogg; codecs=opus should have content type of audio/ogg and a codecs attribute of opus

### Actual behavior

content type is currently set to codecs=opus

### Steps to reproduce

Create a request with a content type containing an optional parameter on the content type header

### Minimal yet complete reproducer code (or URL to code)

The following test added to HttpPostMultiPartRequestDecoderTest will currently fail.

```
    @Test
    public void testDecodeFullHttpRequestWithOptionalParameters() {
        String content = "\n--861fbeab-cd20-470c-9609-d40a0f704466\r\n" +
                "content-disposition: form-data; " +
                "name=\"file\"; filename=\"myfile.ogg\"\r\n" +
                "content-type: audio/ogg; codecs=opus; charset=UTF8\r\ncontent-transfer-encoding: binary\r\n" +
                "\r\n\u0001\u0002\u0003\u0004\r\n--861fbeab-cd20-470c-9609-d40a0f704466--\r\n\",\n";

        FullHttpRequest req = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/upload",
                Unpooled.copiedBuffer(content, CharsetUtil.US_ASCII));
        req.headers().set("content-type", "multipart/form-data; boundary=861fbeab-cd20-470c-9609-d40a0f704466");
        req.headers().set("content-length", content.length());

        HttpPostMultipartRequestDecoder test = new HttpPostMultipartRequestDecoder(req);
        assertEquals("audio/ogg", ((MixedFileUpload)test.getBodyHttpDatas("file").get(0)).getContentType());
    }

```

### Netty version
4.1.74

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)      
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10, Ubuntu 18.04

### PR DESCRIPTION
**Pull request by sjw2547**
Motivation:

When receiving multipart/form-data where the form-data includes a file with optional parameter, in my case a codec parameter, the content-type was incorrectly set to the parameter value. Currently this only behaves correctly if the optional parameter is a character set parameter.

Modification:

When processing the content-type header contents, after splitting the header into the String[], check each item to see if it is a name=value pair, indicating it is an optional parameter. Add an attribute using the split name and value.

Result:

When processing the content-type header, the code now correctly sets the content-type and adds additional attributes for the optional parameters.

Fixes #12663

### CODE REVIEW

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 1]
```diff
@@ -300,6 +300,23 @@ public void testNotBadReleaseBuffersDuringDecodingMixedFactory() throws IOExcept
...
+                "content-type: audio/ogg; codecs=opus; charset=UTF8\r\ncontent-transfer-encoding: binary\r\n" +
+                "\r\n\u0001\u0002\u0003\u0004\r\n--861fbeab-cd20-470c-9609-d40a0f704466--\r\n\",\n";
+
+        FullHttpRequest req = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/upload",
+                Unpooled.copiedBuffer(content, CharsetUtil.US_ASCII));
+        req.headers().set("content-type", "multipart/form-data; boundary=861fbeab-cd20-470c-9609-d40a0f704466");
+        req.headers().set("content-length", content.length());
+
+        HttpPostMultipartRequestDecoder test = new HttpPostMultipartRequestDecoder(req);
+        assertEquals("audio/ogg", ((MixedFileUpload)test.getBodyHttpDatas("file").get(0)).getContentType());
```
Comment (chrisvest) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:317]: Cast to the `FileUpload` interface, instead of relying on a particular implementation being chosen.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java [hunk 2]
```diff
@@ -771,6 +771,18 @@ private InterfaceHttpData findMultipartDisposition() {
                                 throw new ErrorDataDecoderException(e);
                             }
                             currentFieldAttributes.put(HttpHeaderValues.CHARSET, attribute);
+                        } else if (contents[i].contains("=")) {
+                            String name = StringUtil.substringBefore(contents[i], '=');
+                            String values = StringUtil.substringAfter(contents[i], '=');
+                            Attribute attribute;
+                            try {
+                                attribute = factory.createAttribute(request, name, cleanString(values));
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:779]: The `values` may be a [quoted string](https://www.rfc-editor.org/rfc/rfc9110.html#name-quoted-strings) according to the [spec for parameters](https://www.rfc-editor.org/rfc/rfc9110.html#name-parameters), which `cleanString()` will not handle correctly.

We should instead use `cleanString()` for the `name`, which is always a token.

**Review by chrisvest — CHANGES_REQUESTED** [review]

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java (hunk 1 above)
Comment (sjw2547) [reply codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java]: Resolved.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java (hunk 2 above)
Comment (sjw2547) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java]: Resolved.

**Review by chrisvest — APPROVED** [review]

File: codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java [hunk 3]
```diff
@@ -300,6 +300,24 @@ public void testNotBadReleaseBuffersDuringDecodingMixedFactory() throws IOExcept
...
+                "\r\n\u0001\u0002\u0003\u0004\r\n--861fbeab-cd20-470c-9609-d40a0f704466--\r\n\",\n";
+
+        FullHttpRequest req = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/upload",
+                Unpooled.copiedBuffer(content, CharsetUtil.US_ASCII));
+        req.headers().set("content-type", "multipart/form-data; boundary=861fbeab-cd20-470c-9609-d40a0f704466");
+        req.headers().set("content-length", content.length());
+
+        HttpPostMultipartRequestDecoder test = new HttpPostMultipartRequestDecoder(req);
+        FileUpload httpData = (FileUpload) test.getBodyHttpDatas("file").get(0);
+        assertEquals("audio/ogg", httpData.getContentType());
```
Comment (chrisvest) [inline codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostMultiPartRequestDecoderTest.java:318]: The test has a resource leak because you don't `destroy()` the `HttpPostMultipartRequestDecoder`.

Use the `leak` maven profile when running tests locally and then check the log output for any `LEAK:` reports, in order to verify that there are no more leaks.

**Review by chrisvest — CHANGES_REQUESTED** [review]

**Comment by normanmaurer** [comment]
@sjw2547 please sign our ICLA and let me know once done: https://netty.io/s/icla

**Comment by sjw2547** [comment]
@normanmaurer - done

**Comment by normanmaurer** [comment]
@sjw2547 thanks a lot !
