### PR TITLE
Fix bug in Recycler with racing calls to recycle

### LINKED ISSUE #10986: recycler has problems recycling objects in a multi-threaded environment
### Expected behavior

An object is collected in a multi-threaded environment and only exists in one queue.

### Actual behavior

An object is collected in multiple queues in a multithreaded environment.

### Steps to reproduce

```
public void testMultipleRecycleAtDifferentThread() throws InterruptedException {
        Recycler<HandledObject> recycler = newRecycler(1024);
        final HandledObject object = recycler.get();
        final AtomicReference<IllegalStateException> exceptionStore = new AtomicReference<IllegalStateException>();

        final CountDownLatch countDownLatch = new CountDownLatch(2);
        final Thread thread1 = new Thread(new Runnable() {
            @Override
            public void run() {
                try{
                    object.recycle();
                }finally {
                    countDownLatch.countDown();
                }
                
            }
        });
        thread1.start();
        //thread1.join();

        final Thread thread2 = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    object.recycle();
                } catch (IllegalStateException e) {
                    exceptionStore.set(e);
                } finally {
                    countDownLatch.countDown();
                }
            }
        });
        thread2.start();
        //thread2.join();
        
        countDownLatch.await();
        recycler.get();
        IllegalStateException exception = exceptionStore.get();
        if (exception != null) {
            throw exception;
        }
    }
```

Breakpoint debugging recycler.get() method, you will find that there are two queues in the stack, holding the same object.

### Netty version

4.1.59.Final-SNAPSHOT

### JVM version (e.g. `java -version`)

1.8

### OS version (e.g. `uname -a`)

masos

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
It is possible for two separate threads to race on recycling an object.
If this happens, the object might be added to a WeakOrderQueue when it shouldn't be.
The end result of this is that an object could be acquired multiple times, without a recycle in between.
Effectively, it ends up in circulation twice.

Modification:
We fix this by making the update to the lastRecycledId field of the handle, an atomic state transition.
Only the thread that "wins" the race and succeeds in their state transition will be allowed to recycle the object.
The others will bail out on their recycling.
We use weakCompareAndSet because we only need the atomicity guarantee, and the program order within each thread is sufficient.
Also, spurious failures just means we won't recycle that particular object, which is fine.

Result:
Objects no longer risk circulating twice due to a recycle race.

This fixes #10986

### CODE REVIEW

**Review by normanmaurer — APPROVED** [review]
Great work!

**Review by franz1981 — APPROVED** [review]

File: common/src/main/java/io/netty/util/Recycler.java [hunk 1]
```diff
@@ -209,8 +210,16 @@ final int threadLocalSize() {
 
     public interface Handle<T> extends ObjectPool.Handle<T>  { }
 
+    @SuppressWarnings("unchecked")
     private static final class DefaultHandle<T> implements Handle<T> {
```
Comment (franz1981) [inline common/src/main/java/io/netty/util/Recycler.java:214]: You can just extends `AtomicInteger` that would give you back `Unsafe` perf for free :)

Comment (chrisvest) [reply common/src/main/java/io/netty/util/Recycler.java:214]: I considered it, but then I loose the field name which is quite awkward. Also, I think the JIT is able to trust the finals inside A*FUs these days, so they're as fast as VarHandles or Atomic*s these days.
