### PR TITLE
Remove the Handler only after it has initialized the channel

### LINKED ISSUE #9131: ApplicationProtocolNegotiationHandler loses its place in the context too soon
### Expected behavior
```
	@Override
	protected void configurePipeline(ChannelHandlerContext ctx, String protocol)
			throws Exception {
		ctx.pipeline().replace(this, null, initializer);
		// or
		ctx.pipeline().addAfter(this, null, initializer);
		// or
		ctx.pipeline().addBefore(this, null, initializer);
	}
```
should work, similarly to how a ```ChannelInitializer``` works.

### Actual behavior
An exception is thrown on all "relative" pipeline operations, because the ApplicationProtocolNegotiationHandler instance has already been removed from the pipeline BEFORE ```configurePipeline()``` is called:

```ApplicationProtocolNegotiationHandler.java

    @Override
    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
        if (evt instanceof SslHandshakeCompletionEvent) {
            ctx.pipeline().remove(this); // <-- Removed before calling configurePipeline :-(

            SslHandshakeCompletionEvent handshakeEvent = (SslHandshakeCompletionEvent) evt;
            if (handshakeEvent.isSuccess()) {
                SslHandler sslHandler = ctx.pipeline().get(SslHandler.class);
                if (sslHandler == null) {
                    throw new IllegalStateException("cannot find a SslHandler in the pipeline (requir
ed for " +
                                                    "application-level protocol negotiation)");
                }
                String protocol = sslHandler.applicationProtocol();
                configurePipeline(ctx, protocol != null? protocol : fallbackProtocol);
            } else {
                handshakeFailure(ctx, handshakeEvent.cause());
            }
        }

        ctx.fireUserEventTriggered(evt);
    }
```

Compare that to Channelinitializer:

```ChannelInitializer.java

    @SuppressWarnings("unchecked")
    private boolean initChannel(ChannelHandlerContext ctx) throws Exception {
        if (initMap.add(ctx)) { // Guard against re-entrance.
            try {
                initChannel((C) ctx.channel());
            } catch (Throwable cause) {
                // Explicitly call exceptionCaught(...) as we removed the handler before calling init
Channel(...).
                // We do so to prevent multiple calls to initChannel(...).
                exceptionCaught(ctx, cause);
            } finally {
                ChannelPipeline pipeline = ctx.pipeline();
                if (pipeline.context(this) != null) {
                    pipeline.remove(this);
                }
            }
            return true;
        }
        return false;
    }
```

Note that the comment regarding the handler already having been removed in ```Channelinitializer``` is incorrect. See the following excerpt from current code:

```ChannelInitializer.java

    /**
     * {@inheritDoc} If override this method ensure you call super!
     */
    @Override
    public void handlerAdded(ChannelHandlerContext ctx) throws Exception {
        if (ctx.channel().isRegistered()) {
            // This should always be true with our current DefaultChannelPipeline implementation.
            // The good thing about calling initChannel(...) in handlerAdded(...) is that there will be no ordering
            // surprises if a ChannelInitializer will add another ChannelInitializer. This is as all handlers
            // will be added in the expected order.
            if (initChannel(ctx)) {

                // We are done with init the Channel, removing the initializer now.
                removeState(ctx);
            }
        }
    }
```
### Steps to reproduce
Use ```ctx.replace(...)``` in the ```configurePipeline()``` method.

### Minimal yet complete reproducer code (or URL to code)
Not available.

### Netty version
netty-4.1.36.Final

### JVM version (e.g. `java -version`)
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)

### OS version (e.g. `uname -a`)
Linux nemesis 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by RoganDawes**
Motivation:

Previously, any 'relative' pipeline operations, such as
ctx.pipeline().replace(), .addBefore(), addAfter(), etc
would fail as the handler was not present in the pipeline.

Modification:

Used the pattern from ChannelInitializer when invoking configurePipeline().

Result:

Fixes #9131 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@RoganDawes can you please add a unit test ?

**Comment by RoganDawes** [comment]
I see there is no test at all for handler/src/main/java/io/netty/handler/ssl/ApplicationProtocolNegotiationHandler :-(

I honestly don't know how best to set up the test, given that it requires a pipeline with an existing SslHandler in it to fire a handshakeCompletionEvent.

**Comment by RoganDawes** [comment]
Can I add it here: https://github.com/netty/netty/blob/4.1/handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java#L366

Will an assert inside the handler work to break the build if it fails? Or should I use some other mechanism?

**Comment by normanmaurer** [comment]
@RoganDawes I think it should work... why not try to add the assert stuff in there without your pr merged and see if it fails ;) ?

**Comment by RoganDawes** [comment]
I added the assert as discussed, and got this in the test output:

```
09:10:07.751 [nioEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at io.netty.handler.ssl.SniHandlerTest$3$1.configurePipeline(SniHandlerTest.java:367)
```
The tests failed, but not because of this assertion, rather because the countdownlatch did not reach the expected value. Would it not make more sense for the failure to be more specific as to the cause?

To do that, I guess there needs to be some way to propagate the exception from the event thread to the primary JUnit thread, right?

**Comment by RoganDawes** [comment]
Ok, I addressed my issue above by using a CountDownLatch, and checking its value on the main thread.

File: handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java [hunk 1]
```diff
@@ -395,6 +403,8 @@ protected void configurePipeline(ChannelHandlerContext ctx, String protocol) {
 
                 assertTrue(serverApnDoneLatch.await(5, TimeUnit.SECONDS));
                 assertTrue(clientApnDoneLatch.await(5, TimeUnit.SECONDS));
+                assertEquals(0, serverApnCtxLatch.getCount());
+                assertEquals(0, clientApnCtxLatch.getCount());
```
Comment (normanmaurer) [inline handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java]: please use `await(...)` and not `getCount`. if you really not want to call `await(...)` just replace the latch usage with an `AtomicBoolean`.

**Comment by RoganDawes** [comment]
Changed to use AtomicBoolean as suggested, which also resolved the braces on the ```if``` statement :-)

File: handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java (hunk 1 above)
Comment (RoganDawes) [reply handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java]: I didn't want to use ```await(...)``` because it would introduce a 5 second delay on each invocation. An ```AtomicBoolean``` solves that problem nicely, thanks.

File: handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java [hunk 2]
```diff
@@ -381,6 +386,9 @@ protected void initChannel(Channel ch) throws Exception {
                         ch.pipeline().addLast(new ApplicationProtocolNegotiationHandler("foo") {
                             @Override
                             protected void configurePipeline(ChannelHandlerContext ctx, String protocol) {
+                                // addresses issue #9131
+                                if (ctx.pipeline().context(this) != null)
```
[the remark this answers is not in the document]
Comment (RoganDawes) [reply handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java]: Resolved by using ```AtomicBoolean```

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@RoganDawes please fix check style error:

```
13:04:30 [INFO] --- maven-checkstyle-plugin:3.0.0:check (check-style) @ netty-handler ---
13:04:32 [INFO] Starting audit...
13:04:32 [ERROR] /code/handler/src/main/java/io/netty/handler/ssl/ApplicationProtocolNegotiationHandler.java:103: an empty line before } [RegexpMultiline]
13:04:32 Audit done.
```

**Comment by RoganDawes** [comment]
Done!

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@RoganDawes thanks a lot!

**Comment by RoganDawes** [comment]
Thanks Norman!
