### PR TITLE
Make sure we always flush window update frames in AbstractHttp2StreamChannel

### LINKED ISSUE #10072: AbstractHttp2StreamChannel fails to flush window update under certain read patterns
### Expected behavior

Window updates get flushed by `AbstractHttp2StreamChannel`.

### Actual behavior

Under certain conditions that doesn't happen.

### Minimal yet complete reproducer code (or URL to code)
I have a test case that is really ugly and should probably be condensed but it illustrates the issue. I've annotated it with values observed with a debugger during it's execution.
```java
    static ByteBuf bb(int size) {
        ByteBuf buf = UnpooledByteBufAllocator.DEFAULT.buffer();
        for (int i = 0; i < size; i++) {
            buf.writeByte('a');
        }
        return buf;
    }


    class FlushSniffer extends ChannelOutboundHandlerAdapter {

        private boolean didFlush;

        public boolean checkFlush() {
            boolean r = didFlush;
            didFlush = false;
            return r;
        }

        @Override
        public void flush(ChannelHandlerContext ctx) throws Exception {
            didFlush = true;
            super.flush(ctx);
        }
    }

    @Test
    public void windowUpdatesAreFlushed() {
        LastInboundHandler inboundHandler = new LastInboundHandler();
        FlushSniffer flushSniffer = new FlushSniffer();
        parentChannel.pipeline().addFirst(flushSniffer);

        Http2StreamChannel childChannel = newInboundStream(3, false, inboundHandler);
        assertTrue(childChannel.config().isAutoRead());
        childChannel.config().setAutoRead(false);
        assertFalse(childChannel.config().isAutoRead());

        Http2HeadersFrame headersFrame = inboundHandler.readInbound();
        assertNotNull(headersFrame);
        // From the headers.
        assertTrue(flushSniffer.checkFlush());

        // childChannel.readState == IN_PROGRESS due to initial auto-read.
        frameInboundWriter.writeInboundData(childChannel.stream().id(), bb(1), 0, false);
        // readState == IDLE, flowControlledBytes = 1

        frameInboundWriter.writeInboundData(childChannel.stream().id(), bb(1020), 0, false);
        // readState == IDLE, flowControlledBytes = 1, 1 message(1020) buffered.
        assertTrue(flushSniffer.checkFlush());

        // This will trigger a read of the second message (1020 bytes).
        childChannel.read();
        assertTrue(flushSniffer.checkFlush()); // fails.
        // This should have flushed the window update of 1
        // flowControlledBytes = 1020

        childChannel.read();
        // triggered a flow control window updatte in DefaultHttp2LocalFlowCoontroller:465
        // flowControlledBytes = 0 <- we wrote the window update but didn't flush!
        assertTrue(flushSniffer.checkFlush()); // fails: no flush was called.

        Http2DataFrame data = inboundHandler.blockingReadInbound();
        release(data);
    }
```

There are a few problems that I see so far. 

* One is that on `beginRead()` we will write any flow bytes as an update frame and enter `doBeginRead()` but if there are no messages to be had we break out of the loop without flushing [here](https://github.com/netty/netty/blob/netty-4.1.43.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L805-L810).
* A second problem is that when we do write the window update we check if the promise is complete and if it is, we assume it's been flushed [here](https://github.com/netty/netty/blob/netty-4.1.43.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L848-L853). However, the Http2FrameCodec intercepts these frames and always just sets the promise to done [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L313). This may cause an explicit `flush()` call to be ineffective as the stream channel attempts to be clever about it and elid unnecessary flushes [here](https://github.com/netty/netty/blob/netty-4.1.43.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L1034).

### Netty version
branch 4.1, SHA e0d73bca4dd36910c7cdbe3d577c51aeb8287cc6 (Fri Feb 28)

### PR DESCRIPTION
**Pull request by bryce-anderson**
Motivation:

Under certain read patters the AbstractHttp2StreamChannel can fail to
flush, resulting in flow window starvation.

Modifications:

- Ensure we flush if we exit the `doBeginRead()` method.
- Account for the Http2FrameCodec always synchronously finishing writes
  of window update frames.

Result:

Fixes #10072

### CODE REVIEW

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2TestUtil.java [hunk 1]
```diff
@@ -687,6 +687,14 @@ static ByteBuf bb(String s) {
         return ByteBufUtil.writeUtf8(UnpooledByteBufAllocator.DEFAULT, s);
     }
 
+    static ByteBuf bb(int size) {
+        ByteBuf buf = UnpooledByteBufAllocator.DEFAULT.buffer();
+        for (int i = 0; i < size; i++) {
+            buf.writeByte('a');
+        }
+        return buf;
+    }
```
Comment (bryce-anderson) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/Http2TestUtil.java]: This feels like something that almost certainly exists somewhere else.

File: codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java [hunk 2]
```diff
@@ -920,58 +920,57 @@ public void write(Object msg, final ChannelPromise promise) {
             try {
                 if (msg instanceof Http2StreamFrame) {
                     Http2StreamFrame frame = validateStreamFrame((Http2StreamFrame) msg).stream(stream());
-                    if (!firstFrameWritten && !isStreamIdValid(stream().id())) {
```
Comment (bryce-anderson) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java]: This change isn't strictly necessary for this patch but I spent a fair amount of time trying to read through this for the nth time and decided to clean it up so the flow control is more readable. If desired, we can move it to a different patch.

File: codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java [hunk 3]
```diff
@@ -558,10 +558,7 @@ void fireChildRead(Http2Frame frame) {
             // read (unknown, reset) and the trade off is less conditionals for the hot path (headers/data) at the
             // cost of additional readComplete notifications on the rare path.
             if (allocHandle.continueReading()) {
-                if (!readCompletePending) {
-                    readCompletePending = true;
-                    addChannelToReadCompletePendingQueue();
-                }
```
Comment (bryce-anderson) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java]: These are also not strictly necessary but part of the general cleanup I was attempting to do so this is more readable in the future.

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2TestUtil.java (hunk 1 above)
Comment (normanmaurer) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/Http2TestUtil.java]: Just use bytebuf.writeZero(size); ?

Comment (bryce-anderson) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/Http2TestUtil.java]: Would you prefer I replace the body of this method with
`UnpooledByteBufAllocator.DEFAULT.buffer().writeZero(size)` or inline it in the best?

Comment (normanmaurer) [reply codec-http2/src/test/java/io/netty/handler/codec/http2/Http2TestUtil.java]: I dont care... I was just mention it as you said there is most likely something like this already :)

File: codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTest.java [hunk 4]
```diff
@@ -1152,6 +1152,66 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) {
         verifyFramesMultiplexedToCorrectChannel(childChannel, inboundHandler, 3);
     }
 
+    class FlushSniffer extends ChannelOutboundHandlerAdapter {
```
Comment (normanmaurer) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTest.java]: nit: private final static

**Comment by bryce-anderson** [comment]
@normanmaurer, presuming this gets accepted, what are the odds we could get a release relatively soon? I know this just missed the 4.1.46 release but this is a show stopper for us and looks to affect both clients and servers using the `MultiplexHandler`/`MultiplexCodec` API's.

**Comment by normanmaurer** [comment]
I think a release could be done within a week or so :)

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by bryce-anderson** [comment]
Fixed the order of `static`. I suppose I should have tested it before pushing. 🤦‍♂

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@bryce-anderson thanks a lot! nice work...
