### PR TITLE
Fix HTTP startline validation

### LINKED ISSUE #16020: Exception will be thrown if uri string contains the character 'M'.
https://github.com/netty/netty/blame/40ab4184d85f812199b1357efaabf49a25cb029b/codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java#L90

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
The code assumed that oversized bit shifting would result in zeroing out values due to overflow. However, the Java Language Specification instead says that shifts effectively only consider the lower six bits of the shift amount, resulting in modular-arithmetic shifts. The consequence is that, for instance, shifing by the capital letter 'M' produces the same bit mask as carriage-return '\r', which is an illegal character in an HTTP start line. This incorrectly rejected valid URIs.

Modification:
Make the shifting conditional and only use it on character values less than or equal to 64 (the Long bit size). Also add tests to check that valid URLs are accepted.

Result:
Fixes https://github.com/netty/netty/issues/16020

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java [hunk 1]
```diff
@@ -109,27 +109,31 @@ public static boolean isEncodingSafeStartLineToken(CharSequence token) {
...
             if ((ch & ILLEGAL_REQUEST_LINE_TOKEN_OCTET_MASK) != 0) {
                 return false;
             }
         }
         return true;
     }
 
+    private static long charMask(CharSequence token, int i) {
+        char c = token.charAt(i);
+        return c <= 64 ? 1L << c : 0;
```
Comment (yawkat) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java]:
```suggestion
        return c < 64 ? 1L << c : 0;
```

I wonder if there's some prior work on how to do this the most performant way. But for now it's most important to fix this logic, performance can come later

**Review by yawkat — APPROVED** [review]

**Comment by chrisvest** [comment]
As for performance, previously we had:

```
Benchmark                                      Mode  Cnt        Score       Error  Units
HttpRequestEncoderInsertBenchmark.newEncoder  thrpt   40  8424159.978 ± 31482.476  ops/s
HttpRequestEncoderInsertBenchmark.oldEncoder  thrpt   40  9775729.099 ± 18116.093  ops/s
```

And in this PR:

```
Benchmark                                      Mode  Cnt        Score       Error  Units
HttpRequestEncoderInsertBenchmark.newEncoder  thrpt   40  7769854.953 ± 22560.981  ops/s
```

😑

**Comment by yawkat** [comment]
Yea, not ideal and I'm sure this can still be optimized, it should be a relatively common task... But let's get the fix out first.

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java [hunk 2]
```diff
@@ -109,27 +109,31 @@ public static boolean isEncodingSafeStartLineToken(CharSequence token) {
...
             if ((ch & ILLEGAL_REQUEST_LINE_TOKEN_OCTET_MASK) != 0) {
                 return false;
             }
         }
         return true;
     }
 
+    private static long charMask(CharSequence token, int i) {
+        char c = token.charAt(i);
+        return c < 64 ? 1L << c : 0;
```
Comment (franz1981) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java:131]: Why not using s lookup table for this or 
long mask = ((c - 64) >> 63);
return mask & (1L << c);

Assuming c to be >= 0.
I made it by phone so could be wrong but I think you got the idea; mask should use the msb to create a full 0s or 1s mask to produce the actual value. In this way there won't be any comparison.
A lookup table could be used similarly by computing an index to lookup into a table with N + 1 elements

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java [hunk 3]
```diff
@@ -109,27 +109,31 @@ public static boolean isEncodingSafeStartLineToken(CharSequence token) {
...
         for (; i < lenInts; i += 4) {
-            long chars = 1L << token.charAt(i) |
-                    1L << token.charAt(i + 1) |
-                    1L << token.charAt(i + 2) |
-                    1L << token.charAt(i + 3);
+            long chars = charMask(token, i) |
+                    charMask(token, i + 1) |
+                    charMask(token, i + 2) |
+                    charMask(token, i + 3);
             if ((chars & ILLEGAL_REQUEST_LINE_TOKEN_OCTET_MASK) != 0) {
```
Comment (franz1981) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java:116]: I am not sure batching would pay off here: validations are a strange affair!
If we assume is rare to return false, computing the 4 ors and one and with the illegal request line is still not ideal!
Just writing straight comparison chart per char (no need to or and batch) should perform 4 more ands (which are bad) and 4 comparisons, but will make the loads independent..in short comparison outcomes are processed even before CPU does fetch and decode and keeping the 4 char loads independent would make the pipeline able to keep on speculating and processing more chars.

**Review by franz1981 — CHANGES_REQUESTED** [review]

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java (hunk 3 above)
Comment (franz1981) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java:116]: It could payoff only If we could use VarHandle and read from a byte[] 4 chars in parallel into a long, saving 3 loads to happen.
Clearly charMask should use the branchless version I explained and be made batchy as well

Comment (franz1981) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java:116]: In short, I would try just the simple loop case here (using the branchless code I have provided)

**Comment by chrisvest** [comment]
@franz1981 I tried your suggestions but I'm not finding them profitable on my system. Batching and using the conditional remains the fastest approach so far.

**Comment by chrisvest** [comment]
With the masking from https://github.com/netty/netty/pull/16022#discussion_r2615541770

```
Benchmark                                      Mode  Cnt        Score       Error  Units
HttpRequestEncoderInsertBenchmark.newEncoder  thrpt   40  7507408.848 ± 34941.536  ops/s
```

With conditional in charMask but no batching:

```
Benchmark                                      Mode  Cnt        Score       Error  Units
HttpRequestEncoderInsertBenchmark.newEncoder  thrpt   40  7366827.935 ± 78521.744  ops/s
```

With both suggestions together:

```
Benchmark                                      Mode  Cnt        Score        Error  Units
HttpRequestEncoderInsertBenchmark.newEncoder  thrpt   40  6888067.919 ± 124853.544  ops/s
```

**Review by normanmaurer — APPROVED** [review]

**Comment by franz1981** [comment]
I will check on my Ryzen next week but my guess is that you haven't enough random samples w a distribution of chars below/above 64. If the validation is really stressed, branch mispredict should be rather dominant when happen, in my XP

**Comment by franz1981** [comment]
Indeed HttpRequestEncoderInsertBenchmark is just way too predictable to represent a valid benchmark (if we assume in the real world chars really can be both below/above 64 - which separate numbers from letters, for example)

**Comment by normanmaurer** [comment]
Let me pull it in as it is for now to fix the regression. We can work on perf improvements as a followup
