### PR TITLE
Fix #10449, buffer.getBytes(...) not change a file channel position

### LINKED ISSUE #10449: FileUpload.get() created by a HttpPostMultipartRequestDecoder returns incomplete array on 4.1.51
### Expected behavior

UploadFile.get() should return the full byte array uploaded.

### Actual behavior

It appears that although `fileUpload.length()` returns the correct value, the byte array from `get()` returns only a partial array.

### Steps to reproduce

Create a `HttpPostMultipartRequestDecoder` and call offer at least twice with some request form data. The test below passes on 4.1.50 but fails on 4.1.51.

### Minimal yet complete reproducer code (or URL to code)

````java
@Test
public void fileUploadRegression() throws IOException {
    byte[] file = new byte[32000];
    Arrays.fill(file, (byte) 1);

    String body = "--861fbeab-cd20-470c-9609-d40a0f704466\n" +
        "Content-Disposition: form-data; name=\"image\"; filename=\"guangzhou.jpeg\"\n" +
        "Content-Type: image/jpeg\n" +
        "Content-Length: " + file.length + "\n" +
        "\n" + new String(file, UTF_8) + "\n" +
        "--861fbeab-cd20-470c-9609-d40a0f704466--\n";
    byte[] bodyBytes = body.getBytes(UTF_8);

    HttpRequest request = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/upload");
    request.headers().set("content-type", "multipart/form-data; boundary=861fbeab-cd20-470c-9609-d40a0f704466");
    request.headers().set("content-length", bodyBytes.length);
    HttpPostMultipartRequestDecoder decoder = new HttpPostMultipartRequestDecoder(request);
    decoder.offer(new DefaultHttpContent(Unpooled.copiedBuffer(bodyBytes, 0, 8192)));
    decoder.offer(new DefaultHttpContent(Unpooled.copiedBuffer(bodyBytes, 8192, bodyBytes.length - 8192)));
    decoder.offer(new DefaultLastHttpContent());
    FileUpload data = (FileUpload) decoder.getBodyHttpDatas().get(0);
    assertThat(data.length(), is((long)file.length)); // passes
    assertThat(data.get().length, is(file.length)); // fails on 4.1.51
}
````

### Netty version

4.1.51

### JVM version (e.g. `java -version`)

Multiple versions tested (8, 10, 11, 12). 

### OS version (e.g. `uname -a`)

Windows, Linux.

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:

Regression appeared after making changes in fix #10360 .
The main problem here that `buffer.getBytes(buffer.readerIndex(), fileChannel, fileChannel.position(), localsize)`
doesn't change channel position after writes.

Modification:

Manually set position according to the written bytes.

Result:

Fixes #10449 .

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java [hunk 1]
```diff
@@ -156,17 +156,20 @@ public void addContent(ByteBuf buffer, boolean last)
...
                     RandomAccessFile accessFile = new RandomAccessFile(file, "rw");
                     fileChannel = accessFile.getChannel();
                 }
-                buffer.getBytes(buffer.readerIndex(), fileChannel, fileChannel.position(), localsize);
+                long currentPosition = fileChannel.position();
+                int written = buffer.getBytes(buffer.readerIndex(), fileChannel, currentPosition, localsize);
+                if (written > 0) {
+                    fileChannel.position(currentPosition + written);
+                    buffer.readerIndex(buffer.readerIndex() + written);
+                }
```
Comment (njhill) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:171]: I think this may actually need to be a loop since it's not guaranteed to write all of the bytes in a single invocation

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:171]: @amizurov I think @njhill is right here... can you adjust this please ?

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:175]: Sure, according java docs it depends on implementation.

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java (hunk 1 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:175]: instead of `if (written > 0)`, you might better inverse the test to `if (written < 0)` which stands for end of file/channel, therefore giving a break of the `while` loop ?

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:175]: or `if (written <= 0)` since the javadoc does not specify negative result (as in standard Java interaction with file or stream). The idea is to have a clear "break" code, and therefore to not rely only on while condition.

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:175]: @amizurov ^^

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:179]: I changed code according suggestion but i'm not sure is it ok if we break from loop but possible not all data is written or maybe i'm confused :)

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:179]: @amizurov I think we should only break on `< 0` as `0` is valid.

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:177]: Ok, also moved change position and buffer reader index from loop

**Comment by fredericBregier** [comment]
Lgtm

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java [hunk 2]
```diff
@@ -156,17 +156,28 @@ public void addContent(ByteBuf buffer, boolean last)
...
-                int written = 0;
                 if (file == null) {
                     file = tempFile();
                 }
                 if (fileChannel == null) {
                     RandomAccessFile accessFile = new RandomAccessFile(file, "rw");
                     fileChannel = accessFile.getChannel();
                 }
-                buffer.getBytes(buffer.readerIndex(), fileChannel, fileChannel.position(), localsize);
+                int totalWritten = 0;
```
Comment (njhill) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:166]: nit: would be tiny bit simpler to do decrement remaining instead

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java (hunk 2 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:166]: @njhill sorry do you mean decrement `localsize` variable or something like this:
```
int remaining = localsize;
long position = fileChannel.position();
int index = buffer.readerIndex();
while (remaining > 0) {
   int written = buffer.getBytes(index, fileChannel, position, remaining);
   if (written < 0) {
      break;
   }
   remaining -= written;
   position += written;
   index += written;
}
fileChannel.position(position);
buffer.readerIndex(index);
size += localsize - remaining;
```

Comment (njhill) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:166]: @amizurov yes exactly, except to match the current logic the last line would still be just
```java
size += localsize;
```

But noticing that, it looks like this current (now merged) logic is actually slightly wrong and that (ignoring the `remaining` suggestion) this would be more correct:
```java
size += totalWritten;
```
i.e. to keep state consistent in the case where we exit prematurely due to `written < 0` (not sure it's realistic case but since we're handling it, should be done correctly)

WDYT? (cc @normanmaurer)

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:166]: @njhill yeah... Want to do a PR ?

Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java:166]: @njhill, @normanmaurer  I'll create separate PR with code above if you don't mind
