### PR TITLE
Let object serialisation exceptions propagate in the Object Echo example

### LINKED ISSUE #10777: suggestion: netty/example/objectecho inform about missing "implements Serializable" on client side
Hello,

as new user i wanted to try Objectecho "Example", and was confused when i sent **Serializable Object** that were **containing** an **"non-serializable" Object** as some depth field(that i didnt notice earlier), it was not sent at all, and i received no information at all. It took me time to debug and notice that one of its fields was an object that didnt implement Serializable.

Thats why i just throw some suggestion to add into "Objectecho Example" some new user friendly code to inform about it like:

**1)** some "Objectecho Example"  class extending ObjectEncoder:

    @Override
    public boolean acceptOutboundMessage(Object msg) throws Exception {
        if(!super.acceptOutboundMessage(msg)){
            // some information
        }
        return true;
    }

**OR**

(i didnt try enable Asserts, so if you use some, this option might be better)
**2)** **Just add comment about it**, to let new users know they will receive NO information when trying to send complex Objects that in some depth contains non-serializable Object.

**Please note this refer only to "Objectecho Example"  and Encoder (so its client side).** 

Just thought it could be helpfull for new users having same problem.

### Expected behavior

- some warning/error/information for "Objectecho Example"  if there is missing Serializable

### Actual behavior

- Demo give NO information if sent object do not match, client and server print **no information/warning/error at all.**

### Steps to reproduce

- in "Objectecho Example"  try sent Serializable object with not serializable Object in it, it will not be sent and no information will be printed anywhere. Also comments do not mention anything about it.

### Netty version

4.1.43

And ofc, hello to netty users/devs ;)

Please close it if "Objectecho Example" is not prepared for new users and its for testing purpose, or if you think its not needed, since its just suggestion.

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
People may use the object serialisation example as a vehicle to test out sending their own objects across the wire.
If those objects are not actually serialisable for some reason, then we need to let the exception propagate so that this becomes obvious to people.

Modification:
Add a listener to the future that sends the first serialisable message, so that we ensure that any exceptions that shows up during serialisation becomes visible.
Without this, the state of the future that sent the first message was never checked or inspected anywhere.

Result:
Serialisation bugs in code derived from the Object Echo example are much easier to diagnose.

This fixes #10777

### CODE REVIEW

File: example/src/main/java/io/netty/example/objectecho/ObjectEchoClientHandler.java [hunk 1]
```diff
@@ -41,9 +42,10 @@ public ObjectEchoClientHandler() {
     }
 
     @Override
-    public void channelActive(ChannelHandlerContext ctx) {
+    public void channelActive(ChannelHandlerContext ctx) throws Exception {
         // Send the first message if this handler is a client-side handler.
-        ctx.writeAndFlush(firstMessage);
+        ChannelFuture future = ctx.writeAndFlush(firstMessage);
+        future.sync(); // Let object serialisation exceptions propagate.
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/objectecho/ObjectEchoClientHandler.java:48]: @chrisvest this doesn't work as this will block the eventloop. Use a `ChannelFutureListener`

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Comment by chrisvest** [comment]
@normanmaurer Fixed! Please take a look.

**Review by normanmaurer — APPROVED** [review]

File: example/src/main/java/io/netty/example/objectecho/ObjectEchoClientHandler.java [hunk 2]
```diff
@@ -41,9 +45,10 @@ public ObjectEchoClientHandler() {
     }
 
     @Override
-    public void channelActive(ChannelHandlerContext ctx) {
+    public void channelActive(ChannelHandlerContext ctx) throws Exception {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/objectecho/ObjectEchoClientHandler.java:48]: please revert this change ^^

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Comment by chrisvest** [comment]
@normanmaurer Done.
