### PR TITLE
Fix #10261 stomp can be chunked, so implement StompWebSocketFrameEncoder

### LINKED ISSUE #10261: why stomp.js can not get the message body
### Expected behavior
Expect the stomp.js can use netty stomp send a messge to a topic and other stomp.js can receive the message.
### Actual behavior
when Iuse netty stomp send a messge to a topic and other stomp.js  receive the message,I found the stomp.js client can not recevice the message the message body is empty. In the web brower network console chosse ws you will find the message is split to two message .
### Steps to reproduce
use the code in package io.netty.example.stomp  and start the server, use stomp.js send a messge to a topic and other stomp.js receive the message.
### Netty version
4.1.49.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_231"
### OS version (e.g. `uname -a`)
windows 10

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:

Current implementation `StompSubframeEncoder` can encode `StompFrame` into several separate chunks or encode separately `StompHeadersSubframe` and `StompContentSubframe`. But some client libraries (e.g. stomp.js) do not support aggregation.

Modification:

Add StompWebSocketFrameEncoder for integration between origin stomp suframe encoder and `ContinuationWebSocketFrame` to support  chunks on transport level.

Result:

Fixes #10261

### CODE REVIEW

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java [hunk 1]
```diff
@@ -15,33 +15,34 @@
...
+import io.netty.handler.codec.stomp.StompSubframe;
 import io.netty.handler.codec.stomp.StompSubframeAggregator;
 import io.netty.handler.codec.stomp.StompSubframeDecoder;
-import io.netty.handler.codec.stomp.StompSubframeEncoder;
 
 import java.util.List;
 
 @Sharable
-public class StompWebSocketProtocolCodec extends MessageToMessageCodec<WebSocketFrame, ByteBuf> {
+public class StompWebSocketProtocolCodec extends MessageToMessageCodec<WebSocketFrame, StompSubframe> {
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java:33]: @amizurov unfortunately this is a a breaking change as it changes the method signature of some methods

Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java:33]: Yes but this is only example, maybe you can advice another way ?

Comment (normanmaurer) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketProtocolCodec.java:33]: ah sorry missed that... Changing an example is of course fine.

File: example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketFrameEncoder.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+            }
+        } else if (msg instanceof StompHeadersSubframe) {
+            webSocketFrame = new TextWebSocketFrame(false, 0, getFirst(out));
+        } else if (msg instanceof LastStompContentSubframe) {
+            webSocketFrame = new ContinuationWebSocketFrame(true, 0, getFirst(out));
+        } else {
+            webSocketFrame = new ContinuationWebSocketFrame(false, 0, getFirst(out));
+        }
+
+        out.clear();
```
Comment (normanmaurer) [inline example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketFrameEncoder.java:61]: hmm... is this really correct for the case where `msg` isn't an instance of `StompFrame ` ? Seems like you may loose items here then.

Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketFrameEncoder.java:61]: We use this encoder inside `StompWebSocketProtocolCodec` so we accept only `StompSubframe` and don't put it to pipeline, just delegate.

Comment (normanmaurer) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketFrameEncoder.java:61]: still this seems very error-prone. At least we should add an assert imho

Comment (amizurov) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketFrameEncoder.java:61]: Sorry could you please explain what kind of assertion you mean ?

Comment (normanmaurer) [reply example/src/main/java/io/netty/example/stomp/websocket/StompWebSocketFrameEncoder.java:61]: never mind

**Comment by normanmaurer** [comment]
@netty-bot test this please
