### PR TITLE
Fix Zstd compression for large data

### LINKED ISSUE #14972: Zstd compression fails for sources larger than 31MB
The [ZstdEncoder](https://github.com/netty/netty/blob/netty-4.1.118.Final/codec/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java#L99-L125) will fail for outputs larger than 31MB (`io.netty.handler.codec.compression.ZstdConstants#MAX_BLOCK_SIZE`).

From what I can see, it tries to allocate a buffer for the complete output size instead of processing it in chunks.

This is a quick and dirty reproducer generated via Gemini, which highlights this behavior.

This request will fail, while `br`, `gzip`, and `deflate` succeed without a problem.
```
GET http://localhost:18080/
Accept-Encoding: zstd
```

```java
import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.Unpooled;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.SimpleChannelInboundHandler;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.http.DefaultFullHttpResponse;
import io.netty.handler.codec.http.FullHttpResponse;
import io.netty.handler.codec.http.HttpContentCompressor;
import io.netty.handler.codec.http.HttpHeaderNames;
import io.netty.handler.codec.http.HttpHeaderValues;
import io.netty.handler.codec.http.HttpRequest;
import io.netty.handler.codec.http.HttpResponseStatus;
import io.netty.handler.codec.http.HttpServerCodec;
import io.netty.handler.codec.http.HttpUtil;
import io.netty.handler.codec.http.HttpVersion;
import io.netty.handler.logging.LogLevel;
import io.netty.handler.logging.LoggingHandler;
import io.netty.util.CharsetUtil;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.MappedByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.ThreadLocalRandom;

public class NettyHttpServer {

    private static final int SERVER_PORT = 18080;
    private static final String JSON_CONTENT_TYPE = "application/json; charset=UTF-8";
    private static final long FILE_SIZE_BYTES = 32 * 1024 * 1024; // 32MB
    private static final String FILE_NAME = "large.json";

    public static void main(String[] args) throws Exception {
        // Create a dummy 32MB JSON file.
        File file = createLargeJsonFile(FILE_NAME, FILE_SIZE_BYTES);

        EventLoopGroup bossGroup = new NioEventLoopGroup(1); // Use a single thread for the boss group.
        EventLoopGroup workerGroup = new NioEventLoopGroup();
        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup)
                .channel(NioServerSocketChannel.class)
                .option(ChannelOption.SO_BACKLOG, 128)
                .childOption(ChannelOption.SO_KEEPALIVE, true)
                .childOption(ChannelOption.TCP_NODELAY, true) // Disable Nagle's algorithm for low latency.
                .handler(new LoggingHandler(LogLevel.INFO)) // Add logging handler to see what's happening
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    public void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast(
                            new HttpServerCodec(),         // HTTP codec (encoder and decoder)
                            new HttpContentCompressor(),   // Optional: Enable compression.
                            new LargeJsonFileHandler(file) // Our handler to serve the large JSON file
                        );
                    }
                });

            // Bind and start to accept incoming connections.
            ChannelFuture f = b.bind(SERVER_PORT).sync();
            System.out.println("Server started at port " + SERVER_PORT);

            // Wait until the server socket is closed.
            f.channel().closeFuture().sync();
        } finally {
            workerGroup.shutdownGracefully();
            bossGroup.shutdownGracefully();
        }
    }

    private static class LargeJsonFileHandler extends SimpleChannelInboundHandler<HttpRequest> {
        private final File file;

        public LargeJsonFileHandler(File file) {
            this.file = file;
        }

        @Override
        protected void channelRead0(ChannelHandlerContext ctx, HttpRequest req) throws Exception {
            // Handle only GET requests.
            if (!req.method().name().equalsIgnoreCase("GET")) {
                FullHttpResponse response = new DefaultFullHttpResponse(
                    req.protocolVersion(), HttpResponseStatus.METHOD_NOT_ALLOWED,
                    Unpooled.copiedBuffer("Method Not Allowed", CharsetUtil.UTF_8));
                response.headers().set(HttpHeaderNames.CONTENT_TYPE, "text/plain; charset=UTF-8");
                ctx.writeAndFlush(response).addListener(io.netty.channel.ChannelFutureListener.CLOSE);
                return;
            }

            final long fileLength = file.length();
            RandomAccessFile raf = new RandomAccessFile(file, "r");
            FileChannel fc = raf.getChannel();
            MappedByteBuffer mappedByteBuffer = fc.map(FileChannel.MapMode.READ_ONLY, 0, fileLength);

            FullHttpResponse response = new DefaultFullHttpResponse(req.protocolVersion(), HttpResponseStatus.OK, Unpooled.wrappedBuffer(mappedByteBuffer));

            HttpUtil.setContentLength(response, fileLength);
            response.headers().set(HttpHeaderNames.CONTENT_TYPE, JSON_CONTENT_TYPE);
            response.headers().set(HttpHeaderNames.CONNECTION, HttpHeaderValues.KEEP_ALIVE); // Use keep-alive

            // Write the response.  Netty handles the file transfer.
            ctx.writeAndFlush(response);

            // Important: Close the channel *after* the write operation completes.
            ctx.writeAndFlush(Unpooled.EMPTY_BUFFER).addListener(io.netty.channel.ChannelFutureListener.CLOSE);

            // No need to close the RandomAccessFile or FileChannel here.  The MappedByteBuffer
            // holds a reference to the file, and closing them prematurely can cause
            // a java.nio.channels.ClosedChannelException.  The file will be released
            // when the MappedByteBuffer is garbage collected.
        }

        @Override
        public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
            cause.printStackTrace();
            if (ctx.channel().isActive()) {
                FullHttpResponse response = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1,
                    HttpResponseStatus.INTERNAL_SERVER_ERROR,
                    Unpooled.copiedBuffer("Internal Server Error: " + cause.getMessage(), CharsetUtil.UTF_8));
                response.headers().set(HttpHeaderNames.CONTENT_TYPE, "text/plain; charset=UTF-8");
                ctx.writeAndFlush(response).addListener(io.netty.channel.ChannelFutureListener.CLOSE);
            }
        }
    }

    private static File createLargeJsonFile(String fileName, long fileSizeInBytes) throws IOException {
        File file = new File(fileName);
        if (file.exists()) {
            file.delete(); // Delete the file if it already exists
        }
        try (RandomAccessFile raf = new RandomAccessFile(file, "rw")) {
            raf.setLength(fileSizeInBytes); // Pre-allocate the file size
            // Fill the file with JSON-like data.  We'll just repeat a large object.
            long written = 0;
            StringBuilder sb = new StringBuilder(1024);
            // Create a sample JSON object
            sb.append("{");
            for (int i = 0; i < 20; i++) { // Add 20 fields to the object
                sb.append("\"field").append(i).append("\":\"").append(generateRandomString(100)).append("\","); // 100 character string
            }
            sb.append("\"lastField\":\"").append(generateRandomString(100)).append("\"");
            sb.append("}");
            String jsonObject = sb.toString();
            byte[] jsonBytes = jsonObject.getBytes(StandardCharsets.UTF_8);
            while (written < fileSizeInBytes) {
                //Write in chunks
                raf.write(jsonBytes);
                written += jsonBytes.length;
            }
            return file;
        }
    }

    private static String generateRandomString(int length) {
        final String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder sb = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            int randomIndex = ThreadLocalRandom.current().nextInt(characters.length());
            sb.append(characters.charAt(randomIndex));
        }
        return sb.toString();
    }
}
```

### PR DESCRIPTION
**Pull request by skyguard1**
Motivation:

Zstd compression fails for sources larger than 31MB since the default max encode size is 32M. This is PR is to change default max encode size to `Integer.MAX_VALUE` so that `ZstdEncoder` can works for large data

Modification:

Change default max encode size to `Integer.MAX_VALUE` so that `ZstdEncoder` can works for large data

Result:

Fixes #14972

`ZstdEncoder` can works for the large data

### CODE REVIEW

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 1]
```diff
@@ -37,12 +37,21 @@ public class ZstdEncoderTest extends AbstractEncoderTest {
     @Mock
     private ChannelHandlerContext ctx;
 
+    protected static final byte[] BYTES_HUGE = new byte[256 * 1024 * 1024];
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: I think it would be better to just allocate this in `hugeData` so it can be GC'ed once the test completes.

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 2]
```diff
@@ -43,6 +43,14 @@ public void setup() {
         when(ctx.alloc()).thenReturn(ByteBufAllocator.DEFAULT);
     }
 
+    public static ByteBuf[] hugeData() {
+        final byte[] bytesHuge = new byte[256 * 1024 * 1024];
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: Can we just use something slightly larger then 32MB so we still validate that the fix work while not need to reserve too much memory for the test ?

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java (hunk 1 above)
Comment (skyguard1) [reply codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: Done

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java (hunk 2 above)
Comment (skyguard1) [reply codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]: Done

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java [hunk 3]
```diff
@@ -113,7 +113,7 @@ protected ByteBuf allocateBuffer(ChannelHandlerContext ctx, ByteBuf msg, boolean
         while (remaining > 0) {
             int curSize = Math.min(blockSize, remaining);
             remaining -= curSize;
-            bufferSize += Zstd.compressBound(curSize);
+            bufferSize = Math.max(bufferSize, Zstd.compressBound(curSize));
```
Comment (normanmaurer) [inline codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java:118]: Why this change ? Can you add a comment please ?

File: codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java [hunk 4]
```diff
@@ -51,6 +59,16 @@ public EmbeddedChannel createChannel() {
...
+        testCompressionOfLargeDataBatchedFlow(data);
+    }
+
+    @ParameterizedTest
+    @MethodSource("hugeData")
+    public void testCompressionOfHugeBatchedFlow(final ByteBuf data) throws Exception {
+        testCompressionOfLargeDataBatchedFlow(data);
+    }
+
+    public void testCompressionOfLargeDataBatchedFlow(final ByteBuf data) throws Exception {
```
Comment (normanmaurer) [inline codec-compression/src/test/java/io/netty/handler/codec/compression/ZstdEncoderTest.java]:
```suggestion
    private void testCompressionOfLargeDataBatchedFlow(final ByteBuf data) throws Exception {
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java (hunk 3 above)
Comment (skyguard1) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java:118]: This is from [blacelle](https://github.com/blacelle) suggestion in https://github.com/netty/netty/issues/14972#issuecomment-3532156523, I think what he said make sense since the `Zstd.compressBound` returns the maximum size of the compressed data

Comment (normanmaurer) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java:118]: got it... then please add a comment that compressBound returns the maximum size.

Comment (skyguard1) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdEncoder.java:118]: Sure

File: codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdConstants.java [hunk 5]
```diff
@@ -37,7 +37,7 @@ final class ZstdConstants {
     /**
      * Max block size
      */
-    static final int MAX_BLOCK_SIZE = 1 << (DEFAULT_COMPRESSION_LEVEL + 7) + 0x0F;   //  32 M
+    static final int MAX_BLOCK_SIZE = Integer.MAX_VALUE;
```
Comment (blacelle) [inline codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdConstants.java]: I have an issue interpreting the RFC.

https://datatracker.ietf.org/doc/html/rfc8478#section-3.1.1.2.3

I read:

>    The upper 21 bits of Block_Header represent the Block_Size.
   Block_Size is the size of the block excluding the header.  A block
   can contain any number of bytes (even zero), up to
   Block_Maximum_Decompressed_Size, which is the smallest of:
> -  Window_Size
> -  128 KB

Does it mean a blockSize has to be lower than 128KB ? It looks fairly low to me, and it may be unrelated to this PR change (I'm no expert in Zstd).

I mean, do we have a unitTest actually testing a large blockSize? (again blockSize != decodeSize, and I understand decodeSize (as worded in Netty) refers to windowSize (as referred in the RFC)).

Comment (skyguard1) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdConstants.java]: Zstd use the block compression. While the size of a single block is constrained (the maximum being 128 KB or the smaller value in Window_Size), data larger than 128 KB can be split into multiple blocks for compression.

Comment (normanmaurer) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdConstants.java]: Should we maybe rename the field to make it more clear what this is all about ?

Comment (blacelle) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdConstants.java]: If `MAX_BLOCK_SIZE` is a maximum encode size/ maximum window size, it should definitely be renamed.

Should we add an actual `MAX_BLOCK_SIZE` with `128K` value, and ensure `blockSize` is lower than `MAX_BLOCK_SIZE=128K`?

Comment (skyguard1) [reply codec-compression/src/main/java/io/netty/handler/codec/compression/ZstdConstants.java]: `ZsdEncoder` depends on [zstd-jni](https://github.com/luben/zstd-jni) implementation, which I don't think is implemented in Netty. zstd-jni implement the zstd compression algorithm

**Comment by normanmaurer** [comment]
@yawkat PTAL as well

**Review by yawkat — APPROVED** [review]
