### PR TITLE
Fix classloader leaks in GlobalEventExecutor

### LINKED ISSUE #14615: GlobalEventExecutor.terminationFailure - classloader leak with plugin-like classloaders
### Expected behavior

When netty in on the main classpath, and plugins are dynamically loaded and unloaded, there are no memory leaks that link from netty to the unloaded classloader.

### Actual behavior
GlobalEventExecutor.termiantionFailure leaks classloader of the first class accessing it, by storing the stacktrace

Workaround - manually null the stacktrace array after initialization
Proposed fix - switch to a stackless cached exception or avoid caching it

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L83

### Steps to reproduce
Provide netty in main classpath, and run something from GlobalEventExecutor from a plugin classloader

### Netty version
4.1.114

### JVM version (e.g. `java -version`)
OpenJDK 21

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
If Netty is on a main classpath in a system that creates ephemeral classloaders, e.g. for plug-ins, then we should avoid holding on to those ephemeral classloaders.

Modification:
Clear the stack trace in the GlobalEventExecutor termination future, because the stack trace would hold on to class which in turn hold on to class loaders, and it would hold on to an ephemeral classloader if the GEE was first initialized by code in an ephemeral classloader.

Also avoid holding on to context classloaders through the Thread.inheritedAccessControlContext when starting the GEE thread.

Result:
Classloader leaks should be fix.

Fixes #14615

### CODE REVIEW

File: common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java [hunk 1]
```diff
@@ -230,28 +235,38 @@ private void execute0(@Schedule Runnable task) {
...
-                }
-            });
-
-            // Set the thread before starting it as otherwise inEventLoop() may return false and so produce
-            // an assert error.
-            // See https://github.com/netty/netty/issues/4357
-            thread = t;
-            t.start();
+            ClassLoader parentCCL = Thread.currentThread().getContextClassLoader();
+            setContextClassLoader(Thread.currentThread(), null);
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java:239]:
```suggestion
            Thread current = Thread.currentThread();
            ClassLoader parentCCL = current.getContextClassLoader();
            setContextClassLoader(current, null);
```

File: common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java [hunk 2]
```diff
@@ -230,28 +235,38 @@ private void execute0(@Schedule Runnable task) {
...
+                // - https://bugs.openjdk.java.net/browse/JDK-7008595
+                setContextClassLoader(t, null);
+
+                // Set the thread before starting it as otherwise inEventLoop() may return false and so produce
+                // an assert error.
+                // See https://github.com/netty/netty/issues/4357
+                thread = t;
+                t.start();
+            } finally {
+                setContextClassLoader(Thread.currentThread(), parentCCL);
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java:255]:
```suggestion
                setContextClassLoader(current, parentCCL);
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Comment by franz1981** [comment]
@gsmet as well :)

**Review by normanmaurer — APPROVED** [review]
