### PR TITLE
Don't swallow intermediate write failures in MessageToMessageEncoder

### LINKED ISSUE #8429: ChannelOption for FIRE_EXCEPTION_ON_FAILURE?
I want to be able to react to *any* outbound channel failure.

I can add a handler to the tail of my pipeline that will call `promise.addListener(ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE)` for every outbound event, but this is not sufficient.

Specifically, in the case of a `MessageToMessageEncoder` that outputs more than one object, new promises are created for all but the last object:
https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java#L112-L127

If one of those objects then triggers a failure on a subsequent outbound handler, the exception is suppressed.  There might be other scenarios where this can happen as well.

How can I react to these failures when I don't have the opportunity to inject a `ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE`?

Would it be reasonable to have a `ChannelOption` for `FIRE_EXCEPTION_ON_FAILURE`?

### Netty version

4.1.30.Final

### PR DESCRIPTION
**Pull request by bryce-anderson**
Motivation:

If the encoder needs to flush more than one outbound message it will
create a new ChannelPromise for all but the last write which will
swallow failures.

Modification:

Use a PromiseCombiner in the case of multiple messages and the parent
promise isn't the `VoidPromise`.

Result:

Intermediate failures are propagated to the original ChannelPromise.

Fixes #8429.

### CODE REVIEW

**Comment by bryce-anderson** [comment]
A much simpler alternative is to use the `VoidPromise` instead of a new, discarded, `ChannelPromise` for the intermediate writes. The behavior there would be to propagate the exceptions via the `exceptionCaught` pathway which is what the original issue actually wanted.

File: codec/src/test/java/io/netty/handler/codec/MessageToMessageEncoderTest.java [hunk 1]
```diff
@@ -37,4 +42,36 @@ protected void encode(ChannelHandlerContext ctx, Object msg, List<Object> out) t
...
+                    firstWritten = true;
+                    promise.setFailure(firstWriteException);
+                }
+            }
+        };
+
+        EmbeddedChannel channel = new EmbeddedChannel(writeThrower, encoder);
+        Object msg = new Object();
+        ChannelFuture write = channel.writeAndFlush(msg);
+        assertEquals(firstWriteException, write.cause());
```
Comment (normanmaurer) [inline codec/src/test/java/io/netty/handler/codec/MessageToMessageEncoderTest.java]: Call channel.finish() and asset the return value

File: codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java [hunk 2]
```diff
@@ -108,28 +109,36 @@ public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise)
...
+                        writePromiseCombiner(ctx, out, promise);
                     }
-                    ctx.write(out.getUnsafe(sizeMinusOne), promise);
                 }
                 out.recycle();
             }
         }
     }
 
+    private void writeVoidPromise(ChannelHandlerContext ctx, CodecOutputList out) {
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java]: static

File: codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java [hunk 3]
```diff
@@ -108,28 +109,36 @@ public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise)
...
+        final ChannelPromise voidPromise = ctx.voidPromise();
+        for (int i = 0; i < out.size(); i++) {
+            ctx.write(out.getUnsafe(i), voidPromise);
+        }
+    }
+
+    private void writePromiseCombiner(ChannelHandlerContext ctx, CodecOutputList out, ChannelPromise promise) {
```
Comment (normanmaurer) [inline codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java]: Static

**Comment by normanmaurer** [comment]
@bryce-anderson this will not work in some cases as the VoidPromise will not allow to add listeners in any other handler

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec/src/test/java/io/netty/handler/codec/MessageToMessageEncoderTest.java [hunk 4]
```diff
@@ -37,4 +42,37 @@ protected void encode(ChannelHandlerContext ctx, Object msg, List<Object> out) t
...
+        assertEquals(msg, channel.readOutbound());
```
Comment (normanmaurer) [inline codec/src/test/java/io/netty/handler/codec/MessageToMessageEncoderTest.java]: nit: you may want to use `assertSame`

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java [hunk 5]
```diff
@@ -108,28 +109,36 @@ public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise)
...
-                    ctx.write(out.getUnsafe(sizeMinusOne), promise);
                 }
                 out.recycle();
             }
         }
     }
 
+    private static void writeVoidPromise(ChannelHandlerContext ctx, CodecOutputList out) {
+        final ChannelPromise voidPromise = ctx.voidPromise();
+        for (int i = 0; i < out.size(); i++) {
```
Comment (johnou) [inline codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java]: why are we using out.size() here when the original code used sizeMinusOne?

Comment (johnou) [reply codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java]: oh right it loops the first bunch then writes the last..

Comment (normanmaurer) [reply codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java]: good catch! @bryce-anderson please fix and adjust test to catch this

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@bryce-anderson thanks a lot!
