### PR TITLE
Merge WebSocket extensions, close #10792

### LINKED ISSUE #10792: WebSocketClientExtensionHandler doesn't check if extensions are already present in sec-websocket-extensions header
### Expected behavior

Netty verifies that extensions are not already present in sec-websocket-extensions header before appending them.

### Actual behavior

Netty doesn't check, possibly resulting in duplicated values.

### Steps to reproduce

Just read existing code: https://github.com/netty/netty/blob/netty-4.1.54.Final/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketClientExtensionHandler.java#L65-L73

### Netty version

4.1.54

### JVM version (e.g. `java -version`)

Irrelevant

### OS version (e.g. `uname -a`)

Irrelevant

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

We currently append extensions to the user defined "sec-websocket-extensions" headers. This can cause duplicated entries.

Modifications:

* Replace existing `WebSocketExtensionUtil#appendExtension` private helper with a new `computeMergeExtensionsHeaderValue`. User defined parameters have higher precedence.
* Add tests (existing method wasn't tested)
* Reuse code for both client and server side (code was duplicated).

Result:

No more duplicated entries when user defined extensions overlap with the ones Netty generated.

### CODE REVIEW

**Comment by slandelle** [comment]
cc @kurilov

**Comment by slandelle** [comment]
CI failures seems unrelated.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java [hunk 1]
```diff
@@ -72,25 +72,53 @@ static boolean isWebsocketUpgrade(HttpHeaders headers) {
...
+                if (extra.name().equals(userDefined.name())) {
+                    matchingExtra = extra;
+                    break;
+                }
+            }
+            if (matchingExtra == null) {
+                extraExtensions.add(userDefined);
+            } else {
+                // merge with higher precedence to user defined parameters
+                Map<String, String> mergedParameters = new HashMap<String, String>(matchingExtra.parameters());
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java:96]: Does this need to be a `LinkedHashSet` ?

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java [hunk 2]
```diff
@@ -72,25 +72,53 @@ static boolean isWebsocketUpgrade(HttpHeaders headers) {
...
         }
-        newHeaderValue.append(extensionName);
-        for (Entry<String, String> extensionParameter : extensionParameters.entrySet()) {
-            newHeaderValue.append(PARAMETER_SEPARATOR);
-            newHeaderValue.append(extensionParameter.getKey());
-            if (extensionParameter.getValue() != null) {
-                newHeaderValue.append(PARAMETER_EQUAL);
-                newHeaderValue.append(extensionParameter.getValue());
+
+        StringBuilder sb = new StringBuilder();
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java:102]: is the default size of 64 good ?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java (hunk 1 above)
Comment (slandelle) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java:96]: Parameters order is not supposed to be significant. Moreover, `extractExtensions` (in the same class) uses `HashMap` for the parsing side, so using one here too is consistent.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java (hunk 2 above)
Comment (slandelle) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java:102]: The size greatly varies depending on the parameters. The real world example (client side deflate) is have in the tests is 149 chars with 4 extensions ranging from 15 to 70 chars.
Do you have any suggestion? Hardcode 150?

Comment (normanmaurer) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java:102]: yep +1

Comment (slandelle) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketExtensionUtil.java]: done

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@slandelle thanks a lot

**Comment by normanmaurer** [comment]
@slandelle I reverted this commit as it produced NPEs in the tests... please have a look.

**Comment by slandelle** [comment]
@normanmaurer I can see those test failures locally. However, why didn't we see those in the CI for this PR? IIRC, the only failures were on the aarch64 step.

**Comment by normanmaurer** [comment]
@slandelle I think these were introduced by your last change... I did merge by mistake before I waited for the CI to run all of these :/

**Comment by slandelle** [comment]
I fixed the issue and provided a new PR: #10956
