### PR TITLE
Nio|Epoll|KqueueEventLoop task execution might throw UnsupportedOpera…

### LINKED ISSUE #8475: NioEventLoop task execution might throw UnsupportedOperationException on shutdown
### Expected behavior
Execution instead throws `RejectedExecutionException`.

### Actual behavior
There is a racy `UnsupportedOperationException` instead because the task removal is delegated to `MpscChunkedArrayQueue` that does not support removal. This happens with `SingleThreadEventExecutor` that overrides the `newTaskQueue` to return an MPSC queue instead of the `LinkedBlockingQueue` returned by the base class such as `NioEventLoop`, `EpollEventLoop` and `KQueueEventLoop`.

### Steps to reproduce
Schedule task to an event loop concurrently to an event loop shutdown.

### Minimal yet complete reproducer code (or URL to code)
```
    @Test
    public void testTaskRemovalOnShutdownThrowsUnsupportedOperationException() throws Exception {
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        final NioEventLoop loop = (NioEventLoop) group.next();
        final Runnable task = new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    loop.execute(task);
                }
            }
        }.start();
        Thread.sleep(10);
        loop.shutdownNow();
        Thread.sleep(100000);
    }
```

this is a racy test, the event loop shutdown race against the the task producing thread, if you run it enough it will fail:

```
Exception in thread "Thread-0" java.lang.UnsupportedOperationException
	at org.jctools.queues.BaseMpscLinkedArrayQueue.iterator(BaseMpscLinkedArrayQueue.java:201)
	at java.util.AbstractCollection.remove(AbstractCollection.java:282)
	at io.netty.util.concurrent.SingleThreadEventExecutor.removeTask(SingleThreadEventExecutor.java:340)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:781)
	at io.netty.channel.nio.NioEventLoopTest$8.run(NioEventLoopTest.java:195)
```

### Netty version
At least 4.1.x

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
N/A

### PR DESCRIPTION
**Pull request by normanmaurer**
…tionException on shutdown

Motivation:

There is a racy UnsupportedOperationException instead because the task removal is delegated to MpscChunkedArrayQueue that does not support removal. This happens with SingleThreadEventExecutor that overrides the newTaskQueue to return an MPSC queue instead of the LinkedBlockingQueue returned by the base class such as NioEventLoop, EpollEventLoop and KQueueEventLoop.

Modifications:

- Catch the UnsupportedOperationException
- Add unit test.

Result:

Fix #8475

### CODE REVIEW

**Comment by normanmaurer** [comment]
@vietj PTAL

**Comment by vietj** [comment]
looks good

**Comment by johnou** [comment]
cc @davidmoten

File: transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java [hunk 1]
```diff
@@ -170,6 +170,12 @@ protected void wakeup(boolean inEventLoop) {
         }
     }
 
+    @Override
```
Comment (davidmoten) [inline transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java]: Add a bit of javadoc about  the meaning of the returned boolean? (especially as we no longer delegate a call to the queue which could have effectively provided that information via its javadoc). Ditto the other `removeTask` methods.

File: common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java [hunk 2]
```diff
@@ -775,12 +775,18 @@ public void execute(Runnable task) {
         }
 
         boolean inEventLoop = inEventLoop();
-        addTask(task);
         if (!inEventLoop) {
+            if (isShutdown()) {
```
Comment (davidmoten) [inline common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java]: Yes this makes things less racy. Why not use a CAS loop here to make even less racy (especially as we have a  volatile field updater available)?

Comment (davidmoten) [reply common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java]: I see the `shutdown` method is `@Deprecated`. Is that to remove it from the public API but it will still be called by something? A bit of javadoc about the deprecation would be great.

**Comment by davidmoten** [comment]
Having looked at the `shutdown()` method I see it's a tad wasteful with its volatile reads (calling `isShutdown` and `isShuttingDown` and not reusing the read value of `state`). I could clean up if desired.

File: transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java (hunk 1 above)
Comment (normanmaurer) [reply transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java]: @davidmoten sure..

File: common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java (hunk 2 above)
Comment (normanmaurer) [reply common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java]: oh duh! you are right...

**Comment by normanmaurer** [comment]
@davidmoten adjusted based on your feedback. 

@davidmoten if you like you can submit a pr for `shutdown` improvements, that said I am not overly concerned about performance for this method.

File: transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java (hunk 1 above)
Comment (davidmoten) [reply transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java]: ah I meant what does true mean and what does false mean. Does true mean it was found on the queue and removed? Does false mean it is either not supported or not found on the queue?

**Comment by davidmoten** [comment]
>@davidmoten if you like you can submit a pr for shutdown improvements, that said I am not overly concerned about performance for this method.

Yeah I can't think of a scenario where `shutdown` is called in a fast loop or experiences high contention so I'll leave it alone.

File: common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java [hunk 3]
```diff
@@ -778,8 +778,20 @@ public void execute(Runnable task) {
         addTask(task);
         if (!inEventLoop) {
             startThread();
-            if (isShutdown() && removeTask(task)) {
-                reject();
+            if (isShutdown()) {
```
Comment (ejona86) [inline common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java]: Why is this code even caring about `isShutdown()`? It looks like this block should just be deleted. `isShutdown()` is checked by `addTask()`/`offerTask()`. If we added the entry to the queue, then it seems we should commit ourselves to it; attempting to remove it (which is not guaranteed to be successful, since the task may have already run) seems weird.

If this `isShutdown()` check was atomic with `startThread()`, I could sort of understand the removal since we know we didn't start the thread, but as it is it just seems like useless effort.
