### PR TITLE
Fixes issue #11933:FastThreadLocal.set(V) method throws NegativeArraySizeException after called more than (1 << 30) times of new FastThreadLocal()

### LINKED ISSUE #11933: `FastThreadLocal.set(V)` method throws `NegativeArraySizeException` after called more than (1 << 30) times of `new FastThreadLocal()`
### Expected behavior

The `FastThreadLocal.set(V)` method should still work after called more than (1 << 30) and less than (Integer.MAX_VALUE) times of `new FastThreadLocal()`.

### Actual behavior

After called more than (1 << 30) times of `new FastThreadLocal()`, the newly created `FastThreadLocal` instance can not set value anymore.

### Minimal yet complete reproducer code (or URL to code)
```
import io.netty.util.concurrent.FastThreadLocal;
import io.netty.util.internal.InternalThreadLocalMap;

public static void main(String[] args) {
        int expand_threshold = 1 << 30;
        while (true) {
            FastThreadLocal<Object> fst = new FastThreadLocal<>();
            if (InternalThreadLocalMap.lastVariableIndex() < expand_threshold) {
                continue;
            }
            fst.set(new Object()); // throws NegativeArraySizeException
            return;
        }
    }
```
Run the code above, the console prints Exception:

> Exception in thread "main" java.lang.NegativeArraySizeException
> 	at java.util.Arrays.copyOf(Arrays.java:3210)
> 	at java.util.Arrays.copyOf(Arrays.java:3181)
> 	at io.netty.util.internal.InternalThreadLocalMap.expandIndexedVariableTableAndSet(InternalThreadLocalMap.java:342)
> 	at io.netty.util.internal.InternalThreadLocalMap.setIndexedVariable(InternalThreadLocalMap.java:326)
> 	at io.netty.util.concurrent.FastThreadLocal.setKnownNotUnset(FastThreadLocal.java:214)
> 	at io.netty.util.concurrent.FastThreadLocal.set(FastThreadLocal.java:193)
> 	at XXX.main(XXX.java:15)

### Netty version
4.1.72.Final.
### JVM version (e.g. `java -version`)
JDK-8.
### OS version (e.g. `uname -a`)
MacOS.

### PR DESCRIPTION
**Pull request by laosijikaichele**
Motivation:

Fixes issue #11933: FastThreadLocal.set(V) method throws NegativeArraySizeException after called more than (1 << 30) times of new FastThreadLocal()

Modification:

Add index bound check in methods `io.netty.util.internal.InternalThreadLocalMap#expandIndexedVariableTableAndSet` and `io.netty.util.internal.InternalThreadLocalMap#nextVariableIndex`.
Result:

Fixes #11933.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@laosijikaichele can we have an unit test well ? Also I wonder if this is really an issue in real-wold

**Comment by laosijikaichele** [comment]
@normanmaurer OK, will add the unit test soon.

File: common/src/main/java/io/netty/util/internal/InternalThreadLocalMap.java [hunk 1]
```diff
@@ -331,13 +334,18 @@ public boolean setIndexedVariable(int index, Object value) {
...
+        if (index < ARRAY_LIST_CAPACITY_EXPAND_THRESHOLD) {
+            newCapacity = index;
+            newCapacity |= newCapacity >>>  1;
+            newCapacity |= newCapacity >>>  2;
+            newCapacity |= newCapacity >>>  4;
+            newCapacity |= newCapacity >>>  8;
+            newCapacity |= newCapacity >>> 16;
+            newCapacity ++;
+        } else {
+            newCapacity = Integer.MAX_VALUE;
```
Comment (chrisvest) [inline common/src/main/java/io/netty/util/internal/InternalThreadLocalMap.java:347]: `Integer.MAX_VALUE` cannot be used as an array length, in many JVMs. Their max array lengths is some some constant close to but less than that. I've used `Integer.MAX_VALUE - 1000` in other projects. We should define a max capacity constant, and use it here and in `nextVariableIndex`.

Comment (laosijikaichele) [reply common/src/main/java/io/netty/util/internal/InternalThreadLocalMap.java:347]: Yes, but the problem is how to decide the proper value of max array length, seems it's [VM-dependent](https://stackoverflow.com/questions/3038392/do-java-arrays-have-a-maximum-size).

Comment (chrisvest) [reply common/src/main/java/io/netty/util/internal/InternalThreadLocalMap.java:347]: We can pick a conservative minimum that works for all targets. I think it's fine to waste a few slots on that. Trying to compute a value by inspecting the JVM would be too complicated, in my opinion.

Comment (laosijikaichele) [reply common/src/main/java/io/netty/util/internal/InternalThreadLocalMap.java:347]: Maybe we can take Java's `ArrayList` as reference, it choose `Integer.MAX_VALUE - 8` as the max array size. (http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/tip/src/share/classes/java/util/ArrayList.java#l190)

Comment (chrisvest) [reply common/src/main/java/io/netty/util/internal/InternalThreadLocalMap.java:347]: Yeah, that sounds like a good choice.

File: common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java [hunk 2]
```diff
@@ -238,4 +241,52 @@ protected void onRemoval(String value) throws Exception {
...
+                } catch (Throwable t) {
+                    throwable.set(t);
+                }
+            }
+        };
+        FastThreadLocalThread fastThreadLocalThread = new FastThreadLocalThread(runnable);
+        fastThreadLocalThread.start();
+        fastThreadLocalThread.join();
+        // assert the expanded size is not overflowed to negative value
+        assertTrue(!(throwable.get() instanceof NegativeArraySizeException));
```
Comment (normanmaurer) [inline common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java:290]: maybe better to use `assertThat` with the correct `Matcher`

File: common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java [hunk 3]
```diff
@@ -238,4 +241,52 @@ protected void onRemoval(String value) throws Exception {
             onRemovalCalled.set(value);
         }
     }
+
+    @Test
+    public void testConstructionWithIndex() throws Exception {
```
Comment (normanmaurer) [inline common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java:246]: I wonder if we should disable this test by default as it will use a lot of memory. WDYT ?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java (hunk 2 above)
Comment (laosijikaichele) [reply common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java]: Done it.

File: common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java (hunk 3 above)
Comment (laosijikaichele) [reply common/src/test/java/io/netty/util/concurrent/FastThreadLocalTest.java:248]: I think the GC will kicked in and recycle the memory while in the 'loop', so it will not use a lot of memory.

**Review by chrisvest — COMMENTED** [review]
I'm slightly nervous about adding tests that use that much memory since it could cause unrelated tests to fail, but otherwise it looks good.

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@chrisvest I guess it is ok for now and if we see any issues we can disable the test :)

**Comment by normanmaurer** [comment]
@laosijikaichele thanks a lot!
