### PR TITLE
Optimize wrap buffer cumulation in SslHandler and don't mutate input buffers 

### LINKED ISSUE #14069: SslHandler doesn't support a use case where the input ByteBuf is shared across multiple threads
### Expected behavior

There should be a way to pass shared ByteBuf instances to a ChannelPipeline that contains SslHandler. A ByteBuf instance might be cached and that's why it's shared. 

An alternative is to document this limitation clearly in SslHandler javadoc.

### Actual behavior

Currently this will cause problems such as https://github.com/apache/pulsar/issues/2401 reported in Pulsar in 2018.
This was mitigated by calling `.copy()` on the input ByteBuf instances with https://github.com/apache/pulsar/pull/2464 . However, this `.copy()` solution had another issue which is reported as #14068. That is mitigated in Pulsar with https://github.com/apache/pulsar/pull/22760 . 

### Steps to reproduce

It should be possible to reproduce this issue by concurrently passing a ByteBuf instance to multiple channel pipelines that contain a SslHandler.

### Minimal yet complete reproducer code (or URL to code)

System level repro case for Pulsar is documented in https://github.com/apache/pulsar/issues/22601#issuecomment-2122642708 . This is not minimal.

### Netty version

4.1.108

### JVM version (e.g. `java -version`)

openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203171407766522.04~4c8e9a0 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by lhotari**
Motivation:

SslHandler doesn't support sharing the input buffers since the input buffers get mutated. This issue has been reported as #14069. Fixes have already been made to support the use case using read-only buffers as input. However, this is not useful for existing Netty applications.

I checked the Netty code once again and noticed that it's possible to optimize the current implementation in SslHandler and avoid the buffer mutation.

The default behavior in SslHandler causes very hard to debug problems. In Pulsar, there have been issues open for multiple years that have been caused by the SslHandler's default behavior of mutating the input buffers (apache/pulsar#22601 is one starting point to the issues). 

The current implementation of SslHandler will mutate the input buffers by using the input buffer as a cumulation buffer when there's available capacity. This is not optimal at all. This PR contains an improvement where the cumulation buffer is allocated to the final size immediately so that cumulation is more optimal. That's why I think that this will be more optimal in the end and won't cause performance regressions.

After these changes, it should be possible to pass a slice or duplicate of a buffer and the input buffer doesn't get mutated. The input buffer's readIndex will be modified so multiple threads cannot share the same input buffer without a slice or duplicate.

I created a failing test case that shows that a duplicate buffer doesn't prevent input buffer mutation.
image
It's a very surprising behavior of SslHandler that passing a `.retainedDuplicate()` buffer could result in mutations to the original buffer. That's another reason why I think that SslHandler shouldn't ever mutate the inputs.

Modification:

- add `protected ByteBuf composeFirst(ByteBufAllocator allocator, ByteBuf first, int bufferSize)` to AbstractCoalescingBufferQueue to support allocating an optimal cumulation buffer instead of using the input buffer as a cumulation buffer
- remove dead code from `compose` where there was handling for CompositeByteBuf
  - `composeFirst` will be called before `compose` so this case isn't needed.

Result:

Fixes #14069 without the need to set the input buffer as read-only

### CODE REVIEW

File: transport/src/main/java/io/netty/channel/AbstractCoalescingBufferQueue.java [hunk 1]
```diff
@@ -333,7 +333,19 @@ protected final ByteBuf copyAndCompose(ByteBufAllocator alloc, ByteBuf cumulatio
...
+    protected ByteBuf composeFirst(ByteBufAllocator allocator, ByteBuf first, int bufferSize) {
+        return composeFirst(allocator, first);
+    }
+
+    /**
+     * Calculate the first {@link ByteBuf} which will be used in subsequent calls to
+     * {@link #compose(ByteBufAllocator, ByteBuf, ByteBuf)}.
+     * This method is deprecated and will be removed in the future. Implementing classes should
+     * override {@link #composeFirst(ByteBufAllocator, ByteBuf, int)} instead.
+     */
```
Comment (normanmaurer) [inline transport/src/main/java/io/netty/channel/AbstractCoalescingBufferQueue.java:347]:
```suggestion
     * @deprecated Use {AbstractCoalescingBufferQueue#composeFirst(ByteBufAllocator, ByteBuf, int)}
     */
```

File: transport/src/main/java/io/netty/channel/AbstractCoalescingBufferQueue.java [hunk 2]
```diff
@@ -333,7 +333,19 @@ protected final ByteBuf copyAndCompose(ByteBufAllocator alloc, ByteBuf cumulatio
     /**
      * Calculate the first {@link ByteBuf} which will be used in subsequent calls to
      * {@link #compose(ByteBufAllocator, ByteBuf, ByteBuf)}.
+     * @param bufferSize the optimal size of the buffer needed for cumulation
```
Comment (normanmaurer) [inline transport/src/main/java/io/netty/channel/AbstractCoalescingBufferQueue.java:336]:
```suggestion
     * @param bufferSize the optimal size of the buffer needed for cumulation
     * @return the first buffer
```

File: handler/src/main/java/io/netty/handler/ssl/SslHandlerCoalescingBufferQueue.java [hunk 3]
```diff
@@ -42,38 +42,27 @@ abstract class SslHandlerCoalescingBufferQueue extends AbstractCoalescingBufferQ
...
-            }
-            try {
-                first.writeBytes(composite);
-            } catch (Throwable cause) {
-                first.release();
-                PlatformDependent.throwException(cause);
-            }
-            composite.release();
+    protected ByteBuf composeFirst(ByteBufAllocator allocator, ByteBuf first, int bufferSize) {
+        ByteBuf newFirst;
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/ssl/SslHandlerCoalescingBufferQueue.java:51]:
```suggestion
        final ByteBuf newFirst;
```

**Review by normanmaurer — CHANGES_REQUESTED** [review]

**Comment by lhotari** [comment]
@normanmaurer Thanks for the review. I applied your suggestions. PTAL

**Review by normanmaurer — APPROVED** [review]

**Comment by lhotari** [comment]
The issue #12919 explains why SslHandler has been causing issues in Apache Pulsar. The incoming messages come from the network and use LengthFieldBasedFrameDecoder which slices the buffers. The buffer used by LengthFieldBasedFrameDecoder gets mutated by SslHandler later when the same buffers are passed to Apache Bookkeeper client which also uses Netty and contains SslHandler.

Issue #12919 references vert.x issue https://github.com/eclipse-vertx/vert.x/issues/4509 . It seem vert.x applied a workaround in https://github.com/eclipse-vertx/vert.x/issues/4517 .

Found also a workaround data corruption issue within Netty, #11802. That was to address #11792.

**Comment by lhotari** [comment]
@franz1981 do you also have a chance to review this PR? Thanks!

**Comment by lhotari** [comment]
As a followup, I also created #14093 with the title "Duplicate of slice should have the same capacity as the original slice so that it's not writable" to address the issue #12919 by @vietj, "ByteBuf slice duplicates are not slices". 
(In Pulsar, that's why SslHandler was able to corrupt the input buffer of LengthFieldBasedFrameDecoder since calling `.retainedDuplicate` later in Pulsar code "removed" the slice created by LengthFieldBasedFrameDecoder.)

**Review by chrisvest — APPROVED** [review]
