### PR TITLE
Increase default bits for SelfSignedCertificate

### LINKED ISSUE #9018: SelfSignedCertificate fails with FIPS enabled causing OpenSsl to fail
### Expected behavior

For compliance reasons, we have BouncyCastle FIPS mode enabled and use Netty's OpenSSL bindings for TLS termination.

I've noticed that Netty is failing to startup correctly since within `OpenSsl.java` static constructor it creates a `SelfSignedCertificate` with **1024** bits -- as such it is failing to create a KeyManagerFactory.

FIPS 140-2 encryption requires the key length to be 2048 bits or greater.
I would like to  submit a PR to bump the bits for SelfSignedCertificate default to 2048.

### JVM version (e.g. `java -version`)

JRE 1.8

### OS version (e.g. `uname -a`)

darwin (OSX) & OracleLinux

### PR DESCRIPTION
**Pull request by fzakaria**
Motivation:
During OpenSsl.java initialization, a SelfSignedCertificate is created
during the static initialization block to determine if OpenSsl
can be used.

The default key strength for SelfSignedCertificate was too low if FIPS
mode is used and BouncyCastle-FIPS is the only available provider
(necessary for compliance). A simple fix is to just augment the key
strength to the minimum required about by FIPS.

Modification:
Set default key bit length to 2048 but also allow it to be dynamically set via a system property for future proofing to more stricter security compliance.

Result:
Fixes #9018 

Signed-off-by: Farid Zakaria <farid.m.zakaria@gmail.com>

### CODE REVIEW

**Comment by fzakaria** [comment]
I'm not sure I follow.

**Comment by normanmaurer** [comment]
We don’t use the class directly anymore when unit OpenSsl:

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L68

**Comment by fzakaria** [comment]
@normanmaurer I regenerated the certificate & key -- thanks for the tip.
I chose to include the PEM format rather than the byte array; as I find it a bit easier to update/reason through.

` mvn -pl handler clean install`
```
[INFO] Installing /Users/fmzakari/Development/netty/handler/target/netty-handler-4.1.35.Final-SNAPSHOT-sources.jar to /Users/fmzakari/.m2/repository/io/netty/netty-handler/4.1.35.Final-SNAPSHOT/netty-handler-4.1.35.Final-SNAPSHOT-sources.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:45 min
[INFO] Finished at: 2019-04-06T15:23:14-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: handler/src/main/java/io/netty/handler/ssl/OpenSsl.java [hunk 1]
```diff
@@ -64,71 +64,47 @@
...
+            "vYoaK6qzmHXRYlp/PxrjBAZAmkLJs4YTm/XFF+fkeYx4i9zqHbyone5yerRibsHaXZWLnUL+rFoe\n" +
+            "MdKvr0VS3sGmhQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQADQi441pKmXf9FvUV5EHU4v8nJT9Iq\n" +
+            "yqwsKwXnr7AsUlDGHBD7jGrjAXnG5rGxuNKBQ35wRxJATKrUtyaquFUL6H8O6aGQehiFTk6zmPbe\n" +
+            "12Gu44vqqTgIUxnv3JQJiox8S2hMxsSddpeCmSdvmalvD6WG4NthH6B9ZaBEiep1+0s0RUaBYn73\n" +
+            "I7CCUaAtbjfR6pcJjrFk5ei7uwdQZFSJtkP2z8r7zfeANJddAKFlkaMWn7u+OIVuB4XPooWicObk\n" +
+            "NAHFtP65bocUYnDpTVdiyvn8DdqyZ/EO8n1bBKBzuSLplk2msW4pdgaFgY7Vw/0wzcFXfUXmL1uy\n" +
+            "G8sQD/wx\n" +
+            "-----END CERTIFICATE-----";
+
+    private static String KEY = "-----BEGIN PRIVATE KEY-----\n" +
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/ssl/OpenSsl.java]: final

File: handler/src/main/java/io/netty/handler/ssl/OpenSsl.java [hunk 2]
```diff
@@ -64,71 +64,47 @@
...
-            -43, 43, -44, -92, -104, -14, 39, 127, 109, -123, 28, 14, -20, -17, 20, -56, 109,
-            -75, -40, -81, 49, -116, -123, 78, -117, 55, -19, 105, 41, -9, -81, -15, 79, -58,
-            50, -101, 25, 16, -26, 31, -20, 68, 11, 18, 75, -17, -55, 2, 65, 0, -126, -11, 56,
-            -83, -60, 1, -125, 109, 74, 74, -1, -17, 54, 111, -111, 100, 125, 21, 77, 34, 119,
-            -33, 23, -13, 66, 74, -78, 80, -67, 57, -42, 65, 65, 58, 96, 0, 72, -122, 3, -78,
-            119, 68, -76, 5, 50, 37, 51, 10, -54, 54, -102, 90, -6, 127, -93, 97, 53, 24, 57,
-            77, 81, 53, -13, -127
-    };
+    // self-signed certificate for netty.io and the matching private-key
+    private static String CERT = "-----BEGIN CERTIFICATE-----\n" +
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/ssl/OpenSsl.java]: final

File: handler/src/main/java/io/netty/handler/ssl/OpenSsl.java [hunk 3]
```diff
@@ -388,7 +364,9 @@ public Boolean run() {
      * Returns a self-signed {@link X509Certificate} for {@code netty.io}.
      */
     static X509Certificate selfSignedCertificate() throws CertificateException {
-        return (X509Certificate) SslContext.X509_CERT_FACTORY.generateCertificate(new ByteArrayInputStream(CERT_BYTES));
+        return (X509Certificate) SslContext.X509_CERT_FACTORY.generateCertificate(
+                new ByteArrayInputStream(CERT.getBytes())
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/ssl/OpenSsl.java]: `getBytes(CharsetUtil.US_ASCII)`

File: handler/src/main/java/io/netty/handler/ssl/OpenSsl.java [hunk 4]
```diff
@@ -256,7 +232,7 @@
                                                "AEAD-CHACHA20-POLY1305-SHA256");
                         }
 
-                        PemEncoded privateKey = PemPrivateKey.toPEM(UnpooledByteBufAllocator.DEFAULT, true, KEY_BYTES);
+                        PemEncoded privateKey = PemPrivateKey.valueOf(KEY.getBytes());
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/ssl/OpenSsl.java]: `getBytes(CharsetUtil.US_ASCII)`

**Comment by fzakaria** [comment]
Addressed & rebased.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@fzakaria thanks a lot!
