### PR TITLE
Bugfix #8295: WebSocket is closed without an error on protocol violations

### LINKED ISSUE #8295: WebSocket is closed without an error on protocol violations
When client sends a message exceeding server restrictions, web socket should be closed with correct error code and message.

### Expected behavior
response frame is sent: CloseWebSocketFrame(1002, "Max frame length of ... has been exceeded")

### Actual behavior
response frame is sent: CloseWebSocketFrame(1000, null)

### Steps to reproduce
Limit single message size accepted by server.
```
static int MAX_CLIENT_MESSAGE_SIZE = 128 * 1024;

ctx.pipeline().addAfter(ctx.name(), "ws-protocol-handler", new WebSocketServerProtocolHandler(
    webSocketPath, null, true, MAX_CLIENT_MESSAGE_SIZE, false, false));`
```

Send message from client with a greater size:
```
ByteBuf buf = Unpooled.wrappedBuffer(new byte[MAX_CLIENT_MESSAGE_SIZE + 1]);
clientChannel.writeAndFlush(new BinaryWebSocketFrame(buf));
```

### Minimal yet complete reproducer code (or URL to code)
n/a

### Netty version
4.1.29.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b25, mixed mode)

### OS version (e.g. `uname -a`)
Linux gmafxu42 3.0.101-108.35-default #1 SMP Mon Feb 19 21:13:08 UTC 2018 (251ec24) x86_64 x86_64 x86_64 GNU/Linux

### Root cause

io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder#protocolViolation(io.netty.channel.ChannelHandlerContext, io.netty.handler.codec.CorruptedFrameException)

```
private void protocolViolation(ChannelHandlerContext ctx, CorruptedFrameException ex) {
    state = State.CORRUPT;
    --- if (ctx.channel().isActive()) {
    +++ if (ctx.channel().isActive() && closeOnProtocolViolation) {
        Object closeMessage;
        if (receivedClosingHandshake) {
            closeMessage = Unpooled.EMPTY_BUFFER;
        } else {
            --- closeMessage = new CloseWebSocketFrame(1002, null);
            +++ closeMessage = new CloseWebSocketFrame(1002, ex.getMessage());
        }
        --- ctx.writeAndFlush(closeMessage).addListener(ChannelFutureListener.CLOSE);
        +++ ctx.channel().writeAndFlush(closeMessage).addListener(ChannelFutureListener.CLOSE);
    }
    throw ex;
}
```

### PR DESCRIPTION
**Pull request by ursaj**
Motivation:

- Incorrect WebSockets closure affects our production system. 
- Enforced 'close socket on any protocol violation' prevents our custom termination sequence from execution.
- Huge number of parameters is a nightmare both in usage and in support (decoders configuration).

Modification:

- Fix violations handling - send proper response codes.
- Fix for messages leak.
- Introduce decoder's option to disable default behavior (send close frame) on protocol violations.
- Encapsulate WebSocket response codes - `WebSocketCloseStatus`.
- Encapsulate decoder's configuration into a separate class - `WebSocketDecoderConfig`.

Result:

Fixes #8295. 

Note: previous PR #8308 got stuck - I cannot get any response from reviewers... Reopened it as a new PR (this one).

### CODE REVIEW

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java [hunk 1]
```diff
@@ -53,6 +53,65 @@ private void initTestData() {
...
+        outChannel = new EmbeddedChannel(new WebSocket08FrameEncoder(true));
+
+        executeProtocolViolationTest(outChannel, inChannel, maxPayloadLength + 1, expectedStatus, errorMessage);
+
+        response = inChannel.readOutbound();
+        Assert.assertNull(response);
+
+        // Release test data
+        binTestData.release();
+    }
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java]: please call `inChannel.finish()` and `outChannel.finish()` as well and assert return value

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java [hunk 2]
```diff
@@ -154,4 +195,16 @@ private void testBinaryWithLen(EmbeddedChannel outChannel, EmbeddedChannel inCha
         }
         binFrame.release();
     }
+
+    private void transfer(EmbeddedChannel outChannel, EmbeddedChannel inChannel) {
+        // Transfer encoded data into decoder
+        // Loop because there might be multiple frames (gathering write)
+        while (true) {
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java]: please use the same style we do in Netty: `for (;;) { ... }`

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java [hunk 3]
```diff
@@ -408,18 +418,31 @@ private void unmask(ByteBuf frame) {
...
+        protocolViolation(ctx, in, new CorruptedWebSocketFrameException(status, reason));
     }
 
-    private void protocolViolation(ChannelHandlerContext ctx, CorruptedFrameException ex) {
+    private void protocolViolation(ChannelHandlerContext ctx, ByteBuf in, CorruptedWebSocketFrameException ex) {
         state = State.CORRUPT;
-        if (ctx.channel().isActive()) {
+        int readableBytes = in.readableBytes();
+        if (readableBytes > 0) {
+            in.skipBytes(readableBytes);
```
[the remark this answers is not in the document]
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java]: this is a fix for memory leak (when violation happens), caused by `ByteToMessageDecoder#channelRead`

    try {
        <call decoder>
    } finally {
        if (cumulation != null && !cumulation.isReadable()) {
            numReads = 0;
            cumulation.release(); // leak cause - this code is called only when buffer has been fully read.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java [hunk 4]
```diff
@@ -0,0 +1,64 @@
+/*
+ * Copyright 2018 The Netty Project
```
[the remark this answers is not in the document]
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: done

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+    }
+
+    /**
+     * Creates a new instance.
+     */
+    public CorruptedWebSocketFrameException(WebSocketCloseStatus status, Throwable cause) {
+        this(status, null, cause);
+    }
+
+    public WebSocketCloseStatus getCloseStatus() {
```
[the remark this answers is not in the document]
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: done

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java [hunk 6]
```diff
@@ -0,0 +1,310 @@
...
+
+    private final int statusCode;
+    private final String reasonText;
+
+    public WebSocketCloseStatus(int statusCode, String reasonText) {
+        if (!isValidStatusCode(statusCode)) {
+            throw new IllegalArgumentException(
+                "WebSocket close status code does NOT comply with RFC-6455: " + statusCode);
+        }
+        if (reasonText == null) {
```
[the remark this answers is not in the document]
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java]: done

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketDecoderConfig.java [hunk 7]
```diff
@@ -0,0 +1,147 @@
...
+
+    public boolean allowMaskMismatch() {
+        return allowMaskMismatch;
+    }
+
+    public boolean allowExtensions() {
+        return allowExtensions;
+    }
+
+    boolean closeOnProtocolViolation() {
```
[the remark this answers is not in the document]
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketDecoderConfig.java]: unified - changed to public

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java (hunk 1 above)
Comment (ursaj) [reply codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java]: done

File: codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java (hunk 2 above)
Comment (ursaj) [reply codec-http/src/test/java/io/netty/handler/codec/http/websocketx/WebSocket08EncoderDecoderTest.java]: done

**Comment by ursaj** [comment]
Everything has been fixed a week ago. Any chance for approve and merge?

**Comment by normanmaurer** [comment]
@netty-bot test this please...

**Comment by normanmaurer** [comment]
Before pulling this in I would love to have either @slandelle  / @ejona86 or @trustin take a look as well.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+public final class CorruptedWebSocketFrameException extends CorruptedFrameException {
+
+    private static final long serialVersionUID = 3918055132492988338L;
+
+    private final WebSocketCloseStatus closeStatus;
+
+    /**
+     * Creates a new instance.
+     */
+    public CorruptedWebSocketFrameException() {
```
Comment (slandelle) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: dead code, never used

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+        this(WebSocketCloseStatus.PROTOCOL_ERROR, null, null);
+    }
+
+    /**
+     * Creates a new instance.
+     */
+    public CorruptedWebSocketFrameException(WebSocketCloseStatus status, String message, Throwable cause) {
```
Comment (slandelle) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: dead code, never used

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+     * Creates a new instance.
+     */
+    public CorruptedWebSocketFrameException(WebSocketCloseStatus status, String message) {
+        this(status, message, null);
+    }
+
+    /**
+     * Creates a new instance.
+     */
+    public CorruptedWebSocketFrameException(WebSocketCloseStatus status, Throwable cause) {
```
Comment (slandelle) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: dead code, never used

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (slandelle) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java]: Might be worth documenting?

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java [hunk 11]
```diff
@@ -0,0 +1,309 @@
...
+    public static final WebSocketCloseStatus SERVICE_RESTART =
+        new WebSocketCloseStatus(1012, "Service Restart");
+
+    public static final WebSocketCloseStatus TRY_AGAIN_LATER =
+        new WebSocketCloseStatus(1013, "Try Again Later");
+
+    public static final WebSocketCloseStatus BAD_GATEWAY =
+        new WebSocketCloseStatus(1014, "Bad Gateway");
+
+    // 1004, 1005, 1006, 1015 are reserved and should never be used by user
```
Comment (slandelle) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java]: I agree user shouldn't set them in close frames. But what about the receiving side, couldn't a user end up reading them from the close frame there?

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java [hunk 12]
```diff
@@ -0,0 +1,309 @@
...
+    public String toString() {
+        // E.g.: "1000 Bye", "1009 Message too big"
+        return code() + " " + reasonText();
+    }
+
+    public static boolean isValidStatusCode(int code) {
+        return code < 0 ||
+            1000 <= code && code <= 1003 ||
+            1007 <= code && code <= 1014 ||
+            3000 <= code;
```
Comment (slandelle) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java]: See above comment

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java [hunk 13]
```diff
@@ -0,0 +1,309 @@
...
+
+    @Override
+    public int hashCode() {
+        return statusCode;
+    }
+
+    @Override
+    public String toString() {
+        // E.g.: "1000 Bye", "1009 Message too big"
+        return code() + " " + reasonText();
```
Comment (slandelle) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java]: final field to it's computed once and for all, as most values should be constants

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java (hunk 8 above)
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: a) it is required by Serializable interface
b) default unused constructor exists in many (all?) netty exceptions, e.g. in CorruptedFrameException

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java (hunk 11 above)
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java]: on the receiving side this would mean corrupted websocket stream. with corresponding exception.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java (hunk 10 above)
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: it's for usage by users

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java (hunk 9 above)
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CorruptedWebSocketFrameException.java]: it's for usage by users. precisely, I want this exception in my code.

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java (hunk 13 above)
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java]: fixed

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (ursaj) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java]: done

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@slandelle PTAL again

**Comment by normanmaurer** [comment]
@ursaj thanks a lot!

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/Utf8Validator.java [hunk 14]
```diff
@@ -79,7 +78,8 @@ public void finish() {
         codep = 0;
         if (state != UTF8_ACCEPT) {
             state = UTF8_ACCEPT;
-            throw new CorruptedFrameException("bytes are not UTF-8");
+            throw new CorruptedWebSocketFrameException(
+                WebSocketCloseStatus.INVALID_PAYLOAD_DATA, "bytes are not UTF-8");
```
Comment (kamma-cc) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/Utf8Validator.java]: I think the frame being checked leaks when an exception is thrown
