### PR TITLE
[Issue-10320] More values other than chunked defined in Transfer-Encoding header leads to decode failure

### LINKED ISSUE #10320: More values other than chunked defined in Transfer-Encoding header leads to decode failure
According to https://tools.ietf.org/html/rfc7230#page-29, people can specify multiple values for `Transfer-Encoding` HTTP header,  like: `Transfer-Encoding: gzip, chunked`, but Netty does not recognize it as a chunked request in this case.

### Expected behavior
There is no exception in server, and client should get the server response.

### Actual behavior
Exception found in server:

```
java.lang.IllegalArgumentException: text is empty (possibly HTTP/0.9)
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:64)
	at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:206)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
And there is no response back in that case.

### Steps to reproduce
Please refer to the reproducer in the link below.

### Minimal yet complete reproducer code (or URL to code)
Reproducer link: https://github.com/gaol/tests/tree/master/netty/transfer-encoding-gzip-chunked

### Netty version
* 4.1.49.Final
* latest `4.1` branch(commit: 0375e6e01b0b6412c2369a8d3e2a990f41a9edfa)

### JVM version (e.g. `java -version`)
```
[lgao@lgao netty]$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```
### OS version (e.g. `uname -a`)
```
[lgao@lgao netty]$ uname -a
Linux lgao.corp.redhat.com 4.13.16-100.fc25.x86_64 #1 SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

### Linked Issue
https://github.com/eclipse-vertx/vert.x/issues/3353

### PR DESCRIPTION
**Pull request by gaol**
Motivation:

`containsValue()` will check if there are multiple values defined in the specific header name, we need to use this method instead of `contains()` for the `Transfer-Encoding` header to cover the case that multiple values defined, like: `Transfer-Encoding: gzip, chunked`

Modification:

Change from `contains()` to `containsValue()` in `HttpUtil.isTransferEncodingChunked()` method.

Fixes #10320

### CODE REVIEW

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java [hunk 1]
```diff
@@ -486,4 +486,23 @@ private static void testInvalidHeaders0(String requestStr) {
...
+                "\r\n" +
+                "71\r\n"
+                ;
+        EmbeddedChannel channel = new EmbeddedChannel(new HttpRequestDecoder());
+        assertTrue(channel.writeInbound(Unpooled.copiedBuffer(requestStr, CharsetUtil.US_ASCII)));
+        HttpRequest request = channel.readInbound();
+        assertFalse(request.decoderResult().isFailure());
+        assertTrue(request.headers().containsValue("Transfer-Encoding", "chunked", true));
+        assertFalse(request.headers().contains("Content-Length"));
+        LastHttpContent c = channel.readInbound();
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java:505]: you need to call `c.release();`

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java [hunk 2]
```diff
@@ -486,4 +486,23 @@ private static void testInvalidHeaders0(String requestStr) {
...
+
+    @Test
+    public void testTransferCodingGZIPAndChunked() {
+        String requestStr = "POST / HTTP/1.1\r\n" +
+                "Host: example.com\r\n" +
+                "Content-Type: application/x-www-form-urlencoded\r\n" +
+                "Transfer-Encoding: gzip, chunked\r\n" +
+                "\r\n" +
+                "71\r\n"
+                ;
```
Comment (normanmaurer) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java:498]: nit: move the `;` one line up

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java (hunk 1 above)
Comment (gaol) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java]: Done by `channel.releaseInbound()`

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java (hunk 2 above)
Comment (gaol) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java]: Done

**Comment by gaol** [comment]
@normanmaurer Done by addressing the above comments, thanks :)

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java [hunk 3]
```diff
@@ -486,4 +486,23 @@ private static void testInvalidHeaders0(String requestStr) {
...
     }
+
+    @Test
+    public void testTransferCodingGZIPAndChunked() {
+        String requestStr = "POST / HTTP/1.1\r\n" +
+                "Host: example.com\r\n" +
+                "Content-Type: application/x-www-form-urlencoded\r\n" +
+                "Transfer-Encoding: gzip, chunked\r\n" +
+                "\r\n" +
+                "71\r\n";
```
Comment (idelpivnitskiy) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java:497]: Consider writing the full HTTP request (including one or two chunks + last (zero) chunk + some trailers) to make sure that decoder's state machine transitions to the correct state and handles the entire request correctly.

Comment (gaol) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpRequestDecoderTest.java]: Done by move the tests to `HttpContentDecoderTest` to use the pre-defined `gzipped hello world` for testing.

**Comment by gaol** [comment]
@idelpivnitskiy After trying to use the full gzipped http request and checked the desired decoded request content, I found it did not decode the gzip content if we have `Transfer-Encoding: gzip` set, I updated the PR to address it as well. Please review again. Thanks :)

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecoder.java [hunk 4]
```diff
@@ -85,7 +85,15 @@ protected void decode(ChannelHandlerContext ctx, HttpObject msg, List<Object> ou
                 if (contentEncoding != null) {
                     contentEncoding = contentEncoding.trim();
                 } else {
-                    contentEncoding = IDENTITY;
+                    String transferEncoding = headers.get(HttpHeaderNames.TRANSFER_ENCODING);
+                    if (transferEncoding != null) {
+                        contentEncoding = transferEncoding.trim();
+                        if (transferEncoding.contains(",")) {
+                            contentEncoding = transferEncoding.split(",")[0].trim();
+                        }
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecoder.java:93]: This can be changed to the following code to reduce the `trim()` operations and also reduce allocations:

```java
int idx = transferEncoding.indexOf(",");
if (idx != -1) {
    contentEncoding = transferEncoding.subString(0, idx).trim();
} else {
    contentEncoding = transferEncoding.trim();
}
```

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java [hunk 5]
```diff
@@ -563,6 +563,78 @@ public void channelInactive(ChannelHandlerContext ctx) throws Exception {
...
+        HttpRequestDecoder decoder = new HttpRequestDecoder();
+        HttpContentDecoder decompressor = new HttpContentDecompressor();
+        EmbeddedChannel channel = new EmbeddedChannel(decoder, decompressor);
+
+        channel.writeInbound(Unpooled.copiedBuffer(requestStr.getBytes()));
+        channel.writeInbound(Unpooled.copiedBuffer(GZ_HELLO_WORLD));
+
+        HttpRequest request = channel.readInbound();
+        assertTrue(request.decoderResult().isSuccess());
+        assertFalse(request.headers().contains("Content-Length"));
```
Comment (idelpivnitskiy) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java:581]: Consider using `HttpHeaderNames.CONTENT_LENGTH` constant.

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java [hunk 6]
```diff
@@ -563,6 +563,78 @@ public void channelInactive(ChannelHandlerContext ctx) throws Exception {
...
+        EmbeddedChannel channel = new EmbeddedChannel(decoder, decompressor);
+
+        assertTrue(channel.writeInbound(Unpooled.copiedBuffer(requestStr, CharsetUtil.US_ASCII)));
+
+        String chunkLength = Integer.toHexString(GZ_HELLO_WORLD.length);
+        assertTrue(channel.writeInbound(Unpooled.copiedBuffer(chunkLength + "\r\n", CharsetUtil.US_ASCII)));
+        assertTrue(channel.writeInbound(Unpooled.copiedBuffer(GZ_HELLO_WORLD)));
+        assertTrue(channel.writeInbound(Unpooled.copiedBuffer("\r\n".getBytes(CharsetUtil.US_ASCII))));
+        assertTrue(channel.writeInbound(Unpooled.copiedBuffer("0\r\n", CharsetUtil.US_ASCII)));
+        assertTrue(channel.writeInbound(Unpooled.copiedBuffer("My-Trailer: 42\r\n\r\n\r\n", CharsetUtil.US_ASCII)));
```
Comment (idelpivnitskiy) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java:617]: Looks like too many `\r\n`. Should we have only 2 pairs instead of 3?

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java [hunk 7]
```diff
@@ -563,6 +563,78 @@ public void channelInactive(ChannelHandlerContext ctx) throws Exception {
...
+
+        HttpRequest request = channel.readInbound();
+        assertTrue(request.decoderResult().isSuccess());
+        assertTrue(request.headers().containsValue("Transfer-Encoding", "chunked", true));
+        assertFalse(request.headers().contains("Content-Length"));
```
Comment (idelpivnitskiy) [inline codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java:622]: Consider using constants from `HttpHeaderNames` and `HttpHeaderValues`.

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java (hunk 5 above)
Comment (gaol) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java:581]: Done

File: codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecoder.java (hunk 4 above)
Comment (gaol) [reply codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecoder.java:93]: Thanks for the advice, Done

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java (hunk 7 above)
Comment (gaol) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java:622]: Done

File: codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java (hunk 6 above)
Comment (gaol) [reply codec-http/src/test/java/io/netty/handler/codec/http/HttpContentDecoderTest.java:617]: Yeah, that is right. thanks for pointing out. done

**Comment by gaol** [comment]
Updated PR to address review comments. Thanks :)

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@gaol thanks a lot
