### PR TITLE
Use stream error for maxContentLength exceeded in InboundHttp2ToHttpAdapter

### LINKED ISSUE #11994: InboundHttp2ToHttpAdapter maxContentLength exceeded causes connection error
### Expected behavior
When using `InboundHttp2ToHttpAdapter`, sending a payload that exceeds maxContentLength should return a status code of 413 before closing the stream.

### Actual behavior
If a message payload exceeds maxContentLength, a connection error is thrown causing a GO_AWAY to be sent. This is confusing behavior to clients and we have seen load balancers treat these errors as 5xx errors when it's expected to be a client (4xx) error.

https://github.com/netty/netty/blob/c6e65cc006c4e0623e84ef96a88dc5bd5cb00a82/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java#L237-L240

https://github.com/netty/netty/blob/c6e65cc006c4e0623e84ef96a88dc5bd5cb00a82/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L665-L678

Curious if there's something I'm missing about why this results in a connection error.

### Steps to reproduce
Send a payload exceeding maxContentLength configured here to a pipeline using `InboundHttp2ToHttpAdapter`: https://github.com/netty/netty/blob/c6e65cc006c4e0623e84ef96a88dc5bd5cb00a82/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapterBuilder.java#L36-L39

### Netty version
4.1.73.Final

### PR DESCRIPTION
**Pull request by daguimu**
Motivation:

When a message payload exceeds `maxContentLength` in `InboundHttp2ToHttpAdapter`, a connection error (`INTERNAL_ERROR`) is thrown. This sends a GOAWAY frame that closes the entire HTTP/2 connection, affecting all concurrent streams. Load balancers often treat GOAWAY as a 5xx error, even though this is a client-side issue (sending a payload that is too large). Exceeding the content length for a single stream should only affect that stream.

Modification:

Changed the error from `connectionError(INTERNAL_ERROR)` to `streamError(streamId, ENHANCE_YOUR_CALM)` in `onDataRead()`. The `ENHANCE_YOUR_CALM` error code is semantically appropriate for resource limit violations per RFC 7540 Section 7.

Added test `exceedMaxContentLengthShouldCauseStreamErrorNotConnectionError()` that sends oversized data on stream 3 and verifies:
- A `StreamException` (not connection error) is produced
- The error targets stream 3 with `ENHANCE_YOUR_CALM` error code
- The test correctly fails when the fix is reverted

Result:

Fixes #11994.

### CODE REVIEW

File: codec-http2/src/test/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapterTest.java [hunk 1]
```diff
@@ -290,6 +290,56 @@ public void run() throws Http2Exception {
         }
     }
 
+    @Test
+    public void exceedMaxContentLengthShouldCauseStreamErrorNotConnectionError() throws Exception {
```
Comment (chrisvest) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapterTest.java:294]: This test still pass if I undo your change in `InboundHttp2ToHttpAdapter`.

Please make the test capture the scenario described in the original issue, and include assertions on the produced error.

**Review by chrisvest — CHANGES_REQUESTED** [review]

**Comment by daguimu** [comment]
@chrisvest Thanks for the review! You're right — the previous test passed even with the fix reverted because it only checked whether stream 5 was delivered, which could succeed due to LocalChannel's frame-by-frame delivery semantics regardless of connection vs stream error.

I've pushed a new commit that fixes this by asserting on the **produced error** directly:

**Key changes:**
- `boostrapEnv(0, 1, 1)` → `boostrapEnv(1, 1, 1)` — `clientLatch=1` now waits for the RST_STREAM exception on the client side
- Added `awaitResponses()` + assertions on `clientException`:
  - `assertTrue(isStreamError(clientException))` — verifies it is a stream error, not connection error
  - `assertEquals(3, streamEx.streamId())` — targets the oversized stream
  - `assertEquals(Http2Error.ENHANCE_YOUR_CALM, streamEx.error())` — correct error code

**Why this fails when the fix is reverted:**

With `connectionError`, the server sends GOAWAY instead of RST_STREAM. Since `InboundHttp2ToHttpAdapter.onRstStreamRead` is never called on the client, `exceptionCaught` never fires, `clientLatch` never counts down, and `awaitResponses()` times out — correctly failing the test.

With the fix (`streamError`), the server sends RST_STREAM for stream 3 → client's `onRstStreamRead` fires `exceptionCaught` with a `StreamException` → `clientLatch` counts down → all assertions pass.

File: codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java [hunk 2]
```diff
@@ -233,7 +234,7 @@ public int onDataRead(ChannelHandlerContext ctx, int streamId, ByteBuf data, int
         ByteBuf content = msg.content();
         final int dataReadableBytes = data.readableBytes();
         if (content.readableBytes() > maxContentLength - dataReadableBytes) {
-            throw connectionError(INTERNAL_ERROR,
+            throw streamError(streamId, ENHANCE_YOUR_CALM,
```
Comment (normanmaurer) [inline codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java:237]: @ejona86 @bryce-anderson WDYT ?

Comment (bryce-anderson) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java:237]: I think stream error and this status code is appropriate. Typically this would be a 413 response in both HTTP/1.x and HTTP/2 (and then a RST would follow while a HTTP/1.x stream may try to salvage the connection or just close it) but I suspect it will end up surfacing only as a RST_STREAM.

Comment (ejona86) [reply codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java:237]: This is when the request body is too large to fully buffer? Yeah, that shouldn't be a connection error. In fact, ideally I'd expect a regular HTTP error code+RST_STREAM(NO_ERROR), but RST_STREAM alone would work okay.

Nothing in this class should be creating connection errors, right, since all essential protocol errors would have been noticed before getting here? Looking at the other instances:

> throw connectionError(PROTOCOL_ERROR, "Data Frame received for unknown stream id %d", streamId);
> throw connectionError(PROTOCOL_ERROR, "Push Promise Frame received for pre-existing stream id %d",
>                    promisedStreamId);

Seems those can only happens if putMessage() had previously been called, and then PUSH_PROMISE when it passes allowAppend=false to processHeadersBegin() will return null? And that only happens if this was the second HEADERS for the stream. Definitely very strange, but does seem better as a stream error than connection error.

**Comment by yawkat** [comment]
Please follow PR content conventions.

Also, looking at the adapter, it seems weird to me that it has a content length limit at all. It should be possible to avoid the message copy and forward the body as-is. Downstream handlers can limit content length if they wish, but it shouldn't factor in here.

But that may require an incompatible change.

**Comment by daguimu** [comment]
@yawkat Thanks for the feedback! I've updated the PR title and description to follow the content conventions.

Regarding the broader question about whether `maxContentLength` belongs in this adapter — I agree it's worth discussing. It should be possible to let downstream handlers limit content length instead. However, removing it would be an incompatible change. This PR focuses on the minimal fix: converting the existing check from a connection error to a stream error, so it doesn't break other concurrent streams.

Happy to discuss removing the limit entirely as a separate effort if that's desired.

**Review by normanmaurer — APPROVED** [review]

**Comment by normanmaurer** [comment]
@ejona86 @yawkat @bryce-anderson so I am correct to say that you are ok with the change and we should merge it ?

**Comment by ejona86** [comment]
I have no concern. I didn't do a full review, but what I saw made it seem this is strictly better than the old behavior.

**Review by bryce-anderson — COMMENTED** [review]
Post merge 🚢 from me.
