### PR TITLE
Use initialized BouncyCastle providers when available

### LINKED ISSUE #14826: Improve SSL context support using BouncyCastlePemReader in native images
BC provider is instantiated in `BouncyCastlePemReader` even when it is registered as Security provider. When using JVM it doesn't make a difference whether Netty instantiates the provider itself or take the provider instance from `java.security.Security#getProvider`. However when debugging https://github.com/quarkusio/quarkus/issues/46279 I have mentioned that provider instantiated during at the build time has more services then the one created during the first `BouncyCastlePemReader` usage. Registering every required BC class for reflection can be difficult task. Would it be possible to try `Security.getProvider("BC")` (`Security.getProvider("BCFIPS")` respectively) before instantiating classes using reflection API? Alternatively maybe allow users to specify BC provider themselves?

I'd appreciate any change that would allow me to use official Netty API rather than working around my issues. Thank you

### Details

I am using `4.1.118.Final`.

### Steps to reproduce

Clone `git@github.com:michalvavrik/netty-ssl-context-bouncycastle-native-issue-reproducer.git`, run `mvn clean verify -Dnative`. My `SslContextBuilder.forClient().keyManager(certificate, privateKey).build()` works with JVM:

```
2025-02-16 15:28:15,409 DEBUG [io.net.han.ssl.BouncyCastlePemReader] (executor-thread-1) Bouncy Castle provider available
2025-02-16 15:28:15,421 DEBUG [io.net.han.ssl.BouncyCastlePemReader] (executor-thread-1) Parsed PEM object of type org.bouncycastle.openssl.PEMKeyPair and assume key is not encrypted
2025-02-16 15:28:15,490 DEBUG [io.net.han.ssl.OpenSsl] (executor-thread-1) netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
2025-02-16 15:28:15,510 DEBUG [io.net.han.ssl.JdkSslContext] (executor-thread-1) Default protocols (JDK): [TLSv1.3, TLSv1.2] 
2025-02-16 15:28:15,510 DEBUG [io.net.han.ssl.JdkSslContext] (executor-thread-1) Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384]
SSL context for certificate java.io.ByteArrayInputStream@7e2e2176 is io.netty.handler.ssl.JdkSslClientContext@4b6addbd

2025-02-16 15:28:15,634 DEBUG [io.net.han.ssl.BouncyCastlePemReader] (executor-thread-1) Parsed PEM object of type org.bouncycastle.asn1.pkcs.PrivateKeyInfo and assume key is not encrypted
```
 but failing when using the native image:
```
2025-02-16 15:29:56,391 DEBUG [io.net.han.ssl.BouncyCastlePemReader] (executor-thread-1) Bouncy Castle provider available
2025-02-16 15:29:56,391 DEBUG [io.net.han.ssl.BouncyCastlePemReader] (executor-thread-1) Parsed PEM object of type org.bouncycastle.openssl.PEMKeyPair and assume key is not encrypted
2025-02-16 15:29:56,391 DEBUG [io.net.han.ssl.BouncyCastlePemReader] (executor-thread-1) Unable to extract private key: org.bouncycastle.openssl.PEMException: unable to convert key pair: no such algorithm: EC for provider BC
	at org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter.getKeyPair(Unknown Source)
	at io.netty.handler.ssl.BouncyCastlePemReader.getPrivateKey(BouncyCastlePemReader.java:177)
	at io.netty.handler.ssl.BouncyCastlePemReader.getPrivateKey(BouncyCastlePemReader.java:124)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1204)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:421)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:348)
	at org.acme.BouncyCastleEndpoint.pkcs1(BouncyCastleEndpoint.java:39)
	at org.acme.BouncyCastleEndpoint$quarkusrestinvoker$pkcs1_b8002ac5f80c85fa5587227252617383662986bc.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:639)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@21.0.6/java.lang.Thread.runWith(Thread.java:1596)
	at java.base@21.0.6/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)
Caused by: java.security.NoSuchAlgorithmException: no such algorithm: EC for provider BC
	at java.base@21.0.6/sun.security.jca.GetInstance.getService(GetInstance.java:101)
	at java.base@21.0.6/sun.security.jca.GetInstance.getInstance(GetInstance.java:218)
	at java.base@21.0.6/java.security.KeyFactory.getInstance(KeyFactory.java:266)
	at org.bouncycastle.jcajce.util.ProviderJcaJceHelper.createKeyFactory(Unknown Source)
	at org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter.getKeyFactory(Unknown Source)
	... 23 more
```

### Workaround

I have tried using `BC` provider registered as `Security` provider and it worked, but I don't want this to keep in place (Netty can easily change implementation):

```
@com.oracle.svm.core.annotate.TargetClass(className = "io.netty.handler.ssl.BouncyCastlePemReader", onlyWith = NettySslBountyCastleSupportRequired.class)
final class Target_io_netty_handler_ssl_BouncyCastlePemReader {
    @Alias
    private static volatile Provider bcProvider;
    @Alias
    private static volatile boolean attemptedLoading;
    @Alias
    private static volatile Throwable unavailabilityCause;

    @com.oracle.svm.core.annotate.Substitute
    public static boolean isAvailable() {
        if (!attemptedLoading) {
            bcProvider = Security.getProvider(SecurityProviderUtils.BOUNCYCASTLE_PROVIDER_NAME);
            if (bcProvider == null) {
                bcProvider = Security.getProvider(SecurityProviderUtils.BOUNCYCASTLE_FIPS_PROVIDER_NAME);
            }
            if (bcProvider == null) {
                tryLoading();
            } else {
                attemptedLoading = true;
            }
        }
        return unavailabilityCause == null;
    }

    @Alias
    private static void tryLoading() {

    }
}
```

### PR DESCRIPTION
**Pull request by michalvavrik**
Motivation:

Before this change, the 'io.netty.handler.ssl.BouncyCastlePemReader' class used by the SSL context always instantiated a new BouncyCastle provider when one of supported providers were on the classpath. When Netty is used in a native image created with GraalVM, the moment of initialization matters. Providers instantiated when the native image is built will see different classes than providers instantiated during runtime unless every single class the BouncyCastle loads using the reflection API is registered for a reflection. Some frameworks like Quarkus makes sure that BouncyCastle providers are created for users and registered with the Java Security API. However in this case, the providers prepared by Quarkus are ignored and users are left to a difficult task to find all required classes loaded by the BouncyCastle for their use case and register them. This commit prefers the providers registered against the Java Security API and fallbacks to manual class instantiation, so that user experience improves when using native executables.

Modifications:

I have modified 'src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java' to load the 2 supported BouncyCastle providers (BC/BCFIPS) from the Java Security API first and fallback to previous behavior when the providers are not available. I didn't find any test class explicitly testing this 'BouncyCastlePemReader', therefore I added a new test class, 'src/test/java/io/netty/handler/ssl/BouncyCastlePemReaderTest.java', that assures providers are loaded from the Java Security API, but when not available, Netty creates a new providers if respective classes are available on the classpath.

Result:

It will be easier to use SSL context with BouncyCastle support in native images.

Fixes #14826.

### CODE REVIEW

File: handler/src/test/java/io/netty/handler/ssl/BouncyCastlePemReaderTest.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
+/*
+ * Copyright 2016 The Netty Project
```
Comment (normanmaurer) [inline handler/src/test/java/io/netty/handler/ssl/BouncyCastlePemReaderTest.java:2]:
```suggestion
 * Copyright 2025 The Netty Project
```

File: handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java [hunk 2]
```diff
@@ -104,6 +113,19 @@ public Void run() {
         });
     }
 
+    /**
+     * Allows to test {@link #attemptedLoading} under different conditions.
+     *
+     * @return previous {@link #bcProvider} value
+     */
+    static Provider resetBcProvider() {
```
Comment (normanmaurer) [inline handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java:121]: Do we need to use a specific "isolation" when running the tests ?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java (hunk 2 above)
Comment (michalvavrik) [reply handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java:121]: It is either that or using reflection (which I am fine with), I don't know how else to test both scenarios (BC and BCFIPS provider).

Comment (michalvavrik) [reply handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java:121]: I don't think it does. But it can't be run in paralel with other tests, good point, this needs isolation.

Comment (michalvavrik) [reply handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java:121]: Done, test is now isolated.

File: handler/src/test/java/io/netty/handler/ssl/BouncyCastlePemReaderTest.java [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+public class BouncyCastlePemReaderTest {
+
+    @Test
+    public void testBouncyCastleProviderLoaded() {
+        // tests org.bouncycastle.jce.provider.BouncyCastleProvider is detected as available
+        // because provider with matching name is present in 'java.security.Security'
+
+        Assertions.assertTrue(BouncyCastlePemReader.isAvailable());
+        Provider bcProvider = BouncyCastlePemReader.resetBcProvider();
+        Assertions.assertNotNull(bcProvider);
```
Comment (normanmaurer) [inline handler/src/test/java/io/netty/handler/ssl/BouncyCastlePemReaderTest.java:36]: nit: import static method.

Comment (michalvavrik) [reply handler/src/test/java/io/netty/handler/ssl/BouncyCastlePemReaderTest.java:36]: I did import static methods for `Assertions`, done, didn't do it for `Security` or `BouncyCastlePemReader` because there it is so obvious where the static method comes from (belongs) unless I look at the static imports. I can do it for these too, it is just my personal preference.

Comment (michalvavrik) [reply handler/src/test/java/io/netty/handler/ssl/BouncyCastlePemReaderTest.java]: But I can import every single static method if you feel strongly about it, just say a word.

**Review by chrisvest — APPROVED** [review]
