### PR TITLE
Fix sending an empty String like "" causes an error #9429

### LINKED ISSUE #9429: Sending an empty String like "" causes an error

### PR DESCRIPTION
**Pull request by amizurov**
Motivation:

Handle https://tools.ietf.org/html/rfc7692#section-7.2.3.6

Result:

The empty buffer is correctly handled in deflate  encoder/decoder. Fixes #9429 .

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java [hunk 1]
```diff
@@ -73,6 +77,35 @@ protected WebSocketExtensionFilter extensionDecoderFilter() {
 
     @Override
     protected void decode(ChannelHandlerContext ctx, WebSocketFrame msg, List<Object> out) throws Exception {
+        ByteBuf decompressedContent = decompressContent(ctx, msg);
+
+        WebSocketFrame outMsg;
```
Comment (normanmaurer) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: final

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java [hunk 2]
```diff
@@ -81,12 +114,14 @@ protected void decode(ChannelHandlerContext ctx, WebSocketFrame msg, List<Object
         }
 
         boolean readable = msg.content().isReadable();
+        boolean emptyDeflateBlock = EMPTY_DEFLATE_BLOCK.equals(msg.content());
```
Comment (doom369) [inline codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: maybe we can inline this into the condition where it is used?

`if (readable && compositeDecompressedContent.numComponents() <= 0 && !EMPTY_DEFLATE_BLOCK.equals(msg.content())) {`

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java (hunk 1 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]: Done for both encoder/decoder

File: codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java (hunk 2 above)
Comment (amizurov) [reply codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/DeflateDecoder.java]:
```
decoder.writeInbound(msg.content().retain());
        if (appendFrameTail(msg)) {
            decoder.writeInbound(FRAME_TAIL.duplicate());
        }
```
after decompression msg.content() is not readable.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@amizurov thanks a lot!
