### PR TITLE
Fix bugs in BoundedInputStream (#14479)

### LINKED ISSUE #14479: IOException: Maximum number of bytes read
This issue was introduced in v4.1.115 by commit [fbf7a70](https://github.com/netty/netty/commit/fbf7a704a82e7449b48bd0bbb679f5661c6d61a3)

### Expected behavior
Netty starts without error

### Actual behavior
Netty logs an exception when starting:
```
io.netty.util.internal.PlatformDependent -- Error while reading content of /etc/os-release
java.io.IOException: Maximum number of bytes read: 8192
	at io.netty.util.internal.BoundedInputStream.checkMaxBytesRead(BoundedInputStream.java:79)
	at io.netty.util.internal.BoundedInputStream.read(BoundedInputStream.java:58)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:350)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:393)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:160)
	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436)
	at io.netty.util.internal.PlatformDependent$4.run(PlatformDependent.java:246)
	at io.netty.util.internal.PlatformDependent$4.run(PlatformDependent.java:235)
```
What is strange is that `/etc/os-release` is a symlink to `/usr/lib/os-release`, which itself is just a 386 byte file, way under 8192 bytes.  This leads me to think there is a bug in the new `BoundedInputStream` class, but I can't immediately spot it.

### Steps to reproduce
start netty up on a system which has a non-zero /etc/os-release

### Netty version
4.1.115

### JVM version (e.g. `java -version`)
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux 5d84cc8b4bf8 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by scarytom**
Motivation:

A BoundedInputStream was recently introduced to protect against attacks where a large file was placed on the server.  Unfortunately, this has an issue preventing it from reading the last bytes of a file where the buffer size would take the total bytes over the set bound, when reading just the remaining bytes in the file fits underneath the set bound.

Modification:

Adjusted the behaviour of BoundedInputStream to, where appropriate, read 1 more byte than the set bound, to see if the file terminates at this point, in which case there is no need to throw the exception

Result:

Fixes #14479.

### CODE REVIEW

**Review by normanmaurer — APPROVED** [review]

File: common/src/main/java/io/netty/util/internal/BoundedInputStream.java [hunk 1]
```diff
@@ -37,47 +37,37 @@ public BoundedInputStream(@NotNull InputStream in) {
...
+        return b;
     }
 
     @Override
     public int read(byte[] buf, int off, int len) throws IOException {
+        checkMaxBytesRead();
+
         // Calculate the maximum number of bytes that we should try to read.
         int num = Math.min(len, maxBytesRead - numRead + 1);
-        checkMaxBytesRead(num);
```
Comment (idelpivnitskiy) [inline common/src/main/java/io/netty/util/internal/BoundedInputStream.java:58]: The original motivation for checking for `num` was to fail before starting the actual read (no need to try reading if we know we are going out of bound). Is it possible to preserve that behavior?

Comment (idelpivnitskiy) [reply common/src/main/java/io/netty/util/internal/BoundedInputStream.java:58]: `maxBytesRead` already protects from "don't read more than allowed", but it is worth reading if the requested `len` is larger than `maxBytesRead`?

Comment (scarytom) [reply common/src/main/java/io/netty/util/internal/BoundedInputStream.java:58]: > The original motivation for checking for `num` was to fail before starting the actual read (no need to try reading if we know we are going out of bound). Is it possible to preserve that behavior?

No, it is not possible to do that.  You have no idea when the underlying stream will terminate, so just because the request is to read `len` bytes, you cannot assume that many bytes will actually be read.

**Comment by scarytom** [comment]
> checking the bytes consumed after the fact is also doesn't seem right.

It is impossible to do this correctly without attempting to read from the underlying stream.  There is simply no way of telling how many bytes will actually be read without attempting to read them.

At the moment, we have a version of netty out in the wild that is logging stacktraces every time it is started.

> We could split the difference and let the bulk-read operation read up to the limit, and only throw if reads are done at the limit and beyond.

The code that I submitted is already doing this.  It only reads up to the limit, and throws if the underlying stream is not consumed at this point.

File: common/src/main/java/io/netty/util/internal/BoundedInputStream.java [hunk 2]
```diff
@@ -37,47 +37,37 @@ public BoundedInputStream(@NotNull InputStream in) {
...
-            numRead -= num;
-            throw e;
+
+        int b = super.read(buf, off, num);
+
+        if (b > 0) {
+            numRead += b;
         }
+
+        checkMaxBytesRead();
```
Comment (chrisvest) [inline common/src/main/java/io/netty/util/internal/BoundedInputStream.java:64]: What's the idea with potentially throwing after we've done the read?

Comment (scarytom) [reply common/src/main/java/io/netty/util/internal/BoundedInputStream.java:64]: Because we can't know if we hit the bound until after we have done the read

**Comment by normanmaurer** [comment]
@chrisvest @idelpivnitskiy I think this one is fine... can you check again ?

File: common/src/main/java/io/netty/util/internal/BoundedInputStream.java (hunk 1 above)
Comment (idelpivnitskiy) [reply common/src/main/java/io/netty/util/internal/BoundedInputStream.java:58]: Ok, so for the cases when the caller doesn't know about the underlying file size and the `BoundedInputStream` protection, it can still request more which doesn't mean we read that much. Makes sense to me, thanks for clarifying.

**Review by idelpivnitskiy — APPROVED** [review]

**Review by chrisvest — APPROVED** [review]

**Comment by normanmaurer** [comment]
@scarytom thanks a lot
