### PR TITLE
Fix event loop hang in SniHandler

### LINKED ISSUE #9919: Event loop threads hang in SniHandler for SSL records with majorVersion != 3
Under some unknown and rare circumstances 2 worker threads started to consume 100% CPU time of a single core each, permanently and indefinitely. It didn't prevent the app from its normal functioning, nevertheless excessive consumption of cpu is not a normal behaviour.
Noticed this behaviour once by now.

### Actual behavior
Epoll transport enabled. Two threads (out of four) burn 100% CPU time, each has the following stacktrace:

"epollEventLoopGroup-7-1" #20 prio=10 os_prio=0 cpu=120413943.05ms elapsed=889961.34s tid=0x00007fa110003000 nid=0x4381 runnable [0x00007fa124c2d000]
java.lang.Thread.State: RUNNABLE

"epollEventLoopGroup-7-3" #22 prio=10 os_prio=0 cpu=55102833.55ms elapsed=889961.34s tid=0x00007fa110008800 nid=0x4383 runnable [0x00007fa124a2b000]

```
"epollEventLoopGroup-7-3" #22 prio=10 os_prio=0 cpu=54941845.34ms elapsed=889798.92s tid=0x00007fa110008800 nid=0x4383 runnable  [0x00007fa124a2b000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1432)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1419)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1414)
        at io.netty.buffer.AbstractByteBuf.getByte(AbstractByteBuf.java:356)
        at io.netty.buffer.AbstractByteBuf.getUnsignedByte(AbstractByteBuf.java:369)
        at io.netty.handler.ssl.AbstractSniHandler.decode(AbstractSniHandler.java:62)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:493)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@12.0.2/Thread.java:835)
```

### Steps to reproduce
Haven't yet found the scenario.

### Netty version
4.1.44

### JVM version (e.g. `java -version`)
openjdk 12.0.2 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+9-Debian-1)
OpenJDK 64-Bit Server VM (build 12.0.2+9-Debian-1, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux hostname 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by njhill**
Motivation

A bug was introduced in #9806 which looks likely to be the cause of #9919. `SniHandler` will enter an infinite loop if an SSL record is received with SSL major version byte != 3 (i.e. something other than TLS or SSL3.0)

Modifications

- Follow default path as intended  for `majorVersion != 3` in `AbstractSniHandler#decode(...)`
- Add unit test to reproduce the hang

Result

Fixes #9919

### CODE REVIEW

**Comment by njhill** [comment]
@normanmaurer this appears to be a fairly serious vulnerability, I guess it would be trivially easy to cripple an affected server.

File: handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java [hunk 1]
```diff
@@ -344,6 +344,42 @@ public void testFallbackToDefaultContext() throws Exception {
...
+
+            SniHandler handler = new SniHandler(mapping);
+            EmbeddedChannel ch = new EmbeddedChannel(handler);
+
+            // invalid
+            byte[] message = {22, 2, 0, 0, 0};
+            try {
+                // Push the handshake message.
+                ch.writeInbound(Unpooled.wrappedBuffer(message));
+            } catch (Exception e) {
```
Comment (normanmaurer) [inline handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java]: add `fail();` above

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java (hunk 1 above)
Comment (njhill) [reply handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java]: @normanmaurer done, I actually just copied the existing `testFallbackToDefaultContext()` as a starting point, which had this `fail()` commented out for some reason. So I've uncommented it there too since an exception does also get thrown in that case.

File: handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java [hunk 2]
```diff
@@ -320,7 +320,7 @@ public void testFallbackToDefaultContext() throws Exception {
                 ch.writeInbound(Unpooled.wrappedBuffer(message));
                 // TODO(scott): This should fail because the engine should reject zero length records during handshake.
                 // See https://github.com/netty/netty/issues/6348.
-                // fail();
+                fail();
```
Comment (normanmaurer) [inline handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java]: @njhill thanks... Lets see if this works for all JDK versions that we use on the CI :) If so we can close the issue as well.

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java (hunk 1 above)
Comment (normanmaurer) [reply handler/src/test/java/io/netty/handler/ssl/SniHandlerTest.java]: @njhill after some more digging this actually depends on if `jdkCompatibilityMode` is true of not. Let me do a follow up to fix it and then investigate later on.
