### PR TITLE
Fix behavior of HttpPostMultipartRequestDecoder for Memory based Factory

### LINKED ISSUE #11143: HttpPostMultipartRequestDecoder may not add content to an existing upload after being offered data
### Expected behavior

Once a file upload object exists in the multipart request decoder, but not finished, offering more data to the decoder should populate the buffer of the file object

### Actual behavior

The buffer is not created/updated

### Steps to reproduce

- `git clone https://github.com/micronaut-projects/micronaut-core`
- `git checkout upgrade-netty`
- `./gradlew test-suite:test --tests "io.micronaut.upload.StreamUploadSpec.test the file is not corrupted with transferTo"`

### Netty version
4.1.60+ due to https://github.com/netty/netty/pull/11001

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)

### OS version (e.g. `uname -a`)
Darwin MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

This issue is a blocker for Micronaut to upgrade Netty. With the functionality as it is, it is impossible to read a chunk of the file and release it immediately because new buffers are not set on the underlying file upload object.

This line is the culprit. https://github.com/fredericBregier/netty/blob/6daeb0cc51d8689805c1a657e61d395450afec47/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java#L1187

In my case `posDelimiter` is 0, so the content is never added to the upload.

### PR DESCRIPTION
**Pull request by fredericBregier**
Motivation:
When Memory based Factory is used, if the first chunk starts with Line Break, the HttpData
is not filled with the current available buffer if the delimiter is not found yet, while it may
add some.

Fix JavaDoc to note potential wrong usage of content() or getByteBuf() if HttpDatais has
a huge content with the risk of Out Of Memory Exception.

Fix JavaDoc to explain how to release properly the Factory, whatever it is in Memory,
Disk or Mixed mode.

Modifications:
First, when the delimiter is not found, instead of searching Line Break from readerIndex(), we should search
from readerIndex() + readableBytes() - delimiter size, since this is the only part where usefull
Line Break could be searched for, except if readableBytes is less than delimiter size (then we search from
readerIndex).

Second, when a Memory HttpData is created, it should be assigned an empty buffer to be
consistent with the other implementations (Disk or Mixed mode).
We cannot change the default behavior of the content() or getByteBuf() of the Memory based HttpData
since the ByteBuf is supposed to be null when released, but not empty.
When a new ByteBuf is added, one more check verifies if the current ByteBuf is empty, and if so, it
is released and replaced by the new one, without creating a new CompositeByteBuf.

Result:
In the tests testBIgFileUploadDelimiterInMiddleChunkDecoderMemoryFactory and related for other modes,
the buffers are starting with a CRLF.
When we offer only the prefix part of the multipart (no data at all), the current Partial HttpData has
an empty buffer.
The first time we offer the data starting with CRLF to the decoder, it now
has a correct current Partial HttpData with a buffer not empty.

The Benchmark was re-run against this new version.

     Old Benchmark                                                                      Mode  Cnt  Score   Error   Units
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigAdvancedLevel   thrpt    6  4,025 ±  0,035  ops/ms
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigDisabledLevel   thrpt    6  4,258 ±  0,094  ops/ms
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigParanoidLevel   thrpt    6  0,845 ±  0,008  ops/ms
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigSimpleLevel     thrpt    6  4,102 ±  0,028  ops/ms
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighAdvancedLevel  thrpt    6  2,261 ±  0,104  ops/ms
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighDisabledLevel  thrpt    6  2,536 ±  0,020  ops/ms
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighParanoidLevel  thrpt    6  0,183 ±  0,001  ops/ms
    HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighSimpleLevel    thrpt    6  2,399 ±  0,175  ops/ms

     New Benchmark                                                                      Mode  Cnt  Score   Error   Units
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigAdvancedLevel   thrpt    6  5,675 ± 0,315  ops/ms
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigDisabledLevel   thrpt    6  6,067 ± 0,162  ops/ms
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigParanoidLevel   thrpt    6  0,911 ± 0,011  ops/ms
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderBigSimpleLevel     thrpt    6  6,119 ± 0,040  ops/ms
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighAdvancedLevel  thrpt    6  2,620 ± 0,240  ops/ms
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighDisabledLevel  thrpt    6  3,046 ± 0,135  ops/ms
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighParanoidLevel  thrpt    6  0,183 ± 0,002  ops/ms
     HttpPostMultipartRequestDecoderBenchmark.multipartRequestDecoderHighSimpleLevel    thrpt    6  2,988 ± 0,061  ops/ms

So +25 to +45% improvement due to not searching for CRLF/LF into the full buffer when no delimiter is found,
but only from the end and delimiter size + 2 (CRLF).

Fixes #11143

### CODE REVIEW

**Comment by fredericBregier** [comment]
Wait a bit for the user that raised this issue: seems ok but some other points to check still.

**Comment by chrisvest** [comment]
@fredericBregier Do you want to mark this PR as a draft until you think it's ready for review?

**Comment by fredericBregier** [comment]
@chrisvest According to user reporting the issue #11143 it seems OK.
So I believe review can start. ;-)

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMemoryHttpData.java [hunk 1]
```diff
@@ -43,6 +43,7 @@
 
     protected AbstractMemoryHttpData(String name, Charset charset, long size) {
         super(name, charset, size);
+        byteBuf = EMPTY_BUFFER;
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMemoryHttpData.java:46]: Why this change? There are a number of places in the code where we check if `byteBuf` is `null`. Also, when `delete` is called, the `byteBuf` is set to `null`.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java [hunk 2]
```diff
@@ -122,14 +122,16 @@
...
      *
      * @return the contents of the file item as an array of bytes.
      * @throws IOException
      */
     byte[] get() throws IOException;
 
     /**
-     * Returns the content of the file item as a ByteBuf
+     * Returns the content of the file item as a ByteBuf.
+     * One should take care of memory allocation if it is a huge content.
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java:134]: The English for these two comments reads weird. How about:

> Note: this method will allocate a lot of memory, if the data is currently stored on the file system.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java [hunk 3]
```diff
@@ -172,6 +172,34 @@ static int findLineBreak(ByteBuf buffer, int index) {
...
+            // No LF, so neither CRLF
+            return  -1;
+        }
+        int foundLF = 1;
+        if (posFirstChar > 0 && buffer.getByte(index + posFirstChar - 1) == HttpConstants.CR) {
+            posFirstChar--;
+            foundLF++;
+        }
+        // Might be not the last LF or CRLF
+        int nextPos = findLastLineBreak(buffer, index + posFirstChar + foundLF);
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java:196]: I'd prefer this method was iterative rather than recursive. Recursion, especially when based on external input, can cause unpredictable stack usage. It's also harder on the JIT.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java [hunk 4]
```diff
@@ -172,6 +172,34 @@ static int findLineBreak(ByteBuf buffer, int index) {
...
+     * Try to find last LF or CRLF as Line Breaking
+     *
+     * @param buffer the buffer to search in
+     * @param index the index to start from in the buffer
+     * @return a relative position from index > 0 if LF or CRLF is found
+     *         or < 0 if not found
+     */
+    static int findLastLineBreak(ByteBuf buffer, int index) {
+        int toRead = buffer.readableBytes() - (index - buffer.readerIndex());
+        int posFirstChar = buffer.bytesBefore(index, toRead, HttpConstants.LF);
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java:185]: Since we scan start to end, this method can be implemented in terms of `findLineBreak`, right?

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java [hunk 5]
```diff
@@ -1173,6 +1180,8 @@ private static boolean loadDataMultipartOptimized(ByteBuf undecodedChunk, String
                 undecodedChunk.writerIndex(startReaderIndex);
                 return false;
             } else if (posDelimiter > 0) {
+                // posDelimiter is not from startReaderIndex but from startReaderIndex + lastPosition
+                posDelimiter += lastPosition;
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1184]: The `else` branch can be unwrapped since the `if` branch above never completes normally.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java [hunk 6]
```diff
@@ -1159,8 +1160,14 @@ private static boolean loadDataMultipartOptimized(ByteBuf undecodedChunk, String
...
-            // Not found but however perhaps because incomplete so search LF or CRLF
-            posDelimiter = HttpPostBodyUtil.findLineBreak(undecodedChunk, startReaderIndex);
+            // Not found but however perhaps because incomplete so search LF or CRLF from the end within delimiter
+            // possible partial last bytes
+            int lastPosition = undecodedChunk.readableBytes() - bdelimiter.length;
+            if (lastPosition < 0) {
+                // Not enough bytes but can still try to find CRLF
+                lastPosition = 0;
+            }
+            posDelimiter = HttpPostBodyUtil.findLastLineBreak(undecodedChunk, startReaderIndex  + lastPosition);
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1170]: So… we didn't find a complete delimiter, _but_ if we see a CRLF within a delimiters length of the end, then we _might_ have a delimiter that straddles two read calls i.e. two buffers. And that means we can't be sure that we won't have a delimiter in that byte range, so we can only add the content prior to the CRLF to the HttpData. And then in the next call, the data we didn't read here will be carried over, and get more added to it, and then we'll be able to tell if there's really a delimiter there or not.

Is my understanding correct?

**Review by chrisvest — COMMENTED** [review]
Had some comments.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMemoryHttpData.java (hunk 1 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMemoryHttpData.java:46]: The reason is the different behavior between Memory and Disk. When we allocate a Disk based, the buffer, not here, is like it is there. In Memory, it was not.
Therefore, for those realying on existing buffer, even empty, is not correct (as reporting by the user in his issue). He used the `decoder.currentPartialHttpData()` in his code (legal), but then when he asked for the buffer, he's got "null" instead of an empty buffer when the buffer has not yet data pushed by the decoder.

When the buffer is released, the buffer is set to null after releasing it.
So it does not change the global behavior but makes both implementation seemless the same, which was the main issue.

Note that the change also gives more chance to use the current decoded buffer to fill the `currentHttpData`.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java (hunk 2 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java:134]: It's the reverse. I would then propose:

     Note: this method will allocate a lot of memory, if the data is not currently stored on the file system.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java (hunk 3 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java:196]: OK, let me try to break the recursion.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java (hunk 4 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java:185]: Let me see (double check) if those two methods are indeed the same, just by changing the index value.

I'm not that sure since `fineLineBreak` finds the "first" one, while `findLastLineBreak` finds the "last" one (so the recursion for the moment). And as it is not optimized to make a reverse reading (we cannot use `bytesBefore`)...

**Comment by fredericBregier** [comment]
@chrisvest I will update the PR according to your feedback (and the small issues I've found and detailed in your review).

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java (hunk 2 above)
Comment (chrisvest) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java:134]: In `AbstractMemoryHttpData`, the `getByteBuf` method just returns the contained `ByteBuf` instance, so no memory is allocated just from calling that method. Though for the `get` method, it does allocate a new byte array.

For `AbstractDiskHttpData`, both of those methods allocate a byte array.

So the only case that doesn't allocate a lot is `getByteBuf` on `AbstractMemoryHttpData`. So maybe the warning should be unconditional.

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java]: Yes right ! I just write the exact opposite of my own logic, and the reason I wrote this warning.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMemoryHttpData.java (hunk 1 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMemoryHttpData.java:46]: Shall be kept

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java (hunk 2 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpData.java]: Done

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java (hunk 4 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: Not the same (first vs last)

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java (hunk 3 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: Done

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java (hunk 6 above)
Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java:1172]: Correction done

**Review by fredericBregier — COMMENTED** [review]
Corrections from @chrisvest  done

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java (hunk 5 above)
Comment (chrisvest) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java]: I mean that

```
if … {
    return …;
} else if … {
    return …;
}
return …;
```

Can be written as

```
if … {
    return …;
}
if … {
    return …;
}
return …;
```

Intellij likes to point this out.

**Comment by fredericBregier** [comment]
@chrisvest Done ;-)

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java (hunk 4 above)
Comment (chrisvest) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: I was thinking something like this:

```java
    static int findLastLineBreak(ByteBuf buffer, int index) {
        int candidate = findLineBreak(buffer, index);
        int next;
        while (candidate >= 0 && (next = findLineBreak(buffer, index + candidate)) > 0) {
            candidate += next;
        }
        return candidate;
    }
```

Any reason that can't work?

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: Yes indeed, but almost since we need to recheck if there were CR at first pos, or LF, in order to restart at candudate + 2 or +1.
However simplest than current version, I agree.

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: I will change and check of course.

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: @chrisvest  I checked with this version working. Is it ok for you ?

    static int findLastLineBreak(ByteBuf buffer, int index) {
        int candidate = findLineBreak(buffer, index);
        int findCRLF = 0;
        if (candidate >= 0) {
            if (buffer.getByte(index + candidate) == HttpConstants.CR) {
                findCRLF = 2;
            } else {
                findCRLF = 1;
            }
            candidate += findCRLF;
        }
        int next;
        while (candidate > 0 && (next = findLineBreak(buffer, index + candidate)) >= 0) {
            candidate += next;
            if (buffer.getByte(index + candidate) == HttpConstants.CR) {
                findCRLF = 2;
            } else {
                findCRLF = 1;
            }
            candidate += findCRLF;
        }
        return candidate - findCRLF;
    }

Comment (chrisvest) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: Yes, that looks good. Thanks for explaining.

Comment (fredericBregier) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java]: Commited ;-)

**Comment by fredericBregier** [comment]
Docker issue, not code issue...

**Review by chrisvest — APPROVED** [review]

**Comment by chrisvest** [comment]
Thanks!
