### PR TITLE
Fix BufferOverflowException during non-Unsafe PooledDirectByteBuf resize

### LINKED ISSUE #9911: BufferOverflowException with specific buffer sizes
When Netty reallocates pooled buffers that are approximately 256 to 1024 bytes, a `BufferOverflowException` can be thrown. **Furthermore, the exception is swallowed** and is not printed by `LoggingHandler` (I was only able to find it by capturing it from a debugger).

I'm on JDK 13 and therefore `Unsafe` isn't available.

### Expected behavior
Buffers that are between 256 and 1024 bytes should be reallocated successfully. In my application. it always works when the buffer is outside of that range and always throws when the buffer is inside of the range.
### Actual behavior
```
io.netty.handler.codec.EncoderException: java.nio.BufferOverflowException
        at io.netty.codec@4.1.44.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
        at io.netty.codec@4.1.44.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
        at io.netty.handler@4.1.44.Final/io.netty.handler.logging.LoggingHandler.write(LoggingHandler.java:235)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:762)
        at io.netty.transport@4.1.44.Final/io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1089)
        at io.netty.common@4.1.44.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.common@4.1.44.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.transport@4.1.44.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.common@4.1.44.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.common@4.1.44.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.common@4.1.44.Final/io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.nio.BufferOverflowException
        at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:411)
        at io.netty.buffer@4.1.44.Final/io.netty.buffer.PoolArena$DirectArena.memoryCopy(PoolArena.java:795)
        at io.netty.buffer@4.1.44.Final/io.netty.buffer.PoolArena$DirectArena.memoryCopy(PoolArena.java:704)
        at io.netty.buffer@4.1.44.Final/io.netty.buffer.PoolArena.reallocate(PoolArena.java:405)
        at io.netty.buffer@4.1.44.Final/io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
        at io.netty.buffer@4.1.44.Final/io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:306)
        at io.netty.buffer@4.1.44.Final/io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
        at io.netty.codec@4.1.44.Final/io.netty.handler.codec.protobuf.ProtobufVarint32LengthFieldPrepender.encode(ProtobufVarint32LengthFieldPrepender.java:48)
        at io.netty.codec@4.1.44.Final/io.netty.handler.codec.protobuf.ProtobufVarint32LengthFieldPrepender.encode(ProtobufVarint32LengthFieldPrepender.java:40)
        at io.netty.codec@4.1.44.Final/io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
        ... 20 more
```
This leads to messages of certain sizes getting dropped out of the pipeline.
### Minimal yet complete reproducer code (or URL to code)
I haven't been able to reproduce outside of my application (and I tried pretty hard). I suspect that the allocation sequence of pooled buffers in my application must be important. I'll try to come up with a way to test this easily in my application.

### Netty version
```
4.1.44.Final
```
### JVM version (e.g. `java -version`)
```
openjdk 13.0.1 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
```
### OS version (e.g. `uname -a`)
```
Linux OCTOLOGY 5.4.6-arch1-1 #1 SMP PREEMPT Sat, 21 Dec 2019 16:34:41 +0000 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by njhill**
Motivation

Recent optimization #9765 introduced a bug where the native indices of the internal reused duplicate nio buffer are not properly reset prior to using it to copy data during a reallocation operation. This can result in `BufferOverflowException`s thrown during `ByteBuf` capacity changes.

The code path in question applies only to pooled direct buffers when Unsafe is disabled or not available.

Modification

Ensure `ByteBuffer#clear()` is always called on the reused internal nio buffer prior to returning it from `PooledByteBuf#internalNioBuffer()` (protected method); add unit test that exposes the bug.

Result

Fixes #9911

### CODE REVIEW

File: buffer/src/test/java/io/netty/buffer/PoolArenaTest.java [hunk 1]
```diff
@@ -46,6 +48,7 @@ public void testNormalizeAlignedCapacity() throws Exception {
 
     @Test
     public void testDirectArenaOffsetCacheLine() throws Exception {
+        assumeTrue(PlatformDependent.hasUnsafe());
```
Comment (njhill) [inline buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: @normanmaurer I added this because I noticed that it fails when running the tests with `-Dio.netty.noUnsafe=true` (I think it's actually N/A in that case). Should we include test runs with Unsafe disabled in the CI?

Comment (normanmaurer) [reply buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: @njhill yes will add it.

File: buffer/src/test/java/io/netty/buffer/PoolArenaTest.java [hunk 2]
```diff
@@ -107,4 +110,17 @@ public final void testAllocationCounter() {
...
+    @Test
+    public final void testDirectArenaMemoryCopy() {
+        PooledByteBuf<ByteBuffer> src =
+                (PooledByteBuf<ByteBuffer>) PooledByteBufAllocator.DEFAULT.directBuffer(512);
+        PooledByteBuf<ByteBuffer> dst =
+                (PooledByteBuf<ByteBuffer>) PooledByteBufAllocator.DEFAULT.directBuffer(512);
+        // This causes the internal reused ByteBuffer duplicate limit to be set to 128
+        dst.writeBytes(ByteBuffer.allocate(128));
+        // Ensure internal ByteBuffer duplicate limit is properly reset (used in memoryCopy non-Unsafe case)
+        dst.chunk.arena.memoryCopy(src.memory, 0, dst, 512);
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: @njhill we need to call `src.release()` and `dst.release()` as well.

Comment (njhill) [reply buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: @normanmaurer done

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: buffer/src/test/java/io/netty/buffer/PoolArenaTest.java [hunk 3]
```diff
@@ -107,4 +110,20 @@ public final void testAllocationCounter() {
         Assert.assertEquals(1, metric.numNormalDeallocations());
         Assert.assertEquals(1, metric.numNormalAllocations());
     }
+
+    @SuppressWarnings("unchecked")
+    @Test
+    public final void testDirectArenaMemoryCopy() {
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: @njhill nit: remove final ?

Comment (njhill) [reply buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: sure, did it for the adjacent test too

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: buffer/src/test/java/io/netty/buffer/PoolArenaTest.java [hunk 4]
```diff
@@ -107,4 +110,22 @@ public final void testAllocationCounter() {
         Assert.assertEquals(1, metric.numNormalDeallocations());
         Assert.assertEquals(1, metric.numNormalAllocations());
     }
+
+    @Test
+    public void testDirectArenaMemoryCopy() {
+        PooledByteBuf<ByteBuffer> src = unwrapIfNeeded(PooledByteBufAllocator.DEFAULT.directBuffer(512));
+        PooledByteBuf<ByteBuffer> dst = unwrapIfNeeded(PooledByteBufAllocator.DEFAULT.directBuffer(512));
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: @njhill this may produce leaks as you loose the "wrapper".

You need to do something like this:

```java
ByteBuf src =PooledByteBufAllocator.DEFAULT.directBuffer(512);
ByteBuf dst = PooledByteBufAllocator.DEFAULT.directBuffer(512);

// This causes the internal reused ByteBuffer duplicate limit to be set to 128
dst.writeBytes(ByteBuffer.allocate(128));
         
// Ensure internal ByteBuffer duplicate limit is properly reset (used in memoryCopy non-Unsafe case)
PooledByteBuf<ByteBuffer> pooledSrc = unwrapIfNeeded(src);
PooledByteBuf<ByteBuffer> pooledDst = unwrapIfNeeded(dst);

pooledDst.chunk.arena.memoryCopy(pooledSrc.memory, 0, pooledDst, 512);

src.release();
dst.release();
```

Comment (njhill) [reply buffer/src/test/java/io/netty/buffer/PoolArenaTest.java]: @normanmaurer sorry I realized this after pushing but was already falling asleep :) now fixed

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by njhill** [comment]
@normanmaurer hopefully this will help #9943 :)

**Comment by normanmaurer** [comment]
@njhill thanks a lot
