### PR TITLE
Track independent refCnt in MixedAttribute and MixedFileUpload

### LINKED ISSUE #12627: `MixedFileUpload` has inconsistent `ReferenceCounted` behavior when migrating from memory to disk
I can work on a patch for this. My proposed solution is to make `MixedFileUpload` use its own ref counting, like `MemoryFileUpload` already does. However this would be a big change to `MixedFileUpload` so I'm not sure about its compat implications.

---

### Expected behavior

`MixedFileUpload` should behave like a normal `ReferenceCounted` object: Every retain should have a corresponding release that should succeed.

### Actual behavior

Migration of `MixedFileUpload` from memory to disk, when the memory limit is reached, essentially resets the `refCnt` to 1, so if there were more `retain` calls before, their `release` calls will fail.

### Steps to reproduce

Run the test case below. The test case passes if migration is not triggered, e.g. by removing the `addContent` line, or by changing the `limitSize` parameter to a higher value. If migration is triggered, the test case fails with:

```
io.netty.util.IllegalReferenceCountException: refCnt: 1, decrement: 2
	at app//io.netty.util.internal.ReferenceCountUpdater.retryRelease0(ReferenceCountUpdater.java:183)
	at app//io.netty.util.internal.ReferenceCountUpdater.nonFinalRelease0(ReferenceCountUpdater.java:167)
	at app//io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:154)
	at app//io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:81)
	at app//io.netty.handler.codec.http.multipart.MixedFileUpload.release(MixedFileUpload.java:370)
	at app//com.example.MixedFileUploadTest.multipleRetain(MixedFileUploadTest.java:48)
...
```

### Minimal yet complete reproducer code (or URL to code)

```java
package com.example;

import io.netty.buffer.Unpooled;
import io.netty.handler.codec.http.multipart.MixedFileUpload;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public class MixedFileUploadTest {
    private Path tmpDir;

    @BeforeEach
    public void setUp() throws IOException {
        tmpDir = Files.createTempDirectory("MixedFileUploadTest");
    }

    @AfterEach
    public void tearDown() throws IOException {
        Files.list(tmpDir).forEach(path -> {
            try {
                Files.delete(path);
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        });
        Files.delete(tmpDir);
    }

    @Test
    public void multipleRetain() throws IOException {
        MixedFileUpload mixedFileUpload = new MixedFileUpload(
                "foo", "foo", "foo", "foo",
                StandardCharsets.UTF_8,
                -1, 2, tmpDir.toString(), false
        );

        mixedFileUpload.retain();

        // trigger moving to disk
        mixedFileUpload.addContent(Unpooled.wrappedBuffer(new byte[5]), true);

        mixedFileUpload.release(2);
    }
}
```

### Netty version

4.1.77.Final

### JVM version (e.g. `java -version`)

```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
Linux yawkat-oracle 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by yawkat**
Motivation:

Before this patch, MixedAttribute and MixedFileUpload delegated reference counting to their underlying memory or file representation. When the representation changes from memory to disk because the memory size limit was exceeded, the reference count of the old representation is not transferred, so the reference attribute resets to 1. This may leak the memory of the old representation, and may lead to exceptions when users try to release the mixed data.

Modification:

Introduce a new AbstractMixedHttpData class, analogous to the existing abstract classes for disk and memory data. This new class does its own reference counting, and unifies the swapping mechanism for attributes and file uploads.

The change is fairly big, but it's mostly copied from the old implementations. Makes it a bit annoying to review though, so I might have missed a bug.

I tried inheriting from AbstractHttpData, but it didn't really reduce the code size much, and makes some code less clear because it leads to two copies of the name, charset, etc.

Regarding compatibility, I managed to fix most compat issues reported by revapi. However inheriting from a new class in a non-final class is apparently a breaking change no matter what we do, and additionally AbstractReferenceCounted.setRefCnt is problematic. I think both of these errors are unlikely to affect anyone, and are justifiable. I've added an exclusion to the pom.

There is a new test class to test the retain/refCnt behavior. I didn't add it to the HttpDataTest, because the data defined there does not have a size limit we can use to test easily.

Result:

MixedAttribute and MixedFileUpload now behave like any other reference counted object.

Fixes #12627.

### CODE REVIEW

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMixedHttpData.java [hunk 1]
```diff
@@ -0,0 +1,279 @@
...
+                wrapped.release();
+                wrapped = makeDiskData();
+            }
+        }
+        wrapped.setContent(file);
+    }
+
+    @Override
+    public void setContent(InputStream inputStream) throws IOException {
+        if (wrapped instanceof MemoryAttribute) {
```
Comment (chrisvest) [inline codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMixedHttpData.java:182]:
```suggestion
        if (wrapped instanceof AbstractMemoryHttpData) {
```

**Review by chrisvest — CHANGES_REQUESTED** [review]
Spotted a copy-paste bug, but otherwise looks good.

File: codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMixedHttpData.java (hunk 1 above)
Comment (yawkat) [reply codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractMixedHttpData.java]: thanks

**Review by chrisvest — APPROVED** [review]

**Comment by chrisvest** [comment]
Thanks!
