### PR TITLE
Log expected STREAM_CLOSED exceptions for already closed streams at DEBUG level

### LINKED ISSUE #8025: HTTP/2 - Race Condition with RST_STREAM
### Expected behavior
When a RST_STREAM is sent to the remote, any future incoming DATA frames should be ignored.

### Actual behavior
Sometimes an error is thrown instead. (See https://github.com/grpc/grpc-java/issues/3548)

### Steps to reproduce
Send a RST_STREAM frame to a remote endpoint.

### Netty version
4.1.23.Final

### JVM version (e.g. `java -version`)
Java 8

### OS version (e.g. `uname -a`)
Any (observed on Mac and Linux).

For a bit more context. Sending a RST_STREAM will eventually trigger this code in Http2ConnectionHandler, https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L589 . This removes the stream from the active streams metadata and any subsequent DATA frames that come in will be considered as an unknown stream. I was thinking we could just check if the stream may have existed and if so just ignore the DATA frame altogether. So instead of [this](https://github.com/netty/netty/blob/501662a77f8166382eefd18a8620983d27f59d4a/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L535) do something like this

```java
verifyStreamMayHaveExisted(streamId);
return true;
```

### PR DESCRIPTION
**Pull request by bryce-anderson**
Motivation:

There is an intrinsic race between a local session resetting a stream
and the peer no longer sending any frames. This can result in the
session receiving frames for a stream that the local peer no longer
tracks. This results in a StreamException being thrown which triggers a
RST_STREAM frame, which is a good thing, but also logging at level WARN,
which is noisy for an expected and benign condition.

Modification:

Change the log level to DEBUG when logging stream errors with code
STREAM_CLOSED. All others are more interesting and will continue to be
logged at level WARN.

Additionally, it was found that DATA frames for streams that could not
have existed only resulted in a StreamException when the spec is clear
that such a situation should be fatal to the connection, resulting in a
GOAWAY(PROTOCOL_ERROR).

Fixes #8025.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@netty-bot test this please

File: codec-http2/src/test/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoderTest.java [hunk 1]
```diff
@@ -276,6 +277,32 @@ public void dataReadForUnknownStreamShouldApplyFlowControlAndFail() throws Excep
...
+    public void dataReadForUnknownStreamThatCouldntExistFail() throws Exception {
+        when(connection.streamMayHaveExisted(STREAM_ID)).thenReturn(false);
+        when(connection.stream(STREAM_ID)).thenReturn(null);
+        final ByteBuf data = dummyData();
+        int padding = 10;
+        int processedBytes = data.readableBytes() + padding;
+        try {
+            decode().onDataRead(ctx, STREAM_ID, data, padding, true);
+        } catch (Http2Exception ex) {
+            assertFalse(ex instanceof Http2Exception.StreamException);
```
Comment (normanmaurer) [inline codec-http2/src/test/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoderTest.java]: nit: consider using `assertThat(ex, not(instanceOf(Http2Exception.StreamException.class)));`

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@bryce-anderson thanks a lot!
