### PR TITLE
Close delegate resolver from RoundRobinInetAddressResolver

### LINKED ISSUE #9212: UDP ports may remain open after calling RoundRobinDnsAddressResolverGroup#close()
In Netty 4.1.36 (and several versions prior), we've found that UDP ports can "leak" when using multiple `RoundRobinDnsAddressResolverGroup` instances. Please let me begin by acknowledging that I may be missing something important about how `RoundRobinDnsAddressResolverGroup` is _supposed_ to be used, but I _think_ this might be a bug.

### Expected behavior

When calling `RoundRobinDnsAddressResolverGroup#close()`, any persistent resources (UDP ports, in this case) opened by the resolver group should be closed/released.

### Actual behavior

Some UDP ports may remain open after calling `RoundRobinDnsAddressResolverGroup#close()`.

### Steps to reproduce

In a loop, create a new `RoundRobinDnsAddressResolverGroup` and use it to resolve an address. Close the resolver group at the end of each iteration. While running, observe the number of open UDP ports over time (I used `netstat -ap udp | wc -l` under macOS).

### Minimal yet complete reproducer code (or URL to code)

```java
final NioEventLoopGroup eventLoopGroup = new NioEventLoopGroup(1);

try {
    while (true) {
        final RoundRobinDnsAddressResolverGroup resolverGroup =
                new RoundRobinDnsAddressResolverGroup(NioDatagramChannel.class,
                        DefaultDnsServerAddressStreamProvider.INSTANCE);

        // UDP ports don't get opened unless we actually try to do something with
        // the resolver; in the real use case, this happens by way of
        // bootstrap.connect(), but I've opted to use this as a more concise example.
        // I definitely recognize the possibility that there may be nuanced
        // differences between the real use case and this minimal example, but hope
        // it gets the point across.
        resolverGroup.getResolver(eventLoopGroup.next()).resolve(
                InetSocketAddress.createUnresolved("example.com", 80)).get();

        // In a vacuum, I would expect any ports opened by the resolver to be closed
        // by this statement, but they appear to remain open even after the resolver
        // group is closed.
        resolverGroup.close();

        Thread.sleep(1000);
    }
} finally {
    eventLoopGroup.shutdownGracefully().await();
}
```

### Netty version

4.1.36 (going back to at least 4.1.32, and probably earlier than that)

### JVM version (e.g. `java -version`)

```
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

### OS version (e.g. `uname -a`)

```
$ uname -a
Darwin laminar.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by jchambers**
Motivation:

`RoundRobinDnsAddressResolverGroup` ultimately opens UDP ports for DNS resolution. Callers likely expect that [`RoundRobinDnsAddressResolverGroup#close()`](https://netty.io/4.1/api/io/netty/resolver/AddressResolverGroup.html#close--) will close those ports, but that is not currently true (see #9212).

Modifications:

Overrode `RoundRobinInetAddressResolver#close()` to close the delegate name resolver, which in turn closes any UDP ports used for name resolution.

Result:

`RoundRobinDnsAddressResolverGroup#close()` closes UDP ports as expected. This fixes #9212.

### CODE REVIEW

**Comment by jchambers** [comment]
I'm very, very open to feedback on the test for this case. I had to bend a lot of stuff to make the `Channel` in question visible to the test, and none of the options felt really great to me.

**Comment by jchambers** [comment]
I threw in 12616f0 as a suggestion to relieve some (but not all) of the visibility tension in the test. I realized that even though `RoundRobinInetAddressResolver` isn't specifically about DNS _in theory,_ it's used exclusively by `RoundRobinDnsAddressResolverGroup` _in practice._ With that in mind, I moved it to the `resolver-dns` module and made it package-private.

I can think of lots of reasons this is perhaps not the best idea (chief among them: folks may already be depending directly on `RoundRobinInetAddressResolver` in the wild), but wanted to throw it out as a suggestion all the same. I'm happy to drop it or move it to its own pull request if it seems controversial.

File: resolver-dns/src/main/java/io/netty/resolver/dns/RoundRobinInetAddressResolver.java [hunk 1]
```diff
@@ -36,8 +38,8 @@
  * Use {@link #asAddressResolver()} to create a {@link InetSocketAddress} resolver
  */
 @UnstableApi
-public class RoundRobinInetAddressResolver extends InetNameResolver {
-    private final NameResolver<InetAddress> nameResolver;
+class RoundRobinInetAddressResolver extends InetNameResolver {
```
Comment (normanmaurer) [inline resolver-dns/src/main/java/io/netty/resolver/dns/RoundRobinInetAddressResolver.java]: Please don't move it if you can fix the problem in another way as it will "break" people if they depend on the class in their code.

Comment (jchambers) [reply resolver-dns/src/main/java/io/netty/resolver/dns/RoundRobinInetAddressResolver.java]: No problem! Rolled it back.

File: resolver/src/main/java/io/netty/resolver/InetSocketAddressResolver.java [hunk 2]
```diff
@@ -91,6 +91,10 @@ public void operationComplete(Future<List<InetAddress>> future) throws Exception
                 });
     }
 
+    public NameResolver<InetAddress> nameResolver() {
```
Comment (normanmaurer) [inline resolver/src/main/java/io/netty/resolver/InetSocketAddressResolver.java]: can we keep this package-private for now ?

File: resolver/src/main/java/io/netty/resolver/RoundRobinInetAddressResolver.java [hunk 3]
```diff
@@ -100,4 +100,13 @@ public void operationComplete(Future<List<InetAddress>> future) throws Exception
     private static int randomIndex(int numAddresses) {
         return numAddresses == 1 ? 0 : PlatformDependent.threadLocalRandom().nextInt(numAddresses);
     }
+
+    public NameResolver<InetAddress> nameResolver() {
```
Comment (normanmaurer) [inline resolver/src/main/java/io/netty/resolver/RoundRobinInetAddressResolver.java]: can we keep this package-private for now ?

File: resolver-dns/src/test/java/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroupTest.java [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+
+            InflightNameResolver<InetAddress> inflightNameResolver =
+                    (InflightNameResolver<InetAddress>) roundRobinInetAddressResolver.nameResolver();
+
+            DnsNameResolver dnsNameResolver = (DnsNameResolver) inflightNameResolver.delegate;
+
+            assertTrue(dnsNameResolver.ch.isOpen());
+
+            roundRobinGroup.close();
+            dnsNameResolver.ch.closeFuture().await(2, TimeUnit.SECONDS);
```
Comment (normanmaurer) [inline resolver-dns/src/test/java/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroupTest.java]: Should we just use `sync()` and use `@Test(timeout = 2000)` ?

File: resolver/src/main/java/io/netty/resolver/InetSocketAddressResolver.java (hunk 2 above)
Comment (jchambers) [reply resolver/src/main/java/io/netty/resolver/InetSocketAddressResolver.java]: Let me give it a second look. Because `RoundRobinInetAddressResolver` lives in `resolver-dns` and a lot of these classes just live in `resolver`, I think _something_ has to be more public than we'd like, but I could be mistaken.

File: resolver-dns/src/test/java/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroupTest.java (hunk 4 above)
Comment (jchambers) [reply resolver-dns/src/test/java/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroupTest.java]: Sure!

File: resolver/src/main/java/io/netty/resolver/InetSocketAddressResolver.java (hunk 2 above)
Comment (jchambers) [reply resolver/src/main/java/io/netty/resolver/InetSocketAddressResolver.java]: As a compromise, we could skip testing `RoundRobinDnsAddressResolverGroup` and test `RoundRobinInetAddressResolver` directly instead. We wouldn't quite replicate the most common use case, but that would allow us to keep pretty much everything package-private.

Comment (jchambers) [reply resolver/src/main/java/io/netty/resolver/InetSocketAddressResolver.java]: I lied.

Moving the test to the `resolver` module means that we lose visibility on `InflightNameResolver`. That does have a FIXME, though:

```java
// FIXME(trustin): Find a better name and move it to the 'resolver' module.
```

We could try to resolve that as part of this pull request, but that feels like a lot of added scope to me.

So to recap, I think our options are:

1. Do what we have here and publicize some stuff we'd rather not publicize.
2. Narrow the test to cover `RoundRobinInetAddressResolver` instead of `RoundRobinDnsAddressResolverGroup` and resolve the FIXME in `InflightNameResolver`.
3. Forget about the test and just ship the simple fix if we think the other two options are too costly.

What do you think?

File: resolver-dns/src/test/java/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroupTest.java (hunk 4 above)
Comment (jchambers) [reply resolver-dns/src/test/java/io/netty/resolver/dns/RoundRobinDnsAddressResolverGroupTest.java]: Done and pushed.

**Comment by normanmaurer** [comment]
Lee’s just ship the guy for now

**Comment by jchambers** [comment]
Stripped it down to the basics. Think we're good to go.

**Comment by normanmaurer** [comment]
@netty-bot test this please

**Comment by normanmaurer** [comment]
@jchambers thanks a lot!

**Comment by jchambers** [comment]
🤘
