### PR TITLE
Fix alignment handling for pooled direct buffers

### LINKED ISSUE #11101: direct memory allocation error in PooledByteBufAllocator when setting directMemoryCacheAlignment to "1"
Define a `PooledByteBufAllocator` and set ·directMemoryCacheAlignment· to "1" and try to allocate some `ByteBuf` like
```java
PooledByteBufAllocator pooledByteBufAllocator = new PooledByteBufAllocator(
        PlatformDependent.directBufferPreferred(),
        PooledByteBufAllocator.defaultNumHeapArena(),
        PooledByteBufAllocator.defaultNumDirectArena(),
        PooledByteBufAllocator.defaultPageSize(),
        11,
        PooledByteBufAllocator.defaultSmallCacheSize(),
        64,
        PooledByteBufAllocator.defaultUseCacheForAllThreads(),
        1
);

ByteBuf buf1 = pooledByteBufAllocator.directBuffer(16384);
for (int i = 0; i < 16384; i++) {
    buf1.writeByte(1);
}
ByteBuf buf2 = pooledByteBufAllocator.directBuffer(65536);
buf2.writeByte(2);
System.out.println("last byte of buf1: " + buf1.getByte(buf1.capacity() - 1));
```

### Expected behavior
`last byte of the buf1: 1`
### Actual behavior
`last byte of the buf1: 2`
### Steps to reproduce
```java
PooledByteBufAllocator pooledByteBufAllocator = new PooledByteBufAllocator(
        PlatformDependent.directBufferPreferred(),
        PooledByteBufAllocator.defaultNumHeapArena(),
        PooledByteBufAllocator.defaultNumDirectArena(),
        PooledByteBufAllocator.defaultPageSize(),
        11,
        PooledByteBufAllocator.defaultSmallCacheSize(),
        64,
        PooledByteBufAllocator.defaultUseCacheForAllThreads(),
        1
);

ByteBuf buf1 = pooledByteBufAllocator.directBuffer(16384);
ByteBuf buf2 = pooledByteBufAllocator.directBuffer(65536);
System.out.println("memory address of buf1: [" + buf1.memoryAddress() + ", " + (buf1.memoryAddress() + buf1.capacity()) + ")");
System.out.println("memory address of buf2: [" + buf2.memoryAddress() + ", " + (buf2.memoryAddress() + buf2.capacity()) + ")");
```

Got 2 overlapped ranges(on my pc)
memory address of buf1: [2047716884545, 2047716900929)
memory address of buf2: [2047716900928, 2047716966464)

### Netty version
4.1.60.Final
### JVM version (e.g. `java -version`)
1.8.0_271
### OS version (e.g. `uname -a`)
win10

### PR DESCRIPTION
**Pull request by chrisvest**
Motivation:
Alignment handling was broken, and basically turned into a fixed offset into each allocation address regardless of its initial value, instead of ensuring that the allocated address is either aligned or bumped to the nearest alignment offset.
The brokenness of the alignment handling extended so far, that overlapping ByteBuf instances could even be created, as was seen in #11101.

Modification:
Instead of fixing the per-allocation pointer bump, we now ensure that 1) the minimum page size is a whole multiple of the alignment, and 2) the reference memory for each chunk is bumped to the nearest aligned address, and finally 3) ensured that the reservations are whole multiples of the alignment, thus ensuring that the next allocation automatically occurs from an aligned address.

Incidentally, (3) above comes for free because the reservations are in whole pages, and in (1) we ensured that pages are sized in whole multiples of the alignment.

In order to ensure that the memory for a chunk is aligned, we introduce some new PlatformDependent infrastructure.
The PlatformDependent.alignDirectBuffer will produce a slice of the given buffer, and the slice will have an address that is aligned.
This method is plainly available on ByteBuffer in Java 9 onwards, but for pre-9 we have to use Unsafe, which means it can fail and might not be available on all platforms.
Attempts to create a PooledByteBufAllocator that uses alignment, when this is not supported, will throw an exception.
Luckily, I think use of aligned allocations are rare.

Result:
Aligned pooled byte bufs now work correctly, and never have any overlap.

Fixes #11101

### CODE REVIEW

File: buffer/src/main/java/io/netty/buffer/PoolArena.java [hunk 1]
```diff
@@ -601,43 +600,31 @@ boolean isDirect() {
...
+                return new PoolChunk<ByteBuffer>(this, memory, memory, pageSize, pageShifts,
+                        chunkSize, maxPageIdx);
             }
-            final ByteBuffer memory = allocateDirect(chunkSize
-                    + directMemoryCacheAlignment);
-            return new PoolChunk<ByteBuffer>(this, memory, pageSize,
-                    pageShifts, chunkSize, maxPageIdx,
-                    offsetCacheLine(memory));
+
+            final ByteBuffer base = allocateDirect(chunkSize + directMemoryCacheAlignment);
```
Comment (normanmaurer) [inline buffer/src/main/java/io/netty/buffer/PoolArena.java:612]: So this means we may waste `directMemoryCacheAlignment` bytes in the worse case, correct ?

File: buffer/src/test/java/io/netty/buffer/PooledAlignedBigEndianDirectByteBufTest.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+ */
+package io.netty.buffer;
+
+import java.nio.ByteOrder;
+
+import static org.junit.Assert.assertSame;
+
+public class PooledAlignedBigEndianDirectByteBufTest extends PooledBigEndianDirectByteBufTest {
+    private static final int directMemoryCacheAlignment = 1;
+    private static final PooledByteBufAllocator ALLOCATOR = new PooledByteBufAllocator(
```
Comment (normanmaurer) [inline buffer/src/test/java/io/netty/buffer/PooledAlignedBigEndianDirectByteBufTest.java:24]: Should we better not make this static but create a new one in the test ? Otherwise we may end up with using more memory then we really need (due the fact that the ALLOCATOR will not be collected until the JVM dies).

File: common/src/main/java/io/netty/util/internal/PlatformDependent.java [hunk 3]
```diff
@@ -768,6 +768,28 @@ public static void freeDirectNoCleaner(ByteBuffer buffer) {
         decrementMemoryCounter(capacity);
     }
 
+    public static boolean hasAlignDirectByteBuffer() {
+        return hasUnsafe() || PlatformDependent0.hasAlignSliceMethod();
+    }
+
+    public static ByteBuffer alignDirectBuffer(ByteBuffer buffer, int alignment) {
```
Comment (normanmaurer) [inline common/src/main/java/io/netty/util/internal/PlatformDependent.java:775]: should we require that `alignment` is a power of two and so we can use `&` as a replacement for `%` for perf reasons ?

**Review by normanmaurer — CHANGES_REQUESTED** [review]

File: buffer/src/main/java/io/netty/buffer/PoolArena.java (hunk 1 above)
Comment (chrisvest) [reply buffer/src/main/java/io/netty/buffer/PoolArena.java:612]: Yes, that was always the case when alignment was requested.

**Comment by chrisvest** [comment]
@normanmaurer Comments addressed. Please take a look.

File: common/src/main/java/io/netty/util/internal/PlatformDependent.java (hunk 3 above)
Comment (chrisvest) [reply common/src/main/java/io/netty/util/internal/PlatformDependent.java:775]: I switched to using JCTools Pow2 for this, which do these checks.

**Review by normanmaurer — APPROVED** [review]

**Comment by chrisvest** [comment]
@normanmaurer Could adding usage of JCTools cause OSGi failures?

Build is now failing in `Netty/Testsuite/OSGI` on stuff like this:

```
2021-03-23T11:56:13.3334613Z 11:56:13.324 [FelixDispatchQueue] ERROR o.o.p.e.n.i.NativeTestContainer - Framework ERROR event org.osgi.framework.FrameworkEvent[source=io.netty.codec-stomp [16]]
2021-03-23T11:56:13.3340262Z org.osgi.framework.BundleException: Unable to resolve io.netty.codec-stomp [16](R 16.0): missing requirement [io.netty.codec-stomp [16](R 16.0)] osgi.wiring.package; (&(osgi.wiring.package=io.netty.channel)(version>=4.1.0)(!(version>=5.0.0))) [caused by: Unable to resolve io.netty.transport [20](R 20.0): missing requirement [io.netty.transport [20](R 20.0)] osgi.wiring.package; (&(osgi.wiring.package=io.netty.buffer)(version>=4.1.0)(!(version>=5.0.0))) [caused by: Unable to resolve io.netty.buffer [27](R 27.0): missing requirement [io.netty.buffer [27](R 27.0)] osgi.wiring.package; (&(osgi.wiring.package=org.jctools.util)(version>=3.0.0)(!(version>=4.0.0)))]] Unresolved requirements: [[io.netty.codec-stomp [16](R 16.0)] osgi.wiring.package; (&(osgi.wiring.package=io.netty.channel)(version>=4.1.0)(!(version>=5.0.0)))]
2021-03-23T11:56:13.3344698Z 	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
2021-03-23T11:56:13.3346510Z 	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
2021-03-23T11:56:13.3348445Z 	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
2021-03-23T11:56:13.3350596Z 	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
2021-03-23T11:56:13.3352440Z 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by normanmaurer** [comment]
@chrisvest I would hope not as we shade it... But 🤷

**Comment by chrisvest** [comment]
@normanmaurer Apparently OSGi is picky about that... somehow. Let's hope it goes green now.
